AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper Class Reference
Public Member Functions
List< DateTime > GetScheduledDates (RecurrenceVM recurrence, DateTime start, bool futureDatesOnly=true)
Static Public Member Functions
static string GetRecurrenceMessage (RecurrenceVM recurrence)
static string SetOrdinalNumber (int num)
static int ReturnMonthNumber (string month)
Private Member Functions
void SetMinutelySchedule (int interval)
void SetDailySchedule (int interval)
void SetWeeklyDate (DateTime? ends, int interval, List< string > days)
void SetMonthlyDate (DateTime start, DateTime? ends, int interval, int day)
void SetMonthlyDateOffset (DateTime start, DateTime? ends, int interval, WeekDaysTypeCSH weekDaysType, DaySequence daySequence)
void SetYearlyDate (DateTime start, DateTime? ends, Month month, int day)
void SetYearlyDateOffset (DateTime start, DateTime? ends, DaySequence daySequence, WeekDaysTypeCSH weekDaysType, Month month)
Static Private Member Functions
static bool CheckMonthlyOffset (RecurrenceVM recurrence)
static bool CheckYearlyOffset (RecurrenceVM recurrence)
static DateTime GetFirstDay (DateTime pivot, int day)
static List< int > DaysOfTheWeekToInt (List< string > days)
static ? DateTime GenerateMonthlyDate (DateTime scheduledDate, WeekDaysTypeCSH weekDaysType, DaySequence daySequence)
static int FindDay (int year, int month, DayOfWeek day, int daySequenceNumber)
static DayOfWeek GetDayOfWeek (WeekDaysTypeCSH weekDaysTypeCSH)
Private Attributes
List< DateTime > result
DateTime scheduledDate
int occurence
Detailed Description
Definition at line 11 of file CampaignScheduleHelper.cs.
Member Function Documentation
CheckMonthlyOffset()
static bool Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.CheckMonthlyOffset (RecurrenceVM recurrence) inline static private
Definition at line 119 of file CampaignScheduleHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetRecurrenceMessage(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetScheduledDates().
CheckYearlyOffset()
static bool Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.CheckYearlyOffset (RecurrenceVM recurrence) inline static private
Definition at line 124 of file CampaignScheduleHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetRecurrenceMessage(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetScheduledDates().
DaysOfTheWeekToInt()
static List< int > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.DaysOfTheWeekToInt (List< string > days) inline static private
Definition at line 315 of file CampaignScheduleHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetWeeklyDate().
FindDay()
static int Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.FindDay (int year, int month, DayOfWeek day, int daySequenceNumber) inline static private
Definition at line 401 of file CampaignScheduleHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GenerateMonthlyDate().
GenerateMonthlyDate()
static ? DateTime Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GenerateMonthlyDate (DateTime scheduledDate, WeekDaysTypeCSH weekDaysType, DaySequence daySequence) inline static private
Definition at line 328 of file CampaignScheduleHelper.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.FindDay(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetDayOfWeek(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.scheduledDate.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetMonthlyDateOffset().
GetDayOfWeek()
static DayOfWeek Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetDayOfWeek (WeekDaysTypeCSH weekDaysTypeCSH) inline static private
Definition at line 423 of file CampaignScheduleHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GenerateMonthlyDate(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetYearlyDateOffset().
GetFirstDay()
static DateTime Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetFirstDay (DateTime pivot, int day) inline static private
Definition at line 305 of file CampaignScheduleHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetWeeklyDate().
GetRecurrenceMessage()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetRecurrenceMessage (RecurrenceVM recurrence) inline static
Definition at line 73 of file CampaignScheduleHelper.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.CheckMonthlyOffset(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.CheckYearlyOffset(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.Day, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.DaySequence, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.DaysOfWeek, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.Frequency, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.Interval, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.MaxOcurrence, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.Month, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.RecursUntil, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetOrdinalNumber(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.WeekDaysType.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ScheduleVM.SetFutureDateAndRecurrentMessage().
GetScheduledDates()
List< DateTime > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetScheduledDates (RecurrenceVM recurrence, DateTime start, bool futureDatesOnly = true) inline
Definition at line 17 of file CampaignScheduleHelper.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.CheckMonthlyOffset(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.CheckYearlyOffset(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.Day, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.DaySequence, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.DaysOfWeek, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.Frequency, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.Interval, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.MaxOcurrence, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.Month, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.occurence, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.RecursUntil, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.result, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.scheduledDate, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetDailySchedule(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetMinutelySchedule(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetMonthlyDate(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetMonthlyDateOffset(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetWeeklyDate(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetYearlyDate(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetYearlyDateOffset(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RecurrenceVM.WeekDaysType.
ReturnMonthNumber()
static int Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.ReturnMonthNumber (string month) inline static
Definition at line 457 of file CampaignScheduleHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.GenerateRecurrence().
SetDailySchedule()
void Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetDailySchedule (int interval) inline private
Definition at line 134 of file CampaignScheduleHelper.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.result, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.scheduledDate.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetScheduledDates().
SetMinutelySchedule()
void Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetMinutelySchedule (int interval) inline private
Definition at line 129 of file CampaignScheduleHelper.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.result, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.scheduledDate.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetScheduledDates().
SetMonthlyDate()
void Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetMonthlyDate (DateTime start, DateTime? ends, int interval, int day) inline private
Definition at line 153 of file CampaignScheduleHelper.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.occurence, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.result, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.scheduledDate.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetScheduledDates().
SetMonthlyDateOffset()
void Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetMonthlyDateOffset (DateTime start, DateTime? ends, int interval, WeekDaysTypeCSH weekDaysType, DaySequence daySequence) inline private
Definition at line 179 of file CampaignScheduleHelper.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GenerateMonthlyDate(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.occurence, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.result, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.scheduledDate.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetScheduledDates().
SetOrdinalNumber()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetOrdinalNumber (int num) inline static
Definition at line 437 of file CampaignScheduleHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetRecurrenceMessage(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ScheduleVM.SetQuarterlyMessage().
SetWeeklyDate()
void Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetWeeklyDate (DateTime? ends, int interval, List< string > days) inline private
Definition at line 139 of file CampaignScheduleHelper.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.DaysOfTheWeekToInt(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetFirstDay(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.result, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.scheduledDate.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetScheduledDates().
SetYearlyDate()
void Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetYearlyDate (DateTime start, DateTime? ends, Month month, int day) inline private
Definition at line 204 of file CampaignScheduleHelper.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.occurence, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.result, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.scheduledDate.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetScheduledDates().
SetYearlyDateOffset()
void Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetYearlyDateOffset (DateTime start, DateTime? ends, DaySequence daySequence, WeekDaysTypeCSH weekDaysType, Month month) inline private
Definition at line 229 of file CampaignScheduleHelper.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetDayOfWeek(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.occurence, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.result, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.scheduledDate.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetScheduledDates().
Member Data Documentation
occurence
int Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.occurence private
Definition at line 15 of file CampaignScheduleHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetScheduledDates(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetMonthlyDate(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetMonthlyDateOffset(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetYearlyDate(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetYearlyDateOffset().
result
List<DateTime> Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.result private
Definition at line 13 of file CampaignScheduleHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetScheduledDates(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetDailySchedule(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetMinutelySchedule(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetMonthlyDate(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetMonthlyDateOffset(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetWeeklyDate(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetYearlyDate(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetYearlyDateOffset().
scheduledDate
DateTime Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.scheduledDate private
Definition at line 14 of file CampaignScheduleHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GenerateMonthlyDate(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.GetScheduledDates(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetDailySchedule(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetMinutelySchedule(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetMonthlyDate(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetMonthlyDateOffset(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetWeeklyDate(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetYearlyDate(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.SetYearlyDateOffset().
The documentation for this class was generated from the following file:
Source/Domain/Utility/CampaignScheduleHelper.cs