AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence Class Reference
Public Member Functions
Recurrence ()
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.BaseEntity
void Assign (BaseEntity source)
Static Public Member Functions
static Recurrence GenerateRecurrence (XElement recurrenceXML)
Properties
Frequency Frequency [get, set]
int Interval [get, set]
DateTime? RecursUntil [get, set]
int? MaxOcurrence [get, set]
Month Month [get, set]
string DaysOfWeek [get, set]
WeekDaysTypeCSH WeekDaysType [get, set]
DaySequence DaySequence [get, set]
int Day [get, set]
Schedule Schedule [get, set]
int? ScheduleId [get, set]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.BaseEntity
int Id [get, set]
bool Enabled [get, set]
int? ClientId [get, set]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.ModifiedEntity
DateTime DateCreated [get, set]
DateTime DeluxeLastModified [get, set]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.Interface.IModified
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.Interface.IBaseEntity
Detailed Description
Definition at line 10 of file Recurrence.cs.
Constructor & Destructor Documentation
Recurrence()
Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.Recurrence () inline
Definition at line 12 of file Recurrence.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.WeekDaysType.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.GenerateRecurrence().
Member Function Documentation
GenerateRecurrence()
static Recurrence Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.GenerateRecurrence (XElement recurrenceXML) inline static
Definition at line 67 of file Recurrence.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.Month, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.Recurrence(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CampaignScheduleHelper.ReturnMonthNumber().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToSchedule().
Property Documentation
Day
int Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.Day get set
Definition at line 53 of file Recurrence.cs.
DaySequence
DaySequence Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.DaySequence get set
Definition at line 49 of file Recurrence.cs.
DaysOfWeek
string Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.DaysOfWeek get set
Definition at line 41 of file Recurrence.cs.
Frequency
Frequency Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.Frequency get set
Definition at line 19 of file Recurrence.cs.
Interval
int Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.Interval get set
Definition at line 23 of file Recurrence.cs.
MaxOcurrence
int? Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.MaxOcurrence get set
Definition at line 31 of file Recurrence.cs.
Month
Month Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.Month get set
Definition at line 36 of file Recurrence.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.GenerateRecurrence().
RecursUntil
DateTime? Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.RecursUntil get set
Definition at line 27 of file Recurrence.cs.
Schedule
Schedule Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.Schedule get set
Definition at line 58 of file Recurrence.cs.
ScheduleId
int? Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.ScheduleId get set
Definition at line 62 of file Recurrence.cs.
WeekDaysType
WeekDaysTypeCSH Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.WeekDaysType get set
Definition at line 45 of file Recurrence.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.Recurrence().
The documentation for this class was generated from the following file:
Source/Domain/DataModel/UserCampaigns/Recurrence.cs