AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService Interface Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService Interface Reference
Public Member Functions
Task< ServiceResult< string > > Sharing (SharingRequest sharingRequest)
bool Authenticate (IHeaderDictionary headerDictionary)
Task< ServiceResult< string > > UnlinkFromSocial (UnlinkSocialVM unlinkSocialVM)
Task< ServiceResult< CheckSocialVM > > CheckSocialForUser (CheckSocialVM checkSocialVM)
Task< ServiceResult< string > > SaveCredentials (List< SocialAccountInfoVM > socialAccountInfos, int clientId)
Properties
ITwitterService _twitterService [get, set]
ILinkedinService _linkedinService [get, set]
Detailed Description
Definition at line 23 of file SocialNetworkService.cs.
Member Function Documentation
Authenticate()
bool Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.Authenticate (IHeaderDictionary headerDictionary)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.Sharing().
CheckSocialForUser()
Task< ServiceResult< CheckSocialVM > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.CheckSocialForUser (CheckSocialVM checkSocialVM)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.CheckSocialForUser(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.UpdateSocialURLs().
SaveCredentials()
Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.SaveCredentials (List< SocialAccountInfoVM > socialAccountInfos, int clientId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.SaveCredentials().
Sharing()
Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.Sharing (SharingRequest sharingRequest)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.Sharing().
UnlinkFromSocial()
Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.UnlinkFromSocial (UnlinkSocialVM unlinkSocialVM)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.UnlinkSocial().
Property Documentation
_linkedinService
ILinkedinService Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService._linkedinService get set
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.
Definition at line 29 of file SocialNetworkService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.GetLinkedinAccountInfo(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.SocialAuthorization().
_twitterService
ITwitterService Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService._twitterService get set
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.
Definition at line 25 of file SocialNetworkService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.GetTwitterAccountInfo(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.SocialAuthorization().
The documentation for this interface was generated from the following file:
Source/Infrastructure/Social/SocialNetworkService.cs