AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice Interface Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice Interface Reference
Public Member Functions
Task< ServiceResult< PMSPersonaDTO > > GetPersonaInstance (string personaInstanceId, string userId)
Task< ServiceResult< string > > UpdatePersonaInstanceData (string personaInstanceId, List< PersonaInstanceUpdateItem > customFieldData)
Task< ServiceResult< List< CustomFieldShortData > > > GetCustomFieldsForPersona (string personaGuid, string fieldName, bool onlyActive)
Task< ServiceResult< List< string > > > ConvertImagesFromUrlToBase64 (IList< string > imageUrls)
Task< ServiceResult< List< SimplePersonaDTO > > > GetPersonaInstancesForUser_Simple (string userId, string personaName, string personaInstanceName, bool onlyActive, string groupId)
Task< ServiceResult< List< PersonaInstanceWithNameIsDefaultDTO > > > GetPersonaInstanceNamesForUser (string userId, string personaType="")
Task< ServiceResult< IEnumerable< string > > > GetContactIdsForUserPersonas (string userGuid)
Task< ServiceResult< List< PMSPersonaDTO > > > GetFilteredPersonas (string customfieldTag, string customFieldValue)
Task< ServiceResult< IEnumerable< KeyValuePair< Guid, string > > > > GetUserPersonasType (string userGuid)
Detailed Description
Definition at line 23 of file PersonaMicroservice.cs.
Member Function Documentation
ConvertImagesFromUrlToBase64()
Task< ServiceResult< List< string > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.ConvertImagesFromUrlToBase64 (IList< string > imageUrls)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.PersonaMicroservice.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.GetBase64Images().
GetContactIdsForUserPersonas()
Task< ServiceResult< IEnumerable< string > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetContactIdsForUserPersonas (string userGuid)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.PersonaMicroservice.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetContactIdsForUserPersonas().
GetCustomFieldsForPersona()
Task< ServiceResult< List< CustomFieldShortData > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetCustomFieldsForPersona (string personaGuid, string fieldName, bool onlyActive)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.PersonaMicroservice.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.UpdateEmailSPFApproved().
GetFilteredPersonas()
Task< ServiceResult< List< PMSPersonaDTO > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetFilteredPersonas (string customfieldTag, string customFieldValue)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.PersonaMicroservice.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckRefreshTokenForWarning().
GetPersonaInstance()
Task< ServiceResult< PMSPersonaDTO > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetPersonaInstance (string personaInstanceId, string userId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.PersonaMicroservice.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.FindPersonaByType(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetDefaultPersonaForProfile(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonaByGUID(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonasForProfile(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.Single().
GetPersonaInstanceNamesForUser()
Task< ServiceResult< List< PersonaInstanceWithNameIsDefaultDTO > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetPersonaInstanceNamesForUser (string userId, string personaType = "")
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.PersonaMicroservice.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonaInstanceNamesForAudience().
GetPersonaInstancesForUser_Simple()
Task< ServiceResult< List< SimplePersonaDTO > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetPersonaInstancesForUser_Simple (string userId, string personaName, string personaInstanceName, bool onlyActive, string groupId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.PersonaMicroservice.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetDefaultPersonaForProfile(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonasForProfile(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetUserPersonas().
GetUserPersonasType()
Task< ServiceResult< IEnumerable< KeyValuePair< Guid, string > > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetUserPersonasType (string userGuid)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.PersonaMicroservice.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.MyCampaigns().
UpdatePersonaInstanceData()
Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.UpdatePersonaInstanceData (string personaInstanceId, List< PersonaInstanceUpdateItem > customFieldData)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.PersonaMicroservice.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.UpdateEmailSPFApproved().
The documentation for this interface was generated from the following file:
Source/Infrastructure/PMS/PersonaMicroservice.cs