AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF Class Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF Class Reference
Public Member Functions
ContactServiceMF (IConfiguration configuration, ISessionService sessionService, IHttpClientFactory clientFactory, ILoggerFactory loggerFactory)
async Task< ServiceResult< GetContactFieldListResponse > > GetContactFieldList ()
async Task< ServiceResult< GetContactsCountResponse > > GetContactsCount (SegmentationFilter filter)
async Task< ServiceResult< string > > GetContactsCSV (string filter=null, List< string > fields=null)
Get all contacts, with selected fields, that passes filtering.
async Task< ServiceResult< CreateContactResponse > > CreateContact (ContactVM contactVM)
async Task< ServiceResult< UpdateContactResponse > > UpdateContact (ContactVM ContactVM, bool delete=false)
async Task< ServiceResult< ImportContactsResponse > > ImportContacts (string csv, string name, string mapping, ImportContactsType type, string notificationEmailAddress)
async Task< ServiceResult< GetImportListResponse > > GetImportList ()
async Task< ServiceResult< GetImportLogResponse > > GetImportLog (long logId)
async Task< ServiceResult< ImportContactsResponse > > UpdateCollectionField (string csv, CollectionField field, string profileId, string notificationEmailAddress)
async Task< ServiceResult< ImportContactsResponse > > ImportCSV (string csv, string[] mappingArray, ImportContactsType type, string profileId, string notificationEmailAddress)
async Task< ServiceResult< ContactActivityResponse > > GetContactActivity (int contactId, DateTime dateFrom, DateTime dateTo)
async Task< GetContactsByPageResponse > GetContactsByPage (string ticket, string partnerTicket, string filter, string[] fieldNames, int startRowIndex, int maxRows, string sortExpression, int contactId=0)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService
BaseMindfireService (IConfiguration configuration, string serviceName, ISessionService sessionService, IHttpClientFactory clientFactory, ILoggerFactory loggerFactory)
async Task< TResponse > Post< TResponse > (string endpoint, object body)
async Task< TResponse > PostDashboard< TResponse > (string endpoint, object body)
async Task< TResponse > Get< TResponse > (string endpoint)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IContactServiceMF
Private Member Functions
async Task< ServiceResult< ImportItem > > GetFinishedImport (long id)
async Task< ImportContactsResponse > POSTImportContacts (ImportContactsRequest request)
Static Private Member Functions
static List< KeyValue > Serialize (ContactVM contactVM)
Additional Inherited Members
Public Attributes inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService
readonly ILogger _logger
string _accountNamePrefix
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService
ISession _session [get]
RequestCredentials masterRequestCredentials [get, set]
RequestCredentials userRequestCredentials [get, set]
IMindfireSettings configuration [get, set]
string ServiceName [get]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IBaseMindfireService
Detailed Description
Definition at line 40 of file ContactServiceMF.cs.
Constructor & Destructor Documentation
ContactServiceMF()
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.ContactServiceMF (IConfiguration configuration, ISessionService sessionService, IHttpClientFactory clientFactory, ILoggerFactory loggerFactory) inline
Definition at line 42 of file ContactServiceMF.cs.
Member Function Documentation
CreateContact()
async Task< ServiceResult< CreateContactResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.CreateContact (ContactVM contactVM) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IContactServiceMF.
Definition at line 148 of file ContactServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService._logger, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.Serialize(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
GetContactActivity()
async Task< ServiceResult< ContactActivityResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetContactActivity (int contactId, DateTime dateFrom, DateTime dateTo) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IContactServiceMF.
Definition at line 446 of file ContactServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
GetContactFieldList()
async Task< ServiceResult< GetContactFieldListResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetContactFieldList () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IContactServiceMF.
Definition at line 46 of file ContactServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetContactsByPage().
GetContactsByPage()
async Task< GetContactsByPageResponse > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetContactsByPage (string ticket, string partnerTicket, string filter, string[] fieldNames, int startRowIndex, int maxRows, string sortExpression, int contactId = 0) inline
Parameters
ticket
partnerTicket
filter
fieldNames
startRowIndex
maxRows
sortExpression
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IContactServiceMF.
Definition at line 475 of file ContactServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService._logger, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ErrorCode, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ErrorMessage, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetContactFieldList(), Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.RequestCredentials.PartnerTicket, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.GetContactsByPageResponse.Result, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.RequestCredentials.Ticket, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetContactsCSV().
GetContactsCount()
async Task< ServiceResult< GetContactsCountResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetContactsCount (SegmentationFilter filter) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IContactServiceMF.
Definition at line 67 of file ContactServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ErrorCode, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ErrorMessage, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ExceptionMessage, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.GetContactsCountResponse.Result, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
GetContactsCSV()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetContactsCSV (string filter = null, List< string > fields = null) inline
Get all contacts, with selected fields, that passes filtering.
Parameters
filter
fields
Returns
CSV table presented as string
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IContactServiceMF.
Definition at line 106 of file ContactServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetContactsByPage().
GetFinishedImport()
async Task< ServiceResult< ImportItem > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetFinishedImport (long id) inline private
Definition at line 391 of file ContactServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetImportList(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetImportLog().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.ImportCSV(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.UpdateCollectionField().
GetImportList()
async Task< ServiceResult< GetImportListResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetImportList () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IContactServiceMF.
Definition at line 258 of file ContactServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetFinishedImport().
GetImportLog()
async Task< ServiceResult< GetImportLogResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetImportLog (long logId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IContactServiceMF.
Definition at line 281 of file ContactServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetFinishedImport().
ImportContacts()
async Task< ServiceResult< ImportContactsResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.ImportContacts (string csv, string name, string mapping, ImportContactsType type, string notificationEmailAddress) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IContactServiceMF.
Definition at line 226 of file ContactServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.POSTImportContacts(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.ImportCSV(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.UpdateCollectionField().
ImportCSV()
async Task< ServiceResult< ImportContactsResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.ImportCSV (string csv, string[] mappingArray, ImportContactsType type, string profileId, string notificationEmailAddress) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IContactServiceMF.
Definition at line 359 of file ContactServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetFinishedImport(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.ImportContacts().
POSTImportContacts()
async Task< ImportContactsResponse > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.POSTImportContacts (ImportContactsRequest request) inline private
Definition at line 588 of file ContactServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService._logger.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.ImportContacts().
Serialize()
static List< KeyValue > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.Serialize (ContactVM contactVM) inline static private
Definition at line 304 of file ContactServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.String.ClearSpecialCharacters().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.CreateContact(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.UpdateContact().
UpdateCollectionField()
async Task< ServiceResult< ImportContactsResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.UpdateCollectionField (string csv, CollectionField field, string profileId, string notificationEmailAddress) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IContactServiceMF.
Definition at line 336 of file ContactServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.GetFinishedImport(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.ImportContacts().
UpdateContact()
async Task< ServiceResult< UpdateContactResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.UpdateContact (ContactVM ContactVM, bool delete = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IContactServiceMF.
Definition at line 190 of file ContactServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService._logger, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.Serialize(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
The documentation for this class was generated from the following file:
Source/Infrastructure/Mindfire/ContactServiceMF.cs