AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService Class Reference
Public Member Functions
SettingsService ()
SettingsService (IMapper mapper, ApplicationDbContext dbContext, IConfiguration configuration, ILogger< SettingsService > logger, ISocialNetworkService socialNetworkService, ISessionService sessionService)
async Task< ServiceResult< SettingsVM > > AddOrUpdate (SettingsVM settingsVM)
ServiceResult< SettingsVM > SingleByName (string name, int? clientId)
ServiceResult< string > GetLibraryJson ()
async Task< ServiceResult< string > > UpdateLibraryJson (string value)
async Task< ServiceResult< string > > UpdateSliderJson (string value)
ServiceResult< string > GetSliderJson ()
ServiceResult< string > GetFrontCanvasJson ()
ServiceResult< string > GetBackCanvasJson ()
async Task< ServiceResult< string > > UpdateCanvasJson (string value, string place)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< Settings, SettingsVM >
NamedDbService ()
NamedDbService (IMapper mapper, IApplicationDbContext dbContext, IConfiguration configuration, ILogger< NamedDbService< TModel, TModelVM > > logger, ISocialNetworkService socialNetworkService, ISessionService sessionService)
override async Task< ServiceResult< TModelVM > > Update (TModelVM entityVM)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService
Detailed Description
Definition at line 35 of file SettingsService.cs.
Constructor & Destructor Documentation
SettingsService() [1/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.SettingsService () inline
Definition at line 37 of file SettingsService.cs.
SettingsService() [2/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.SettingsService (IMapper mapper, ApplicationDbContext dbContext, IConfiguration configuration, ILogger< SettingsService > logger, ISocialNetworkService socialNetworkService, ISessionService sessionService) inline
Definition at line 40 of file SettingsService.cs.
Member Function Documentation
AddOrUpdate()
async Task< ServiceResult< SettingsVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.AddOrUpdate (SettingsVM settingsVM) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.
Definition at line 53 of file SettingsService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SettingsVM.SettingsGroupId.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.UpdateCanvasJson(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.UpdateLibraryJson(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.UpdateSliderJson().
GetBackCanvasJson()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.GetBackCanvasJson () inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.
Definition at line 165 of file SettingsService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.SingleByName().
GetFrontCanvasJson()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.GetFrontCanvasJson () inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.
Definition at line 155 of file SettingsService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.SingleByName().
GetLibraryJson()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.GetLibraryJson () inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.
Definition at line 109 of file SettingsService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.SingleByName().
GetSliderJson()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.GetSliderJson () inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.
Definition at line 144 of file SettingsService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.SingleByName().
SingleByName()
ServiceResult< SettingsVM > Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.SingleByName (string name, int? clientId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.
Definition at line 96 of file SettingsService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.GetBackCanvasJson(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService.GetCampaignsForProfile(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.GetFrontCanvasJson(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.GetLibraryJson(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.GetSliderJson(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.UpdateCanvasJson(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.UpdateLibraryJson(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.UpdateSliderJson().
UpdateCanvasJson()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.UpdateCanvasJson (string value, string place) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.
Definition at line 176 of file SettingsService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.AddOrUpdate(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.SingleByName().
UpdateLibraryJson()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.UpdateLibraryJson (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.
Definition at line 119 of file SettingsService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.AddOrUpdate(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.SingleByName().
UpdateSliderJson()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.UpdateSliderJson (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.
Definition at line 132 of file SettingsService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.AddOrUpdate(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.SingleByName().
The documentation for this class was generated from the following file:
Source/API/Services/SettingsService.cs