AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService Interface Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService Interface Reference
Public Member Functions
Task< ServiceResult< SettingsVM > > AddOrUpdate (SettingsVM settingsVM)
ServiceResult< SettingsVM > SingleByName (string name, int? clientId)
ServiceResult< string > GetLibraryJson ()
Task< ServiceResult< string > > UpdateLibraryJson (string value)
Task< ServiceResult< string > > UpdateSliderJson (string value)
ServiceResult< string > GetSliderJson ()
ServiceResult< string > GetFrontCanvasJson ()
ServiceResult< string > GetBackCanvasJson ()
Task< ServiceResult< string > > UpdateCanvasJson (string value, string place)
Detailed Description
Definition at line 21 of file SettingsService.cs.
Member Function Documentation
AddOrUpdate()
Task< ServiceResult< SettingsVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.AddOrUpdate (SettingsVM settingsVM)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.
GetBackCanvasJson()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.GetBackCanvasJson ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.
GetFrontCanvasJson()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.GetFrontCanvasJson ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.
GetLibraryJson()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.GetLibraryJson ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.
GetSliderJson()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.GetSliderJson ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.
SingleByName()
ServiceResult< SettingsVM > Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.SingleByName (string name, int? clientId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetFromEmailAddress(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapScheduleToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SendTestEmail(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UpdateMAML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateNameAndContentUrls(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateUserCampaign().
UpdateCanvasJson()
Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.UpdateCanvasJson (string value, string place)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.
UpdateLibraryJson()
Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.UpdateLibraryJson (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.
UpdateSliderJson()
Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.UpdateSliderJson (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.
The documentation for this interface was generated from the following file:
Source/API/Services/SettingsService.cs