AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable Class Reference
Public Member Functions
ContactCSVTable ()
ContactCSVTable (string csv, string rowSeparator="\n", string fieldSeparator=",")
ContactCSVTable (string csv, List< ContactFieldMappingVM > mapping, ImportContactsType importContactsType, string rowSeparator="\n", string fieldSeparator=",")
ServiceResult< string > CollectionFieldsInsert (CollectionField field, string newValue, string oldValue)
ServiceResult< string > CollectionFieldsDelete (CollectionField field, string oldValue)
ServiceResult< string > CollectionFieldsReplace (CollectionField field, string newValue, string oldValue)
ServiceResult< string > CountContacts (ContactCSVTable csv, int maxContacts)
ServiceResult< string > ReplaceHeader ()
ServiceResult< string > FormatDateFields ()
ServiceResult< string > SetDateField (string field)
ServiceResult< string > SetStateField (IReadOnlyCollection< StateVM > states, string field="State")
ServiceResult< string > SetSource (string source)
Add ContsctSource column if it does'n exist and fill it with selected source.
ServiceResult< string > SetAccountId (string clientName="")
ServiceResult< string > CheckImportType ()
ServiceResult< string > ValidateCSV (string clientName, ImportContactsType importContactsType)
ServiceResult< string > ValidateRow (int rowIndex, string clientName, ImportContactsType importContactsType)
ServiceResult< string > GetErrorRows (string csv)
ServiceResult< List< ContactVM > > ToContactList ()
ServiceResult< ContactVM > ToSingleContact ()
ServiceResult< string > AddContactList (IEnumerable< ContactVM > contacts, bool excludeProperties)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable
CSVTable (string rowSeparator="\n", string fieldSeparator=",")
Constructor 1.
CSVTable (string csv, string rowSeparator="\n", string fieldSeparator=",")
Constructor 2 (with csv string)
void LoadCSV (string csv)
Load csv data from string.
string ToCSV (string rowSeparator, string fieldSeparator)
To csv.
string ToCSV ()
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >
Table ()
int GetColumnNo (string columnName)
T[] Row (int row)
T[][] AllRows ()
T[] Column (int no)
T[] Column (string columnName)
T Data (int row, int columnNo)
T Data (int row, string columnName)
T DataOrDefault (int row, string columnName)
string[] Header ()
void SetValue (int row, int columnNo, T value)
Set value for specific field.
void SetValue (int row, string columnName, T value)
Set value for specific field.
bool SetHeader (string[] names)
Set header.
bool SetHeader (List< string > names)
Set header.
bool DeleteRow (int row)
Delete row.
bool AppendRow (List< T > data)
Append row.
bool InsertRow (int index, List< T > data)
Insert row.
bool DeleteColumn (string columnName)
Delete column.
bool DeleteColumn (int no)
Delete column.
bool AppendColumn (string columnName, List< T > data)
bool InsertEmptyValues ()
check if there are fields without "" (that are null)
Properties
List< ContactFieldMappingVM > Mapping [get]
Dictionary< int, string > ErrorLog [get, set]
ImportContactsType ImportContactsType [get]
List< ContactVM > ContactList [get, set]
ContactVM Contact [get, set]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >
int Columns [get]
int Rows [get]
Private Member Functions
ServiceResult< string > DeleteColumnsFromCSV ()
void CheckStringProperty (PropertyInfo propertyInfo, int index, string value, string clientName)
void CheckDateTimeProperty (PropertyInfo propertyInfo, int index, string value)
void CheckIntegerProperty (PropertyInfo propertyInfo, int index, string value)
void CheckBooleanProperty (PropertyInfo propertyInfo, int index, string value)
ContactVM CreateContact (int rowNo)
void AppendRow (ContactVM model)
Static Private Member Functions
static bool IsNullableType (Type type)
static void SetValue (ContactVM model, string propertyName, object value)
Additional Inherited Members
Protected Attributes inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable
string _fieldSeparator
Field separator property.
string _rowSeparator
Row separator property.
Protected Attributes inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >
List< List< T > > _data
List< string > _header
Detailed Description
Definition at line 14 of file ContactCSVTable.cs.
Constructor & Destructor Documentation
ContactCSVTable() [1/3]
Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactCSVTable () inline
Definition at line 40 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.Contact, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactList, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ErrorLog, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.Mapping.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.GetErrorRows().
ContactCSVTable() [2/3]
Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactCSVTable (string csv, string rowSeparator = "\n", string fieldSeparator = ",") inline
Definition at line 47 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.Contact, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactList, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ErrorLog, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.Mapping.
ContactCSVTable() [3/3]
Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactCSVTable (string csv, List< ContactFieldMappingVM > mapping, ImportContactsType importContactsType, string rowSeparator = "\n", string fieldSeparator = ",") inline
Definition at line 54 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.Contact, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactList, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ErrorLog, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.Mapping.
Member Function Documentation
AddContactList()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.AddContactList (IEnumerable< ContactVM > contacts, bool excludeProperties) inline
Parameters
contacts
excludeProperties
Returns
Definition at line 715 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >._header, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.AppendRow(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetPropertyNames().
AppendRow()
void Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.AppendRow (ContactVM model) inline private
Parameters
model
Definition at line 699 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.AppendRow(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Header().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.AddContactList(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.AppendRow().
CheckBooleanProperty()
void Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CheckBooleanProperty (PropertyInfo propertyInfo, int index, string value) inline private
Parameters
propertyInfo
index
value
Definition at line 615 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ErrorLog.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ValidateRow().
CheckDateTimeProperty()
void Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CheckDateTimeProperty (PropertyInfo propertyInfo, int index, string value) inline private
Parameters
propertyInfo
index
value
Definition at line 589 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ErrorLog.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ValidateRow().
CheckImportType()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CheckImportType () inline
Returns
Definition at line 370 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.GetColumnNo().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatCSV().
CheckIntegerProperty()
void Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CheckIntegerProperty (PropertyInfo propertyInfo, int index, string value) inline private
Parameters
propertyInfo
index
value
Definition at line 602 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ErrorLog.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ValidateRow().
CheckStringProperty()
void Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CheckStringProperty (PropertyInfo propertyInfo, int index, string value, string clientName) inline private
Parameters
propertyInfo
index
value
Definition at line 503 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ErrorLog.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ValidateRow().
CollectionFieldsDelete()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CollectionFieldsDelete (CollectionField field, string oldValue) inline
Parameters
field
oldValue
Returns
Definition at line 97 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.GetColumnNo(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Rows, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetValue().
CollectionFieldsInsert()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CollectionFieldsInsert (CollectionField field, string newValue, string oldValue) inline
Parameters
field
newValue
oldValue
Returns
Definition at line 70 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.GetColumnNo(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Rows, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetValue().
CollectionFieldsReplace()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CollectionFieldsReplace (CollectionField field, string newValue, string oldValue) inline
Parameters
field
newValue
oldValue
Returns
Definition at line 117 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.GetColumnNo(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Rows, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetValue().
CountContacts()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CountContacts (ContactCSVTable csv, int maxContacts) inline
Parameters
csv
maxContacts
Returns
Definition at line 143 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Column(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Column().
CreateContact()
ContactVM Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CreateContact (int rowNo) inline private
Parameters
rowNo
Returns
Definition at line 662 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >._header, Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Columns, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetValue().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ToContactList(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ToSingleContact().
DeleteColumnsFromCSV()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.DeleteColumnsFromCSV () inline private
Returns
Definition at line 187 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.DeleteColumn(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.Mapping.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ReplaceHeader().
FormatDateFields()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.FormatDateFields () inline
Returns
Definition at line 200 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.GetColumnNo(), Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetDateFields(), Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.Replace, Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Rows, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetValue().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatCSV().
GetErrorRows()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.GetErrorRows (string csv) inline
Parameters
csv
Returns
Definition at line 477 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable._fieldSeparator, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable._rowSeparator, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactCSVTable(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ErrorLog.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetErrorCSV().
IsNullableType()
static bool Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.IsNullableType (Type type) inline static private
Parameters
type
Returns
Definition at line 627 of file ContactCSVTable.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetValue().
ReplaceHeader()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ReplaceHeader () inline
Returns
Definition at line 163 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >._header, Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Columns, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.DeleteColumnsFromCSV(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.Mapping.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatCSV().
SetAccountId()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetAccountId (string clientName = "") inline
Returns
Definition at line 312 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.AppendColumn(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.GetColumnNo(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.HashHelper.GetHashCode(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Rows, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetValue().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatCSV().
SetDateField()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetDateField (string field) inline
Parameters
field
Returns
Definition at line 220 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.AppendColumn(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.GetColumnNo(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Rows, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetValue().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatCSV().
SetSource()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetSource (string source) inline
Add ContsctSource column if it does'n exist and fill it with selected source.
Parameters
source
Returns
Definition at line 285 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.AppendColumn(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.GetColumnNo(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Rows, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetValue().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatCSV().
SetStateField()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetStateField (IReadOnlyCollection< StateVM > states, string field = "State") inline
Parameters
states
field
Returns
Definition at line 252 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ErrorLog, Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.GetColumnNo(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Rows, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetValue().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatCSV().
SetValue()
static void Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetValue (ContactVM model, string propertyName, object value) inline static private
Parameters
model
propertyName
value
Definition at line 638 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.IsNullableType().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CollectionFieldsDelete(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CollectionFieldsInsert(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CollectionFieldsReplace(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CreateContact(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.FormatDateFields(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetAccountId(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetDateField(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetSource(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetStateField().
ToContactList()
ServiceResult< List< ContactVM > > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ToContactList () inline
Returns
Definition at line 676 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >._data, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactList, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CreateContact().
ToSingleContact()
ServiceResult< ContactVM > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ToSingleContact () inline
Returns
Definition at line 690 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.Contact, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CreateContact().
ValidateCSV()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ValidateCSV (string clientName, ImportContactsType importContactsType) inline
Returns
Definition at line 383 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.DeleteRow(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ErrorLog, Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Rows, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ValidateRow().
ValidateRow()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ValidateRow (int rowIndex, string clientName, ImportContactsType importContactsType) inline
Parameters
rowIndex
Returns
Definition at line 403 of file ContactCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >._header, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CheckBooleanProperty(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CheckDateTimeProperty(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CheckIntegerProperty(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CheckStringProperty(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Columns, Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.DataOrDefault(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ErrorLog.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ValidateCSV().
Property Documentation
Contact
ContactVM Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.Contact get set private
Definition at line 32 of file ContactCSVTable.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactCSVTable(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactCSVTable(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactCSVTable(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ToSingleContact().
ContactList
List<ContactVM> Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactList get set private
Definition at line 28 of file ContactCSVTable.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactCSVTable(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactCSVTable(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactCSVTable(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ToContactList().
ErrorLog
Dictionary<int, string> Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ErrorLog get set
Definition at line 20 of file ContactCSVTable.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CheckBooleanProperty(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CheckDateTimeProperty(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CheckIntegerProperty(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CheckStringProperty(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactCSVTable(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactCSVTable(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactCSVTable(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetErrorCSV(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.GetErrorRows(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetStateField(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ValidateCSV(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ValidateRow().
ImportContactsType
ImportContactsType Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ImportContactsType get
Definition at line 24 of file ContactCSVTable.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatCSV().
Mapping
List<ContactFieldMappingVM> Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.Mapping get
Definition at line 16 of file ContactCSVTable.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactCSVTable(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactCSVTable(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ContactCSVTable(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.DeleteColumnsFromCSV(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ReplaceHeader().
The documentation for this class was generated from the following file:
Source/Domain/Utility/ContactCSVTable.cs