AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService Class Reference
Public Member Functions
SessionService ()
SessionService (IHttpContextAccessor httpContextAccessor, IServiceProvider serviceProvider, IConfiguration configuration)
void SetUserId (string userId)
virtual ApplicationUser SessionGetUser ()
string GetSessionString (string key)
int? GetSessionInt32 (string key)
string SessionGetUserId ()
string SessionGetClientName ()
string SessionGetMFAccountNamePrefix ()
string SessionGetMFDomain ()
string SessionGetMFAccountId ()
string SessionGetRootUrl ()
string SessionGetDefaultUserType ()
string SessionGetS3Bucket ()
string SessionGetTechnicalSupportPhone ()
string SessionGetDefaultFromAddress ()
string SessionGetCompanyId ()
string SessionGetTenant ()
int? SessionGetClientId ()
int? SessionGetMFMasterAccountId ()
int? SessionGetUserCreditCard ()
int? SessionGetDeadlineForSubscription ()
int? SessionGetMaxContacts ()
int? SessionGetMaxPersonas ()
string SessionGetGlobalFormId ()
string SessionGetSFAuthToken ()
string SessionGetSFInstance ()
string SessionGetSFRefreshToken ()
string SessionGetSFApiVersion ()
string SessionGetUserEmail ()
bool SetSessionString (string key, string value)
bool SetSessionInt32 (string key, int value)
bool SessionSetUserId (string value)
bool SessionSetClientName (string value)
bool SessionSetMFAccountNamePrefix (string value)
bool SessionSetMFDomain (string value)
bool SessionSetMFAccountId (string value)
bool SessionSetRootUrl (string value)
bool SessionSetDefaultUserType (string value)
bool SessionSetS3Bucket (string value)
bool SessionSetTechnicalSupportPhone (string value)
bool SessionSetDefaultFromAddress (string value)
bool SessionSetCompanyId (string value)
bool SessionSetTenant (string value)
bool SessionSetClientId (int value)
bool SessionSetMFMasterAccountId (int value)
bool SessionSetUserCreditCard (int value)
bool SessionSetDeadlineForSubscription (int value)
bool SessionSetMaxContacts (int value)
bool SessionSetMaxPersonas (int value)
bool SessionSetGlobalFormId (string value)
bool SessionSetSFAuthToken (string value)
bool SessionSetSFInstance (string value)
bool SessionSetSFRefreshToken (string value)
bool SessionSetSFApiVersion (string value)
bool SessionGetUserEmail (string value)
void ClearSessionVariables ()
bool SetSessionVariables (ClientVM client, ApplicationUser user)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService
Public Attributes
readonly IHttpContextAccessor _httpContextAccessor
string userId
Properties
ApplicationDbContext _dbContext [get]
IJobPoolService _jobPoolService [get]
HttpContext HttpContext [get]
ISession _session [get]
ISession Session [get]
bool Ephemeral [get, set]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService
Private Member Functions
ISession GetSession ()
Private Attributes
readonly IServiceProvider _serviceProvider
readonly IConfiguration _configuration
DictionarySession dictionarySession
bool _ephemeral = false
Detailed Description
Definition at line 16 of file SessionService.cs.
Constructor & Destructor Documentation
SessionService() [1/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionService () inline
Definition at line 52 of file SessionService.cs.
SessionService() [2/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionService (IHttpContextAccessor httpContextAccessor, IServiceProvider serviceProvider, IConfiguration configuration) inline
Definition at line 56 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._configuration, Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._httpContextAccessor, and Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._serviceProvider.
Member Function Documentation
ClearSessionVariables()
void Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.ClearSessionVariables () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 392 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.GetSession().
GetSession()
ISession Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.GetSession () inline private
Definition at line 28 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._configuration, Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._jobPoolService, Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.dictionarySession, Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.Ephemeral, Deluxe.DeluxeBrandCenter.AMM.Domain.Services.IJobPoolService.GetCurrentJobRunner(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.HttpContext, and Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.userId.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.ClearSessionVariables().
GetSessionInt32()
int? Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.GetSessionInt32 (string key) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 123 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
GetSessionString()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.GetSessionString (string key) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 118 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetClientId()
int? Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetClientId () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 188 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetClientName()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetClientName () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 133 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetCompanyId()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetCompanyId () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 178 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetDeadlineForSubscription()
int? Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetDeadlineForSubscription () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 203 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetDefaultFromAddress()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetDefaultFromAddress () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 173 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetDefaultUserType()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetDefaultUserType () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 158 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetGlobalFormId()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetGlobalFormId () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 218 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetMaxContacts()
int? Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetMaxContacts () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 208 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetMaxPersonas()
int? Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetMaxPersonas () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 213 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetMFAccountId()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetMFAccountId () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 148 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetMFAccountNamePrefix()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetMFAccountNamePrefix () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 138 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetMFDomain()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetMFDomain () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 143 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetMFMasterAccountId()
int? Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetMFMasterAccountId () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 193 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetRootUrl()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetRootUrl () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 153 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetS3Bucket()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetS3Bucket () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 163 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetSFApiVersion()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetSFApiVersion () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 238 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetSFAuthToken()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetSFAuthToken () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 223 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetSFInstance()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetSFInstance () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 228 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetSFRefreshToken()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetSFRefreshToken () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 233 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetTechnicalSupportPhone()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetTechnicalSupportPhone () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 168 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetTenant()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetTenant () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 183 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetUser()
virtual ApplicationUser Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetUser () inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 107 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session, Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.userId, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.Users.
SessionGetUserCreditCard()
int? Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetUserCreditCard () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 198 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetUserEmail() [1/2]
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetUserEmail () inline
Definition at line 243 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionGetUserEmail() [2/2]
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetUserEmail (string value) inline
Definition at line 385 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionGetUserId()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetUserId () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 128 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
SessionSetClientId()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetClientId (int value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 330 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionInt32().
SessionSetClientName()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetClientName (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 275 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionSetCompanyId()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetCompanyId (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 320 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionSetDeadlineForSubscription()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetDeadlineForSubscription (int value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 345 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionInt32().
SessionSetDefaultFromAddress()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetDefaultFromAddress (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 315 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionSetDefaultUserType()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetDefaultUserType (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 300 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionSetGlobalFormId()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetGlobalFormId (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 360 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionSetMaxContacts()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetMaxContacts (int value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 350 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionInt32().
SessionSetMaxPersonas()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetMaxPersonas (int value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 355 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionInt32().
SessionSetMFAccountId()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetMFAccountId (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 290 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionSetMFAccountNamePrefix()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetMFAccountNamePrefix (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 280 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionSetMFDomain()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetMFDomain (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 285 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionSetMFMasterAccountId()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetMFMasterAccountId (int value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 335 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionInt32().
SessionSetRootUrl()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetRootUrl (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 295 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionSetS3Bucket()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetS3Bucket (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 305 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionSetSFApiVersion()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetSFApiVersion (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 380 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionSetSFAuthToken()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetSFAuthToken (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 365 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionSetSFInstance()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetSFInstance (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 370 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionSetSFRefreshToken()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetSFRefreshToken (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 375 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionSetTechnicalSupportPhone()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetTechnicalSupportPhone (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 310 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionSetTenant()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetTenant (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 325 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SessionSetUserCreditCard()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetUserCreditCard (int value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 340 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionInt32().
SessionSetUserId()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetUserId (string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 270 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString().
SetSessionInt32()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionInt32 (string key, int value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 260 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetClientId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetDeadlineForSubscription(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetMaxContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetMaxPersonas(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetMFMasterAccountId(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetUserCreditCard().
SetSessionString()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString (string key, string value) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 250 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetUserEmail(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetClientName(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetCompanyId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetDefaultFromAddress(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetDefaultUserType(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetGlobalFormId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetMFAccountId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetMFAccountNamePrefix(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetMFDomain(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetRootUrl(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetS3Bucket(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetSFApiVersion(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetSFAuthToken(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetSFInstance(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetSFRefreshToken(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetTechnicalSupportPhone(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetTenant(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionSetUserId().
SetSessionVariables()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionVariables (ClientVM client, ApplicationUser user) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 397 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ClientVM.CompanyId, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ClientVM.DeadlineForSubscription, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ClientVM.DefaultFromAddress, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ClientVM.DefaultUserType, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ClientVM.GlobalFormId, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityVM.Id, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ClientVM.MaxContacts, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ClientVM.MaxPersonas, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ClientVM.MFAccountNamePrefix, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ClientVM.MFDomain, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ClientVM.MFMasterAccountId, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityNamedVM.Name, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ClientVM.RootUrl, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ClientVM.S3Bucket, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ClientVM.TechnicalSupportPhone, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ClientVM.Tenant, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ClientVM.UserCreditCard.
SetUserId()
void Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetUserId (string userId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 67 of file SessionService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.userId.
Member Data Documentation
_configuration
readonly IConfiguration Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._configuration private
Definition at line 20 of file SessionService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.GetSession(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionService().
_ephemeral
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._ephemeral = false private
Definition at line 72 of file SessionService.cs.
_httpContextAccessor
readonly IHttpContextAccessor Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._httpContextAccessor
Definition at line 19 of file SessionService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionService().
_serviceProvider
readonly IServiceProvider Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._serviceProvider private
Definition at line 18 of file SessionService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionService().
dictionarySession
DictionarySession Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.dictionarySession private
Definition at line 22 of file SessionService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.GetSession().
userId
string Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.userId
Definition at line 21 of file SessionService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.GetSession(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetUser(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetUserId().
Property Documentation
_dbContext
ApplicationDbContext Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._dbContext get private
Definition at line 24 of file SessionService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.GetSession(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetUser().
_jobPoolService
IJobPoolService Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._jobPoolService get private
Definition at line 25 of file SessionService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.GetSession().
_session
ISession Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService._session get
Definition at line 51 of file SessionService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.GetSessionInt32(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.GetSessionString(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetClientId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetClientName(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetCompanyId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetDeadlineForSubscription(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetDefaultFromAddress(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetDefaultUserType(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetGlobalFormId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetMaxContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetMaxPersonas(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetMFAccountId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetMFAccountNamePrefix(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetMFDomain(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetMFMasterAccountId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetRootUrl(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetS3Bucket(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetSFApiVersion(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetSFAuthToken(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetSFInstance(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetSFRefreshToken(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetTechnicalSupportPhone(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetTenant(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetUser(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetUserCreditCard(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetUserEmail(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SessionGetUserId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionInt32(), Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionString(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.SetSessionVariables().
Ephemeral
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.Ephemeral get set
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 74 of file SessionService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.GetSession().
HttpContext
HttpContext Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.HttpContext get
Definition at line 26 of file SessionService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.GetSession().
Session
ISession Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.Session get
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.
Definition at line 65 of file SessionService.cs.
The documentation for this class was generated from the following file:
Source/API/Services/SessionService.cs