AMM: Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< TService > Class Template Reference
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< TService > Class Template Reference
Root Controller.
Public Member Functions
RootController ()
Empty Root Controller Constructor.
RootController (TService service)
Root Controller Constructor.
Protected Member Functions
ControllerResult< Guid > StartJob< T > (Func< IServiceProvider, Task< T > > func, IJobPoolService jobPoolService)
ControllerResult< JobVM< T > > GetJob< T > (Guid id, IJobPoolService jobPoolService)
ControllerResult< JobVM< T > > GetJobServiceResult< T > (Guid id, IJobPoolService jobPoolService)
ControllerResult< JobVM< T > > GetJobApiResponse< T > (Guid id, IJobPoolService jobPoolService)
Properties
TService service [get]
Base service for controller.
Static Private Member Functions
static ControllerResult< JobVM< T > > GetJob< S, T > (Guid id, IJobPoolService jobPoolService, Func< Job< S >, ControllerResult< JobVM< T > > > getResult)
Detailed Description
Root Controller.
Template Parameters
TService Base service
Definition at line 22 of file RootController.cs.
Constructor & Destructor Documentation
RootController() [1/2]
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< TService >.RootController () inline
Empty Root Controller Constructor.
Definition at line 34 of file RootController.cs.
RootController() [2/2]
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< TService >.RootController (TService service) inline
Root Controller Constructor.
Parameters
service
Definition at line 43 of file RootController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< TService >.service.
Member Function Documentation
GetJob< S, T >()
static ControllerResult< JobVM< T > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< TService >.GetJob< S, T > (Guid id, IJobPoolService jobPoolService, Func< Job< S >, ControllerResult< JobVM< T > > > getResult) inline static private
Type Constraints
S : class
T : class
Definition at line 61 of file RootController.cs.
GetJob< T >()
ControllerResult< JobVM< T > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< TService >.GetJob< T > (Guid id, IJobPoolService jobPoolService) inline protected
Type Constraints
T : class
Definition at line 75 of file RootController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From().
GetJobApiResponse< T >()
ControllerResult< JobVM< T > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< TService >.GetJobApiResponse< T > (Guid id, IJobPoolService jobPoolService) inline protected
Type Constraints
T : class
Definition at line 85 of file RootController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From().
GetJobServiceResult< T >()
ControllerResult< JobVM< T > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< TService >.GetJobServiceResult< T > (Guid id, IJobPoolService jobPoolService) inline protected
Type Constraints
T : class
Definition at line 80 of file RootController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From().
StartJob< T >()
ControllerResult< Guid > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< TService >.StartJob< T > (Func< IServiceProvider, Task< T > > func, IJobPoolService jobPoolService) inline protected
Template Parameters
T
Parameters
func
jobPoolService
Returns
Type Constraints
T : class
Definition at line 55 of file RootController.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.Session.
Property Documentation
service
TService Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< TService >.service get
Base service for controller.
Definition at line 27 of file RootController.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< TService >.RootController().
The documentation for this class was generated from the following file:
Source/API/Controllers/RootController.cs