AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService Interface Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService Interface Reference
Public Member Functions
ServiceResult< string > Auth (int clientId)
ServiceResult< IAuthenticatedUser > GetProfile (TwitterAccount twitterAccount)
Task< ServiceResult< string > > PublishTweet (SocialContent socialContent, SocialAccount socialAccount, string socialToken)
Task< bool > DoesExist (Expression< Func< TwitterAccount, bool > > predicate)
Task< ServiceResult< TwitterAccountVM > > Remove (UnlinkSocialVM unlinkSocialVM)
Task< ServiceResult< List< TwitterAccount > > > GetBySocialToken (string socialToken)
Task< ServiceResult< SocialAccountInfoVM > > GetSocailAccountInfo (string verifierCode, string authorizationId, string clientName)
Task< ServiceResult< string > > SaveCredentials (SocialAccountInfoVM socialAccountInfo, int clientId)
Detailed Description
Definition at line 26 of file TwitterService.cs.
Member Function Documentation
Auth()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.Auth (int clientId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.SocialAuthorization().
DoesExist()
Task< bool > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.DoesExist (Expression< Func< TwitterAccount, bool > > predicate)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckSocialForUser(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.UnlinkFromSocial().
GetBySocialToken()
Task< ServiceResult< List< TwitterAccount > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.GetBySocialToken (string socialToken)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckSocialForUser().
GetProfile()
ServiceResult< IAuthenticatedUser > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.GetProfile (TwitterAccount twitterAccount)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckSocialForUser().
GetSocailAccountInfo()
Task< ServiceResult< SocialAccountInfoVM > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.GetSocailAccountInfo (string verifierCode, string authorizationId, string clientName)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.GetTwitterAccountInfo().
PublishTweet()
Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.PublishTweet (SocialContent socialContent, SocialAccount socialAccount, string socialToken)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Sharing().
Remove()
Task< ServiceResult< TwitterAccountVM > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.Remove (UnlinkSocialVM unlinkSocialVM)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckSocialForUser(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.UnlinkFromSocial().
SaveCredentials()
Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.SaveCredentials (SocialAccountInfoVM socialAccountInfo, int clientId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.SaveCredentials().
The documentation for this interface was generated from the following file:
Source/Infrastructure/Social/TwitterService.cs