AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService Interface Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService Interface Reference
Public Member Functions
Task< ServiceResult< IPaginate< PMSPersonaDTO > > > GetPersonasForProfile (string userId, FilterConfiguration filterConfiguration=null)
Task< ServiceResult< PMSPersonaDTO > > GetDefaultPersonaForProfile (string userId, Audience audience)
Task< ServiceResult< PMSPersonaDTO > > GetPersonaByGUID (string personaGuid)
Task< ServiceResult< List< SimplePersonaDTO > > > GetUserPersonas (string userId)
Task< ServiceResult< PMSPersonaDTO > > Single (string id)
Task< ServiceResult< PMSPersonaDTO > > UpdateEmailSPFApproved (string personaGUID, string fieldVal)
Task< ServiceResult< List< PersonaInstanceWithNameIsDefaultDTO > > > GetPersonaInstanceNamesForCampaign (int? campaignId=0)
Task< ServiceResult< IEnumerable< string > > > GetContactIdsForUserPersonas (string userGuid)
Detailed Description
Definition at line 20 of file PersonaService.cs.
Member Function Documentation
GetContactIdsForUserPersonas()
Task< ServiceResult< IEnumerable< string > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.GetContactIdsForUserPersonas (string userGuid)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.
GetDefaultPersonaForProfile()
Task< ServiceResult< PMSPersonaDTO > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.GetDefaultPersonaForProfile (string userId, Audience audience)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetCampaign().
GetPersonaByGUID()
Task< ServiceResult< PMSPersonaDTO > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.GetPersonaByGUID (string personaGuid)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.CampaignDetails(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController.GetPersonaByGUID(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.SyncPersonaDataWithMF().
GetPersonaInstanceNamesForCampaign()
Task< ServiceResult< List< PersonaInstanceWithNameIsDefaultDTO > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.GetPersonaInstanceNamesForCampaign (int? campaignId = 0)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController.GetProfilesAndPersonas().
GetPersonasForProfile()
Task< ServiceResult< IPaginate< PMSPersonaDTO > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.GetPersonasForProfile (string userId, FilterConfiguration filterConfiguration = null)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CheckSocialAccounts(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController.GetPersonas().
GetUserPersonas()
Task< ServiceResult< List< SimplePersonaDTO > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.GetUserPersonas (string userId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.
Single()
Task< ServiceResult< PMSPersonaDTO > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.Single (string id)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapEmailElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapScheduleToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapSocialElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.PendingCampaigns(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SendTestEmail(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateNameAndContentUrls(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateUserCampaign().
UpdateEmailSPFApproved()
Task< ServiceResult< PMSPersonaDTO > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.UpdateEmailSPFApproved (string personaGUID, string fieldVal)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.
The documentation for this interface was generated from the following file:
Source/API/Services/PersonaService.cs