AMM: Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController Class Reference
Persona Controller.
Public Member Functions
PersonaController (IPersonaService pesonaService)
Persona Controller Constructor.
async Task< ControllerResult< IPaginate< PMSPersonaDTO > > > GetPersonas ([FromBody] FilterConfiguration filterConfiguration)
Get a list of all Personas.
async Task< ControllerResult< PMSPersonaDTO > > GetPersonaByGUID ([FromQuery] string personaGUID)
Get details of requested Persona from Microservice.
async Task< ControllerResult< List< PersonaInstanceWithNameIsDefaultDTO > > > GetProfilesAndPersonas ([FromQuery] int? campaignId=0)
Private Attributes
readonly IPersonaService _personaService
Detailed Description
Persona Controller.
Definition at line 21 of file PersonaController.cs.
Constructor & Destructor Documentation
PersonaController()
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController.PersonaController (IPersonaService pesonaService) inline
Persona Controller Constructor.
Parameters
pesonaService Persona service
Definition at line 27 of file PersonaController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController._personaService.
Member Function Documentation
GetPersonaByGUID()
async Task< ControllerResult< PMSPersonaDTO > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController.GetPersonaByGUID ([FromQuery] string personaGUID) inline
Get details of requested Persona from Microservice.
Returns
Details of requested Persona
<response code = "200"> Persona or Error message</response>
Definition at line 51 of file PersonaController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController._personaService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.GetPersonaByGUID().
GetPersonas()
async Task< ControllerResult< IPaginate< PMSPersonaDTO > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController.GetPersonas ([FromBody] FilterConfiguration filterConfiguration) inline
Get a list of all Personas.
Returns
List of all Personas
<response code = "200">List of all Personas or Error message</response>
Definition at line 40 of file PersonaController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController._personaService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.GetPersonasForProfile().
GetProfilesAndPersonas()
async Task< ControllerResult< List< PersonaInstanceWithNameIsDefaultDTO > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController.GetProfilesAndPersonas ([FromQuery] int? campaignId = 0) inline
Returns
Definition at line 61 of file PersonaController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController._personaService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.GetPersonaInstanceNamesForCampaign().
Member Data Documentation
_personaService
readonly IPersonaService Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController._personaService private
Definition at line 32 of file PersonaController.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController.GetPersonaByGUID(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController.GetPersonas(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController.GetProfilesAndPersonas(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.PersonaController.PersonaController().
The documentation for this class was generated from the following file:
Source/API/Controllers/PersonaController.cs