AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.IStateService Interface Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.IStateService Interface Reference
Public Member Functions
ServiceResult< IReadOnlyCollection< StateVM > > GetStates (bool returnCanadian=false)
Detailed Description
Definition at line 14 of file StateService.cs.
Member Function Documentation
GetStates()
ServiceResult< IReadOnlyCollection< StateVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IStateService.GetStates (bool returnCanadian = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.StateService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GenerateGroupCreationOptions(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController.GetCanadianProvinces(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController.GetStates().
The documentation for this interface was generated from the following file:
Source/API/Services/StateService.cs