AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util Class Reference
Classes
class DateTimeUtils
class Email
class String
class Tags
class XML
Static Public Member Functions
static string ExcludeImgFromString (this string htmlContent, string hashTagImage)
static string GetExceptionMessage (Exception exception)
static string GetInnerException (Exception exception)
static object ChangeType (object value, Type conversion)
static string FormatBoolYesNo (this string value)
static string ToBase64Encode (this string plainText)
static string ToBase64Decode (this string base64EncodedData)
static bool CheckIfStringIsURL (this string link)
static string CheckMimeType (this string filename)
static bool IsBase64String (this string s)
static string BlogCurrentTimeFormat ()
static string RemoveUrlSrc (this string xmlValue)
static string GetFilenameForS3 (this string linkS3, string bucketS3, bool withSubFolders=true)
static ? int FirstIndexMatch (this IEnumerable< string > data, string value)
static string ReplaceStageFolder (this IConfiguration configuration, string url)
static string ReplaceStageFolder (this string url, string stageFolder)
static string RemoveSpecialCharacters (this string str)
static string GetThumbnail (this string path)
Detailed Description
Definition at line 14 of file Utility.cs.
Member Function Documentation
BlogCurrentTimeFormat()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.BlogCurrentTimeFormat () inline static
Definition at line 135 of file Utility.cs.
ChangeType()
static object Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ChangeType (object value, Type conversion) inline static
Definition at line 71 of file Utility.cs.
CheckIfStringIsURL()
static bool Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.CheckIfStringIsURL (this string link) inline static
Definition at line 118 of file Utility.cs.
CheckMimeType()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.CheckMimeType (this string filename) inline static
Definition at line 123 of file Utility.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishImage(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishVideo().
ExcludeImgFromString()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ExcludeImgFromString (this string htmlContent, string hashTagImage) inline static
Definition at line 16 of file Utility.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.FillHtmlWithPersonalInfo().
FirstIndexMatch()
static ? int Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.FirstIndexMatch (this IEnumerable< string > data, string value) inline static
Definition at line 150 of file Utility.cs.
FormatBoolYesNo()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.FormatBoolYesNo (this string value) inline static
Definition at line 103 of file Utility.cs.
GetExceptionMessage()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.GetExceptionMessage (Exception exception) inline static
Definition at line 51 of file Utility.cs.
GetFilenameForS3()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.GetFilenameForS3 (this string linkS3, string bucketS3, bool withSubFolders = true) inline static
Definition at line 145 of file Utility.cs.
GetInnerException()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.GetInnerException (Exception exception) inline static
Definition at line 61 of file Utility.cs.
GetThumbnail()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.GetThumbnail (this string path) inline static
Definition at line 179 of file Utility.cs.
IsBase64String()
static bool Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.IsBase64String (this string s) inline static
Definition at line 128 of file Utility.cs.
RemoveSpecialCharacters()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.RemoveSpecialCharacters (this string str) inline static
Definition at line 165 of file Utility.cs.
RemoveUrlSrc()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.RemoveUrlSrc (this string xmlValue) inline static
Definition at line 140 of file Utility.cs.
ReplaceStageFolder() [1/2]
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ReplaceStageFolder (this IConfiguration configuration, string url) inline static
Definition at line 155 of file Utility.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.FillRuleGroup(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapEmailElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapMicrositeElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapSocialElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToEmailElement(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToSocialElement(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.ParseHtmlForSelectedArticle(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetMessageBody(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateContentUrls(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateNameAndContentUrls().
ReplaceStageFolder() [2/2]
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ReplaceStageFolder (this string url, string stageFolder) inline static
Definition at line 160 of file Utility.cs.
ToBase64Decode()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ToBase64Decode (this string base64EncodedData) inline static
Definition at line 113 of file Utility.cs.
ToBase64Encode()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ToBase64Encode (this string plainText) inline static
Definition at line 108 of file Utility.cs.
The documentation for this class was generated from the following file:
Source/Domain/Utility/Utility.cs