AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService Class Reference
Public Member Functions
PersonaService ()
PersonaService (ApplicationDbContext dbContext, IPersonaMicroservice personaMicroservice, IHttpContextAccessor httpContextAccessor, ISessionService sessionService)
async Task< ApplicationUser > GetUser ()
async Task< ServiceResult< IPaginate< PMSPersonaDTO > > > GetPersonasForProfile (string userId, FilterConfiguration filterConfiguration=null)
async Task< ServiceResult< PMSPersonaDTO > > GetDefaultPersonaForProfile (string userId, Audience audience)
async Task< ServiceResult< PMSPersonaDTO > > UpdateEmailSPFApproved (string personaGUID, string fieldVal)
async Task< ServiceResult< PMSPersonaDTO > > GetPersonaByGUID (string personaGuid)
async Task< ServiceResult< List< SimplePersonaDTO > > > GetUserPersonas (string userId)
async Task< ServiceResult< PMSPersonaDTO > > Single (string id)
async Task< ServiceResult< List< PersonaInstanceWithNameIsDefaultDTO > > > GetPersonaInstanceNamesForCampaign (int? campaignId=0)
async Task< ServiceResult< IEnumerable< string > > > GetContactIdsForUserPersonas (string userGuid)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService
Private Member Functions
async Task< ServiceResult< PMSPersonaDTO > > FindPersonaByType (List< SimplePersonaDTO > personas, string personaType)
async Task< ServiceResult< List< PersonaInstanceWithNameIsDefaultDTO > > > GetPersonaInstanceNamesForAudience (Audience audience)
Private Attributes
readonly IHttpContextAccessor _httpContextAccessor
readonly IPersonaMicroservice _personaMicroservice
readonly ISessionService _sessionService
readonly ApplicationDbContext _dbContext
Detailed Description
Definition at line 31 of file PersonaService.cs.
Constructor & Destructor Documentation
PersonaService() [1/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.PersonaService () inline
Definition at line 33 of file PersonaService.cs.
PersonaService() [2/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.PersonaService (ApplicationDbContext dbContext, IPersonaMicroservice personaMicroservice, IHttpContextAccessor httpContextAccessor, ISessionService sessionService) inline
Definition at line 36 of file PersonaService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._httpContextAccessor, Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._personaMicroservice, and Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._sessionService.
Member Function Documentation
FindPersonaByType()
async Task< ServiceResult< PMSPersonaDTO > > Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.FindPersonaByType (List< SimplePersonaDTO > personas, string personaType) inline private
Definition at line 211 of file PersonaService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._personaMicroservice, Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetPersonaInstance(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUserId().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetDefaultPersonaForProfile().
GetContactIdsForUserPersonas()
async Task< ServiceResult< IEnumerable< string > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetContactIdsForUserPersonas (string userGuid) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.
Definition at line 276 of file PersonaService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._personaMicroservice, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetContactIdsForUserPersonas().
GetDefaultPersonaForProfile()
async Task< ServiceResult< PMSPersonaDTO > > Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetDefaultPersonaForProfile (string userId, Audience audience) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.
Definition at line 84 of file PersonaService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._personaMicroservice, Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.FindPersonaByType(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetPersonaInstance(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetPersonaInstancesForUser_Simple(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetUser().
GetPersonaByGUID()
async Task< ServiceResult< PMSPersonaDTO > > Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonaByGUID (string personaGuid) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.
Definition at line 168 of file PersonaService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._personaMicroservice, Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetPersonaInstance(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUserId().
GetPersonaInstanceNamesForAudience()
async Task< ServiceResult< List< PersonaInstanceWithNameIsDefaultDTO > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonaInstanceNamesForAudience (Audience audience) inline private
Definition at line 245 of file PersonaService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._personaMicroservice, Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetPersonaInstanceNamesForUser(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUserId().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonaInstanceNamesForCampaign().
GetPersonaInstanceNamesForCampaign()
async Task< ServiceResult< List< PersonaInstanceWithNameIsDefaultDTO > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonaInstanceNamesForCampaign (int? campaignId = 0) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.
Definition at line 227 of file PersonaService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.Campaigns, and Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonaInstanceNamesForAudience().
GetPersonasForProfile()
async Task< ServiceResult< IPaginate< PMSPersonaDTO > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonasForProfile (string userId, FilterConfiguration filterConfiguration = null) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.
Definition at line 59 of file PersonaService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._personaMicroservice, Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetPersonaInstance(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetPersonaInstancesForUser_Simple(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUserId().
GetUser()
async Task< ApplicationUser > Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetUser () inline
Definition at line 52 of file PersonaService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._httpContextAccessor, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.Users.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetDefaultPersonaForProfile().
GetUserPersonas()
async Task< ServiceResult< List< SimplePersonaDTO > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetUserPersonas (string userId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.
Definition at line 184 of file PersonaService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._personaMicroservice, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetPersonaInstancesForUser_Simple().
Single()
async Task< ServiceResult< PMSPersonaDTO > > Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.Single (string id) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.
Definition at line 200 of file PersonaService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._personaMicroservice, Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetPersonaInstance(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUserId().
UpdateEmailSPFApproved()
async Task< ServiceResult< PMSPersonaDTO > > Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.UpdateEmailSPFApproved (string personaGUID, string fieldVal) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.
Definition at line 145 of file PersonaService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._personaMicroservice, Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetCustomFieldsForPersona(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetGlobalFormId(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.UpdatePersonaInstanceData().
Member Data Documentation
_dbContext
readonly ApplicationDbContext Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._dbContext private
Definition at line 51 of file PersonaService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonaInstanceNamesForCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetUser(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.PersonaService().
_httpContextAccessor
readonly IHttpContextAccessor Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._httpContextAccessor private
Definition at line 48 of file PersonaService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetUser(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.PersonaService().
_personaMicroservice
readonly IPersonaMicroservice Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._personaMicroservice private
Definition at line 49 of file PersonaService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.FindPersonaByType(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetContactIdsForUserPersonas(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetDefaultPersonaForProfile(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonaByGUID(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonaInstanceNamesForAudience(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonasForProfile(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetUserPersonas(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.PersonaService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.Single(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.UpdateEmailSPFApproved().
_sessionService
readonly ISessionService Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService._sessionService private
Definition at line 50 of file PersonaService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.FindPersonaByType(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonaByGUID(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonaInstanceNamesForAudience(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonasForProfile(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.PersonaService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.Single(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.UpdateEmailSPFApproved().
The documentation for this class was generated from the following file:
Source/API/Services/PersonaService.cs