AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF Class Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF Class Reference
Public Member Functions
ProgramServiceMF (IConfiguration configuration, ISessionService sessionService, IHttpClientFactory clientFactory, ILoggerFactory loggerFactory)
async Task< ServiceResult< PublishProgramResponse > > PublishProgram (string programXML)
async Task< ServiceResult< PublishProgramResponse > > PublishProgram (RequestCredentials credentials, string programXML)
async Task< ServiceResult< UndoProgramChangesResponse > > UndoProgramChanges (RequestCredentials credentials, int programId)
async Task< ServiceResult< UndoProgramChangesResponse > > UndoProgramChanges (string ticket, int programId)
async Task< ServiceResult< UndoProgramChangesResponse > > UndoProgramChanges (int programId)
async Task< ServiceResult< ProgramCheckoutResponse > > CheckOutProgram (string ticket, int programId)
async Task< ServiceResult< ProgramCheckoutResponse > > CheckOutProgram (RequestCredentials credentials, int programId)
async Task< ServiceResult< ProgramCheckoutResponse > > CheckOutProgram (int programId)
async Task< ServiceResult< ProgramCheckinResponse > > CheckInProgram (string ticket, string programXML)
async Task< ServiceResult< ProgramCheckinResponse > > CheckInProgram (string ticket, string programXML, string comment="")
async Task< ServiceResult< ProgramCheckinResponse > > CheckInProgram (RequestCredentials credentials, string programXML, string comment="")
async Task< ServiceResult< ProgramCheckinResponse > > CheckInProgram (string programXML)
async Task< ServiceResult< GetProgramListResponse > > GetProgramList (RequestCredentials credentials, short status=255)
async Task< ServiceResult< GetProgramResponse > > GetProgram (int programId)
async Task< ServiceResult< GetProgramInfoResponse > > GetProgramInfo (int programId)
async Task< ServiceResult< GetProgramInfoResponse > > GetProgramInfo (string mfTicket, int programId)
async Task< ServiceResult< GetOutboundsScheduleListResponse > > GetOutboundsScheduleList (List< KeyValuePair< string, string > > outboundList)
Task< ServiceResult< GetProgramResponse > > GetProgram (string ticket, int programId)
async Task< ServiceResult< GetProgramResponse > > GetProgram (RequestCredentials credentials, int programId)
async Task< ServiceResult< ProgramCheckinResponse > > StopCampaign (int programId, string ticket, string comment)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService
BaseMindfireService (IConfiguration configuration, string serviceName, ISessionService sessionService, IHttpClientFactory clientFactory, ILoggerFactory loggerFactory)
async Task< TResponse > Post< TResponse > (string endpoint, object body)
async Task< TResponse > PostDashboard< TResponse > (string endpoint, object body)
async Task< TResponse > Get< TResponse > (string endpoint)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF
Additional Inherited Members
Public Attributes inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService
readonly ILogger _logger
string _accountNamePrefix
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService
ISession _session [get]
RequestCredentials masterRequestCredentials [get, set]
RequestCredentials userRequestCredentials [get, set]
IMindfireSettings configuration [get, set]
string ServiceName [get]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IBaseMindfireService
Detailed Description
Definition at line 42 of file ProgramServiceMF.cs.
Constructor & Destructor Documentation
ProgramServiceMF()
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.ProgramServiceMF (IConfiguration configuration, ISessionService sessionService, IHttpClientFactory clientFactory, ILoggerFactory loggerFactory) inline
Definition at line 44 of file ProgramServiceMF.cs.
Member Function Documentation
CheckInProgram() [1/4]
async Task< ServiceResult< ProgramCheckinResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckInProgram (RequestCredentials credentials, string programXML, string comment = "") inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 170 of file ProgramServiceMF.cs.
CheckInProgram() [2/4]
async Task< ServiceResult< ProgramCheckinResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckInProgram (string programXML) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 203 of file ProgramServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckInProgram(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
CheckInProgram() [3/4]
async Task< ServiceResult< ProgramCheckinResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckInProgram (string ticket, string programXML) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 154 of file ProgramServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckInProgram(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.configuration.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckInProgram(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckInProgram(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckInProgram(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.StopCampaign().
CheckInProgram() [4/4]
async Task< ServiceResult< ProgramCheckinResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckInProgram (string ticket, string programXML, string comment = "") inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 162 of file ProgramServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckInProgram(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.configuration.
CheckOutProgram() [1/3]
async Task< ServiceResult< ProgramCheckoutResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckOutProgram (int programId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 148 of file ProgramServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckOutProgram(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
CheckOutProgram() [2/3]
async Task< ServiceResult< ProgramCheckoutResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckOutProgram (RequestCredentials credentials, int programId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 125 of file ProgramServiceMF.cs.
CheckOutProgram() [3/3]
async Task< ServiceResult< ProgramCheckoutResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckOutProgram (string ticket, int programId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 117 of file ProgramServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckOutProgram(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.configuration.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckOutProgram(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckOutProgram(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.StopCampaign().
GetOutboundsScheduleList()
async Task< ServiceResult< GetOutboundsScheduleListResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.GetOutboundsScheduleList (List< KeyValuePair< string, string > > outboundList) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 290 of file ProgramServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ErrorCode, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ErrorMessage, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ExceptionMessage, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.GetOutboundsScheduleListResponse.Result, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
GetProgram() [1/3]
async Task< ServiceResult< GetProgramResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.GetProgram (int programId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 237 of file ProgramServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.GetProgram(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.GetProgram(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.GetProgram().
GetProgram() [2/3]
async Task< ServiceResult< GetProgramResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.GetProgram (RequestCredentials credentials, int programId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 333 of file ProgramServiceMF.cs.
GetProgram() [3/3]
Task< ServiceResult< GetProgramResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.GetProgram (string ticket, int programId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 325 of file ProgramServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.configuration, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.GetProgram().
GetProgramInfo() [1/2]
async Task< ServiceResult< GetProgramInfoResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.GetProgramInfo (int programId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 242 of file ProgramServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ErrorCode, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ErrorMessage, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ExceptionMessage, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.GetProgramInfoResponse.Result, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
GetProgramInfo() [2/2]
async Task< ServiceResult< GetProgramInfoResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.GetProgramInfo (string mfTicket, int programId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 265 of file ProgramServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ErrorCode, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ErrorMessage, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ExceptionMessage, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.GetProgramInfoResponse.Result, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
GetProgramList()
async Task< ServiceResult< GetProgramListResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.GetProgramList (RequestCredentials credentials, short status = 255) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 210 of file ProgramServiceMF.cs.
PublishProgram() [1/2]
async Task< ServiceResult< PublishProgramResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.PublishProgram (RequestCredentials credentials, string programXML) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 55 of file ProgramServiceMF.cs.
PublishProgram() [2/2]
async Task< ServiceResult< PublishProgramResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.PublishProgram (string programXML) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 50 of file ProgramServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.PublishProgram(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.PublishProgram().
StopCampaign()
async Task< ServiceResult< ProgramCheckinResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.StopCampaign (int programId, string ticket, string comment) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 357 of file ProgramServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckInProgram(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.CheckOutProgram(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.configuration, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.UndoProgramChanges().
UndoProgramChanges() [1/3]
async Task< ServiceResult< UndoProgramChangesResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.UndoProgramChanges (int programId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 111 of file ProgramServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.UndoProgramChanges(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.userRequestCredentials.
UndoProgramChanges() [2/3]
async Task< ServiceResult< UndoProgramChangesResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.UndoProgramChanges (RequestCredentials credentials, int programId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 80 of file ProgramServiceMF.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.StopCampaign(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.UndoProgramChanges(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.UndoProgramChanges().
UndoProgramChanges() [3/3]
async Task< ServiceResult< UndoProgramChangesResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.UndoProgramChanges (string ticket, int programId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.
Definition at line 103 of file ProgramServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.configuration, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.UndoProgramChanges().
The documentation for this class was generated from the following file:
Source/Infrastructure/Mindfire/ProgramServiceMF.cs