AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service Interface Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service Interface Reference
Public Member Functions
Task< ServiceResult< AmazonResponse > > DownloadCampaignTemplate (string campaignTemplateFileName)
Task< ServiceResult< AmazonResponse > > DownloadString (string urlstring, string s3Bucket=null)
Task< ServiceResult< AmazonResponse > > DeleteFile (string urlstring, string s3Bucket=null)
Task< ServiceResult< AmazonResponse > > DownloadStringHTML (string url)
Task< ServiceResult< AmazonResponse > > UploadHtml (string htmlContent, string htmlName)
Task< ServiceResult< AmazonResponse > > UploadText (string content, string name)
Task< ServiceResult< AmazonResponse > > UploadCSV (IFormFile content, string folder, string bucket)
Task< ServiceResult< AmazonResponse > > UploadBadCSV (string csv, string fileName)
string GetS3RootUrl ()
string GetRssFeedsFolder ()
Task< ServiceResult< AmazonResponse > > DownloadRssFeed (string filename)
Task< ServiceResult< AmazonResponse > > UploadRssFeed (string filename, string xml)
Task< ServiceResult< AmazonResponse > > DownloadHTMLFromContent (string fileName, string folder=null)
Task< ServiceResult< string > > DownloadHtmlContent (string contentUrl)
Task< ServiceResult< string > > DownloadPreviewTemplate (string path)
Properties
string Bucket [get, set]
Detailed Description
Definition at line 19 of file AmazonS3Service.cs.
Member Function Documentation
DeleteFile()
Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DeleteFile (string urlstring, string s3Bucket = null)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts().
DownloadCampaignTemplate()
Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadCampaignTemplate (string campaignTemplateFileName)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.CampaignDetails(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetInsideMessages(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.HasIndivGroupTemplates(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.PendingCampaignDetails(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Scripts.SyncCampaignElementMetadata.Run(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateNameAndContentUrls().
DownloadHtmlContent()
Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadHtmlContent (string contentUrl)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateContentUrls().
DownloadHTMLFromContent()
Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadHTMLFromContent (string fileName, string folder = null)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.
DownloadPreviewTemplate()
Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadPreviewTemplate (string path)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.CampaignDetails(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateContentUrls().
DownloadRssFeed()
Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadRssFeed (string filename)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.
DownloadString()
Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadString (string urlstring, string s3Bucket = null)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.CampaignDetails(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapSocialElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToEmailElement(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService.SendEmail(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetMessageBody(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts().
DownloadStringHTML()
Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadStringHTML (string url)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.CampaignDetails().
GetRssFeedsFolder()
string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.GetRssFeedsFolder ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.
GetS3RootUrl()
string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.GetS3RootUrl ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapSocialElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateContentUrls(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UploadHtmlContent().
UploadBadCSV()
Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.UploadBadCSV (string csv, string fileName)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetErrorCSV().
UploadCSV()
Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.UploadCSV (IFormFile content, string folder, string bucket)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetColumnNames().
UploadHtml()
Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.UploadHtml (string htmlContent, string htmlName)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.CampaignDetails(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateContentUrls(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UploadHtmlContent().
UploadRssFeed()
Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.UploadRssFeed (string filename, string xml)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.
UploadText()
Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.UploadText (string content, string name)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapSocialElementToXML().
Property Documentation
Bucket
string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.Bucket get set
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.
Definition at line 36 of file AmazonS3Service.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.CampaignDetails(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapSocialElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToEmailElement(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetMessageBody().
The documentation for this interface was generated from the following file:
Source/Infrastructure/AWS/S3/AmazonS3Service.cs