AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService Interface Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService Interface Reference
Public Member Functions
Task< IEnumerable< TClass > > getSqlMSSqlAsync< TClass > (string sql)
Task< IEnumerable< TClass > > getSqlRedShiftAsync< TClass > (string sql)
Task< Dictionary< string, List< Dictionary< string, object > > > > getSqlRedShiftMultipleAsync (IEnumerable<(string, string)> namedQueries)
Task< DTOCamapigns > getCampaignsAsync (long accountId, IEnumerable< long > campaingIds, IEnumerable< long > programIds, bool thisMonth=false)
Task< IEnumerable< DBOCampaignElements > > getCamapignElements (long accountId, IEnumerable< long > campaignIds)
string getSentEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getOpenedEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getClicksEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getSpamEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getUnsubscribeEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getSuppressedEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getUndeliverableEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
Task< IEnumerable< DTOCampaignLaunches > > getTopNCampaigns (int topN, int clientId, bool thisMonth=false, bool onlyActive=true)
Task< int > geTotalNumberOfLaunchedCampaigns (int clientId, bool thisMonth=false, bool onlyActive=true)
string getSocialPostsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getPrintsSentSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getMicrositeVisitsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getMicrositeClicksSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getMicrositeSubmitsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getTopNEngagedCampaignsSql (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getTopNEngagedContactsSql (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
Task< IEnumerable< DTONamedCount > > getTopNClickRateByOutboundName (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
Task< IEnumerable< DTONamedCount > > getTopNClickRateByOutboundScheduleName (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
Task< IEnumerable< DTONamedCount > > getTopNClickRateByEmail (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
Task< IEnumerable< DTONamedCount > > getTopNClickRateByAction (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
Task< IEnumerable< DateValue > > getClickRatesOverDays (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
Task< IEnumerable< DTONamedCount > > getTopNOpenRateByOutboundName (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
Task< IEnumerable< DTONamedCount > > getTopNOpenRateByOutboundScheduleName (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
Task< IEnumerable< DateValue > > getOpenRatesOverDays (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
Task< IEnumerable< DTOContactDetail > > getContactDetails (long accountId, int campaignId)
Task< IEnumerable< DTOInboundElement > > getInboundElements (long accountId, int campaignId)
Task< IEnumerable< DTOOutboundDetail > > getOutboundDetails (long accountId, int campaignId)
Task< IEnumerable< string > > getElegetOutboundElementContactsSentTo (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Task< IEnumerable< string > > getElegetOutboundElementContactsOpened (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Task< IEnumerable< string > > getElegetOutboundElementContactsClicks (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Task< IEnumerable< string > > getElegetOutboundElementContactsSpam (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Task< IEnumerable< string > > getElegetOutboundElementContactsHardBounced (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Task< IEnumerable< string > > getElegetOutboundElementContactsSoftBounced (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Task< IEnumerable< string > > getElegetOutboundElementContactsSuppressed (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Task< IEnumerable< string > > getElegetOutboundElementContactsFailed (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Task< IEnumerable< string > > getElegetOutboundElementContactsUnsubscribed (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Detailed Description
Definition at line 20 of file RedShiftService.cs.
Member Function Documentation
getCamapignElements()
Task< IEnumerable< DBOCampaignElements > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getCamapignElements (long accountId, IEnumerable< long > campaignIds)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignElements(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsWithElements().
getCampaignsAsync()
Task< DTOCamapigns > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getCampaignsAsync (long accountId, IEnumerable< long > campaingIds, IEnumerable< long > programIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsWithElements().
getClickRatesOverDays()
Task< IEnumerable< DateValue > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getClickRatesOverDays (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getClickRates().
getClicksEmailsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getClicksEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getContactDetails()
Task< IEnumerable< DTOContactDetail > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getContactDetails (long accountId, int campaignId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getCampaignDetails().
getElegetOutboundElementContactsClicks()
Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsClicks (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsClickedOutboundSchedule().
getElegetOutboundElementContactsFailed()
Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsFailed (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsFailedOutboundSchedule().
getElegetOutboundElementContactsHardBounced()
Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsHardBounced (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsHardBouncedOutboundSchedule().
getElegetOutboundElementContactsOpened()
Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsOpened (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsThatOpenedOutboundSchedule().
getElegetOutboundElementContactsSentTo()
Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsSentTo (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSentToOutboundSchedule().
getElegetOutboundElementContactsSoftBounced()
Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsSoftBounced (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSoftBouncedOutboundSchedule().
getElegetOutboundElementContactsSpam()
Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsSpam (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSpamOutboundSchedule().
getElegetOutboundElementContactsSuppressed()
Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsSuppressed (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSuppressedOutboundSchedule().
getElegetOutboundElementContactsUnsubscribed()
Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsUnsubscribed (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsUnsubscribedOutboundSchedule().
getInboundElements()
Task< IEnumerable< DTOInboundElement > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getInboundElements (long accountId, int campaignId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getCampaignDetails().
getMicrositeClicksSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getMicrositeClicksSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getMicrositeSubmitsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getMicrositeSubmitsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getMicrositeVisitsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getMicrositeVisitsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getOpenedEmailsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getOpenedEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getOpenRatesOverDays()
Task< IEnumerable< DateValue > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getOpenRatesOverDays (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getOpenRates().
geTotalNumberOfLaunchedCampaigns()
Task< int > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.geTotalNumberOfLaunchedCampaigns (int clientId, bool thisMonth = false, bool onlyActive = true)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getOutboundDetails()
Task< IEnumerable< DTOOutboundDetail > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getOutboundDetails (long accountId, int campaignId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getCampaignDetails().
getPrintsSentSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getPrintsSentSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getSentEmailsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getSentEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getSocialPostsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getSocialPostsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getSpamEmailsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getSpamEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getSqlMSSqlAsync< TClass >()
Task< IEnumerable< TClass > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getSqlMSSqlAsync< TClass > (string sql)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
getSqlRedShiftAsync< TClass >()
Task< IEnumerable< TClass > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getSqlRedShiftAsync< TClass > (string sql)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
getSqlRedShiftMultipleAsync()
Task< Dictionary< string, List< Dictionary< string, object > > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getSqlRedShiftMultipleAsync (IEnumerable<(string, string)> namedQueries)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getSuppressedEmailsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getSuppressedEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getTopNCampaigns()
Task< IEnumerable< DTOCampaignLaunches > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNCampaigns (int topN, int clientId, bool thisMonth = false, bool onlyActive = true)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getTopNClickRateByAction()
Task< IEnumerable< DTONamedCount > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNClickRateByAction (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getClickRates(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getOpenRates().
getTopNClickRateByEmail()
Task< IEnumerable< DTONamedCount > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNClickRateByEmail (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getClickRates().
getTopNClickRateByOutboundName()
Task< IEnumerable< DTONamedCount > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNClickRateByOutboundName (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getClickRates().
getTopNClickRateByOutboundScheduleName()
Task< IEnumerable< DTONamedCount > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNClickRateByOutboundScheduleName (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getClickRates().
getTopNEngagedCampaignsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNEngagedCampaignsSql (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getTopNEngagedContactsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNEngagedContactsSql (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getTopNOpenRateByOutboundName()
Task< IEnumerable< DTONamedCount > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNOpenRateByOutboundName (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getOpenRates().
getTopNOpenRateByOutboundScheduleName()
Task< IEnumerable< DTONamedCount > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNOpenRateByOutboundScheduleName (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getOpenRates().
getUndeliverableEmailsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getUndeliverableEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getUnsubscribeEmailsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getUnsubscribeEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
The documentation for this interface was generated from the following file:
Source/API/Services/RedShiftService.cs