var _csv_log_campaign_script_entry_8cs =
[
    [ "Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogCampaignScriptEntry", "d2/d67/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_script_runner_1_1_models_1_1_csv_log_campaign_script_entry.html", "d2/d67/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_script_runner_1_1_models_1_1_csv_log_campaign_script_entry" ]
];