AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService Class Reference
Public Member Functions
BIService (IRedShiftService redShiftService, IContactManagerService contactManagerService, IUserCampaignService userCampaignService, ISessionService sessionService)
async Task< IEnumerable< DBOCampaignElements > > GetCampaignElements (AdvisorFilter filter)
async Task< DTOCamapigns > GetCampaignsWithElements (AdvisorFilter filter)
async Task< DTOCampaignsAndStats > GetCampaignsAndStats (MainFilter filter)
async Task< DTOOpenRates > getOpenRates (MainFilter filter)
async Task< DTOClickRates > getClickRates (MainFilter filter)
async Task< DTOCampaignDetails > getCampaignDetails (int accountId, int campaignId)
async Task< byte[]> getContactsThatOpenedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
async Task< byte[]> getContactsSentToOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
async Task< byte[]> getContactsClickedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
async Task< byte[]> getContactsSpamOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
async Task< byte[]> getContactsHardBouncedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
async Task< byte[]> getContactsSoftBouncedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
async Task< byte[]> getContactsSuppressedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
async Task< byte[]> getContactsFailedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
async Task< byte[]> getContactsUnsubscribedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
async Task< byte[]> GetContactActivityCSV (int accountId, int campaignId, int outboundId, int outboundScheduleId, int columnId)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService
Static Private Member Functions
static SegmentationFilter getMFAccountIdFilter (IEnumerable< string > accountIds)
Private Attributes
readonly IRedShiftService _redShiftService
readonly IContactManagerService _contactManagerService
readonly IUserCampaignService _userCampaignService
readonly ISessionService _sessionService
Detailed Description
Definition at line 33 of file BiService.cs.
Constructor & Destructor Documentation
BIService()
Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.BIService (IRedShiftService redShiftService, IContactManagerService contactManagerService, IUserCampaignService userCampaignService, ISessionService sessionService) inline
Definition at line 39 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._contactManagerService, Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService, Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._sessionService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._userCampaignService.
Member Function Documentation
getCampaignDetails()
async Task< DTOCampaignDetails > Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getCampaignDetails (int accountId, int campaignId) inline
Parameters
accountId
campaignId
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.
Definition at line 261 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getContactDetails(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getInboundElements(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getOutboundDetails().
GetCampaignElements()
async Task< IEnumerable< DBOCampaignElements > > Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignElements (AdvisorFilter filter) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.
Definition at line 51 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.AdvisorFilter.AccountId, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.AdvisorFilter.CampaingIds, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getCamapignElements().
GetCampaignsAndStats()
async Task< DTOCampaignsAndStats > Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats (MainFilter filter) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.
Definition at line 120 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService, Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._sessionService, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.AdvisorFilter.AccountId, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.MainFilter.Advisor, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.AdvisorFilter.CampaingIds, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.TopCampaignsFilter.Count, Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsWithElements(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getClicksEmailsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getMicrositeClicksSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getMicrositeSubmitsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getMicrositeVisitsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getOpenedEmailsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.geTotalNumberOfLaunchedCampaigns(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getPrintsSentSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getSentEmailsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getSocialPostsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getSpamEmailsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getSqlRedShiftMultipleAsync(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getSuppressedEmailsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNCampaigns(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNEngagedCampaignsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNEngagedContactsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getUndeliverableEmailsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getUnsubscribeEmailsSql(), Deluxe.DeluxeBrandCenter.AMM.Domain.BI.MainFilter.Global, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.TopCampaignsFilter.OnlyActive, Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId(), Deluxe.DeluxeBrandCenter.AMM.Domain.BI.AdvisorFilter.ThisMonth, and Deluxe.DeluxeBrandCenter.AMM.Domain.BI.GlobalFilter.TopCampaigns.
GetCampaignsWithElements()
async Task< DTOCamapigns > Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsWithElements (AdvisorFilter filter) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.
Definition at line 56 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService, Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._userCampaignService, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.AdvisorFilter.AccountId, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.AdvisorFilter.CampaingIds, Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getCamapignElements(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getCampaignsAsync(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.GetList(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUserId(), and Deluxe.DeluxeBrandCenter.AMM.Domain.BI.AdvisorFilter.ThisMonth.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats().
getClickRates()
async Task< DTOClickRates > Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getClickRates (MainFilter filter) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.
Definition at line 238 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.AdvisorFilter.AccountId, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.MainFilter.Advisor, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.AdvisorFilter.CampaingIds, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.TopCampaignsFilter.Count, Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getClickRatesOverDays(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNClickRateByAction(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNClickRateByEmail(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNClickRateByOutboundName(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNClickRateByOutboundScheduleName(), Deluxe.DeluxeBrandCenter.AMM.Domain.BI.MainFilter.Global, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.AdvisorFilter.ThisMonth, and Deluxe.DeluxeBrandCenter.AMM.Domain.BI.GlobalFilter.TopCampaigns.
GetContactActivityCSV()
async Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetContactActivityCSV (int accountId, int campaignId, int outboundId, int outboundScheduleId, int columnId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.
Definition at line 439 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsClickedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsFailedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsHardBouncedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSentToOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSoftBouncedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSpamOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSuppressedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsThatOpenedOutboundSchedule(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsUnsubscribedOutboundSchedule().
getContactsClickedOutboundSchedule()
async Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsClickedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.
Definition at line 312 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._contactManagerService, Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DownloadCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsClicks(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getMFAccountIdFilter().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetContactActivityCSV().
getContactsFailedOutboundSchedule()
async Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsFailedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.
Definition at line 402 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._contactManagerService, Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DownloadCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsFailed(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getMFAccountIdFilter().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetContactActivityCSV().
getContactsHardBouncedOutboundSchedule()
async Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsHardBouncedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.
Definition at line 348 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._contactManagerService, Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DownloadCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsHardBounced(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getMFAccountIdFilter().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetContactActivityCSV().
getContactsSentToOutboundSchedule()
async Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSentToOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.
Definition at line 294 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._contactManagerService, Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DownloadCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsSentTo(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getMFAccountIdFilter().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetContactActivityCSV().
getContactsSoftBouncedOutboundSchedule()
async Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSoftBouncedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.
Definition at line 366 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._contactManagerService, Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DownloadCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsSoftBounced(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getMFAccountIdFilter().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetContactActivityCSV().
getContactsSpamOutboundSchedule()
async Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSpamOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.
Definition at line 330 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._contactManagerService, Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DownloadCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsSpam(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getMFAccountIdFilter().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetContactActivityCSV().
getContactsSuppressedOutboundSchedule()
async Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSuppressedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.
Definition at line 384 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._contactManagerService, Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DownloadCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsSuppressed(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getMFAccountIdFilter().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetContactActivityCSV().
getContactsThatOpenedOutboundSchedule()
async Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsThatOpenedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.
Definition at line 276 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._contactManagerService, Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DownloadCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsOpened(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getMFAccountIdFilter().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetContactActivityCSV().
getContactsUnsubscribedOutboundSchedule()
async Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsUnsubscribedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.
Definition at line 420 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._contactManagerService, Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DownloadCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getElegetOutboundElementContactsUnsubscribed(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getMFAccountIdFilter().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetContactActivityCSV().
getMFAccountIdFilter()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getMFAccountIdFilter (IEnumerable< string > accountIds) inline static private
Definition at line 483 of file BiService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsClickedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsFailedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsHardBouncedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSentToOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSoftBouncedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSpamOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSuppressedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsThatOpenedOutboundSchedule(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsUnsubscribedOutboundSchedule().
getOpenRates()
async Task< DTOOpenRates > Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getOpenRates (MainFilter filter) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.
Definition at line 224 of file BiService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.AdvisorFilter.AccountId, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.MainFilter.Advisor, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.AdvisorFilter.CampaingIds, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.TopCampaignsFilter.Count, Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getOpenRatesOverDays(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNClickRateByAction(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNOpenRateByOutboundName(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.getTopNOpenRateByOutboundScheduleName(), Deluxe.DeluxeBrandCenter.AMM.Domain.BI.MainFilter.Global, Deluxe.DeluxeBrandCenter.AMM.Domain.BI.AdvisorFilter.ThisMonth, and Deluxe.DeluxeBrandCenter.AMM.Domain.BI.GlobalFilter.TopCampaigns.
Member Data Documentation
_contactManagerService
readonly IContactManagerService Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._contactManagerService private
Definition at line 36 of file BiService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.BIService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsClickedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsFailedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsHardBouncedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSentToOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSoftBouncedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSpamOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSuppressedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsThatOpenedOutboundSchedule(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsUnsubscribedOutboundSchedule().
_redShiftService
readonly IRedShiftService Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._redShiftService private
Definition at line 35 of file BiService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.BIService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getCampaignDetails(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignElements(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsWithElements(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getClickRates(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsClickedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsFailedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsHardBouncedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSentToOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSoftBouncedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSpamOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSuppressedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsThatOpenedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsUnsubscribedOutboundSchedule(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getOpenRates().
_sessionService
readonly ISessionService Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._sessionService private
Definition at line 38 of file BiService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.BIService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsWithElements().
_userCampaignService
readonly IUserCampaignService Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService._userCampaignService private
Definition at line 37 of file BiService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.BIService(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsWithElements().
The documentation for this class was generated from the following file:
Source/API/Services/BiService.cs