AMM: Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController Class Reference
Public Member Functions
BIController (IBIService bIService)
ControllerResult< Guid > StartCampaignsAndStatsJob ([FromBody] MainFilter param, [FromServices] IJobPoolService jobPoolService)
ControllerResult< JobVM< DTOCampaignsAndStats > > GetCampaignsAndStatsJob ([FromQuery] Guid id, [FromServices] IJobPoolService jobPoolService)
async Task< ControllerResult< IEnumerable< DBOCampaignElements > > > GetCampaignElements ([FromBody] AdvisorFilter param)
async Task< ControllerResult< DTOClickRates > > GetClickRates ([FromBody] MainFilter param)
async Task< ControllerResult< DTOOpenRates > > GetOpenRates ([FromBody] MainFilter param)
ControllerResult< Guid > StartCampaignDetailsJob ([FromQuery] int accountId, [FromQuery] int campaignId, [FromServices] IJobPoolService jobPoolService)
ControllerResult< JobVM< DTOCampaignDetails > > GetCampaignDetailsJob ([FromQuery] Guid id, [FromServices] IJobPoolService jobPoolService)
ControllerResult< Guid > StartContactActivityCsvJob ([FromQuery] int accountId, [FromQuery] int campaignId, [FromQuery] int outboundId, [FromQuery] int outboundScheduleId, [FromQuery] int columnId, [FromServices] IJobPoolService jobPoolService)
ControllerResult< JobVM< byte[]> > GetContactActivityCsvJob ([FromQuery] Guid id, [FromServices] IJobPoolService jobPoolService)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IBIService >
RootController ()
Empty Root Controller Constructor.
RootController (TService service)
Root Controller Constructor.
Private Attributes
readonly IBIService _bIService
Additional Inherited Members
Protected Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IBIService >
ControllerResult< Guid > StartJob< T > (Func< IServiceProvider, Task< T > > func, IJobPoolService jobPoolService)
ControllerResult< JobVM< T > > GetJob< T > (Guid id, IJobPoolService jobPoolService)
ControllerResult< JobVM< T > > GetJobServiceResult< T > (Guid id, IJobPoolService jobPoolService)
ControllerResult< JobVM< T > > GetJobApiResponse< T > (Guid id, IJobPoolService jobPoolService)
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IBIService >
TService service [get]
Base service for controller.
Detailed Description
Definition at line 22 of file BIController.cs.
Constructor & Destructor Documentation
BIController()
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.BIController (IBIService bIService) inline
Parameters
bIService
Definition at line 29 of file BIController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController._bIService.
Member Function Documentation
GetCampaignDetailsJob()
ControllerResult< JobVM< DTOCampaignDetails > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.GetCampaignDetailsJob ([FromQuery] Guid id, [FromServices] IJobPoolService jobPoolService) inline
Returns
Definition at line 108 of file BIController.cs.
GetCampaignElements()
async Task< ControllerResult< IEnumerable< DBOCampaignElements > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.GetCampaignElements ([FromBody] AdvisorFilter param) inline
Parameters
param
Returns
Definition at line 63 of file BIController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController._bIService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.GetCampaignElements().
GetCampaignsAndStatsJob()
ControllerResult< JobVM< DTOCampaignsAndStats > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.GetCampaignsAndStatsJob ([FromQuery] Guid id, [FromServices] IJobPoolService jobPoolService) inline
Returns
List of campaigns for given filter and statistics for those campaigns
Definition at line 52 of file BIController.cs.
GetClickRates()
async Task< ControllerResult< DTOClickRates > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.GetClickRates ([FromBody] MainFilter param) inline
Parameters
param
Returns
Definition at line 74 of file BIController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController._bIService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.getClickRates().
GetContactActivityCsvJob()
ControllerResult< JobVM< byte[]> > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.GetContactActivityCsvJob ([FromQuery] Guid id, [FromServices] IJobPoolService jobPoolService) inline
Returns
Definition at line 147 of file BIController.cs.
GetOpenRates()
async Task< ControllerResult< DTOOpenRates > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.GetOpenRates ([FromBody] MainFilter param) inline
Parameters
param
Returns
Definition at line 85 of file BIController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController._bIService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.getOpenRates().
StartCampaignDetailsJob()
ControllerResult< Guid > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.StartCampaignDetailsJob ([FromQuery] int accountId, [FromQuery] int campaignId, [FromServices] IJobPoolService jobPoolService) inline
Parameters
accountId
campaignId
jobPoolService
Returns
Definition at line 98 of file BIController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.getCampaignDetails().
StartCampaignsAndStatsJob()
ControllerResult< Guid > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.StartCampaignsAndStatsJob ([FromBody] MainFilter param, [FromServices] IJobPoolService jobPoolService) inline
Parameters
param Optional
jobPoolService
Returns
List of campaigns for given filter and statistics for those campaigns
Definition at line 42 of file BIController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.GetCampaignsAndStats().
StartContactActivityCsvJob()
ControllerResult< Guid > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.StartContactActivityCsvJob ([FromQuery] int accountId, [FromQuery] int campaignId, [FromQuery] int outboundId, [FromQuery] int outboundScheduleId, [FromQuery] int columnId, [FromServices] IJobPoolService jobPoolService) inline
Parameters
accountId
campaignId
outboundId
outboundScheduleId
columnId
jobPoolService
Returns
Definition at line 124 of file BIController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.GetContactActivityCSV().
Member Data Documentation
_bIService
readonly IBIService Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController._bIService private
Definition at line 24 of file BIController.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.BIController(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.GetCampaignElements(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.GetClickRates(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.GetOpenRates().
The documentation for this class was generated from the following file:
Source/API/Controllers/BIController.cs