var 20190710094741___subject_read_only_8cs =
[
    [ "Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.Migrations.SubjectReadOnly", "dc/dff/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_databases_1_1_migrations_1_1_subject_read_only.html", "dc/dff/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_databases_1_1_migrations_1_1_subject_read_only" ]
];