AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T > Class Template Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T > Class Template Reference
Public Member Functions
ApiResponse (T data)
ApiResponse (T data, List< string > errorMessages)
ApiResponse (List< string > errorMessages)
ApiResponse (T data, string errorMessage)
ApiResponse (T data, IReadOnlyCollection< KeyValuePair< string, string > > errorMessages)
ApiResponse (IReadOnlyCollection< KeyValuePair< string, string > > errorMessages)
Properties
T Data [get]
List< string > ErrorMessages = null [get]
Static Private Member Functions
static List< string > KeyValuePairCollectionToList (IReadOnlyCollection< KeyValuePair< string, string > > collections)
Detailed Description
Definition at line 5 of file ApiResponse.cs.
Constructor & Destructor Documentation
ApiResponse() [1/6]
Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ApiResponse (T data) inline
Definition at line 14 of file ApiResponse.cs.
ApiResponse() [2/6]
Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ApiResponse (T data, List< string > errorMessages) inline
Definition at line 19 of file ApiResponse.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ErrorMessages.
ApiResponse() [3/6]
Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ApiResponse (List< string > errorMessages) inline
Definition at line 25 of file ApiResponse.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ErrorMessages.
ApiResponse() [4/6]
Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ApiResponse (T data, string errorMessage) inline
Definition at line 30 of file ApiResponse.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ErrorMessages.
ApiResponse() [5/6]
Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ApiResponse (T data, IReadOnlyCollection< KeyValuePair< string, string > > errorMessages) inline
Definition at line 39 of file ApiResponse.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ErrorMessages, and Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.KeyValuePairCollectionToList().
ApiResponse() [6/6]
Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ApiResponse (IReadOnlyCollection< KeyValuePair< string, string > > errorMessages) inline
Definition at line 45 of file ApiResponse.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ErrorMessages, and Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.KeyValuePairCollectionToList().
Member Function Documentation
KeyValuePairCollectionToList()
static List< string > Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.KeyValuePairCollectionToList (IReadOnlyCollection< KeyValuePair< string, string > > collections) inline static private
Definition at line 50 of file ApiResponse.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ApiResponse(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ApiResponse().
Property Documentation
Data
T Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.Data get
Definition at line 7 of file ApiResponse.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult().
ErrorMessages
List<string> Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ErrorMessages = null get
Definition at line 12 of file ApiResponse.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ApiResponse(), Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ApiResponse(), Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ApiResponse(), Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ApiResponse(), Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ApiResponse(), and Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.From< T >().
The documentation for this class was generated from the following file:
Source/Domain/ControllerModel/ApiResponse.cs