AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService Interface Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService Interface Reference
Public Member Functions
Task< ServiceResult< List< OutboundScheduleVM > > > GetOutboundsScheduleListAsync (OutboundFilterVM outboundFilterVM)
Task< ServiceResult< UserCampaign > > SetOutboundIds (UserCampaign userCampaign)
Task< ServiceResult< IList< UserCampaignSimpleVM > > > MyCampaigns (string status, bool waitingApproval)
Task< ServiceResult< IList< UserCampaignSimpleVM > > > PendingCampaigns ()
Task< ServiceResult< UserCampaignVM > > PendingCampaignDetails (int id)
Task< ServiceResult< UserCampaignVM > > CampaignDetails (int id)
Task< ServiceResult< UserCampaignVM > > StopCampaign (int programId)
Task< ServiceResult< UserCampaignVM > > StartCampaign (int programId)
Task< ServiceResult< IList< string > > > StopCampaigns (List< int > programIds, ApplicationUser user)
void SetContentVariable (XElement contentVariablesXMLElement, string name, string value, bool htmlEncode=true)
void FillAdvisorContentVariables (PMSPersonaDTO personalInfo, IEnumerable< XElement > contentVariables, XElement contentVariablesXMLElement, bool isForDirectMail=false, int clientId=0, bool hasAlternateAddress=false)
void FillAdvisorColumns (ICollection< XElement > columns, XElement rouleGroup, PMSPersonaDTO personalInf, bool hasAlternateAddress=false)
void NormalizeDMVariablesAndColumns (XElement columns, XElement rouleGroup)
Task< ServiceResult< ICollection< UserCampaign > > > SyncPersonaDataWithMF (string personaInstanceId)
Task< ServiceResult< IList< string > > > GetBase64Images (IList< string > imageUrls)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >
Task< ServiceResult< TModelVM > > Single (int id)
Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate, int clientId)
Task< ServiceResult< TModel > > Entity (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
Task< ServiceResult< List< TModelVM > > > GetList ()
Task< ServiceResult< List< TModelVM > > > GetList (Expression< Func< TModel, bool > > predicate=null, Expression< Func< TModel, object > > orderBy=null, bool descending=false, bool disableTracking=true, string[] navigationPaths=null, bool clientSide=false, params Expression< Func< TModel, object > >[] include)
Task< ServiceResult< TModelVM > > Delete (int id)
Task< ServiceResult< TModel > > UpdateEntity (TModel entity)
Task< ServiceResult< TModelVM > > Update (TModelVM entity)
Task< string > UpdateSocialURLs (PMSPersonaDTO personalInfo)
void FillHtmlWithPersonalInfo (ref string htmlContent, PMSPersonaDTO personalInfo, List< KeyValuePair< string, string > > editorFields=null, int? clientId=0, bool preview=false)
void FillHtmlContent (ref string htmlContent, PMSPersonaDTO personalInfo, SignatureBlockVM signatureBlock, string insideMessage=null, List< KeyValuePair< string, string > > editorFields=null, bool preview=false)
Additional Inherited Members
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >
IApplicationDbContext dbContext [get, set]
IMapper mapper [get, set]
ILogger< DBService< TModel, TModelVM > > logger [get]
Detailed Description
Definition at line 34 of file UserCampaignService.cs.
Member Function Documentation
CampaignDetails()
Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.CampaignDetails (int id)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.
FillAdvisorColumns()
void Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.FillAdvisorColumns (ICollection< XElement > columns, XElement rouleGroup, PMSPersonaDTO personalInf, bool hasAlternateAddress = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.
FillAdvisorContentVariables()
void Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.FillAdvisorContentVariables (PMSPersonaDTO personalInfo, IEnumerable< XElement > contentVariables, XElement contentVariablesXMLElement, bool isForDirectMail = false, int clientId = 0, bool hasAlternateAddress = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.FillRuleGroup().
GetBase64Images()
Task< ServiceResult< IList< string > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.GetBase64Images (IList< string > imageUrls)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.
GetOutboundsScheduleListAsync()
Task< ServiceResult< List< OutboundScheduleVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.GetOutboundsScheduleListAsync (OutboundFilterVM outboundFilterVM)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.
MyCampaigns()
Task< ServiceResult< IList< UserCampaignSimpleVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.MyCampaigns (string status, bool waitingApproval)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.
NormalizeDMVariablesAndColumns()
void Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.NormalizeDMVariablesAndColumns (XElement columns, XElement rouleGroup)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapDirectMailElementToXML().
PendingCampaignDetails()
Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.PendingCampaignDetails (int id)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.
PendingCampaigns()
Task< ServiceResult< IList< UserCampaignSimpleVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.PendingCampaigns ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.
SetContentVariable()
void Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.SetContentVariable (XElement contentVariablesXMLElement, string name, string value, bool htmlEncode = true)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.FillRuleGroup().
SetOutboundIds()
Task< ServiceResult< UserCampaign > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.SetOutboundIds (UserCampaign userCampaign)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign().
StartCampaign()
Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.StartCampaign (int programId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.
StopCampaign()
Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.StopCampaign (int programId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.
StopCampaigns()
Task< ServiceResult< IList< string > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.StopCampaigns (List< int > programIds, ApplicationUser user)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AdminService.DeactivateUser().
SyncPersonaDataWithMF()
Task< ServiceResult< ICollection< UserCampaign > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.SyncPersonaDataWithMF (string personaInstanceId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Scripts.SyncCampaignWithPersona.Run().
The documentation for this interface was generated from the following file:
Source/API/Services/UserCampaignService.cs