AMM: Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController Class Reference
Public Member Functions
ContactManagerController (IContactManagerService service, ISessionService sessionService)
Contact Manager CTOR.
async Task< ControllerResult > SFCallback (string code)
async Task< ControllerResult< IEnumerable< ContactVM > > > CreateContact ([FromBody] List< ContactVM > contactVMList)
Create list of contacts.
async Task< ControllerResult< PaginatedContactsVM > > GetContacts ([FromBody] ContactFilterVM contactFilterVM)
Get a list of filtered profile contacts, filter is a must.
async Task< ControllerResult< ContactVM > > GetContact ([FromQuery] string AccountID)
Get contact by AccountId.
async Task< ControllerResult< IEnumerable< MyContactActivity > > > GetLastActivities ([FromBody] ContactActivitiesVM contactActivitiesVM)
Get a campaign activities for contact.
async Task< ControllerResult< int > > CountContacts ([FromBody] SegmentationFilter filter)
async Task< ControllerResult< IEnumerable< ContactVM > > > UpdateContact ([FromBody] List< ContactVM > contactVMList)
Update list of contacts.
ControllerResult< System.Guid > StartDeleteContactJob ([FromBody] List< ContactVM > contactVMList, [FromServices] IJobPoolService jobPoolService)
Start the job for delete list of contacts.
ControllerResult< JobVM< IEnumerable< ContactVM > > > GetDeleteContactJob ([FromQuery] System.Guid id, [FromServices] IJobPoolService jobPoolService)
Get the job for delete list of contacts.
ControllerResult< System.Guid > StartDownloadContactsJob ([FromServices] IJobPoolService jobPoolService)
Start the job for downloading all contacts.
ControllerResult< JobVM< byte[]> > GetDownloadContactsJob ([FromQuery] System.Guid id, [FromServices] IJobPoolService jobPoolService)
Get the job for downloading all contacts.
ControllerResult DownloadTags ()
Download all tags.
async Task< ControllerResult > DownUnsubscribedContacts ()
Download unsubscribed Contacts.
async Task< ControllerResult< IPaginate< AssociatedGroupVM > > > GetContactAssociatedGroups ([FromBody] AssociatedGroupsFilterVM associatedGroupsFilterVM)
Get all groups that the contacts has.
async Task< ControllerResult< ContactMapingVM > > UploadCSV (IFormFile uploadedFile)
First Step in upload csv.
ControllerResult< System.Guid > StartUploadContactsJob ([FromBody] UploadContactsVM uploadContactsVM, [FromServices] IJobPoolService jobPoolService)
Second step in csv upload. Starts a background job.
ControllerResult< JobVM< UploadContactsResponse > > GetUploadContactsJob ([FromQuery] System.Guid id, [FromServices] IJobPoolService jobPoolService)
Check if an upload job has finished.
ControllerResult< ContactGroupVM[]> GetContactGroupDB ()
Get all group name that are active in db.
async Task< ControllerResult< IPaginate< ContactGroupVM > > > GetGroups ([FromBody] FilterConfiguration filterConfiguration)
Get groups.
async Task< ControllerResult< ContactGroupVM > > GetGroup ([FromQuery] int groupId)
Get a group.
async Task< ControllerResult< ContactGroupVM > > DeleteGroup ([FromQuery] int groupId)
Delete group.
async Task< ControllerResult< ContactGroupVM > > AddOrUpdateContactGroup ([FromBody] ContactGroupVM contactGroupVM)
Add or update group.
async Task< ControllerResult< ContactGroupVM > > RemoveContactFromGroup ([FromBody] ContactForRemoveFromGroupVM contactForRemoveFromGroupVM)
Remove contact from a group.
async Task< ControllerResult< byte[]> > DownloadGroupContacts ([FromQuery] int groupId)
Download contacts that contain the group.
async Task< ControllerResult< IEnumerable< GroupCreationOption > > > GenerateGroupCreationOptions ([FromBody] List< string > fields)
Generate options for group create or update.
async Task< ControllerResult< IPaginate< ContactVM > > > GetGroupContactsPaginated ([FromBody] GetGroupContacts getGroupContacts)
Get contacts for given group.
async Task< ControllerResult< string[]> > GetTagNames ()
Get all tag names that contacts contain.
async Task< ControllerResult< IPaginate< ContactTagVM > > > GetTags ([FromBody] FilterConfiguration filterConfiguration)
Get tags.
ControllerResult< System.Guid > StartDeleteTagJob ([FromQuery] int contactTagId, [FromServices] IJobPoolService jobPoolService)
Start the job for deleting a tag.
ControllerResult< JobVM< ContactTagVM > > GetDeleteTagJob ([FromQuery] System.Guid id, [FromServices] IJobPoolService jobPoolService)
Get the job for deleting the tag.
ControllerResult< System.Guid > StartAddOrUpdateTagJob ([FromBody] ContactTagVM contactTagVM, [FromServices] IJobPoolService jobPoolService)
Add or update tag.
ControllerResult< JobVM< ContactTagVM > > GetAddOrUpdateTagJob ([FromQuery] System.Guid id, [FromServices] IJobPoolService jobPoolService)
Get the job for add or update tag.
async Task< ControllerResult > DownloadTagContacts ([FromBody] DownloadTagContactsVM downloadTagContactsVM)
Download contacts that contain the tag.
async Task< ControllerResult< IPaginate< UnsubscribedContact > > > GetUnsubscribedContacts ([FromBody] FilterConfiguration filterConfiguration)
Get Unsubscribed contacts.
async Task< ControllerResult > DisconnectRT ([FromQuery] System.Guid? userId)
Removes RedTail connections for selected User. If userId param is null Current user is disconnectred from CRM (Redtail, Salesforce)
async Task< ControllerResult< IEnumerable< System.Web.Mvc.SelectListItem > > > GetRedtailTagGroups ()
Get Red Tail List.
async Task< ControllerResult< IEnumerable< System.Web.Mvc.SelectListItem > > > RedTailLogin ([FromBody] LoginVM redtailLoginVM)
Check credentials for login and update profil table.
async Task< ControllerResult< IEnumerable< ContactVM > > > GetContactsByRedtailTagGroup ([FromBody] RedTailTagGroupVM redTailTagGroup)
Get Red Tail Contact List by Red Tail Id.
async Task< ControllerResult< UploadContactsResponse > > UploadRedTailContacts ([FromBody] UploadContactsRT uploadContactsRT)
async Task< ControllerResult > DisconnectSF ([FromQuery] System.Guid? userId, [FromServices] ISessionService sessionService)
Removes Salesforce connections for selected User. If userId param is null Current user is disconnectred from CRM (Redtail, Salesforce)
ControllerResult< string > GetSalesforceLoginUrl ()
Get SalesForce Contacts by given inputs values.
async Task< ControllerResult< IEnumerable< ContactImportAdminVM > > > GetSalesForceContacts (SalesForceGetContactInput salesForceGetContactInput)
async Task< ControllerResult< IEnumerable< ContactImportAdminVM > > > GetSFLeads (SalesForceGetContactInput salesForceGetContactInput)
Get SalesForce Leads by given inputs values.
ControllerResult< IEnumerable< SalesForceCustomFieldAdminVM > > GetCustomFields ()
Get CustomFields from SalesForce.
async Task< ControllerResult< UploadContactsResponse > > UploadSalesForceContacts ([FromBody] UploadContactsSFVM uploadContactsSFVM)
Upload contacts from SalesForce with Group name.
async Task< ControllerResult< IEnumerable< SalesForceCustomFieldAdminVM > > > SalesforceInit ()
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >
RootController ()
Empty Root Controller Constructor.
RootController (TService service)
Root Controller Constructor.
Private Attributes
readonly ISessionService _sessionService
Additional Inherited Members
Protected Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >
ControllerResult< Guid > StartJob< T > (Func< IServiceProvider, Task< T > > func, IJobPoolService jobPoolService)
ControllerResult< JobVM< T > > GetJob< T > (Guid id, IJobPoolService jobPoolService)
ControllerResult< JobVM< T > > GetJobServiceResult< T > (Guid id, IJobPoolService jobPoolService)
ControllerResult< JobVM< T > > GetJobApiResponse< T > (Guid id, IJobPoolService jobPoolService)
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >
TService service [get]
Base service for controller.
Detailed Description
Definition at line 31 of file ContactManagerController.cs.
Constructor & Destructor Documentation
ContactManagerController()
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.ContactManagerController (IContactManagerService service, ISessionService sessionService) inline
Contact Manager CTOR.
Parameters
service
sessionService
Definition at line 39 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController._sessionService.
Member Function Documentation
AddOrUpdateContactGroup()
async Task< ControllerResult< ContactGroupVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.AddOrUpdateContactGroup ([FromBody] ContactGroupVM contactGroupVM) inline
Add or update group.
Parameters
contactGroupVM Groups must contain id if it needs to be updated otherwise its added
Returns
Return added or updated group model
Definition at line 457 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientName().
CountContacts()
async Task< ControllerResult< int > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.CountContacts ([FromBody] SegmentationFilter filter) inline
Parameters
filter
Returns
Definition at line 186 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
CreateContact()
async Task< ControllerResult< IEnumerable< ContactVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.CreateContact ([FromBody] List< ContactVM > contactVMList) inline
Create list of contacts.
Parameters
contactVMList
Returns
List of created contacts
<response code="200">List of created contacts or Error message</response>
Definition at line 65 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientName().
DeleteGroup()
async Task< ControllerResult< ContactGroupVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.DeleteGroup ([FromQuery] int groupId) inline
Delete group.
Parameters
groupId group id
Returns
Deleted group model
Definition at line 446 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
DisconnectRT()
async Task< ControllerResult > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.DisconnectRT ([FromQuery] System.Guid? userId) inline
Removes RedTail connections for selected User. If userId param is null Current user is disconnectred from CRM (Redtail, Salesforce)
Parameters
userId Optional
Returns
Definition at line 631 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service, Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUserId(), and Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.Success.
DisconnectSF()
async Task< ControllerResult > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.DisconnectSF ([FromQuery] System.Guid? userId, [FromServices] ISessionService sessionService) inline
Removes Salesforce connections for selected User. If userId param is null Current user is disconnectred from CRM (Redtail, Salesforce)
Parameters
userId Optional
Returns
Definition at line 692 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service, and Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.Success.
DownloadGroupContacts()
async Task< ControllerResult< byte[]> > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.DownloadGroupContacts ([FromQuery] int groupId) inline
Download contacts that contain the group.
Parameters
groupId Id of the group
Returns
CSV file with contacts
Definition at line 487 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
DownloadTagContacts()
async Task< ControllerResult > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.DownloadTagContacts ([FromBody] DownloadTagContactsVM downloadTagContactsVM) inline
Download contacts that contain the tag.
Parameters
downloadTagContactsVM Object containing the name of the tag
Returns
CSV file with contacts
Definition at line 596 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.GenerateEqualFilter(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
DownloadTags()
ControllerResult Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.DownloadTags () inline
Download all tags.
Returns
CSV file with all contacts
Definition at line 329 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
DownUnsubscribedContacts()
async Task< ControllerResult > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.DownUnsubscribedContacts () inline
Download unsubscribed Contacts.
Returns
CSV file with all contacts
Definition at line 345 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GenerateGroupCreationOptions()
async Task< ControllerResult< IEnumerable< GroupCreationOption > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GenerateGroupCreationOptions ([FromBody] List< string > fields) inline
Generate options for group create or update.
Parameters
fields State, Tags, GroupName, City, Company
Returns
List of options and values
Definition at line 504 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetAddOrUpdateTagJob()
ControllerResult< JobVM< ContactTagVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetAddOrUpdateTagJob ([FromQuery] System.Guid id, [FromServices] IJobPoolService jobPoolService) inline
Get the job for add or update tag.
Returns
Return job
Definition at line 585 of file ContactManagerController.cs.
GetContact()
async Task< ControllerResult< ContactVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetContact ([FromQuery] string AccountID) inline
Get contact by AccountId.
Returns
Contact(as the only in the list)
<response code="200">List of filtered contacts or Error message</response>
Definition at line 163 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetContactAssociatedGroups()
async Task< ControllerResult< IPaginate< AssociatedGroupVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetContactAssociatedGroups ([FromBody] AssociatedGroupsFilterVM associatedGroupsFilterVM) inline
Get all groups that the contacts has.
Parameters
associatedGroupsFilterVM Filter with name of group
Returns
List of Groups
Definition at line 362 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetContactGroupDB()
ControllerResult< ContactGroupVM[]> Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetContactGroupDB () inline
Get all group name that are active in db.
Returns
List of group names
Definition at line 413 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetContacts()
async Task< ControllerResult< PaginatedContactsVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetContacts ([FromBody] ContactFilterVM contactFilterVM) inline
Get a list of filtered profile contacts, filter is a must.
Returns
List of filtered contacts
<response code="200">List of filtered contacts or Error message</response>
Definition at line 152 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetContactsByRedtailTagGroup()
async Task< ControllerResult< IEnumerable< ContactVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetContactsByRedtailTagGroup ([FromBody] RedTailTagGroupVM redTailTagGroup) inline
Get Red Tail Contact List by Red Tail Id.
Returns
List of Contacts by Red Tail Id
Definition at line 668 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetCustomFields()
ControllerResult< IEnumerable< SalesForceCustomFieldAdminVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetCustomFields () inline
Get CustomFields from SalesForce.
Returns
List of CustomFields from Tables(Contact, Lead)
Definition at line 749 of file ContactManagerController.cs.
GetDeleteContactJob()
ControllerResult< JobVM< IEnumerable< ContactVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetDeleteContactJob ([FromQuery] System.Guid id, [FromServices] IJobPoolService jobPoolService) inline
Get the job for delete list of contacts.
Returns
The requested job
<response code="200">The requested job</response>
Definition at line 298 of file ContactManagerController.cs.
GetDeleteTagJob()
ControllerResult< JobVM< ContactTagVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetDeleteTagJob ([FromQuery] System.Guid id, [FromServices] IJobPoolService jobPoolService) inline
Get the job for deleting the tag.
Returns
The requested job
<response code="200">The requested job</response>
Definition at line 563 of file ContactManagerController.cs.
GetDownloadContactsJob()
ControllerResult< JobVM< byte[]> > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetDownloadContactsJob ([FromQuery] System.Guid id, [FromServices] IJobPoolService jobPoolService) inline
Get the job for downloading all contacts.
Returns
CSV file with all contacts
Definition at line 319 of file ContactManagerController.cs.
GetGroup()
async Task< ControllerResult< ContactGroupVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetGroup ([FromQuery] int groupId) inline
Get a group.
Parameters
groupId id of the group
Returns
Group model
Definition at line 435 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetGroupContactsPaginated()
async Task< ControllerResult< IPaginate< ContactVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetGroupContactsPaginated ([FromBody] GetGroupContacts getGroupContacts) inline
Get contacts for given group.
Parameters
getGroupContacts
Returns
Paginated list of contacts
Definition at line 515 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetGroups()
async Task< ControllerResult< IPaginate< ContactGroupVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetGroups ([FromBody] FilterConfiguration filterConfiguration) inline
Get groups.
Parameters
filterConfiguration Sort and pagination
Returns
Paginated list of Groups
Definition at line 424 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetLastActivities()
async Task< ControllerResult< IEnumerable< MyContactActivity > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetLastActivities ([FromBody] ContactActivitiesVM contactActivitiesVM) inline
Get a campaign activities for contact.
Returns
List of campaign activities for contact
<response code="200">List of filtered contacts or Error message</response>
Definition at line 175 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetRedtailTagGroups()
async Task< ControllerResult< IEnumerable< System.Web.Mvc.SelectListItem > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetRedtailTagGroups () inline
Get Red Tail List.
Returns
List of Red Tails
Definition at line 648 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetSalesForceContacts()
async Task< ControllerResult< IEnumerable< ContactImportAdminVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetSalesForceContacts (SalesForceGetContactInput salesForceGetContactInput) inline
Parameters
salesForceGetContactInput
Returns
Definition at line 721 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetSalesforceLoginUrl()
ControllerResult< string > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetSalesforceLoginUrl () inline
Get SalesForce Contacts by given inputs values.
Returns
List of Contacts
Definition at line 710 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetSFLeads()
async Task< ControllerResult< IEnumerable< ContactImportAdminVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetSFLeads (SalesForceGetContactInput salesForceGetContactInput) inline
Get SalesForce Leads by given inputs values.
Returns
List of Leads
Definition at line 739 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetTagNames()
async Task< ControllerResult< string[]> > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetTagNames () inline
Get all tag names that contacts contain.
Returns
List of tag names
Definition at line 529 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetTags()
async Task< ControllerResult< IPaginate< ContactTagVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetTags ([FromBody] FilterConfiguration filterConfiguration) inline
Get tags.
Parameters
filterConfiguration Sort and pagination
Returns
Paginated list of Tags
Definition at line 540 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetUnsubscribedContacts()
async Task< ControllerResult< IPaginate< UnsubscribedContact > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetUnsubscribedContacts ([FromBody] FilterConfiguration filterConfiguration) inline
Get Unsubscribed contacts.
Parameters
filterConfiguration Sort and pagination
Returns
List of unsubscribed contacts
Definition at line 617 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
GetUploadContactsJob()
ControllerResult< JobVM< UploadContactsResponse > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.GetUploadContactsJob ([FromQuery] System.Guid id, [FromServices] IJobPoolService jobPoolService) inline
Check if an upload job has finished.
Returns
The result of the upload if finished, or 204 if it's in progress.
Definition at line 399 of file ContactManagerController.cs.
RedTailLogin()
async Task< ControllerResult< IEnumerable< System.Web.Mvc.SelectListItem > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.RedTailLogin ([FromBody] LoginVM redtailLoginVM) inline
Check credentials for login and update profil table.
Returns
All tag groups for that credentials
Definition at line 658 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
RemoveContactFromGroup()
async Task< ControllerResult< ContactGroupVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.RemoveContactFromGroup ([FromBody] ContactForRemoveFromGroupVM contactForRemoveFromGroupVM) inline
Remove contact from a group.
Parameters
contactForRemoveFromGroupVM
Returns
Contact
Definition at line 476 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
SalesforceInit()
async Task< ControllerResult< IEnumerable< SalesForceCustomFieldAdminVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.SalesforceInit () inline
Returns
Definition at line 768 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
SFCallback()
async Task< ControllerResult > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.SFCallback (string code) inline
Parameters
code
Returns
Definition at line 50 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service, and Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.Success.
StartAddOrUpdateTagJob()
ControllerResult< System.Guid > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.StartAddOrUpdateTagJob ([FromBody] ContactTagVM contactTagVM, [FromServices] IJobPoolService jobPoolService) inline
Add or update tag.
Parameters
contactTagVM Tag must contain id if it needs to be updated otherwise its added
jobPoolService
Returns
Job
Definition at line 575 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.AddOrUpdateTag().
StartDeleteContactJob()
ControllerResult< System.Guid > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.StartDeleteContactJob ([FromBody] List< ContactVM > contactVMList, [FromServices] IJobPoolService jobPoolService) inline
Start the job for delete list of contacts.
Parameters
contactVMList
jobPoolService
Returns
Job processing deleting the contacts
<response code="200">Job processing deleting the contacts</response>
Definition at line 287 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.UpdateContactMF().
StartDeleteTagJob()
ControllerResult< System.Guid > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.StartDeleteTagJob ([FromQuery] int contactTagId, [FromServices] IJobPoolService jobPoolService) inline
Start the job for deleting a tag.
Parameters
contactTagId tag id
jobPoolService
Returns
Job processing deleting the tag
Definition at line 552 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DeleteTag().
StartDownloadContactsJob()
ControllerResult< System.Guid > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.StartDownloadContactsJob ([FromServices] IJobPoolService jobPoolService) inline
Start the job for downloading all contacts.
Returns
Job GUID
Definition at line 309 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DownloadCSV().
StartUploadContactsJob()
ControllerResult< System.Guid > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.StartUploadContactsJob ([FromBody] UploadContactsVM uploadContactsVM, [FromServices] IJobPoolService jobPoolService) inline
Second step in csv upload. Starts a background job.
Parameters
uploadContactsVM
jobPoolService
Returns
Returns job GUID.
Definition at line 389 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.UploadContacts().
UpdateContact()
async Task< ControllerResult< IEnumerable< ContactVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.UpdateContact ([FromBody] List< ContactVM > contactVMList) inline
Update list of contacts.
Parameters
contactVMList
Returns
List of updated contacts
<response code="200">List of updated contacts or Error message</response>
Definition at line 198 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientName().
UploadCSV()
async Task< ControllerResult< ContactMapingVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.UploadCSV (IFormFile uploadedFile) inline
First Step in upload csv.
Parameters
uploadedFile It is required for the file to be a .csv format and also to contain at least two columns and one row after header.
Returns
Returns an object that contains FileName, CSV header and exmple row, Import contact types and available contact properties.
Definition at line 377 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
UploadRedTailContacts()
async Task< ControllerResult< UploadContactsResponse > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.UploadRedTailContacts ([FromBody] UploadContactsRT uploadContactsRT) inline
Parameters
uploadContactsRT
Returns
Definition at line 679 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
UploadSalesForceContacts()
async Task< ControllerResult< UploadContactsResponse > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.UploadSalesForceContacts ([FromBody] UploadContactsSFVM uploadContactsSFVM) inline
Upload contacts from SalesForce with Group name.
Definition at line 758 of file ContactManagerController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< IContactManagerService >.service.
Member Data Documentation
_sessionService
readonly ISessionService Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController._sessionService private
Definition at line 33 of file ContactManagerController.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.AddOrUpdateContactGroup(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.ContactManagerController(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.CreateContact(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.DisconnectRT(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.UpdateContact().
The documentation for this class was generated from the following file:
Source/API/Controllers/ContactManagerController.cs