AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService Class Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService Class Reference
Public Member Functions
TwitterService (ApplicationDbContext dbContext, ClientDbContext clientDbContext, IMapper mapper, ILogger< TwitterService > logger, ISessionService sessionService, IHttpClientFactory httpClientFactory)
ServiceResult< ITwitterCredentials > AuthenticateWithAccountCreds (TwitterAccount account)
ServiceResult< string > Auth (int clientId)
async Task< ServiceResult< string > > PublishTweet (SocialContent socialContent, SocialAccount socialAccount, string socialToken)
async Task< ServiceResult< string > > SaveCredentials (SocialAccountInfoVM socialAccountInfo, int clientId)
ServiceResult< IAuthenticatedUser > GetProfile (TwitterAccount twitterAccount)
async Task< ServiceResult< SocialAccountInfoVM > > GetSocailAccountInfo (string verifierCode, string authorizationId, string clientName)
virtual async Task< ServiceResult< List< TwitterAccount > > > GetBySocialToken (string socialToken)
async Task< ServiceResult< TwitterAccountVM > > Remove (UnlinkSocialVM unlinkSocialVM)
async Task< bool > DoesExist (Expression< Func< TwitterAccount, bool > > predicate)
List< SettingsVM > GetSettings (string groupName, int clientId=0)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService
Private Member Functions
ServiceResult< IAuthenticationContext > Authenticate (int clientId=0)
ServiceResult< string > PublishMessage (string message, TwitterAccount twitterAccount)
ServiceResult< string > PublishUrl (string message, string url, TwitterAccount twitterAccount)
async Task< ServiceResult< string > > PublishImage (string url, TwitterAccount twitterAccount, string message="")
async Task< ServiceResult< string > > PublishVideo (string url, TwitterAccount twitterAccount, string message="")
Static Private Member Functions
static string CheckTwitterCategory (SocialContent socialContent)
Private Attributes
readonly ApplicationDbContext _dbContext
readonly ClientDbContext _clientDbContext
readonly IMapper _mapper
readonly ILogger< TwitterService > _logger
readonly ISessionService _sessionService
readonly IHttpClientFactory _httpClientFactory
Detailed Description
Definition at line 37 of file TwitterService.cs.
Constructor & Destructor Documentation
TwitterService()
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.TwitterService (ApplicationDbContext dbContext, ClientDbContext clientDbContext, IMapper mapper, ILogger< TwitterService > logger, ISessionService sessionService, IHttpClientFactory httpClientFactory) inline
Definition at line 45 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._clientDbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._httpClientFactory, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._logger, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._mapper, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._sessionService.
Member Function Documentation
Auth()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.Auth (int clientId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.
Definition at line 96 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.Authenticate().
Authenticate()
ServiceResult< IAuthenticationContext > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.Authenticate (int clientId = 0) inline private
Definition at line 64 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetSettings().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.Auth().
AuthenticateWithAccountCreds()
ServiceResult< ITwitterCredentials > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.AuthenticateWithAccountCreds (TwitterAccount account) inline
Definition at line 81 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.TwitterAccount.AccessToken, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.TwitterAccount.AccessTokenSecret, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.BaseEntity.ClientId, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetSettings(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.Twitter.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishImage(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishMessage(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishUrl(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishVideo().
CheckTwitterCategory()
static string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.CheckTwitterCategory (SocialContent socialContent) inline static private
Definition at line 143 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.Link, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.Picture, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialLink.Url, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture.Url, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialVideo.Url, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.Video.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishTweet().
DoesExist()
async Task< bool > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.DoesExist (Expression< Func< TwitterAccount, bool > > predicate) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.
Definition at line 436 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._logger, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.TwitterAccounts.
GetBySocialToken()
virtual async Task< ServiceResult< List< TwitterAccount > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetBySocialToken (string socialToken) inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.
Definition at line 396 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._logger, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesAsync(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.TwitterAccounts.
GetProfile()
ServiceResult< IAuthenticatedUser > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetProfile (TwitterAccount twitterAccount) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.
Definition at line 321 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.TwitterAccount.AccessToken, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.TwitterAccount.AccessTokenSecret, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.BaseEntity.ClientId, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetSettings().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishImage(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishMessage(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishUrl(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishVideo(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.SaveCredentials().
GetSettings()
List< SettingsVM > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetSettings (string groupName, int clientId = 0) inline
Definition at line 456 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._mapper.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.Authenticate(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.AuthenticateWithAccountCreds(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetProfile(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetSocailAccountInfo().
GetSocailAccountInfo()
async Task< ServiceResult< SocialAccountInfoVM > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetSocailAccountInfo (string verifierCode, string authorizationId, string clientName) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.
Definition at line 344 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._clientDbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.SocialAccountInfoVM.AccessToken, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.Clients, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetSettings(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesAsync(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.TwitterAccounts.
PublishImage()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishImage (string url, TwitterAccount twitterAccount, string message = "") inline private
Definition at line 209 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._httpClientFactory, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.AuthenticateWithAccountCreds(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.CheckMimeType(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetProfile().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishTweet().
PublishMessage()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishMessage (string message, TwitterAccount twitterAccount) inline private
Definition at line 163 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.AuthenticateWithAccountCreds(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetProfile().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishTweet().
PublishTweet()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishTweet (SocialContent socialContent, SocialAccount socialAccount, string socialToken) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.
Definition at line 111 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialAccount.AccountId, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.CheckTwitterCategory(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishImage(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishMessage(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishUrl(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishVideo(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.TwitterAccounts.
PublishUrl()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishUrl (string message, string url, TwitterAccount twitterAccount) inline private
Definition at line 186 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.AuthenticateWithAccountCreds(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetProfile().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishTweet().
PublishVideo()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishVideo (string url, TwitterAccount twitterAccount, string message = "") inline private
Definition at line 245 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._httpClientFactory, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.AuthenticateWithAccountCreds(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.CheckMimeType(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetProfile().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishTweet().
Remove()
async Task< ServiceResult< TwitterAccountVM > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.Remove (UnlinkSocialVM unlinkSocialVM) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.
Definition at line 418 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._logger, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.UnlinkSocialVM.DbId, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesAsync(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.UnlinkSocialVM.SocialToken, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.TwitterAccounts.
SaveCredentials()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.SaveCredentials (SocialAccountInfoVM socialAccountInfo, int clientId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.
Definition at line 280 of file TwitterService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.SocialAccountInfoVM.AccessToken, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.SocialAccountInfoVM.AccessTokenSecret, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetProfile(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesAsync(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.SocialAccountInfoVM.SocialToken, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.TwitterAccounts.
Member Data Documentation
_clientDbContext
readonly ClientDbContext Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._clientDbContext private
Definition at line 40 of file TwitterService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetSocailAccountInfo(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.TwitterService().
_dbContext
readonly ApplicationDbContext Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._dbContext private
Definition at line 39 of file TwitterService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.DoesExist(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetBySocialToken(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetSocailAccountInfo(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishTweet(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.Remove(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.SaveCredentials(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.TwitterService().
_httpClientFactory
readonly IHttpClientFactory Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._httpClientFactory private
Definition at line 44 of file TwitterService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishImage(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishVideo(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.TwitterService().
_logger
readonly ILogger<TwitterService> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._logger private
Definition at line 42 of file TwitterService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.DoesExist(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetBySocialToken(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.Remove(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.TwitterService().
_mapper
readonly IMapper Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._mapper private
Definition at line 41 of file TwitterService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetSettings(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.TwitterService().
_sessionService
readonly ISessionService Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService._sessionService private
Definition at line 43 of file TwitterService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetBySocialToken(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.TwitterService().
The documentation for this class was generated from the following file:
Source/Infrastructure/Social/TwitterService.cs