AMM: Deluxe.DeluxeBrandCenter.AMM.Tests.SUT.API.Services.CampaignBuilderService.LaunchCampaign.SocialCampaignElementArranger Class Reference
Deluxe.DeluxeBrandCenter.AMM.Tests.SUT.API.Services.CampaignBuilderService.LaunchCampaign.SocialCampaignElementArranger Class Reference
Public Member Functions
Task Arrange (IContext ctx)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Tests.Arrangers.IArranger< IContext >
Task Arrange (TContext context)
Static Public Member Functions
static void MutateProgramXml (XElement programXml)
Detailed Description
Definition at line 125 of file LaunchCampaign.Arrangers.cs.
Member Function Documentation
Arrange()
Task Deluxe.DeluxeBrandCenter.AMM.Tests.SUT.API.Services.CampaignBuilderService.LaunchCampaign.SocialCampaignElementArranger.Arrange (IContext ctx) inline
Definition at line 127 of file LaunchCampaign.Arrangers.cs.
References Deluxe.DeluxeBrandCenter.AMM.Tests.SUT.API.Services.CampaignBuilderService.LaunchCampaign.IContext.CampaignBuilderService, and Deluxe.DeluxeBrandCenter.AMM.Tests.Mocks.IMockService< TDependencies >.Dependencies.
MutateProgramXml()
static void Deluxe.DeluxeBrandCenter.AMM.Tests.SUT.API.Services.CampaignBuilderService.LaunchCampaign.SocialCampaignElementArranger.MutateProgramXml (XElement programXml) inline static
Definition at line 136 of file LaunchCampaign.Arrangers.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Tests.SUT.API.Services.CampaignBuilderService.LaunchCampaign.FilterValidationError.FilterValidationError(), Deluxe.DeluxeBrandCenter.AMM.Tests.SUT.API.Services.CampaignBuilderService.LaunchCampaign.MapperException.MapperException(), Deluxe.DeluxeBrandCenter.AMM.Tests.SUT.API.Services.CampaignBuilderService.LaunchCampaign.PublishProgramError.PublishProgramError(), Deluxe.DeluxeBrandCenter.AMM.Tests.SUT.API.Services.CampaignBuilderService.LaunchCampaign.SetOutboundIdsError.SetOutboundIdsError(), Deluxe.DeluxeBrandCenter.AMM.Tests.SUT.API.Services.CampaignBuilderService.LaunchCampaign.SetOutboundIdsException.SetOutboundIdsException(), and Deluxe.DeluxeBrandCenter.AMM.Tests.SUT.API.Services.CampaignBuilderService.LaunchCampaign.Success.Success().
The documentation for this class was generated from the following file:
Source/Tests/SUT/API/Services/CampaignBuilderService/LaunchCampaign.Arrangers.cs