AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService Class Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService Class Reference
Public Member Functions
SalesforceService (IConfiguration configuration, ISessionService sessionService, ApplicationDbContext dbContext)
async Task< ServiceResult< List< SFQueryContactVM > > > GetGetSalesForceContacts (SalesForceGetContactInput salesForceGetContactInput, string instanceUrl, string accessToken, string apiVersion)
async Task< ServiceResult< List< SFQueryLeadsVM > > > GetSalesForceLeads (SalesForceGetContactInput salesForceGetContactInput, string instanceUrl, string accessToken, string apiVersion)
async Task< ServiceResult< List< SalesForceCustomFieldAdminVM > > > GetCustomFieldsAdmin (string[] tableNames, string instanceUrl, string accessToken, string apiVersion)
async Task< ServiceResult< AuthInfo > > Authenticate (string code)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService
Properties
IConfiguration Configuration [get]
ISession _session [get]
string callbackUrl [get]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService
Private Member Functions
string SetCustomFieldValue (string customFieldType, string customFieldValue)
async Task< ServiceResult< string > > GetCustomFieldWhereExpression (string customFieldId, string customFieldValue, string instanceUrl, string accessToken)
Static Private Member Functions
static string EncodeInputString (string inputStr)
Private Attributes
readonly string SFClientId
readonly string SFClientSecret
readonly string ApiVersion
readonly ISessionService _sessionService
readonly List< string > NonQuotedDataTypes = ["Number", "Checkbox", "Currency", "Date", "DateTime", "Percent"]
readonly List< string > UnsupportedDataTypes = ["Location"]
Detailed Description
Definition at line 32 of file SalesforceService.cs.
Constructor & Destructor Documentation
SalesforceService()
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SalesforceService (IConfiguration configuration, ISessionService sessionService, ApplicationDbContext dbContext) inline
Definition at line 49 of file SalesforceService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService._session, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.ApiVersion, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.callbackUrl, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.Settings, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SFClientId, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SFClientSecret.
Member Function Documentation
Authenticate()
async Task< ServiceResult< AuthInfo > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.Authenticate (string code) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService.
Definition at line 242 of file SalesforceService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.ApiVersion, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SFClientId, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SFClientSecret.
EncodeInputString()
static string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.EncodeInputString (string inputStr) inline static private
Definition at line 60 of file SalesforceService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.GetGetSalesForceContacts(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.GetSalesForceLeads(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SetCustomFieldValue().
GetCustomFieldsAdmin()
async Task< ServiceResult< List< SalesForceCustomFieldAdminVM > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.GetCustomFieldsAdmin (string[] tableNames, string instanceUrl, string accessToken, string apiVersion) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService.
Definition at line 212 of file SalesforceService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.GetCustomFieldWhereExpression().
GetCustomFieldWhereExpression()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.GetCustomFieldWhereExpression (string customFieldId, string customFieldValue, string instanceUrl, string accessToken) inline private
Definition at line 187 of file SalesforceService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.ApiVersion, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.GetCustomFieldsAdmin(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SetCustomFieldValue(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.UnsupportedDataTypes.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.GetGetSalesForceContacts(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.GetSalesForceLeads().
GetGetSalesForceContacts()
async Task< ServiceResult< List< SFQueryContactVM > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.GetGetSalesForceContacts (SalesForceGetContactInput salesForceGetContactInput, string instanceUrl, string accessToken, string apiVersion) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService.
Definition at line 85 of file SalesforceService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SalesForceGetContactInput.AccountName, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SalesForceGetContactInput.CustomFieldId, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SalesForceGetContactInput.CustomFieldValue, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.EncodeInputString(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SalesForceGetContactInput.ExcludeNoEmail, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.GetCustomFieldWhereExpression(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SalesForceGetContactInput.LeadSource, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SalesForceGetContactInput.State.
GetSalesForceLeads()
async Task< ServiceResult< List< SFQueryLeadsVM > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.GetSalesForceLeads (SalesForceGetContactInput salesForceGetContactInput, string instanceUrl, string accessToken, string apiVersion) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService.
Definition at line 137 of file SalesforceService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SalesForceGetContactInput.AccountName, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SalesForceGetContactInput.CustomFieldId, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SalesForceGetContactInput.CustomFieldValue, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.EncodeInputString(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SalesForceGetContactInput.ExcludeNoEmail, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.GetCustomFieldWhereExpression(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SalesForceGetContactInput.LeadSource, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SalesForceGetContactInput.State.
SetCustomFieldValue()
string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SetCustomFieldValue (string customFieldType, string customFieldValue) inline private
Definition at line 65 of file SalesforceService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.EncodeInputString(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.NonQuotedDataTypes.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.GetCustomFieldWhereExpression().
Member Data Documentation
_sessionService
readonly ISessionService Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService._sessionService private
Definition at line 41 of file SalesforceService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SalesforceService().
ApiVersion
readonly string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.ApiVersion private
Definition at line 40 of file SalesforceService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.Authenticate(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.GetCustomFieldWhereExpression(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SalesforceService().
NonQuotedDataTypes
readonly List<string> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.NonQuotedDataTypes = ["Number", "Checkbox", "Currency", "Date", "DateTime", "Percent"] private
Definition at line 43 of file SalesforceService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SetCustomFieldValue().
SFClientId
readonly string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SFClientId private
Definition at line 38 of file SalesforceService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.Authenticate(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SalesforceService().
SFClientSecret
readonly string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SFClientSecret private
Definition at line 39 of file SalesforceService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.Authenticate(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SalesforceService().
UnsupportedDataTypes
readonly List<string> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.UnsupportedDataTypes = ["Location"] private
Definition at line 44 of file SalesforceService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.GetCustomFieldWhereExpression().
Property Documentation
_session
ISession Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService._session get private
Definition at line 42 of file SalesforceService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SalesforceService().
callbackUrl
string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.callbackUrl get
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService.
Definition at line 45 of file SalesforceService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SalesforceService().
Configuration
IConfiguration Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.Configuration get
Definition at line 34 of file SalesforceService.cs.
The documentation for this class was generated from the following file:
Source/Infrastructure/Salesforce/SalesforceService.cs