AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF Class Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF Class Reference
Public Member Functions
ReportServiceMF (IConfiguration configuration, ISessionService sessionService, IHttpClientFactory clientFactory, ILoggerFactory loggerFactory, ApplicationDbContext dbContext)
async Task< ServiceResult< GetUnsubscribedCredentialsResponse > > GetUnsubscribeCredentials (string userEmail, string userPassword)
async Task< ServiceResult< GetUnsubscribedListResponse > > GetUnsubscribedList (string email, List< string > passwords)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService
BaseMindfireService (IConfiguration configuration, string serviceName, ISessionService sessionService, IHttpClientFactory clientFactory, ILoggerFactory loggerFactory)
async Task< TResponse > Post< TResponse > (string endpoint, object body)
async Task< TResponse > PostDashboard< TResponse > (string endpoint, object body)
async Task< TResponse > Get< TResponse > (string endpoint)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IReportServiceMF
Public Attributes
readonly ISessionService _sessionService
readonly ApplicationDbContext _dbContext
Public Attributes inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService
readonly ILogger _logger
string _accountNamePrefix
Additional Inherited Members
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService
ISession _session [get]
RequestCredentials masterRequestCredentials [get, set]
RequestCredentials userRequestCredentials [get, set]
IMindfireSettings configuration [get, set]
string ServiceName [get]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IBaseMindfireService
Detailed Description
Definition at line 22 of file ReportServiceMF.cs.
Constructor & Destructor Documentation
ReportServiceMF()
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF.ReportServiceMF (IConfiguration configuration, ISessionService sessionService, IHttpClientFactory clientFactory, ILoggerFactory loggerFactory, ApplicationDbContext dbContext) inline
Definition at line 27 of file ReportServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF._dbContext, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF._sessionService.
Member Function Documentation
GetUnsubscribeCredentials()
async Task< ServiceResult< GetUnsubscribedCredentialsResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF.GetUnsubscribeCredentials (string userEmail, string userPassword) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IReportServiceMF.
Definition at line 40 of file ReportServiceMF.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF.GetUnsubscribedList().
GetUnsubscribedList()
async Task< ServiceResult< GetUnsubscribedListResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF.GetUnsubscribedList (string email, List< string > passwords) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IReportServiceMF.
Definition at line 44 of file ReportServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF._dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF._sessionService, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.GetUnsubscribedCredentialsResponse.AccountList, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ErrorCode, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ErrorMessage, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.ExceptionMessage, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF.GetUnsubscribeCredentials(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF.GetUnsubscribedList(), Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.GetUnsubscribedListResponse.Result, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesAsync(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUserId(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.Users.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF.GetUnsubscribedList().
Member Data Documentation
_dbContext
readonly ApplicationDbContext Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF._dbContext
Definition at line 25 of file ReportServiceMF.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF.GetUnsubscribedList(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF.ReportServiceMF().
_sessionService
readonly ISessionService Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF._sessionService
Definition at line 24 of file ReportServiceMF.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF.GetUnsubscribedList(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF.ReportServiceMF().
The documentation for this class was generated from the following file:
Source/Infrastructure/Mindfire/ReportServiceMF.cs