AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService Interface Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService Interface Reference
Public Member Functions
Task< ServiceResult< IEnumerable< ContactVM > > > CreateContactMF (List< ContactVM > contactVMList)
Task< ServiceResult< IEnumerable< ContactVM > > > GetContacts (SegmentationFilter filter=null, List< string > fields=null, string filterString=null, bool allContacts=false)
Task< ServiceResult< ContactVM > > GetContact (string accountId)
Task< ServiceResult< IEnumerable< ContactVM > > > UpdateContactMF (List< ContactVM > contactVMList, bool doDelete=false)
Task< ServiceResult< PaginatedContactsVM > > GetPaginatedContacts (ContactFilterVM contactFilter, bool countContacts=false, int contactId=0)
Task< ServiceResult< IPaginate< AssociatedGroupVM > > > GetContactAssociatedGroups (AssociatedGroupsFilterVM associatedGroupsFilterVM)
Task< ServiceResult< IEnumerable< MyContactActivity > > > GetLastActivities (ContactActivitiesVM contactActivitiesVM)
Task< ServiceResult< ContactMapingVM > > GetColumnNames (IFormFile file)
Task< ServiceResult< UploadContactsResponse > > UploadContacts (UploadContactsVM uploadContactsVM, string source)
ServiceResult< ContactGroupVM[]> GetContactGroupDB ()
Task< ServiceResult< IPaginate< ContactGroupVM > > > GetGroups (FilterConfiguration filterConfiguration)
Task< ServiceResult< ContactGroupVM > > GetGroup (int groupId, IDictionary< string, IEnumerable< string > > filterOut=null, bool doGetSimpleContacts=true)
Task< ServiceResult< ContactGroupVM > > DeleteGroup (int groupId)
Task< ServiceResult< ContactGroupVM > > AddOrUpdateContactGroup (ContactGroupVM contactGroupVM)
Task< ServiceResult< IEnumerable< GroupCreationOption > > > GenerateGroupCreationOptions (List< string > fields)
ServiceResult< ContactGroupVM > AddManualContacts (ContactGroupVM contactGroupVM)
Task< ServiceResult< ContactGroup > > AddOrUpdateGroupDb (ContactGroupVM contactGroupVM, string migrationUserId="")
Task< ServiceResult< byte[]> > DownloadGroupContactsCSV (int groupId)
Task< ServiceResult< IPaginate< ContactVM > > > GetGroupContactsPaginated (GetGroupContacts getGroupContacts)
Task< ServiceResult< string[]> > GetTagNames ()
Task< ServiceResult< IPaginate< ContactTagVM > > > GetTags (FilterConfiguration filterConfiguration)
Task< ServiceResult< ContactTagVM > > DeleteTag (int tagId)
Task< ServiceResult< ContactTagVM > > AddOrUpdateTag (ContactTagVM tagVM)
Task< ServiceResult< ContactGroupVM > > RemoveContactFromGroup (ContactForRemoveFromGroupVM contactForRemoveFromGroupVM)
Task< ServiceResult< IPaginate< UnsubscribedContact > > > GetUnsubscribedContactsPaginated (FilterConfiguration filterConfiguration)
Task< ServiceResult< IEnumerable< UnsubscribedContact > > > GetUnsubscribedContacts ()
Task< ServiceResult< IEnumerable< int > > > GetUnsubscribedContactsId ()
Task< ServiceResult< IDictionary< string, IEnumerable< string > > > > GetContactsForFilteringOut ()
Task< ServiceResult< byte[]> > DownloadCSV (SegmentationFilter segmentationFilter=null, bool allContacts=false)
ServiceResult< byte[]> DownloadTagsCSV ()
Task< ServiceResult< byte[]> > DownloadUnsubscribedContactsCSV ()
Task< ServiceResult< bool > > DisconnectRedTail (string userId)
Task< ServiceResult< IEnumerable< SelectListItem > > > GetRedtailTagGroups ()
Task< ServiceResult< IEnumerable< ContactVM > > > GetRedtailTagGroup (RedTailTagGroupVM redTailTagGroup)
Task< ServiceResult< UploadContactsResponse > > UploadRedTailContacts (UploadContactsRT uploadContactsRT)
Task< ServiceResult< bool > > SFAuthenticte (string code)
Task< ServiceResult< bool > > DisconnectSalesforce (string userId)
Task< ServiceResult< IEnumerable< ContactImportAdminVM > > > GetSFContacts (SalesForceGetContactInput salesForceGetContactInput)
Task< ServiceResult< IEnumerable< ContactImportAdminVM > > > GetSFLeads (SalesForceGetContactInput salesForceGetContactInput)
Task< ServiceResult< IEnumerable< SalesForceCustomFieldAdminVM > > > SalesForceInit ()
Task< ServiceResult< UploadContactsResponse > > UploadSaleForceContacts (UploadContactsSFVM uploadContactsSFVM)
Task< ServiceResult< IEnumerable< SelectListItem > > > RedtailLogin (string username, string password)
Task< ServiceResult< int > > CountContacts (SegmentationFilter filter)
string GetSFCallbackURL ()
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< Contact, ContactVM >
Task< ServiceResult< TModelVM > > Single (int id)
Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate, int clientId)
Task< ServiceResult< TModel > > Entity (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
Task< ServiceResult< List< TModelVM > > > GetList ()
Task< ServiceResult< List< TModelVM > > > GetList (Expression< Func< TModel, bool > > predicate=null, Expression< Func< TModel, object > > orderBy=null, bool descending=false, bool disableTracking=true, string[] navigationPaths=null, bool clientSide=false, params Expression< Func< TModel, object > >[] include)
Task< ServiceResult< TModelVM > > Delete (int id)
Task< ServiceResult< TModel > > UpdateEntity (TModel entity)
Task< ServiceResult< TModelVM > > Update (TModelVM entity)
Task< string > UpdateSocialURLs (PMSPersonaDTO personalInfo)
void FillHtmlWithPersonalInfo (ref string htmlContent, PMSPersonaDTO personalInfo, List< KeyValuePair< string, string > > editorFields=null, int? clientId=0, bool preview=false)
void FillHtmlContent (ref string htmlContent, PMSPersonaDTO personalInfo, SignatureBlockVM signatureBlock, string insideMessage=null, List< KeyValuePair< string, string > > editorFields=null, bool preview=false)
Additional Inherited Members
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< Contact, ContactVM >
IApplicationDbContext dbContext [get, set]
IMapper mapper [get, set]
ILogger< DBService< TModel, TModelVM > > logger [get]
Detailed Description
Definition at line 39 of file ContactManagerService.cs.
Member Function Documentation
AddManualContacts()
ServiceResult< ContactGroupVM > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.AddManualContacts (ContactGroupVM contactGroupVM)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
AddOrUpdateContactGroup()
Task< ServiceResult< ContactGroupVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.AddOrUpdateContactGroup (ContactGroupVM contactGroupVM)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
AddOrUpdateGroupDb()
Task< ServiceResult< ContactGroup > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.AddOrUpdateGroupDb (ContactGroupVM contactGroupVM, string migrationUserId = "")
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
AddOrUpdateTag()
Task< ServiceResult< ContactTagVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.AddOrUpdateTag (ContactTagVM tagVM)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.StartAddOrUpdateTagJob().
CountContacts()
Task< ServiceResult< int > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.CountContacts (SegmentationFilter filter)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
CreateContactMF()
Task< ServiceResult< IEnumerable< ContactVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.CreateContactMF (List< ContactVM > contactVMList)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
DeleteGroup()
Task< ServiceResult< ContactGroupVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DeleteGroup (int groupId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
DeleteTag()
Task< ServiceResult< ContactTagVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DeleteTag (int tagId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.StartDeleteTagJob().
DisconnectRedTail()
Task< ServiceResult< bool > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DisconnectRedTail (string userId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
DisconnectSalesforce()
Task< ServiceResult< bool > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DisconnectSalesforce (string userId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
DownloadCSV()
Task< ServiceResult< byte[]> > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DownloadCSV (SegmentationFilter segmentationFilter = null, bool allContacts = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.DownloadRecipientList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsClickedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsFailedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsHardBouncedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSentToOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSoftBouncedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSpamOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsSuppressedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsThatOpenedOutboundSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.getContactsUnsubscribedOutboundSchedule(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.StartDownloadContactsJob().
DownloadGroupContactsCSV()
Task< ServiceResult< byte[]> > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DownloadGroupContactsCSV (int groupId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
DownloadTagsCSV()
ServiceResult< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DownloadTagsCSV ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
DownloadUnsubscribedContactsCSV()
Task< ServiceResult< byte[]> > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DownloadUnsubscribedContactsCSV ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GenerateGroupCreationOptions()
Task< ServiceResult< IEnumerable< GroupCreationOption > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GenerateGroupCreationOptions (List< string > fields)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetColumnNames()
Task< ServiceResult< ContactMapingVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetColumnNames (IFormFile file)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetContact()
Task< ServiceResult< ContactVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetContact (string accountId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetContactAssociatedGroups()
Task< ServiceResult< IPaginate< AssociatedGroupVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetContactAssociatedGroups (AssociatedGroupsFilterVM associatedGroupsFilterVM)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetContactGroupDB()
ServiceResult< ContactGroupVM[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetContactGroupDB ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateUserCampaign().
GetContacts()
Task< ServiceResult< IEnumerable< ContactVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetContacts (SegmentationFilter filter = null, List< string > fields = null, string filterString = null, bool allContacts = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetContactsForFilteringOut()
Task< ServiceResult< IDictionary< string, IEnumerable< string > > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetContactsForFilteringOut ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetGroup()
Task< ServiceResult< ContactGroupVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetGroup (int groupId, IDictionary< string, IEnumerable< string > > filterOut = null, bool doGetSimpleContacts = true)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetGroupContactsPaginated()
Task< ServiceResult< IPaginate< ContactVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetGroupContactsPaginated (GetGroupContacts getGroupContacts)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetGroups()
Task< ServiceResult< IPaginate< ContactGroupVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetGroups (FilterConfiguration filterConfiguration)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetLastActivities()
Task< ServiceResult< IEnumerable< MyContactActivity > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetLastActivities (ContactActivitiesVM contactActivitiesVM)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetPaginatedContacts()
Task< ServiceResult< PaginatedContactsVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetPaginatedContacts (ContactFilterVM contactFilter, bool countContacts = false, int contactId = 0)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetRedtailTagGroup()
Task< ServiceResult< IEnumerable< ContactVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetRedtailTagGroup (RedTailTagGroupVM redTailTagGroup)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetRedtailTagGroups()
Task< ServiceResult< IEnumerable< SelectListItem > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetRedtailTagGroups ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetSFCallbackURL()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetSFCallbackURL ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetSFContacts()
Task< ServiceResult< IEnumerable< ContactImportAdminVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetSFContacts (SalesForceGetContactInput salesForceGetContactInput)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetSFLeads()
Task< ServiceResult< IEnumerable< ContactImportAdminVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetSFLeads (SalesForceGetContactInput salesForceGetContactInput)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetTagNames()
Task< ServiceResult< string[]> > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetTagNames ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetTags()
Task< ServiceResult< IPaginate< ContactTagVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetTags (FilterConfiguration filterConfiguration)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetUnsubscribedContacts()
Task< ServiceResult< IEnumerable< UnsubscribedContact > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetUnsubscribedContacts ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetUnsubscribedContactsId()
Task< ServiceResult< IEnumerable< int > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetUnsubscribedContactsId ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
GetUnsubscribedContactsPaginated()
Task< ServiceResult< IPaginate< UnsubscribedContact > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetUnsubscribedContactsPaginated (FilterConfiguration filterConfiguration)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
RedtailLogin()
Task< ServiceResult< IEnumerable< SelectListItem > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.RedtailLogin (string username, string password)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
RemoveContactFromGroup()
Task< ServiceResult< ContactGroupVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.RemoveContactFromGroup (ContactForRemoveFromGroupVM contactForRemoveFromGroupVM)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
SalesForceInit()
Task< ServiceResult< IEnumerable< SalesForceCustomFieldAdminVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.SalesForceInit ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
SFAuthenticte()
Task< ServiceResult< bool > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.SFAuthenticte (string code)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
UpdateContactMF()
Task< ServiceResult< IEnumerable< ContactVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.UpdateContactMF (List< ContactVM > contactVMList, bool doDelete = false)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.StartDeleteContactJob().
UploadContacts()
Task< ServiceResult< UploadContactsResponse > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.UploadContacts (UploadContactsVM uploadContactsVM, string source)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.StartUploadContactsJob().
UploadRedTailContacts()
Task< ServiceResult< UploadContactsResponse > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.UploadRedTailContacts (UploadContactsRT uploadContactsRT)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
UploadSaleForceContacts()
Task< ServiceResult< UploadContactsResponse > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.UploadSaleForceContacts (UploadContactsSFVM uploadContactsSFVM)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.
The documentation for this interface was generated from the following file:
Source/API/Services/ContactManager/ContactManagerService.cs