AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.IIDPService Interface Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.IIDPService Interface Reference
Public Member Functions
string GetUserIdFromClaims (IEnumerable< Claim > claims)
Task< HttpResponseMessage > ValidateToken (string jwt)
If the IDP returns 401, terminate the request. If the IDP returns 200, proceed with the request execution.
Task< HttpResponseMessage > RefreshToken (string token)
POST /api/refresh Body { “refreshToken” : “t” } -200 with new token and refresh token if refresh token is valid -401 if refresh token is invalid.
Detailed Description
Definition at line 14 of file IDPService.cs.
Member Function Documentation
GetUserIdFromClaims()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.IIDPService.GetUserIdFromClaims (IEnumerable< Claim > claims)
Username string
CompanyId integer
UserGroupId integer
UserId integer
SiteId integer
ExternalId string
MlsFeeds object
UserGuid GUID
Parameters
Token
Returns
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.IDPService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.IDPExtensionMethods.AddIDPAuthentication(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.DatabaseSession().
RefreshToken()
Task< HttpResponseMessage > Deluxe.DeluxeBrandCenter.AMM.API.Services.IIDPService.RefreshToken (string token)
POST /api/refresh Body { “refreshToken” : “t” } -200 with new token and refresh token if refresh token is valid -401 if refresh token is invalid.
Parameters
token
Returns
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.IDPService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.IDPController.RefreshToken().
ValidateToken()
Task< HttpResponseMessage > Deluxe.DeluxeBrandCenter.AMM.API.Services.IIDPService.ValidateToken (string jwt)
If the IDP returns 401, terminate the request. If the IDP returns 200, proceed with the request execution.
Parameters
jwt
Returns
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.IDPService.
The documentation for this interface was generated from the following file:
Source/API/Services/IDP/IDPService.cs