AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession Class Reference
Public Member Functions
DatabaseSession (ApplicationDbContext dbContext, HttpContext httpContext, bool isAmmJwt)
DatabaseSession (ApplicationDbContext dbContext, string userId)
bool TryGetValue (string key, out byte[] value)
void Clear ()
void Remove (string key)
void Set (string key, byte[] value)
Task CommitAsync (CancellationToken token)
Task LoadAsync (CancellationToken token)
Properties
string Id [get]
bool IsAvailable [get]
IEnumerable< string > Keys [get]
Private Member Functions
Domain.DataModel.Session GetOrCreateSession (string userId)
Private Attributes
readonly Domain.DataModel.Session session
readonly ApplicationDbContext dbContext
Detailed Description
Definition at line 15 of file DatabaseSession.cs.
Constructor & Destructor Documentation
DatabaseSession() [1/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.DatabaseSession (ApplicationDbContext dbContext, HttpContext httpContext, bool isAmmJwt) inline
Definition at line 20 of file DatabaseSession.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.GetOrCreateSession(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IIDPService.GetUserIdFromClaims(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.session.
DatabaseSession() [2/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.DatabaseSession (ApplicationDbContext dbContext, string userId) inline
Definition at line 41 of file DatabaseSession.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.GetOrCreateSession(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.session.
Member Function Documentation
Clear()
void Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Clear () inline
Definition at line 87 of file DatabaseSession.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.dbContext, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.Session.Id, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesWithoutTimestamps(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.session, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SessionData.
CommitAsync()
Task Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.CommitAsync (CancellationToken token) inline
Definition at line 142 of file DatabaseSession.cs.
GetOrCreateSession()
Domain.DataModel.Session Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.GetOrCreateSession (string userId) inline private
Definition at line 47 of file DatabaseSession.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesWithoutTimestamps(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.Session, Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.session, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.Users.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.DatabaseSession(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.DatabaseSession().
LoadAsync()
Task Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.LoadAsync (CancellationToken token) inline
Definition at line 147 of file DatabaseSession.cs.
Remove()
void Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Remove (string key) inline
Definition at line 98 of file DatabaseSession.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.dbContext, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.Session.Id, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesWithoutTimestamps(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.session, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SessionData.
Set()
void Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Set (string key, byte[] value) inline
Definition at line 114 of file DatabaseSession.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.dbContext, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.Session.Id, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesWithoutTimestamps(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.session, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SessionData.
TryGetValue()
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.TryGetValue (string key, out byte[] value) inline
Definition at line 68 of file DatabaseSession.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.dbContext, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.Session.Id, Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.session, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SessionData.
Member Data Documentation
dbContext
readonly ApplicationDbContext Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.dbContext private
Definition at line 18 of file DatabaseSession.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Clear(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.DatabaseSession(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.DatabaseSession(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.GetOrCreateSession(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Remove(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Set(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.TryGetValue().
session
readonly Domain.DataModel.Session Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.session private
Definition at line 17 of file DatabaseSession.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Clear(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.DatabaseSession(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.DatabaseSession(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.GetOrCreateSession(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Remove(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Set(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.TryGetValue().
Property Documentation
Id
string Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Id get
Definition at line 64 of file DatabaseSession.cs.
IsAvailable
bool Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.IsAvailable get
Definition at line 65 of file DatabaseSession.cs.
Keys
IEnumerable<string> Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Keys get
Definition at line 66 of file DatabaseSession.cs.
The documentation for this class was generated from the following file:
Source/API/Services/Session/DatabaseSession.cs