AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService Interface Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService Interface Reference
Public Member Functions
Task< IEnumerable< DBOCampaignElements > > GetCampaignElements (AdvisorFilter filter)
Task< DTOCamapigns > GetCampaignsWithElements (AdvisorFilter filter)
Task< DTOCampaignsAndStats > GetCampaignsAndStats (MainFilter filter)
Task< DTOClickRates > getClickRates (MainFilter filter)
Task< DTOOpenRates > getOpenRates (MainFilter filter)
Task< DTOCampaignDetails > getCampaignDetails (int accountId, int campaignId)
Task< byte[]> getContactsSentToOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Task< byte[]> getContactsThatOpenedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Task< byte[]> getContactsClickedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Task< byte[]> getContactsSpamOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Task< byte[]> getContactsHardBouncedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Task< byte[]> getContactsSoftBouncedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Task< byte[]> getContactsSuppressedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Task< byte[]> getContactsFailedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Task< byte[]> getContactsUnsubscribedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Task< byte[]> GetContactActivityCSV (int accountId, int campaignId, int outboundId, int outboundScheduleId, int columnId)
Detailed Description
Definition at line 14 of file BiService.cs.
Member Function Documentation
getCampaignDetails()
Task< DTOCampaignDetails > Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.getCampaignDetails (int accountId, int campaignId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.StartCampaignDetailsJob().
GetCampaignElements()
Task< IEnumerable< DBOCampaignElements > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.GetCampaignElements (AdvisorFilter filter)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.GetCampaignElements().
GetCampaignsAndStats()
Task< DTOCampaignsAndStats > Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.GetCampaignsAndStats (MainFilter filter)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.StartCampaignsAndStatsJob().
GetCampaignsWithElements()
Task< DTOCamapigns > Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.GetCampaignsWithElements (AdvisorFilter filter)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.
getClickRates()
Task< DTOClickRates > Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.getClickRates (MainFilter filter)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.GetClickRates().
GetContactActivityCSV()
Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.GetContactActivityCSV (int accountId, int campaignId, int outboundId, int outboundScheduleId, int columnId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.StartContactActivityCsvJob().
getContactsClickedOutboundSchedule()
Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.getContactsClickedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.
getContactsFailedOutboundSchedule()
Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.getContactsFailedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.
getContactsHardBouncedOutboundSchedule()
Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.getContactsHardBouncedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.
getContactsSentToOutboundSchedule()
Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.getContactsSentToOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.
getContactsSoftBouncedOutboundSchedule()
Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.getContactsSoftBouncedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.
getContactsSpamOutboundSchedule()
Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.getContactsSpamOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.
getContactsSuppressedOutboundSchedule()
Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.getContactsSuppressedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.
getContactsThatOpenedOutboundSchedule()
Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.getContactsThatOpenedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.
getContactsUnsubscribedOutboundSchedule()
Task< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.getContactsUnsubscribedOutboundSchedule (int accountId, int campaignId, int outboundId, int outboundScheduleId, List< string > fields)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.
getOpenRates()
Task< DTOOpenRates > Deluxe.DeluxeBrandCenter.AMM.API.Services.IBIService.getOpenRates (MainFilter filter)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.BIController.GetOpenRates().
The documentation for this interface was generated from the following file:
Source/API/Services/BiService.cs