AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria Class Reference
Public Member Functions
SegmentationFilterCriteria ()
SegmentationFilterCriteria (string field, string operation, string value, int row)
Static Public Member Functions
static SegmentationFilterCriteria GenerateFilterCriteria (string field, string operation, string value, int row)
Properties
int Row [get, set]
string Field [get, set]
string Operation [get, set]
string Value [get, set]
Detailed Description
Definition at line 719 of file MindfireServiceModel.cs.
Constructor & Destructor Documentation
SegmentationFilterCriteria() [1/2]
Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.SegmentationFilterCriteria () inline
Definition at line 721 of file MindfireServiceModel.cs.
SegmentationFilterCriteria() [2/2]
Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.SegmentationFilterCriteria (string field, string operation, string value, int row) inline
Definition at line 725 of file MindfireServiceModel.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.Field, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.Operation, and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.Row.
Member Function Documentation
GenerateFilterCriteria()
static SegmentationFilterCriteria Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.GenerateFilterCriteria (string field, string operation, string value, int row) inline static
Definition at line 733 of file MindfireServiceModel.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.Field, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.Operation, and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.Row.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddManualContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContact(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.RolloutDates(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.RolloutNONEState(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.RolloutTags(), Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.SetDateFields(), Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.SetFilterCriteriasForNONEState(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.SetTagsField().
Property Documentation
Field
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.Field get set
Definition at line 751 of file MindfireServiceModel.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.GenerateFilterCriteria(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.SegmentationFilterCriteria().
Operation
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.Operation get set
Definition at line 757 of file MindfireServiceModel.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.GenerateFilterCriteria(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.SegmentationFilterCriteria().
Row
int Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.Row get set
Definition at line 745 of file MindfireServiceModel.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.GenerateFilterCriteria(), Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.SegmentationFilterCriteria(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.SetNoGroupFoundCriteria().
Value
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.Value get set
Definition at line 763 of file MindfireServiceModel.cs.
The documentation for this class was generated from the following file:
Source/Domain/ExtServiceModel/MindfireServiceModel.cs