AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM > Class Template Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM > Class Template Reference
Public Member Functions
DBService ()
DBService (IMapper mapper, IApplicationDbContext dbContext, IConfiguration configuration, ILogger< DBService< TModel, TModelVM > > logger, ISocialNetworkService socialNetworkService, ISessionService sessionService)
virtual async Task< string > UpdateSocialURLs (PMSPersonaDTO personalInfo)
virtual async Task< ServiceResult< TModelVM > > Delete (int id)
virtual async Task< ServiceResult< TModel > > Entity (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
virtual async Task< ServiceResult< TModelVM > > Single (int id)
virtual async Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
virtual async Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate, int clientId)
virtual async Task< ServiceResult< List< TModelVM > > > GetList ()
virtual async Task< ServiceResult< List< TModelVM > > > GetList (Expression< Func< TModel, bool > > predicate=null, Expression< Func< TModel, object > > orderBy=null, bool descending=false, bool disableTracking=false, string[] navigationPaths=null, bool clientSide=false, params Expression< Func< TModel, object > >[] include)
virtual async Task< ServiceResult< TModelVM > > Update (TModelVM entity)
virtual async Task< ServiceResult< TModel > > UpdateEntity (TModel entity)
virtual async Task< bool > DoesExist< TModelCheck > (int id)
virtual void FillHtmlWithPersonalInfo (ref string htmlContent, PMSPersonaDTO personalInfo, List< KeyValuePair< string, string > > editorFields=null, int? clientId=0, bool preview=false)
virtual void FillHtmlContent (ref string htmlContent, PMSPersonaDTO personalInfo, SignatureBlockVM signatureBlock, string insideMessage=null, List< KeyValuePair< string, string > > editorFields=null, bool preview=false)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >
Public Attributes
ISocialNetworkService _socialNetworkService
ISessionService _sessionService
Protected Attributes
readonly DbSet< TModel > _dbSet
Properties
IApplicationDbContext dbContext [get, set]
IMapper mapper [get, set]
IConfiguration configuration [get, set]
ILogger< DBService< TModel, TModelVM > > logger [get]
string Client [get]
int? ClientId [get]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >
Private Attributes
readonly string _modelName = typeof(TModel).Name
Detailed Description
Type Constraints
TModel : BaseEntity
TModelVM : BaseEntityVM
Definition at line 70 of file DBService.cs.
Constructor & Destructor Documentation
DBService() [1/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.DBService () inline
Definition at line 96 of file DBService.cs.
DBService() [2/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.DBService (IMapper mapper, IApplicationDbContext dbContext, IConfiguration configuration, ILogger< DBService< TModel, TModelVM > > logger, ISocialNetworkService socialNetworkService, ISessionService sessionService) inline
Definition at line 102 of file DBService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._dbSet, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._socialNetworkService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.configuration, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.logger, and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.mapper.
Member Function Documentation
Delete()
virtual async Task< ServiceResult< TModelVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Delete (int id) inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.
Definition at line 167 of file DBService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._dbSet, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._modelName, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.mapper, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.SaveChangesAsync(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId().
DoesExist< TModelCheck >()
virtual async Task< bool > Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.DoesExist< TModelCheck > (int id) inline virtual
Type Constraints
TModelCheck : BaseEntity
Definition at line 416 of file DBService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._dbSet, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._modelName, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.logger, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId().
Entity()
virtual async Task< ServiceResult< TModel > > Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Entity (Expression< Func< TModel, bool > > predicate = null, bool disableTracking = false, string[] navigationPaths = null, params Expression< Func< TModel, object > >[] include) inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.
Definition at line 185 of file DBService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._dbSet, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._modelName, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.logger, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.UpdateEntity().
FillHtmlContent()
virtual void Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.FillHtmlContent (ref string htmlContent, PMSPersonaDTO personalInfo, SignatureBlockVM signatureBlock, string insideMessage = null, List< KeyValuePair< string, string > > editorFields = null, bool preview = false) inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.
Definition at line 707 of file DBService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.FillHtmlWithPersonalInfo(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SignatureBlockVM.Signature.
FillHtmlWithPersonalInfo()
virtual void Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.FillHtmlWithPersonalInfo (ref string htmlContent, PMSPersonaDTO personalInfo, List< KeyValuePair< string, string > > editorFields = null, int? clientId = 0, bool preview = false) inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.
Definition at line 427 of file DBService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.ClientId, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.configuration, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PMSPersonaDTO.Data, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ExcludeImgFromString(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.Settings.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.FillHtmlContent().
GetList() [1/2]
virtual async Task< ServiceResult< List< TModelVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.GetList () inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.
Definition at line 322 of file DBService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._dbSet, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.mapper, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId().
GetList() [2/2]
virtual async Task< ServiceResult< List< TModelVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.GetList (Expression< Func< TModel, bool > > predicate = null, Expression< Func< TModel, object > > orderBy = null, bool descending = false, bool disableTracking = false, string[] navigationPaths = null, bool clientSide = false, params Expression< Func< TModel, object > >[] include) inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.
Definition at line 329 of file DBService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._dbSet, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.mapper, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId().
Single() [1/3]
virtual async Task< ServiceResult< TModelVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single (Expression< Func< TModel, bool > > predicate, int clientId) inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.
Definition at line 286 of file DBService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._dbSet, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._modelName, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.logger, and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.mapper.
Single() [2/3]
virtual async Task< ServiceResult< TModelVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single (Expression< Func< TModel, bool > > predicate = null, bool disableTracking = false, string[] navigationPaths = null, params Expression< Func< TModel, object > >[] include) inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.
Definition at line 241 of file DBService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._dbSet, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._modelName, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.mapper, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId().
Single() [3/3]
virtual async Task< ServiceResult< TModelVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single (int id) inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.
Definition at line 228 of file DBService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._dbSet, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._modelName, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.mapper, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Update(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< TModel, TModelVM >.Update().
Update()
virtual async Task< ServiceResult< TModelVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Update (TModelVM entity) inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.
Reimplemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< TModel, TModelVM >.
Definition at line 390 of file DBService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._dbSet, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.mapper, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.SaveChangesAsync(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single().
UpdateEntity()
virtual async Task< ServiceResult< TModel > > Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.UpdateEntity (TModel entity) inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.
Definition at line 409 of file DBService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._dbSet, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Entity(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.SaveChangesAsync(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId().
UpdateSocialURLs()
virtual async Task< string > Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.UpdateSocialURLs (PMSPersonaDTO personalInfo) inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.
Definition at line 120 of file DBService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._socialNetworkService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.CheckSocialForUser(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PMSPersonaDTO.Data.
Member Data Documentation
_dbSet
readonly DbSet<TModel> Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._dbSet protected
Definition at line 72 of file DBService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.DBService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Delete(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.DoesExist< TModelCheck >(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Entity(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.GetList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.GetList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Update(), Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< TModel, TModelVM >.Update(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.UpdateEntity().
_modelName
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._modelName = typeof(TModel).Name private
Definition at line 89 of file DBService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Delete(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.DoesExist< TModelCheck >(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Entity(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single().
_sessionService
ISessionService Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._sessionService
Definition at line 92 of file DBService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.DBService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Delete(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.DoesExist< TModelCheck >(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Entity(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.FillHtmlContent(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.GetList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.GetList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Update(), Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< TModel, TModelVM >.Update(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.UpdateEntity().
_socialNetworkService
ISocialNetworkService Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._socialNetworkService
Definition at line 91 of file DBService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.DBService(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.UpdateSocialURLs().
Property Documentation
Client
string Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Client get
Definition at line 94 of file DBService.cs.
ClientId
int? Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.ClientId get
Definition at line 95 of file DBService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.FillHtmlWithPersonalInfo().
configuration
IConfiguration Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.configuration get set
Definition at line 81 of file DBService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.DBService(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.FillHtmlWithPersonalInfo().
dbContext
IApplicationDbContext Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.dbContext get set
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.
Definition at line 73 of file DBService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.DBService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Delete(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.FillHtmlWithPersonalInfo(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Update(), Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< TModel, TModelVM >.Update(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.UpdateEntity().
logger
ILogger<DBService<TModel, TModelVM> > Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.logger get
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.
Definition at line 85 of file DBService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.DBService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Delete(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.DoesExist< TModelCheck >(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Entity(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< TModel, TModelVM >.Update().
mapper
IMapper Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.mapper get set
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.
Definition at line 77 of file DBService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.DBService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Delete(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.GetList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.GetList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Update(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< TModel, TModelVM >.Update().
The documentation for this class was generated from the following file:
Source/API/Services/DBService.cs