AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService Interface Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService Interface Reference
Public Member Functions
Task< ServiceResult< List< SFQueryContactVM > > > GetGetSalesForceContacts (SalesForceGetContactInput salesForceGetContactInput, string instanceUrl, string accessToken, string apiVersion)
Task< ServiceResult< List< SFQueryLeadsVM > > > GetSalesForceLeads (SalesForceGetContactInput salesForceGetContactInput, string instanceUrl, string accessToken, string apiVersion)
Task< ServiceResult< List< SalesForceCustomFieldAdminVM > > > GetCustomFieldsAdmin (string[] tableNames, string instanceUrl, string accessToken, string apiVersion)
Task< ServiceResult< AuthInfo > > Authenticate (string code)
Properties
string callbackUrl [get]
Detailed Description
Definition at line 20 of file SalesforceService.cs.
Member Function Documentation
Authenticate()
Task< ServiceResult< AuthInfo > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService.Authenticate (string code)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.SFAuthenticte().
GetCustomFieldsAdmin()
Task< ServiceResult< List< SalesForceCustomFieldAdminVM > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService.GetCustomFieldsAdmin (string[] tableNames, string instanceUrl, string accessToken, string apiVersion)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.SalesForceInit().
GetGetSalesForceContacts()
Task< ServiceResult< List< SFQueryContactVM > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService.GetGetSalesForceContacts (SalesForceGetContactInput salesForceGetContactInput, string instanceUrl, string accessToken, string apiVersion)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSFContacts().
GetSalesForceLeads()
Task< ServiceResult< List< SFQueryLeadsVM > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService.GetSalesForceLeads (SalesForceGetContactInput salesForceGetContactInput, string instanceUrl, string accessToken, string apiVersion)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSFLeads().
Property Documentation
callbackUrl
string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService.callbackUrl get
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.
Definition at line 27 of file SalesforceService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSFCallbackURL().
The documentation for this interface was generated from the following file:
Source/Infrastructure/Salesforce/SalesforceService.cs