AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialLink Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialLink Class Reference
Public Member Functions
SocialLink ()
Static Package Functions
static SocialLink GenerateSocialLink (SharingMessage sharingMessage)
Properties
string Url [get, set]
string Caption [get, set]
Private Member Functions
SocialLink (SharingMessage sharingMessage)
Detailed Description
Definition at line 116 of file SharingRequest.cs.
Constructor & Destructor Documentation
SocialLink() [1/2]
Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialLink.SocialLink () inline
Definition at line 118 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialLink.GenerateSocialLink().
SocialLink() [2/2]
Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialLink.SocialLink (SharingMessage sharingMessage) inline private
Definition at line 122 of file SharingRequest.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialLink.Caption, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.Link.caption, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.Parts.link, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.SharingMessage.parts, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialLink.Url, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.Link.url.
Member Function Documentation
GenerateSocialLink()
static SocialLink Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialLink.GenerateSocialLink (SharingMessage sharingMessage) inline static package
Definition at line 127 of file SharingRequest.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialLink.SocialLink().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.SocialContent().
Property Documentation
Caption
string Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialLink.Caption get set
Definition at line 136 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialLink.SocialLink().
Url
string Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialLink.Url get set
Definition at line 132 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.CheckShareMediaCategory(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.CheckTwitterCategory(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialLink.SocialLink().
The documentation for this class was generated from the following file:
Source/Domain/ViewModel/Social/SharingRequest.cs