AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable Class Reference
Public Member Functions
CSVTable (string rowSeparator="\n", string fieldSeparator=",")
Constructor 1.
CSVTable (string csv, string rowSeparator="\n", string fieldSeparator=",")
Constructor 2 (with csv string)
void LoadCSV (string csv)
Load csv data from string.
string ToCSV (string rowSeparator, string fieldSeparator)
To csv.
string ToCSV ()
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >
Table ()
int GetColumnNo (string columnName)
T[] Row (int row)
T[][] AllRows ()
T[] Column (int no)
T[] Column (string columnName)
T Data (int row, int columnNo)
T Data (int row, string columnName)
T DataOrDefault (int row, string columnName)
string[] Header ()
void SetValue (int row, int columnNo, T value)
Set value for specific field.
void SetValue (int row, string columnName, T value)
Set value for specific field.
bool SetHeader (string[] names)
Set header.
bool SetHeader (List< string > names)
Set header.
bool DeleteRow (int row)
Delete row.
bool AppendRow (List< T > data)
Append row.
bool InsertRow (int index, List< T > data)
Insert row.
bool DeleteColumn (string columnName)
Delete column.
bool DeleteColumn (int no)
Delete column.
bool AppendColumn (string columnName, List< T > data)
bool InsertEmptyValues ()
check if there are fields without "" (that are null)
Protected Attributes
string _fieldSeparator
Field separator property.
string _rowSeparator
Row separator property.
Protected Attributes inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >
List< List< T > > _data
List< string > _header
Additional Inherited Members
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >
int Columns [get]
int Rows [get]
Detailed Description
Definition at line 7 of file CSVTable.cs.
Constructor & Destructor Documentation
CSVTable() [1/2]
Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable.CSVTable (string rowSeparator = "\n", string fieldSeparator = ",") inline
Constructor 1.
Parameters
rowSeparator Row separaator is "\n"
fieldSeparator Field separator is "," by default
Definition at line 23 of file CSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable._fieldSeparator, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable._rowSeparator.
CSVTable() [2/2]
Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable.CSVTable (string csv, string rowSeparator = "\n", string fieldSeparator = ",") inline
Constructor 2 (with csv string)
Parameters
csv CSV data
rowSeparator Row separaator is "\n"
fieldSeparator Field separator is "," by default
Definition at line 35 of file CSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable._fieldSeparator, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable._rowSeparator, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable.LoadCSV().
Member Function Documentation
LoadCSV()
void Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable.LoadCSV (string csv) inline
Load csv data from string.
Parameters
csv
Definition at line 47 of file CSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >._data, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable._fieldSeparator, Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >._header, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable._rowSeparator, Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.AppendRow(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.InsertEmptyValues(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.SetHeader().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable.CSVTable().
ToCSV() [1/2]
string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable.ToCSV () inline
Definition at line 97 of file CSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >._data, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable._fieldSeparator, Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >._header, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable._rowSeparator, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.String.ClearSpecialCharacters(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Rows.
ToCSV() [2/2]
string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable.ToCSV (string rowSeparator, string fieldSeparator) inline
To csv.
Parameters
rowSeparator string
fieldSeparator string
Returns
Definition at line 72 of file CSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >._data, Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >._header, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.String.ClearSpecialCharacters(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Rows.
Member Data Documentation
_fieldSeparator
string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable._fieldSeparator protected
Field separator property.
Definition at line 12 of file CSVTable.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable.CSVTable(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable.CSVTable(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.GetErrorRows(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable.LoadCSV(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable.ToCSV().
_rowSeparator
string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable._rowSeparator protected
Row separator property.
Definition at line 16 of file CSVTable.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable.CSVTable(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable.CSVTable(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.GetErrorRows(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable.LoadCSV(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable.ToCSV().
The documentation for this class was generated from the following file:
Source/Domain/Utility/CSVTable.cs