AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SharingRequest Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SharingRequest Class Reference
Public Member Functions
SharingRequest ()
SharingRequest (SharingBodyVM sharingBodyVM)
Static Public Member Functions
static SharingRequest GenerateSharingRequest (SharingBodyVM sharingBodyVM)
Properties
PublishForUser PublishForUser [get, set]
SocialContent SocialContent [get, set]
Detailed Description
Definition at line 7 of file SharingRequest.cs.
Constructor & Destructor Documentation
SharingRequest() [1/2]
Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SharingRequest.SharingRequest () inline
Definition at line 9 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SharingRequest.GenerateSharingRequest().
SharingRequest() [2/2]
Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SharingRequest.SharingRequest (SharingBodyVM sharingBodyVM) inline
Definition at line 13 of file SharingRequest.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.GeneratePublishForUser(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.GenerateSocialContent(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.SharingBodyVM.request, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.Request.sharing_message.
Member Function Documentation
GenerateSharingRequest()
static SharingRequest Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SharingRequest.GenerateSharingRequest (SharingBodyVM sharingBodyVM) inline static
Definition at line 19 of file SharingRequest.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SharingRequest.SharingRequest().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapSocialElementToXML().
Property Documentation
PublishForUser
PublishForUser Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SharingRequest.PublishForUser get set
Definition at line 24 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Sharing().
SocialContent
SocialContent Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SharingRequest.SocialContent get set
Definition at line 28 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapSocialElementToXML(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Sharing().
The documentation for this class was generated from the following file:
Source/Domain/ViewModel/Social/SharingRequest.cs