var namespace_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_domain_1_1_data_model_1_1_contact_manager =
[
    [ "ContactGroup", "db/de4/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_domain_1_1_data_model_1_1_contact_manager_1_1_contact_group.html", "db/de4/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_domain_1_1_data_model_1_1_contact_manager_1_1_contact_group" ],
    [ "ContactTag", "dc/d10/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_domain_1_1_data_model_1_1_contact_manager_1_1_contact_tag.html", "dc/d10/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_domain_1_1_data_model_1_1_contact_manager_1_1_contact_tag" ]
];