AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ActivityCSVTable Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ActivityCSVTable Class Reference
Public Member Functions
ActivityCSVTable (string csv, string rowSeparator="\n", string fieldSeparator=",")
ServiceResult< IEnumerable< MyContactActivity > > ToMyContactActivityList ()
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable
CSVTable (string rowSeparator="\n", string fieldSeparator=",")
Constructor 1.
CSVTable (string csv, string rowSeparator="\n", string fieldSeparator=",")
Constructor 2 (with csv string)
void LoadCSV (string csv)
Load csv data from string.
string ToCSV (string rowSeparator, string fieldSeparator)
To csv.
string ToCSV ()
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >
Table ()
int GetColumnNo (string columnName)
T[] Row (int row)
T[][] AllRows ()
T[] Column (int no)
T[] Column (string columnName)
T Data (int row, int columnNo)
T Data (int row, string columnName)
T DataOrDefault (int row, string columnName)
string[] Header ()
void SetValue (int row, int columnNo, T value)
Set value for specific field.
void SetValue (int row, string columnName, T value)
Set value for specific field.
bool SetHeader (string[] names)
Set header.
bool SetHeader (List< string > names)
Set header.
bool DeleteRow (int row)
Delete row.
bool AppendRow (List< T > data)
Append row.
bool InsertRow (int index, List< T > data)
Insert row.
bool DeleteColumn (string columnName)
Delete column.
bool DeleteColumn (int no)
Delete column.
bool AppendColumn (string columnName, List< T > data)
bool InsertEmptyValues ()
check if there are fields without "" (that are null)
Properties
List< MyContactActivity > MyContactActivityList [get, set]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >
int Columns [get]
int Rows [get]
Private Member Functions
MyContactActivity CreateMyContactActivity (int rowNo)
Static Private Member Functions
static bool IsNullableType (Type type)
static void SetValue (MyContactActivity model, string propertyName, object value)
Additional Inherited Members
Protected Attributes inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVTable
string _fieldSeparator
Field separator property.
string _rowSeparator
Row separator property.
Protected Attributes inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >
List< List< T > > _data
List< string > _header
Detailed Description
Definition at line 9 of file ActivityCSVTable.cs.
Constructor & Destructor Documentation
ActivityCSVTable()
Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ActivityCSVTable.ActivityCSVTable (string csv, string rowSeparator = "\n", string fieldSeparator = ",") inline
Definition at line 16 of file ActivityCSVTable.cs.
Member Function Documentation
CreateMyContactActivity()
MyContactActivity Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ActivityCSVTable.CreateMyContactActivity (int rowNo) inline private
Definition at line 41 of file ActivityCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >._header, Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >.Columns, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ActivityCSVTable.SetValue().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ActivityCSVTable.ToMyContactActivityList().
IsNullableType()
static bool Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ActivityCSVTable.IsNullableType (Type type) inline static private
Definition at line 21 of file ActivityCSVTable.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ActivityCSVTable.SetValue().
SetValue()
static void Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ActivityCSVTable.SetValue (MyContactActivity model, string propertyName, object value) inline static private
Definition at line 26 of file ActivityCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ActivityCSVTable.IsNullableType().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ActivityCSVTable.CreateMyContactActivity().
ToMyContactActivityList()
ServiceResult< IEnumerable< MyContactActivity > > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ActivityCSVTable.ToMyContactActivityList () inline
Definition at line 51 of file ActivityCSVTable.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< string >._data, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ActivityCSVTable.CreateMyContactActivity(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ActivityCSVTable.MyContactActivityList.
Property Documentation
MyContactActivityList
List<MyContactActivity> Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ActivityCSVTable.MyContactActivityList get set private
Definition at line 11 of file ActivityCSVTable.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ActivityCSVTable.ToMyContactActivityList().
The documentation for this class was generated from the following file:
Source/Domain/Utility/ActivityCSVTable.cs