var 20190221113339___remove_broker_dealer_8_designer_8cs =
[
    [ "Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.Migrations.RemoveBrokerDealer", "da/d2a/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_databases_1_1_migrations_1_1_remove_broker_dealer.html", "da/d2a/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_databases_1_1_migrations_1_1_remove_broker_dealer" ]
];