AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture Class Reference
Public Member Functions
SocialPicture ()
Static Package Functions
static SocialPicture GenerateSocialPicture (SharingMessage sharingMessage)
Properties
string Url [get, set]
string Caption [get, set]
Private Member Functions
SocialPicture (SharingMessage sharingMessage)
Detailed Description
Definition at line 142 of file SharingRequest.cs.
Constructor & Destructor Documentation
SocialPicture() [1/2]
Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture.SocialPicture () inline
Definition at line 144 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture.GenerateSocialPicture().
SocialPicture() [2/2]
Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture.SocialPicture (SharingMessage sharingMessage) inline private
Definition at line 148 of file SharingRequest.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture.Caption, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.Picture.caption, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.SharingMessage.parts, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.Parts.picture, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture.Url, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.Picture.url.
Member Function Documentation
GenerateSocialPicture()
static SocialPicture Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture.GenerateSocialPicture (SharingMessage sharingMessage) inline static package
Definition at line 162 of file SharingRequest.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture.SocialPicture().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.SocialContent().
Property Documentation
Caption
string Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture.Caption get set
Definition at line 157 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture.SocialPicture().
Url
string Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture.Url get set
Definition at line 153 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.CheckShareMediaCategory(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.CheckTwitterCategory(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMediaIMAGE(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture.SocialPicture().
The documentation for this class was generated from the following file:
Source/Domain/ViewModel/Social/SharingRequest.cs