AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService Interface Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService Interface Reference
Public Member Functions
ServiceResult< string > LoginRedirect (int clientId)
Task< ServiceResult< LinkedinAuthorizationTokenResponse > > GetAccessToken (LinkedinAuthorizationCode linkedinAuthorizationCode, int clientId)
Task< ServiceResult< GetProfileResponse > > GetProfile (string accessToken, int clientId)
Task< ServiceResult< ShareResponse > > SharePost (SocialContent socialContent, SocialAccount socialAccount, string socialToken)
Task< bool > DoesExist (Expression< Func< LinkedinAccount, bool > > predicate)
Task< ServiceResult< LinkedinAccountVM > > Remove (UnlinkSocialVM unlinkSocialVM)
Task< ServiceResult< List< LinkedinAccountVM > > > GetBySocialToken (string socialToken)
Task< ServiceResult< SocialAccountInfoVM > > GetSocailAccountInfo (string code, string state, int clientId)
Task< ServiceResult< string > > SaveCredentials (SocialAccountInfoVM socialAccountInfo, int clientId)
Task< ServiceResult< TokenExpirationWarningStatusResponse > > CheckTokensStatusForWarning (string accessToken, string refreshToken, int clientId)
Detailed Description
Definition at line 28 of file LinkedinService.cs.
Member Function Documentation
CheckTokensStatusForWarning()
Task< ServiceResult< TokenExpirationWarningStatusResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.CheckTokensStatusForWarning (string accessToken, string refreshToken, int clientId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckRefreshTokenForWarning(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckSocialForUser().
DoesExist()
Task< bool > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.DoesExist (Expression< Func< LinkedinAccount, bool > > predicate)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckSocialForUser(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.UnlinkFromSocial().
GetAccessToken()
Task< ServiceResult< LinkedinAuthorizationTokenResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.GetAccessToken (LinkedinAuthorizationCode linkedinAuthorizationCode, int clientId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.
GetBySocialToken()
Task< ServiceResult< List< LinkedinAccountVM > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.GetBySocialToken (string socialToken)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckSocialForUser().
GetProfile()
Task< ServiceResult< GetProfileResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.GetProfile (string accessToken, int clientId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckSocialForUser().
GetSocailAccountInfo()
Task< ServiceResult< SocialAccountInfoVM > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.GetSocailAccountInfo (string code, string state, int clientId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.GetLinkedinAccountInfo().
LoginRedirect()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.LoginRedirect (int clientId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.SocialAuthorization().
Remove()
Task< ServiceResult< LinkedinAccountVM > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.Remove (UnlinkSocialVM unlinkSocialVM)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckSocialForUser(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.UnlinkFromSocial().
SaveCredentials()
Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.SaveCredentials (SocialAccountInfoVM socialAccountInfo, int clientId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.SaveCredentials().
SharePost()
Task< ServiceResult< ShareResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.SharePost (SocialContent socialContent, SocialAccount socialAccount, string socialToken)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Sharing().
The documentation for this interface was generated from the following file:
Source/Infrastructure/Social/LinkedinService.cs