AMM: Deluxe.DeluxeBrandCenter.AMM.API.Program Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Program Class Reference
Static Public Member Functions
static void Main (string[] args)
Static Protected Member Functions
static IConfigurationBuilder ConfigureConfigurationBuilder (ConfigurationManager configurationManager, string[] args)
static IConfigurationRoot BuildConfiguration (ConfigurationManager configurationManager, string[] args)
static void ConfigureLogging (IConfigurationRoot config)
static void ConfigureServices (IServiceCollection services, IConfigurationRoot config)
static void ConfigureJson (IMvcBuilder mvcBuilder)
static void ConfigureHost (ConfigureHostBuilder host)
static void ConfigureWebHost (ConfigureWebHostBuilder webHost)
static WebApplication BuildApplication (WebApplicationBuilder builder)
static void ConfigureApplication (WebApplication application, IConfigurationRoot config)
static void MigrateDatabase (WebApplication app, IConfigurationRoot config)
Detailed Description
Definition at line 52 of file Program.cs.
Member Function Documentation
BuildApplication()
static WebApplication Deluxe.DeluxeBrandCenter.AMM.API.Program.BuildApplication (WebApplicationBuilder builder) inline static protected
Definition at line 397 of file Program.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Program.Main(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Program.Main().
BuildConfiguration()
static IConfigurationRoot Deluxe.DeluxeBrandCenter.AMM.API.Program.BuildConfiguration (ConfigurationManager configurationManager, string[] args) inline static protected
Definition at line 102 of file Program.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureConfigurationBuilder().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Program.Main().
ConfigureApplication()
static void Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureApplication (WebApplication application, IConfigurationRoot config) inline static protected
Definition at line 402 of file Program.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Program.Main(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Program.Main().
ConfigureConfigurationBuilder()
static IConfigurationBuilder Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureConfigurationBuilder (ConfigurationManager configurationManager, string[] args) inline static protected
Definition at line 90 of file Program.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Program.BuildConfiguration(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Program.Main().
ConfigureHost()
static void Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureHost (ConfigureHostBuilder host) inline static protected
Definition at line 387 of file Program.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Program.Main(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Program.Main().
ConfigureJson()
static void Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureJson (IMvcBuilder mvcBuilder) inline static protected
Definition at line 361 of file Program.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureServices().
ConfigureLogging()
static void Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureLogging (IConfigurationRoot config) inline static protected
Definition at line 107 of file Program.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Program.Main(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Program.Main().
ConfigureServices()
static void Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureServices (IServiceCollection services, IConfigurationRoot config) inline static protected
Definition at line 126 of file Program.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.Clients, Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureJson(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SetUserId(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.Users.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Program.Main(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Program.Main().
ConfigureWebHost()
static void Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureWebHost (ConfigureWebHostBuilder webHost) inline static protected
Definition at line 392 of file Program.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Program.Main(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Program.Main().
Main()
static void Deluxe.DeluxeBrandCenter.AMM.API.Program.Main (string[] args) inline static
Parameters
args
Definition at line 58 of file Program.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Program.BuildApplication(), Deluxe.DeluxeBrandCenter.AMM.API.Program.BuildConfiguration(), Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureApplication(), Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureHost(), Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureLogging(), Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureServices(), Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureWebHost(), and Deluxe.DeluxeBrandCenter.AMM.API.Program.MigrateDatabase().
MigrateDatabase()
static void Deluxe.DeluxeBrandCenter.AMM.API.Program.MigrateDatabase (WebApplication app, IConfigurationRoot config) inline static protected
Definition at line 432 of file Program.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Program.Main(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Program.Main().
The documentation for this class was generated from the following file:
Source/API/Program.cs