AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service Class Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service Class Reference
Public Member Functions
AmazonS3Service (ILogger< AmazonS3Service > logger, IConfiguration configuration, ISessionService sessionService)
async Task< ServiceResult< AmazonResponse > > DownloadCampaignTemplate (string campaignTemplateFileName)
async Task< ServiceResult< AmazonResponse > > DownloadStringHTML (string url)
async Task< ServiceResult< AmazonResponse > > DownloadString (string url, string s3Bucket=null)
async Task< ServiceResult< AmazonResponse > > DeleteFile (string url, string s3Bucket=null)
async Task< ServiceResult< AmazonResponse > > UploadHtml (string htmlContent, string htmlName)
async Task< ServiceResult< AmazonResponse > > UploadText (string content, string name)
async Task< ServiceResult< AmazonResponse > > UploadCSV (IFormFile content, string fileName, string bucket)
async Task< ServiceResult< AmazonResponse > > UploadBadCSV (string csvContent, string csvFN)
string GetS3RootUrl ()
string GetRssFeedsFolder ()
async Task< ServiceResult< AmazonResponse > > DownloadRssFeed (string filename)
async Task< ServiceResult< AmazonResponse > > UploadRssFeed (string filename, string xml)
async Task< ServiceResult< AmazonResponse > > DownloadHTMLFromContent (string fileName, string folder=null)
async Task< ServiceResult< string > > DownloadHtmlContent (string contentUrl)
async Task< ServiceResult< string > > DownloadPreviewTemplate (string path)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service
Properties
string Bucket [get, set]
ISession _session [get]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service
Private Member Functions
async Task< ServiceResult< AmazonResponse > > DownloadStringFromUrl (string url, string s3Bucket=null)
async Task< ServiceResult< AmazonResponse > > DownloadFromContent (string fileName, string baseFolder, string subFolder)
Private Attributes
readonly string _s3UrlPrefix
readonly AmazonS3Client _amazonClient
readonly ILogger _logger
readonly IConfiguration _configuration
readonly ISessionService _sessionService
Detailed Description
Definition at line 41 of file AmazonS3Service.cs.
Constructor & Destructor Documentation
AmazonS3Service()
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.AmazonS3Service (ILogger< AmazonS3Service > logger, IConfiguration configuration, ISessionService sessionService) inline
Definition at line 60 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._amazonClient, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._configuration, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._logger, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._s3UrlPrefix, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._sessionService.
Member Function Documentation
DeleteFile()
async Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DeleteFile (string url, string s3Bucket = null) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.
Definition at line 89 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._amazonClient, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.Bucket.
DownloadCampaignTemplate()
async Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadCampaignTemplate (string campaignTemplateFileName) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.
Definition at line 75 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._configuration, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadStringFromUrl().
DownloadFromContent()
async Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadFromContent (string fileName, string baseFolder, string subFolder) inline private
Definition at line 267 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._configuration, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadStringFromUrl().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadHTMLFromContent().
DownloadHtmlContent()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadHtmlContent (string contentUrl) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.
Definition at line 284 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._logger, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadStringHTML().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadPreviewTemplate().
DownloadHTMLFromContent()
async Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadHTMLFromContent (string fileName, string folder = null) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.
Definition at line 278 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadFromContent().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.TemplateService.GetDisclosureTextTemplate(), Deluxe.DeluxeBrandCenter.AMM.API.Services.TemplateService.GetInsideMessageTemplate(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.TemplateService.GetSignatureBlock().
DownloadPreviewTemplate()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadPreviewTemplate (string path) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.
Definition at line 302 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._configuration, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadHtmlContent().
DownloadRssFeed()
async Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadRssFeed (string filename) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.
Definition at line 236 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadStringFromUrl().
DownloadString()
async Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadString (string url, string s3Bucket = null) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.
Definition at line 85 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadStringFromUrl().
DownloadStringFromUrl()
async Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadStringFromUrl (string url, string s3Bucket = null) inline private
Definition at line 108 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._amazonClient, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.Bucket.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadCampaignTemplate(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadFromContent(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadRssFeed(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadString(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadStringHTML().
DownloadStringHTML()
async Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadStringHTML (string url) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.
Definition at line 80 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._configuration, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.Bucket, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadStringFromUrl().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadHtmlContent().
GetRssFeedsFolder()
string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.GetRssFeedsFolder () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.
Definition at line 231 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.GetS3RootUrl().
GetS3RootUrl()
string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.GetS3RootUrl () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.
Definition at line 226 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._s3UrlPrefix, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.Bucket.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.GetRssFeedsFolder().
UploadBadCSV()
async Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadBadCSV (string csvContent, string csvFN) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.
Definition at line 199 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._amazonClient, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._s3UrlPrefix, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.Bucket.
UploadCSV()
async Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadCSV (IFormFile content, string fileName, string bucket) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.
Definition at line 175 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._amazonClient, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._s3UrlPrefix.
UploadHtml()
async Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadHtml (string htmlContent, string htmlName) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.
Definition at line 126 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._amazonClient, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.Bucket.
UploadRssFeed()
async Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadRssFeed (string filename, string xml) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.
Definition at line 241 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._amazonClient, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._s3UrlPrefix, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.Bucket.
UploadText()
async Task< ServiceResult< AmazonResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadText (string content, string name) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.
Definition at line 151 of file AmazonS3Service.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._amazonClient, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.Bucket.
Member Data Documentation
_amazonClient
readonly AmazonS3Client Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._amazonClient private
Definition at line 55 of file AmazonS3Service.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.AmazonS3Service(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DeleteFile(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadStringFromUrl(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadBadCSV(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadCSV(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadHtml(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadRssFeed(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadText().
_configuration
readonly IConfiguration Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._configuration private
Definition at line 57 of file AmazonS3Service.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.AmazonS3Service(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadCampaignTemplate(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadFromContent(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadPreviewTemplate(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadStringHTML().
_logger
readonly ILogger Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._logger private
Definition at line 56 of file AmazonS3Service.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.AmazonS3Service(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadHtmlContent().
_s3UrlPrefix
readonly string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._s3UrlPrefix private
Definition at line 54 of file AmazonS3Service.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.AmazonS3Service(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.GetS3RootUrl(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadBadCSV(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadCSV(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadRssFeed().
_sessionService
readonly ISessionService Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._sessionService private
Definition at line 58 of file AmazonS3Service.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.AmazonS3Service().
Property Documentation
_session
ISession Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service._session get private
Definition at line 59 of file AmazonS3Service.cs.
Bucket
string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.Bucket get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.
Definition at line 43 of file AmazonS3Service.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DeleteFile(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadStringFromUrl(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadStringHTML(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.GetS3RootUrl(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadBadCSV(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadHtml(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadRssFeed(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.UploadText().
The documentation for this class was generated from the following file:
Source/Infrastructure/AWS/S3/AmazonS3Service.cs