AMM: Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Extensions.IProgramServiceMFExtensions Class Reference
Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Extensions.IProgramServiceMFExtensions Class Reference
Static Public Member Functions
static async Task< ServiceResult< ProgramCheckoutResponse > > CheckOutProgramResiliently (this IProgramServiceMF programServiceMF, string ticket, int programId)
static async Task< ServiceResult< GetProgramResponse > > GetProgramResiliently (this IProgramServiceMF programServiceMF, string ticket, int programId)
static async Task< ServiceResult< ProgramCheckinResponse > > CheckInProgramResiliently (this IProgramServiceMF programServiceMF, string ticket, int programId, string programXML, string comment)
Detailed Description
Definition at line 9 of file IProgramServiceMFExtensions.cs.
Member Function Documentation
CheckInProgramResiliently()
static async Task< ServiceResult< ProgramCheckinResponse > > Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Extensions.IProgramServiceMFExtensions.CheckInProgramResiliently (this IProgramServiceMF programServiceMF, string ticket, int programId, string programXML, string comment) inline static
Definition at line 51 of file IProgramServiceMFExtensions.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.CheckInProgram(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.UndoProgramChanges().
CheckOutProgramResiliently()
static async Task< ServiceResult< ProgramCheckoutResponse > > Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Extensions.IProgramServiceMFExtensions.CheckOutProgramResiliently (this IProgramServiceMF programServiceMF, string ticket, int programId) inline static
Definition at line 11 of file IProgramServiceMFExtensions.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.CheckOutProgram(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.UndoProgramChanges().
GetProgramResiliently()
static async Task< ServiceResult< GetProgramResponse > > Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Extensions.IProgramServiceMFExtensions.GetProgramResiliently (this IProgramServiceMF programServiceMF, string ticket, int programId) inline static
Definition at line 31 of file IProgramServiceMFExtensions.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.GetProgram(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.UndoProgramChanges().
The documentation for this class was generated from the following file:
Scripts/ScriptRunner/Extensions/IProgramServiceMFExtensions.cs