AMM: Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType > Class Template Reference
Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType > Class Template Reference
Public Member Functions
CsvLogger (string filePath, string fileName, bool consoleLog, int capacity=10)
script logger constructor
void Log (CsvLogEntryType message)
Adds log object to cache. If cache is full, it will be appended to file and cleared.
async Task< string > Finish ()
Finish logging. Flushes remaining log cache to file.
bool IsProcessed (string id)
checks if the item is already processed
void Processed (string id)
adds the item to processed list
Properties
static DateTime _started [get]
Private Member Functions
record struct ProcessedRecord (string Data)
void Save ()
void Flush ()
void LoadProcessed ()
void SaveProcessed ()
Private Attributes
readonly string _fileName
readonly int _capacity
readonly bool _consoleLog
readonly List< CsvLogEntryType > _logCache
readonly List< ProcessedRecord > _processed
readonly List< ProcessedRecord > _processedCache
readonly string _processedFileName
Detailed Description
Template Parameters
CsvLogEntryType
Type Constraints
CsvLogEntryType : CsvLogEntry
Definition at line 19 of file CsvLogger.cs.
Constructor & Destructor Documentation
CsvLogger()
Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.CsvLogger (string filePath, string fileName, bool consoleLog, int capacity = 10) inline
script logger constructor
Parameters
config
fileName Log file name without extension. If extension exists it will be ignored.
capacity After filling capacity log will be saved/appended to log file and internal log cache will be cleared.
overwrite Overwrite existing log file
Definition at line 49 of file CsvLogger.cs.
References Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._capacity, Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._consoleLog, Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._fileName, Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._logCache, Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._processed, Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._processedCache, Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._processedFileName, and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.LoadProcessed().
Member Function Documentation
Finish()
async Task< string > Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Finish () inline
Finish logging. Flushes remaining log cache to file.
Definition at line 98 of file CsvLogger.cs.
References Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._consoleLog, Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._fileName, Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._logCache, and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Flush().
Flush()
void Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Flush () inline private
Definition at line 177 of file CsvLogger.cs.
References Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._consoleLog, Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._logCache, and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Save().
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Finish(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Log().
IsProcessed()
bool Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.IsProcessed (string id) inline
checks if the item is already processed
Parameters
id
Returns
Definition at line 121 of file CsvLogger.cs.
References Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._processed.
LoadProcessed()
void Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.LoadProcessed () inline private
Definition at line 188 of file CsvLogger.cs.
References Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._consoleLog, Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._processed, Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._processedFileName, and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.ProcessedRecord().
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.CsvLogger().
Log()
void Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Log (CsvLogEntryType message) inline
Adds log object to cache. If cache is full, it will be appended to file and cleared.
Template Parameters
T
Parameters
message
args
Returns
Definition at line 81 of file CsvLogger.cs.
References Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._capacity, Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._consoleLog, Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._logCache, and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Flush().
Processed()
void Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Processed (string id) inline
adds the item to processed list
Parameters
id
Definition at line 129 of file CsvLogger.cs.
References Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._processed, and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._processedCache.
ProcessedRecord()
record struct Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.ProcessedRecord (string Data) inline private
Definition at line 21 of file CsvLogger.cs.
References Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.ProcessedRecord().
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.LoadProcessed(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.ProcessedRecord().
Save()
void Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Save () inline private
Definition at line 156 of file CsvLogger.cs.
References Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._consoleLog, Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._fileName, Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._logCache, and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.SaveProcessed().
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Flush().
SaveProcessed()
void Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.SaveProcessed () inline private
Definition at line 210 of file CsvLogger.cs.
References Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._consoleLog, Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._processedCache, and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._processedFileName.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Save().
Member Data Documentation
_capacity
readonly int Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._capacity private
Definition at line 35 of file CsvLogger.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.CsvLogger(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Log().
_consoleLog
readonly bool Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._consoleLog private
Definition at line 36 of file CsvLogger.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.CsvLogger(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Finish(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Flush(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.LoadProcessed(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Log(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Save(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.SaveProcessed().
_fileName
readonly string Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._fileName private
Definition at line 34 of file CsvLogger.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.CsvLogger(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Finish(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Save().
_logCache
readonly List<CsvLogEntryType> Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._logCache private
Definition at line 37 of file CsvLogger.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.CsvLogger(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Finish(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Flush(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Log(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Save().
_processed
readonly List<ProcessedRecord> Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._processed private
Definition at line 38 of file CsvLogger.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.CsvLogger(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.IsProcessed(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.LoadProcessed(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Processed().
_processedCache
readonly List<ProcessedRecord> Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._processedCache private
Definition at line 39 of file CsvLogger.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.CsvLogger(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.Processed(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.SaveProcessed().
_processedFileName
readonly string Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._processedFileName private
Definition at line 41 of file CsvLogger.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.CsvLogger(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.LoadProcessed(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >.SaveProcessed().
Property Documentation
_started
DateTime Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Models.CsvLogger< CsvLogEntryType >._started static get private
Definition at line 40 of file CsvLogger.cs.
The documentation for this class was generated from the following file:
Scripts/ScriptRunner/Models/CsvLogger.cs