AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper Class Reference
Static Public Member Functions
static string Serialize< T > (T obj, JsonSerializerOptions options)
static string Serialize< T > (T obj)
static T Deserialize< T > (string json, JsonSerializerOptions options)
static T Deserialize< T > (string json)
static JsonNode Parse (string json, JsonNodeOptions options)
static JsonNode Parse (string json)
Properties
static JsonSerializerOptions SerializerOptions [get, set]
static JsonNodeOptions NodeOptions [get, set]
Static Private Attributes
static JsonSerializerOptions serializerOptions = new()
static JsonNodeOptions nodeOptions = new()
static readonly object serializerOptionsLock = new()
static readonly object nodeOptionsLock = new()
Detailed Description
Definition at line 90 of file JsonHelper.cs.
Member Function Documentation
Deserialize< T >() [1/2]
static T Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Deserialize< T > (string json) inline static
Definition at line 138 of file JsonHelper.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Deserialize< T >(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.serializerOptions.
Deserialize< T >() [2/2]
static T Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Deserialize< T > (string json, JsonSerializerOptions options) inline static
Definition at line 133 of file JsonHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Deserialize< T >().
Parse() [1/2]
static JsonNode Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Parse (string json) inline static
Definition at line 148 of file JsonHelper.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.nodeOptions, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Parse().
Parse() [2/2]
static JsonNode Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Parse (string json, JsonNodeOptions options) inline static
Definition at line 143 of file JsonHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Mapper.AutoMapperDefaultConfiguration.AutoMapperDefaultConfiguration(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.CampaignDetails(), Deluxe.DeluxeBrandCenter.AMM.Domain.Mapper.AutoMapperDefaultConfiguration.JsonObjectTypeConverter.Convert(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.FormatContactLists(), Deluxe.DeluxeBrandCenter.AMM.API.Services.TemplateService.GetSingleByTemplateId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLtoCampaignElement(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToSchedule(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Parse(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SaveCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetScheduleConfig(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UpdateLaunchedCampaign().
Serialize< T >() [1/2]
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Serialize< T > (T obj) inline static
Definition at line 128 of file JsonHelper.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.serializerOptions.
Serialize< T >() [2/2]
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Serialize< T > (T obj, JsonSerializerOptions options) inline static
Definition at line 123 of file JsonHelper.cs.
Member Data Documentation
nodeOptions
JsonNodeOptions Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.nodeOptions = new() static private
Definition at line 93 of file JsonHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Parse().
nodeOptionsLock
readonly object Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.nodeOptionsLock = new() static private
Definition at line 109 of file JsonHelper.cs.
serializerOptions
JsonSerializerOptions Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.serializerOptions = new() static private
Definition at line 92 of file JsonHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Deserialize< T >(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Serialize< T >().
serializerOptionsLock
readonly object Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.serializerOptionsLock = new() static private
Definition at line 95 of file JsonHelper.cs.
Property Documentation
NodeOptions
JsonNodeOptions Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.NodeOptions static get set
Definition at line 110 of file JsonHelper.cs.
SerializerOptions
JsonSerializerOptions Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.SerializerOptions static get set
Definition at line 96 of file JsonHelper.cs.
The documentation for this class was generated from the following file:
Source/Domain/Utility/JsonHelper.cs