AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService Class Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService Class Reference
Public Member Functions
LinkedinService (ApplicationDbContext dbContext, IMapper mapper, ILogger< LinkedinService > logger, ISessionService sessionService, IHttpClientFactory httpClientFactory)
List< SettingsVM > GetSettings (string groupName, int clientId)
ServiceResult< string > LoginRedirect (int clientId)
async Task< ServiceResult< LinkedinAuthorizationTokenResponse > > GetAccessToken (LinkedinAuthorizationCode linkedinAuthorizationCode, int clientId)
async Task< ServiceResult< GetProfileResponse > > GetProfile (string accessToken, int clientId)
async Task< ServiceResult< TokenStatusResponse > > TokenStatus (string token, List< SettingsVM > linkedintSettings)
async Task< ServiceResult< TokenExpirationWarningStatusResponse > > CheckTokensStatusForWarning (string accessToken, string refreshToken, int clientId)
async Task< ServiceResult< ShareResponse > > SharePost (SocialContent socialContent, SocialAccount socialAccount, string socialToken)
async Task< ServiceResult< string > > SaveCredentials (SocialAccountInfoVM socialAccountInfo, int clientId)
async Task< bool > DoesExist (Expression< Func< LinkedinAccount, bool > > predicate)
async Task< ServiceResult< LinkedinAccountVM > > Remove (UnlinkSocialVM unlinkSocialVM)
virtual async Task< ServiceResult< List< LinkedinAccountVM > > > GetBySocialToken (string socialToken)
async Task< ServiceResult< SocialAccountInfoVM > > GetSocailAccountInfo (string code, string state, int clientId)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService
Public Attributes
ApplicationDbContext _dbContext
Private Member Functions
async Task< ServiceResult< ShareRequest > > GenerateShareRequest (SocialContent socialContent, string accessToken, int clientId)
async Task< ServiceResult< List< Media > > > GenerateShareMedia (SocialContent socialContent, string purn, string accessToken, int clientId)
async Task< ServiceResult< Media > > GenerateShareMediaVideo (SocialVideo video, string purn, string accessToken, int clientId)
async Task< ServiceResult< Media > > GenerateShareMediaIMAGE (SocialPicture picture, string purn, string accessToken, int clientId)
async Task< ServiceResult< UploadImageResponse > > UploadImage (string accessToken, string uploadUrl, string imageUrl)
async Task< ServiceResult< UploadImageResponse > > UploadVideo (string accessToken, string uploadUrl, string videoUrl)
async Task< ServiceResult< byte[]> > DownloadImage (string url)
async Task< ServiceResult< byte[]> > DownloadVideo (string url)
async Task< ServiceResult< RegisterUploadResponse > > RegisterImage (string purn, string accessToken, int clientId)
async Task< ServiceResult< RegisterUploadResponse > > RegisterVideo (string purn, string accessToken, int clientId)
Static Private Member Functions
static ServiceResult< string > GenerateLoginQuery (List< SettingsVM > linkedintSettings)
static ServiceResult< TokenExpirationWarningStatusResponse > DeterminingWarnings (List< SettingsVM > settings, ServiceResult< TokenStatusResponse > tokenStatus)
static ShareMediaCategory CheckShareMediaCategory (SocialContent socialContent)
static RegisterUploadRequest GenerateRegisterImageRequest (string purn)
static RegisterUploadRequest GenerateRegisterVideoRequest (string purn)
Private Attributes
readonly IMapper _mapper
readonly ILogger< LinkedinService > _logger
readonly ISessionService _sessionService
readonly string linkedinSettingsGroupName = "LinkedinSettings"
readonly IHttpClientFactory _httpClientFactory
Detailed Description
Definition at line 41 of file LinkedinService.cs.
Constructor & Destructor Documentation
LinkedinService()
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.LinkedinService (ApplicationDbContext dbContext, IMapper mapper, ILogger< LinkedinService > logger, ISessionService sessionService, IHttpClientFactory httpClientFactory) inline
Definition at line 50 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._httpClientFactory, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._mapper, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._sessionService.
Member Function Documentation
CheckShareMediaCategory()
static ShareMediaCategory Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.CheckShareMediaCategory (SocialContent socialContent) inline static private
Definition at line 538 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.Link, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.Picture, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialLink.Url, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture.Url, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialVideo.Url, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.Video.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMedia().
CheckTokensStatusForWarning()
async Task< ServiceResult< TokenExpirationWarningStatusResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.CheckTokensStatusForWarning (string accessToken, string refreshToken, int clientId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.
Definition at line 303 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.DeterminingWarnings(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetSettings(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.linkedinSettingsGroupName, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.TokenStatus().
DeterminingWarnings()
static ServiceResult< TokenExpirationWarningStatusResponse > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.DeterminingWarnings (List< SettingsVM > settings, ServiceResult< TokenStatusResponse > tokenStatus) inline static private
Definition at line 326 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.ConvertUnixTimestampToDate(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ServiceModel.ServiceResult< T >.Data.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.CheckTokensStatusForWarning().
DoesExist()
async Task< bool > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.DoesExist (Expression< Func< LinkedinAccount, bool > > predicate) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.
Definition at line 844 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.LinkedinAccounts.
DownloadImage()
async Task< ServiceResult< byte[]> > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.DownloadImage (string url) inline private
Definition at line 666 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._httpClientFactory.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.UploadImage().
DownloadVideo()
async Task< ServiceResult< byte[]> > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.DownloadVideo (string url) inline private
Definition at line 672 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._httpClientFactory.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.UploadVideo().
GenerateLoginQuery()
static ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateLoginQuery (List< SettingsVM > linkedintSettings) inline static private
Definition at line 95 of file LinkedinService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.LoginRedirect().
GenerateRegisterImageRequest()
static RegisterUploadRequest Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateRegisterImageRequest (string purn) inline static private
Definition at line 720 of file LinkedinService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.RegisterImage().
GenerateRegisterVideoRequest()
static RegisterUploadRequest Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateRegisterVideoRequest (string purn) inline static private
Definition at line 780 of file LinkedinService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.RegisterVideo().
GenerateShareMedia()
async Task< ServiceResult< List< Media > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMedia (SocialContent socialContent, string purn, string accessToken, int clientId) inline private
Definition at line 497 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.CheckShareMediaCategory(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMediaIMAGE(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMediaVideo(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.Picture, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.Video.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareRequest().
GenerateShareMediaIMAGE()
async Task< ServiceResult< Media > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMediaIMAGE (SocialPicture picture, string purn, string accessToken, int clientId) inline private
Definition at line 591 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.RegisterImage(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.UploadImage(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture.Url.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMedia().
GenerateShareMediaVideo()
async Task< ServiceResult< Media > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMediaVideo (SocialVideo video, string purn, string accessToken, int clientId) inline private
Definition at line 558 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.RegisterVideo(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.UploadVideo(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialVideo.Url.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMedia().
GenerateShareRequest()
async Task< ServiceResult< ShareRequest > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareRequest (SocialContent socialContent, string accessToken, int clientId) inline private
Definition at line 444 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMedia(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetProfile(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetSettings(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Media.Id, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.linkedinSettingsGroupName, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.Text.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.SharePost().
GetAccessToken()
async Task< ServiceResult< LinkedinAuthorizationTokenResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetAccessToken (LinkedinAuthorizationCode linkedinAuthorizationCode, int clientId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.
Definition at line 126 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._httpClientFactory, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetSettings(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.linkedinSettingsGroupName.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetSocailAccountInfo().
GetBySocialToken()
virtual async Task< ServiceResult< List< LinkedinAccountVM > > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetBySocialToken (string socialToken) inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.
Definition at line 882 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._mapper, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.LinkedinAccounts, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesAsync(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId().
GetProfile()
async Task< ServiceResult< GetProfileResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetProfile (string accessToken, int clientId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.
Definition at line 205 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._httpClientFactory, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareRequest(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetSocailAccountInfo(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.SaveCredentials().
GetSettings()
List< SettingsVM > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetSettings (string groupName, int clientId) inline
Definition at line 65 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._mapper.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.CheckTokensStatusForWarning(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareRequest(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetAccessToken(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.LoginRedirect().
GetSocailAccountInfo()
async Task< ServiceResult< SocialAccountInfoVM > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetSocailAccountInfo (string code, string state, int clientId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.
Definition at line 905 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetAccessToken(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetProfile(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.LinkedinAccounts, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesAsync().
LoginRedirect()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.LoginRedirect (int clientId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.
Definition at line 85 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateLoginQuery(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetSettings(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.linkedinSettingsGroupName.
RegisterImage()
async Task< ServiceResult< RegisterUploadResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.RegisterImage (string purn, string accessToken, int clientId) inline private
Definition at line 679 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._httpClientFactory, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateRegisterImageRequest().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMediaIMAGE().
RegisterVideo()
async Task< ServiceResult< RegisterUploadResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.RegisterVideo (string purn, string accessToken, int clientId) inline private
Definition at line 740 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._httpClientFactory, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateRegisterVideoRequest().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMediaVideo().
Remove()
async Task< ServiceResult< LinkedinAccountVM > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.Remove (UnlinkSocialVM unlinkSocialVM) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.
Definition at line 864 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.UnlinkSocialVM.DbId, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.LinkedinAccounts, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesAsync().
SaveCredentials()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.SaveCredentials (SocialAccountInfoVM socialAccountInfo, int clientId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.
Definition at line 803 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.SocialAccountInfoVM.AccessToken, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetProfile(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.LinkedinAccounts, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.SocialAccountInfoVM.RefreshToken, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesAsync(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.SocialAccountInfoVM.SocialToken.
SharePost()
async Task< ServiceResult< ShareResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.SharePost (SocialContent socialContent, SocialAccount socialAccount, string socialToken) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.
Definition at line 372 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._httpClientFactory, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialAccount.AccountId, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareRequest(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.LinkedinAccounts.
TokenStatus()
async Task< ServiceResult< TokenStatusResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.TokenStatus (string token, List< SettingsVM > linkedintSettings) inline
Definition at line 239 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._httpClientFactory.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.CheckTokensStatusForWarning().
UploadImage()
async Task< ServiceResult< UploadImageResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.UploadImage (string accessToken, string uploadUrl, string imageUrl) inline private
Definition at line 624 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.DownloadImage().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMediaIMAGE().
UploadVideo()
async Task< ServiceResult< UploadImageResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.UploadVideo (string accessToken, string uploadUrl, string videoUrl) inline private
Definition at line 645 of file LinkedinService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.DownloadVideo().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMediaVideo().
Member Data Documentation
_dbContext
ApplicationDbContext Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._dbContext
Definition at line 43 of file LinkedinService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.DoesExist(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetBySocialToken(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetSocailAccountInfo(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.LinkedinService(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.Remove(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.SaveCredentials(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.SharePost().
_httpClientFactory
readonly IHttpClientFactory Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._httpClientFactory private
Definition at line 48 of file LinkedinService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.DownloadImage(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.DownloadVideo(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetAccessToken(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetProfile(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.LinkedinService(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.RegisterImage(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.RegisterVideo(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.SharePost(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.TokenStatus().
_logger
readonly ILogger<LinkedinService> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._logger private
Definition at line 45 of file LinkedinService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.CheckTokensStatusForWarning(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.DoesExist(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMedia(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMediaIMAGE(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMediaVideo(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareRequest(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetAccessToken(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetBySocialToken(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetProfile(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetSettings(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetSocailAccountInfo(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.LinkedinService(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.RegisterImage(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.RegisterVideo(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.Remove(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.SaveCredentials(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.SharePost().
_mapper
readonly IMapper Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._mapper private
Definition at line 44 of file LinkedinService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetBySocialToken(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetSettings(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.LinkedinService().
_sessionService
readonly ISessionService Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService._sessionService private
Definition at line 46 of file LinkedinService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetBySocialToken(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.LinkedinService().
linkedinSettingsGroupName
readonly string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.linkedinSettingsGroupName = "LinkedinSettings" private
Definition at line 47 of file LinkedinService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.CheckTokensStatusForWarning(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareRequest(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetAccessToken(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.LoginRedirect().
The documentation for this class was generated from the following file:
Source/Infrastructure/Social/LinkedinService.cs