AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService Class Reference
Public Member Functions
CampaignBuilderService (IMapper mapper, IApplicationDbContext dbContext, ICampaignService campaignService, IPersonaService personaService, ISignatureBlockService signatureBlockService, ICampaignElementService campaignElementService, IAmazonS3Service amazonS3Service, ISendEmailService sendEmailService, IMindfireService mindfireService, ITemplateService templateService, IConfiguration configuration, ILogger< CampaignBuilderService > logger, IContactManagerService contactManagerService, IUserCampaignService userCampaignService, ISocialNetworkService socialNetworkService, ISettingsService settingsService, ISessionService sessionService, IHttpClientFactory httpClientFactory)
async Task< ServiceResult< UserCampaignVM > > GetCampaign (int campaignId)
async Task< ServiceResult< IPaginate< UserCampaignVM > > > GetListForProfile (CampaignGetVM campaignGetVM)
async Task< ServiceResult< UserCampaignVM > > GetUserCampaignById (int userCampaignId)
async Task< ServiceResult< UserCampaignVM > > GetUserCampaignByName (string userCampaignName)
async Task< ServiceResult< UserCampaignVM > > SaveCampaign (JsonObject userCampaignJson)
async Task< ServiceResult< UserCampaignVM > > UpdateUserCampaign (JsonObject userCampaignJson)
async Task< ServiceResult< UserCampaignVM > > UpdateNameAndContentUrls (Step1VM step1VM)
async Task< ServiceResult< IEnumerable< string > > > GetInsideMessages (bool isCompanyPersona, int campaignId)
async Task< ServiceResult< UserCampaignVM > > LaunchCampaign (int userCampaignId, AddressInfoModelVM alternateAddress)
virtual ServiceResult< string > ValidateContactFilter (XElement filter)
virtual async Task< ServiceResult< XElement > > MapUserCampaignToXML (XElement programXML, UserCampaign userCampaign, PMSPersonaDTO personalInfo, string mfDomain)
async Task< ServiceResult< SendEmailResult > > SendTestEmail (SendTestEmailVM sendTestEmailVM)
async Task< ServiceResult< string > > CheckCampaignName (int id, string campaignName)
async Task< ServiceResult< byte[]> > DownloadRecipientList (int userCampaignId)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< UserCampaign, UserCampaignVM >
NamedDbService ()
NamedDbService (IMapper mapper, IApplicationDbContext dbContext, IConfiguration configuration, ILogger< NamedDbService< TModel, TModelVM > > logger, ISocialNetworkService socialNetworkService, ISessionService sessionService)
override async Task< ServiceResult< TModelVM > > Update (TModelVM entityVM)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignBuilderService
Private Member Functions
async Task< ServiceResult< string > > CheckSocialAccounts (List< XElement > campaignElements, PMSPersonaDTO persona)
async Task HasIndivGroupTemplates (UserCampaignVM userCampaign)
async Task< ServiceResult< CampaignElement > > SetMessageBody (string bodyText, CampaignElement campaignElement, string mfDomain=null)
async Task< ServiceResult< JsonObject > > UploadHtmlContent (JsonObject htmlContentJson, JsonObject celement)
async Task< ServiceResult< UserCampaignVM > > UpdateContentUrls (UserCampaignVM userCampaign, PMSPersonaDTO personalInfo, Step1VM step1VM)
string GetFromEmailAddress (string personaEmail, string campaignElementFromEmailAddress=null)
async Task< string > ParseHtmlForSelectedArticle (string htmlContent, RSSItemVM rssItem)
async Task< ServiceResult< UserCampaignVM > > LaunchAlreadyLaunchedCampaign (UserCampaign userCampaign, PMSPersonaDTO personalInfo, string mfDomain)
async Task< ServiceResult< UserCampaignVM > > RevertChangesCheckIn (string program, string errorMessage)
void FillRuleGroup (ref XElement programXML, string ruleGroupName, PMSPersonaDTO personalInfo, SignatureBlockVM signatureBlock, string mfDomen, UserCampaign userCampaign=null, string insideMessage=null)
void SetStageFolder (XElement contentVariablesXMLElement)
async Task< ServiceResult< CampaignElement > > MapXMLtoCampaignElement (XDocument mamlDoc, XElement campaignElementItem, int userCampaignId, PMSPersonaDTO persona, string fromAddress=null)
async Task< ServiceResult< XElement > > MapCampaignElementToXML (XElement campaignElementItem, CampaignElementVM dbCampaignElement, UserCampaign userCampaign, XElement ruleGroup)
async Task< ServiceResult< XElement > > MapMicrositeSchedules (XElement campaignElementItem, CampaignElementVM campaignElement, UserCampaign userCampaign)
ServiceResult< Schedule > MapXMLToSchedule (XElement scheduleItem, int campaignElementId, PMSPersonaDTO persona, XElement campaignElementItem, DateTime firstSchedule)
async Task< ServiceResult< XElement > > MapScheduleToXML (XElement scheduleItem, ScheduleVM dbSchedule, UserCampaign userCampaign)
async Task< ServiceResult< XElement > > MapEmailElementToXML (XElement campaignElementItem, CampaignElementVM dbCampaignElement, UserCampaign userCampaign, XElement ruleGroup)
async Task< ServiceResult< CampaignElement > > MapXMLToEmailElement (XElement campaignElementItem, CampaignElement campaignElement)
ServiceResult< XElement > MapBlogElementToXML (XElement campaignElementItem, string userEmail)
async Task< ServiceResult< XElement > > MapSocialElementToXML (XElement campaignElementItem, CampaignElementVM dbCampaignElement, UserCampaign userCampaign, string mfDomain)
async Task< ServiceResult< CampaignElement > > MapXMLToSocialElement (XElement campaignElementItem, CampaignElement campaignElement)
ServiceResult< XElement > MapDirectMailElementToXML (XElement campaignElementItem, CampaignElementVM dbCampaignElement, UserCampaign userCampaign, XElement ruleGroup)
async Task< ServiceResult< CampaignElement > > MapXMLToDirectMailElement (XElement campaignElementItem, CampaignElement campaignElement)
async Task AddEditorFields (string templateId, int campaignElementId)
ServiceResult< XElement > MapMicrositeElementToXML (XElement campaignElementItem)
async Task SetMode (UserCampaignVM userCampaignVM)
async Task SetUserCampaignVM (UserCampaignVM userCampaign, bool setSchedules=false, string timeZone=null)
Static Private Member Functions
static void SetValueToObjectProperty< T > (ref T model, string propertyName, string propertyValue)
static string GenerateUrlByProfileId (string personaGuid, string oldUrl)
static void SetProgramId (byte[] programByteArray, UserCampaign userCampaign)
static void FormatContactLists (ref XDocument campaign, string dummyContactAccountId)
static void makeEmailContactList (XElement contactList)
static void makePrintContactList (XElement contactList, string dummyContactAccountId, bool isPersonaOnly)
static ServiceResult< CampaignElement > MapXMLToBlogElement (XElement campaignElementItem, CampaignElement campaignElement)
static ServiceResult< CampaignElement > MapXMLToMicrositeElement (XElement campaignElementItem, CampaignElement campaignElement)
static SegmentationFilter AddFilteroutMissingEmailOrAddress (SegmentationFilter segmentationFilter, bool hasEmail, bool hasPrint)
static void SetScheduleConfig (UserCampaignVM userCampaignVM, IEnumerable< XElement > campaignElements, string timeZone)
static void SetPreviewScheduleConfig (UserCampaignVM userCampaignVM)
static ServiceResult< XElement > SetFilterForLaunch (string filter)
static bool checkParentheses (string input)
Private Attributes
readonly IPersonaService _personaService
readonly ISignatureBlockService _signatureBlockService
readonly ICampaignService _campaignService
readonly ICampaignElementService _campaignElementService
readonly ITemplateService _templateService
readonly IAmazonS3Service _amazonS3Service
readonly ISendEmailService _sendEmailService
readonly IMindfireService _mindfireService
readonly IContactManagerService _contactManagerService
readonly IUserCampaignService _userCampaignService
readonly ISettingsService _settingsService
readonly IHttpClientFactory _httpClientFactory
readonly IConfiguration _configuration
Detailed Description
Definition at line 64 of file CampaignBuilderService.cs.
Constructor & Destructor Documentation
CampaignBuilderService()
Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CampaignBuilderService (IMapper mapper, IApplicationDbContext dbContext, ICampaignService campaignService, IPersonaService personaService, ISignatureBlockService signatureBlockService, ICampaignElementService campaignElementService, IAmazonS3Service amazonS3Service, ISendEmailService sendEmailService, IMindfireService mindfireService, ITemplateService templateService, IConfiguration configuration, ILogger< CampaignBuilderService > logger, IContactManagerService contactManagerService, IUserCampaignService userCampaignService, ISocialNetworkService socialNetworkService, ISettingsService settingsService, ISessionService sessionService, IHttpClientFactory httpClientFactory) inline
Definition at line 79 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._campaignElementService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._campaignService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._configuration, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._contactManagerService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._httpClientFactory, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._personaService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._sendEmailService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._settingsService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._signatureBlockService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._templateService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._userCampaignService.
Member Function Documentation
AddEditorFields()
async Task Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.AddEditorFields (string templateId, int campaignElementId) inline private
Definition at line 2894 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._templateService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.Single().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToDirectMailElement(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToEmailElement().
AddFilteroutMissingEmailOrAddress()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.AddFilteroutMissingEmailOrAddress (SegmentationFilter segmentationFilter, bool hasEmail, bool hasPrint) inline static private
Definition at line 3076 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.CriteriaJoinOperator, and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.DownloadRecipientList().
CheckCampaignName()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CheckCampaignName (int id, string campaignName) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignBuilderService.
Definition at line 3013 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._mindfireService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.programService.
checkParentheses()
static bool Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.checkParentheses (string input) inline static private
Definition at line 3421 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetFilterForLaunch().
CheckSocialAccounts()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CheckSocialAccounts (List< XElement > campaignElements, PMSPersonaDTO persona) inline private
Definition at line 278 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._personaService, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PMSPersonaDTO.Data, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.GetPersonasForProfile().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetCampaign().
DownloadRecipientList()
async Task< ServiceResult< byte[]> > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.DownloadRecipientList (int userCampaignId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignBuilderService.
Definition at line 3045 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._contactManagerService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.AddFilteroutMissingEmailOrAddress(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.DownloadCSV().
FillRuleGroup()
void Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.FillRuleGroup (ref XElement programXML, string ruleGroupName, PMSPersonaDTO personalInfo, SignatureBlockVM signatureBlock, string mfDomen, UserCampaign userCampaign = null, string insideMessage = null) inline private
Definition at line 1931 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._userCampaignService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.FillAdvisorContentVariables(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.FillHtmlWithPersonalInfo(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ReplaceStageFolder(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.SetContentVariable(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetStageFolder(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SignatureBlockVM.Signature.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapUserCampaignToXML().
FormatContactLists()
static void Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.FormatContactLists (ref XDocument campaign, string dummyContactAccountId) inline static private
Definition at line 1533 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.makeEmailContactList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.makePrintContactList(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Parse().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign().
GenerateUrlByProfileId()
static string Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GenerateUrlByProfileId (string personaGuid, string oldUrl) inline static private
Definition at line 1187 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateContentUrls().
GetCampaign()
async Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetCampaign (int campaignId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignBuilderService.
Definition at line 119 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._campaignService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._personaService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._settingsService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._signatureBlockService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CheckSocialAccounts(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadCampaignTemplate(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.GetComment(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.GetDefaultPersonaForProfile(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ISignatureBlockService.getDefaultSignatureBlock(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.HasIndivGroupTemplates(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLtoCampaignElement(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetScheduleConfig(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetUserCampaignVM(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.SingleByName().
GetFromEmailAddress()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetFromEmailAddress (string personaEmail, string campaignElementFromEmailAddress = null) inline private
Definition at line 1144 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._settingsService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.SingleByName().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapEmailElementToXML(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateNameAndContentUrls().
GetInsideMessages()
async Task< ServiceResult< IEnumerable< string > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetInsideMessages (bool isCompanyPersona, int campaignId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignBuilderService.
Definition at line 1195 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._templateService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadCampaignTemplate(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ITemplateService.GetSingleByTemplateId().
GetListForProfile()
async Task< ServiceResult< IPaginate< UserCampaignVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetListForProfile (CampaignGetVM campaignGetVM) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignBuilderService.
Definition at line 361 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.CampaignGetVM.AwaitingApprowal, Deluxe.DeluxeBrandCenter.AMM.Domain.ServiceModel.ServiceResult< T >.Data, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.CampaignGetVM.MindFireStatus, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.programService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetUserCampaignVM().
GetUserCampaignById()
async Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetUserCampaignById (int userCampaignId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignBuilderService.
Definition at line 426 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetMode(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetPreviewScheduleConfig().
GetUserCampaignByName()
async Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetUserCampaignByName (string userCampaignName) inline
Definition at line 440 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetMode().
HasIndivGroupTemplates()
async Task Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.HasIndivGroupTemplates (UserCampaignVM userCampaign) inline private
Definition at line 325 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadCampaignTemplate(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.UserCampaignVM.FileUrl.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetCampaign(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateNameAndContentUrls().
LaunchAlreadyLaunchedCampaign()
async Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchAlreadyLaunchedCampaign (UserCampaign userCampaign, PMSPersonaDTO personalInfo, string mfDomain) inline private
Definition at line 1470 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapUserCampaignToXML(), Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaign.ProgramId, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.programService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.RevertChangesCheckIn().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign().
LaunchCampaign()
async Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign (int userCampaignId, AddressInfoModelVM alternateAddress) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignBuilderService.
Definition at line 1226 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._campaignElementService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._campaignService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._configuration, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._personaService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._settingsService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._userCampaignService, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.AddressInfoVM.Addresses, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.AddressInfoVM.City, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadCampaignTemplate(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.FormatContactLists(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.GetPersonaByGUID(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.AddressInfoVM.InsuranceState, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchAlreadyLaunchedCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapUserCampaignToXML(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Parse(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.programService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.SetOutboundIds(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetProgramId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetUserCampaignVM(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.SingleByName(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.AddressInfoVM.State, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.ValidateContactFilter(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.AddressInfoVM.Zip.
makeEmailContactList()
static void Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.makeEmailContactList (XElement contactList) inline static private
Definition at line 1601 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.FormatContactLists().
makePrintContactList()
static void Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.makePrintContactList (XElement contactList, string dummyContactAccountId, bool isPersonaOnly) inline static private
Definition at line 1660 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.FormatContactLists().
MapBlogElementToXML()
ServiceResult< XElement > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapBlogElementToXML (XElement campaignElementItem, string userEmail) inline private
Definition at line 2603 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.SharingMessageBlog.PublishForUser, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.BlogRequestVM.Request, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RequestBlog.SharingMessage, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.PublishForUserBlog.UserFeed.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapCampaignElementToXML().
MapCampaignElementToXML()
async Task< ServiceResult< XElement > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapCampaignElementToXML (XElement campaignElementItem, CampaignElementVM dbCampaignElement, UserCampaign userCampaign, XElement ruleGroup) inline private
Definition at line 2092 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapBlogElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapDirectMailElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapEmailElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapMicrositeElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapMicrositeSchedules(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapScheduleToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapSocialElementToXML(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityNamedVM.Name, Deluxe.DeluxeBrandCenter.AMM.Domain.CampaignElementVM.ReadOnly, Deluxe.DeluxeBrandCenter.AMM.Domain.CampaignElementVM.Schedules, and Deluxe.DeluxeBrandCenter.AMM.Domain.CampaignElementVM.Type.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapUserCampaignToXML().
MapDirectMailElementToXML()
ServiceResult< XElement > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapDirectMailElementToXML (XElement campaignElementItem, CampaignElementVM dbCampaignElement, UserCampaign userCampaign, XElement ruleGroup) inline private
Definition at line 2818 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._userCampaignService, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaign.CampaignElements, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.NormalizeDMVariablesAndColumns().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapCampaignElementToXML().
MapEmailElementToXML()
async Task< ServiceResult< XElement > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapEmailElementToXML (XElement campaignElementItem, CampaignElementVM dbCampaignElement, UserCampaign userCampaign, XElement ruleGroup) inline private
Definition at line 2443 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._personaService, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaign.Campaign, Deluxe.DeluxeBrandCenter.AMM.Domain.CampaignElementVM.ContentUrl, Deluxe.DeluxeBrandCenter.AMM.Domain.CampaignElementVM.FromAddress, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.GetComment(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetFromEmailAddress(), Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.Campaign.Mode, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaign.PersonaGuid, Deluxe.DeluxeBrandCenter.AMM.Domain.CampaignElementVM.ReadOnly, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ReplaceStageFolder(), Deluxe.DeluxeBrandCenter.AMM.Domain.CampaignElementVM.ReplyTo, Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.Single(), and Deluxe.DeluxeBrandCenter.AMM.Domain.CampaignElementVM.Subject.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapCampaignElementToXML().
MapMicrositeElementToXML()
ServiceResult< XElement > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapMicrositeElementToXML (XElement campaignElementItem) inline private
Definition at line 2913 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ReplaceStageFolder().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapCampaignElementToXML().
MapMicrositeSchedules()
async Task< ServiceResult< XElement > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapMicrositeSchedules (XElement campaignElementItem, CampaignElementVM campaignElement, UserCampaign userCampaign) inline private
Definition at line 2172 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaign.CampaignElements, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityVM.Id, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapScheduleToXML(), and Deluxe.DeluxeBrandCenter.AMM.Domain.CampaignElementVM.Schedules.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapCampaignElementToXML().
MapScheduleToXML()
async Task< ServiceResult< XElement > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapScheduleToXML (XElement scheduleItem, ScheduleVM dbSchedule, UserCampaign userCampaign) inline private
Definition at line 2378 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._personaService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._settingsService, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaign.PersonaGuid, Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.SingleByName(), Deluxe.DeluxeBrandCenter.AMM.Domain.ScheduleVM.Start, Deluxe.DeluxeBrandCenter.AMM.Domain.ScheduleVM.Status, Deluxe.DeluxeBrandCenter.AMM.Domain.ScheduleVM.Stop, Deluxe.DeluxeBrandCenter.AMM.Domain.ScheduleVM.Subject, and Deluxe.DeluxeBrandCenter.AMM.Domain.ScheduleVM.Type.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapCampaignElementToXML(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapMicrositeSchedules().
MapSocialElementToXML()
async Task< ServiceResult< XElement > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapSocialElementToXML (XElement campaignElementItem, CampaignElementVM dbCampaignElement, UserCampaign userCampaign, string mfDomain) inline private
Definition at line 2637 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._personaService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.Bucket, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadString(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SharingRequest.GenerateSharingRequest(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.GetComment(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.GetS3RootUrl(), Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaign.PersonaGuid, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ReplaceStageFolder(), Deluxe.DeluxeBrandCenter.AMM.Domain.CampaignElementVM.SelectedSocialAccounts, Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.Single(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SharingRequest.SocialContent, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.UploadText().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapCampaignElementToXML().
MapUserCampaignToXML()
virtual async Task< ServiceResult< XElement > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapUserCampaignToXML (XElement programXML, UserCampaign userCampaign, PMSPersonaDTO personalInfo, string mfDomain) inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignBuilderService.
Definition at line 1797 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._signatureBlockService, Deluxe.DeluxeBrandCenter.AMM.Domain.ServiceModel.ServiceResult< T >.Data, Deluxe.DeluxeBrandCenter.AMM.Domain.ServiceModel.ServiceResult< T >.ErrorMessage, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.FillRuleGroup(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.GetComment(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapCampaignElementToXML(), Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.BaseEntityNamed.Name, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetFilterForLaunch(), Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.Signature, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.Single().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchAlreadyLaunchedCampaign(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign().
MapXMLToBlogElement()
static ServiceResult< CampaignElement > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToBlogElement (XElement campaignElementItem, CampaignElement campaignElement) inline static private
Definition at line 2752 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.TextBlog.Description, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.SharingMessageBlog.Parts, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.BlogRequestVM.Request, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.RequestBlog.SharingMessage, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.PartsBlog.Text.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLtoCampaignElement().
MapXMLtoCampaignElement()
async Task< ServiceResult< CampaignElement > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLtoCampaignElement (XDocument mamlDoc, XElement campaignElementItem, int userCampaignId, PMSPersonaDTO persona, string fromAddress = null) inline private
Definition at line 1990 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.GetComment(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToBlogElement(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToDirectMailElement(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToEmailElement(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToMicrositeElement(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToSocialElement(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.Optional, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Parse().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetCampaign(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateNameAndContentUrls().
MapXMLToDirectMailElement()
async Task< ServiceResult< CampaignElement > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToDirectMailElement (XElement campaignElementItem, CampaignElement campaignElement) inline private
Definition at line 2882 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.AddEditorFields(), Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.BaseEntity.Id, and Deluxe.DeluxeBrandCenter.AMM.Domain.CampaignElement.TemplateId.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLtoCampaignElement().
MapXMLToEmailElement()
async Task< ServiceResult< CampaignElement > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToEmailElement (XElement campaignElementItem, CampaignElement campaignElement) inline private
Definition at line 2541 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.AddEditorFields(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.Bucket, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadString(), Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.BaseEntity.Id, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ReplaceStageFolder(), and Deluxe.DeluxeBrandCenter.AMM.Domain.CampaignElement.TemplateId.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLtoCampaignElement().
MapXMLToMicrositeElement()
static ServiceResult< CampaignElement > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToMicrositeElement (XElement campaignElementItem, CampaignElement campaignElement) inline static private
Definition at line 2944 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLtoCampaignElement().
MapXMLToSchedule()
ServiceResult< Schedule > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToSchedule (XElement scheduleItem, int campaignElementId, PMSPersonaDTO persona, XElement campaignElementItem, DateTime firstSchedule) inline private
Definition at line 2228 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._settingsService, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PMSPersonaDTO.Data, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaigns.Recurrence.GenerateRecurrence(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.GetComment(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Parse(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.SingleByName().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLtoCampaignElement().
MapXMLToSocialElement()
async Task< ServiceResult< CampaignElement > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToSocialElement (XElement campaignElementItem, CampaignElement campaignElement) inline private
Definition at line 2772 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.SharingMessage.parts, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.Parts.picture, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ReplaceStageFolder(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.SharingBodyVM.request, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetMessageBody(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.Request.sharing_message, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.Picture.url.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLtoCampaignElement().
ParseHtmlForSelectedArticle()
async Task< string > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.ParseHtmlForSelectedArticle (string htmlContent, RSSItemVM rssItem) inline private
Definition at line 1165 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._httpClientFactory, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.RSSItemVM.Description, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.RSSItemVM.Link, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ReplaceStageFolder(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.RSSItemVM.Title, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Description.URL, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Description.Value.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateContentUrls().
RevertChangesCheckIn()
async Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.RevertChangesCheckIn (string program, string errorMessage) inline private
Definition at line 1521 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._mindfireService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.programService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchAlreadyLaunchedCampaign().
SaveCampaign()
async Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SaveCampaign (JsonObject userCampaignJson) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignBuilderService.
Definition at line 458 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._configuration, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Parse(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateUserCampaign().
SendTestEmail()
async Task< ServiceResult< SendEmailResult > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SendTestEmail (SendTestEmailVM sendTestEmailVM) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignBuilderService.
Definition at line 2961 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._personaService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._sendEmailService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._settingsService, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SendTestEmailVM.IsTemplateFromUrl, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SendTestEmailVM.PersonaGUID, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ISendEmailService.SendEmail(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.SingleByName(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SendTestEmailVM.Template, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SendTestEmailVM.Title.
SetFilterForLaunch()
static ServiceResult< XElement > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetFilterForLaunch (string filter) inline static private
Definition at line 3393 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.checkParentheses().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapUserCampaignToXML().
SetMessageBody()
async Task< ServiceResult< CampaignElement > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetMessageBody (string bodyText, CampaignElement campaignElement, string mfDomain = null) inline private
Definition at line 737 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.Bucket, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadString(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ReplaceStageFolder(), and Deluxe.DeluxeBrandCenter.AMM.Domain.CampaignElement.Ticks.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToSocialElement(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetUserCampaignVM().
SetMode()
async Task Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetMode (UserCampaignVM userCampaignVM) inline private
Definition at line 3175 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._campaignService, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.UserCampaignVM.CampaignId.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetUserCampaignById(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetUserCampaignByName(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateContentUrls(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateUserCampaign().
SetPreviewScheduleConfig()
static void Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetPreviewScheduleConfig (UserCampaignVM userCampaignVM) inline static private
Definition at line 3327 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetUserCampaignById().
SetProgramId()
static void Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetProgramId (byte[] programByteArray, UserCampaign userCampaign) inline static private
Definition at line 1446 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign().
SetScheduleConfig()
static void Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetScheduleConfig (UserCampaignVM userCampaignVM, IEnumerable< XElement > campaignElements, string timeZone) inline static private
Definition at line 3182 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.GetComment(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Parse(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.PreviewDescription.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetCampaign(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateNameAndContentUrls().
SetStageFolder()
void Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetStageFolder (XElement contentVariablesXMLElement) inline private
Definition at line 1972 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.FillRuleGroup().
SetUserCampaignVM()
async Task Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetUserCampaignVM (UserCampaignVM userCampaign, bool setSchedules = false, string timeZone = null) inline private
Definition at line 3338 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._templateService, Deluxe.DeluxeBrandCenter.AMM.API.Services.ITemplateService.GetSingleByTemplateId(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.UserCampaignVM.OutboundIds, and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetMessageBody().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetListForProfile(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateNameAndContentUrls().
SetValueToObjectProperty< T >()
static void Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetValueToObjectProperty< T > (ref T model, string propertyName, string propertyValue) inline static private
Definition at line 803 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.XmlHelper.EscapeXml().
UpdateContentUrls()
async Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateContentUrls (UserCampaignVM userCampaign, PMSPersonaDTO personalInfo, Step1VM step1VM) inline private
Definition at line 1038 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._signatureBlockService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadHtmlContent(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadPreviewTemplate(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GenerateUrlByProfileId(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.GetS3RootUrl(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.ParseHtmlForSelectedArticle(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ReplaceStageFolder(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetMode(), Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.Signature, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SignatureBlockVM.Signature, Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.Single(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.UploadHtml().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateNameAndContentUrls().
UpdateNameAndContentUrls()
async Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateNameAndContentUrls (Step1VM step1VM) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignBuilderService.
Definition at line 824 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._httpClientFactory, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._personaService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._settingsService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._templateService, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Step1VM.CustomSettings, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.RSSItemVM.Description, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadCampaignTemplate(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetFromEmailAddress(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ITemplateService.GetSingleByTemplateId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.HasIndivGroupTemplates(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Step1VM.IsChangedPersonaType, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.RSSItemVM.Link, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLtoCampaignElement(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Step1VM.PersonaGUID, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.ReplaceStageFolder(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Step1VM.RSSItem, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetScheduleConfig(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetUserCampaignVM(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Step1VM.SignatureBlockId, Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.SingleByName(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.RSSItemVM.Title, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateContentUrls(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Description.URL, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Step1VM.UserCampaignId, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Step1VM.UserCampaignName, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Description.Value.
UpdateUserCampaign()
async Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateUserCampaign (JsonObject userCampaignJson) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignBuilderService.
Definition at line 488 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._contactManagerService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._personaService, Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._settingsService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.GetContactGroupDB(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetMode(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.SingleByName(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UploadHtmlContent().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SaveCampaign().
UploadHtmlContent()
async Task< ServiceResult< JsonObject > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UploadHtmlContent (JsonObject htmlContentJson, JsonObject celement) inline private
Definition at line 765 of file CampaignBuilderService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.GetS3RootUrl(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.UploadHtml().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateUserCampaign().
ValidateContactFilter()
virtual ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.ValidateContactFilter (XElement filter) inline virtual
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignBuilderService.
Definition at line 1404 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign().
Member Data Documentation
_amazonS3Service
readonly IAmazonS3Service Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._amazonS3Service private
Definition at line 71 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CampaignBuilderService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetInsideMessages(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.HasIndivGroupTemplates(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapSocialElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToEmailElement(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetMessageBody(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateContentUrls(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateNameAndContentUrls(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UploadHtmlContent().
_campaignElementService
readonly ICampaignElementService Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._campaignElementService private
Definition at line 69 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CampaignBuilderService(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign().
_campaignService
readonly ICampaignService Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._campaignService private
Definition at line 68 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CampaignBuilderService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetMode().
_configuration
readonly IConfiguration Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._configuration private
Definition at line 78 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CampaignBuilderService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SaveCampaign().
_contactManagerService
readonly IContactManagerService Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._contactManagerService private
Definition at line 74 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CampaignBuilderService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.DownloadRecipientList(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateUserCampaign().
_httpClientFactory
readonly IHttpClientFactory Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._httpClientFactory private
Definition at line 77 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CampaignBuilderService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.ParseHtmlForSelectedArticle(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateNameAndContentUrls().
_mindfireService
readonly IMindfireService Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._mindfireService private
Definition at line 73 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CampaignBuilderService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CheckCampaignName(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetListForProfile(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchAlreadyLaunchedCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.RevertChangesCheckIn().
_personaService
readonly IPersonaService Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._personaService private
Definition at line 66 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CampaignBuilderService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CheckSocialAccounts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapEmailElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapScheduleToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapSocialElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SendTestEmail(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateNameAndContentUrls(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateUserCampaign().
_sendEmailService
readonly ISendEmailService Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._sendEmailService private
Definition at line 72 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CampaignBuilderService(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SendTestEmail().
_settingsService
readonly ISettingsService Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._settingsService private
Definition at line 76 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CampaignBuilderService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetFromEmailAddress(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapScheduleToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SendTestEmail(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateNameAndContentUrls(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateUserCampaign().
_signatureBlockService
readonly ISignatureBlockService Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._signatureBlockService private
Definition at line 67 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CampaignBuilderService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapUserCampaignToXML(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateContentUrls().
_templateService
readonly ITemplateService Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._templateService private
Definition at line 70 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.AddEditorFields(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CampaignBuilderService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetInsideMessages(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetUserCampaignVM(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.UpdateNameAndContentUrls().
_userCampaignService
readonly IUserCampaignService Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService._userCampaignService private
Definition at line 75 of file CampaignBuilderService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.CampaignBuilderService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.FillRuleGroup(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.LaunchCampaign(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapDirectMailElementToXML().
The documentation for this class was generated from the following file:
Source/API/Services/CampaignBuilderService.cs