AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService Class Reference
Public Member Functions
AccountService (ApplicationDbContext dbContext, ILogger< AccountService > logger, IConfiguration configuration, IAmazonS3Service amazonS3Service, IMindfireService mindfireService, IPersonaService personaService, IAccountStatusService accountStatusService, IMapper mapper, IClientService clientService, IUserService userService, IDBCService dbcService, ISessionService sessionService, ISocialNetworkService socialNetworkService, UserManager< ApplicationUser > userManager, RoleManager< ApplicationRole > roleManager)
async Task< ServiceResult< ApplicationUser > > RegisterAdvisor (User clientUser, string userId, bool admin)
async Task< ServiceResult< ApplicationUser > > registerUserAdminWithUserId (string UserName, string Email, string userId)
async Task< ServiceResult< ApplicationUser > > registerUserAdvisorWithUserId (string UserName, string Email, string userId)
async Task< ServiceResult< AuthenticateResponse > > RegisterMFUser (Domain.DataModel.Profile profile)
async Task< ServiceResult< IsRegisteredVM > > IsRegistered (string userId)
async Task< ServiceResult< LoginResponseVM > > SignIn (LogInVM Credentials, ApplicationUser appUser=null)
async Task< ServiceResult< LoginResponseVM > > SSOSignIn (int clientId, string repId, string userId, bool admin)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService
Public Attributes
readonly ISessionService _sessionService
readonly ISocialNetworkService _socialNetworkService
Properties
ISession _session [get]
IClientService clientService [get]
IConfiguration configuration [get]
IAmazonS3Service amazonS3Service [get]
ILogger< AccountService > logger [get]
IMapper mapper [get]
IMindfireService mindfireService [get]
IDBCService dbcService [get]
IUserService userService [get]
IPersonaService _personaService [get]
IAccountStatusService _accountStatusService [get]
UserManager< ApplicationUser > _userManager [get]
RoleManager< ApplicationRole > _roleManager [get]
ApplicationDbContext dbContext [get]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService
Private Member Functions
async Task< ServiceResult< ApplicationUser > > registerApplicationUserWithUserId (string UserName, string Email, string Role, string userId, int accountStatusId)
async Task< ServiceResult< Domain.DataModel.Profile > > RegisterProfile (Domain.DataModel.Profile profile)
Static Private Member Functions
static void MapProfileToUser (Domain.DataModel.Profile profile, ApplicationUser applicationUser)
Detailed Description
Definition at line 115 of file AccountService.cs.
Constructor & Destructor Documentation
AccountService()
Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.AccountService (ApplicationDbContext dbContext, ILogger< AccountService > logger, IConfiguration configuration, IAmazonS3Service amazonS3Service, IMindfireService mindfireService, IPersonaService personaService, IAccountStatusService accountStatusService, IMapper mapper, IClientService clientService, IUserService userService, IDBCService dbcService, ISessionService sessionService, ISocialNetworkService socialNetworkService, UserManager< ApplicationUser > userManager, RoleManager< ApplicationRole > roleManager) inline
Definition at line 117 of file AccountService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._accountStatusService, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._personaService, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._roleManager, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._socialNetworkService, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._userManager, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.clientService, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.configuration, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.dbcService, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.mapper, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.mindfireService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.userService.
Member Function Documentation
IsRegistered()
async Task< ServiceResult< IsRegisteredVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.IsRegistered (string userId) inline
Parameters
clientId
repId
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.
Definition at line 449 of file AccountService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.dbcService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBCService.GetUser(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.logger, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.Users.
MapProfileToUser()
static void Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.MapProfileToUser (Domain.DataModel.Profile profile, ApplicationUser applicationUser) inline static private
Definition at line 703 of file AccountService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterAdvisor().
RegisterAdvisor()
async Task< ServiceResult< ApplicationUser > > Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterAdvisor (User user, string userId, bool admin) inline
Parameters
user
userId
admin
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.
Definition at line 218 of file AccountService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.Client.User.AsProfile(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.dbContext, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.Client.User.Email, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.Client.User.GetAgUserId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.MapProfileToUser(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterProfile(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerUserAdminWithUserId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerUserAdvisorWithUserId(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesAsync(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.Users.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SSOSignIn().
registerApplicationUserWithUserId()
async Task< ServiceResult< ApplicationUser > > Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerApplicationUserWithUserId (string UserName, string Email, string Role, string userId, int accountStatusId) inline private
Definition at line 289 of file AccountService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._roleManager, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._userManager, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.dbContext, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesAsync().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerUserAdminWithUserId(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerUserAdvisorWithUserId().
RegisterMFUser()
async Task< ServiceResult< AuthenticateResponse > > Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterMFUser (Domain.DataModel.Profile profile) inline
Parameters
profile
Returns
Definition at line 318 of file AccountService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.accountService, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.mindfireService, Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetMFAccountNamePrefix(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.userService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterProfile().
RegisterProfile()
async Task< ServiceResult< Domain.DataModel.Profile > > Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterProfile (Domain.DataModel.Profile profile) inline private
Parameters
profile
Returns
Definition at line 359 of file AccountService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.configuration, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.configurationService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.contactService, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.mindfireService, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.RequestCredentials.NewInstance(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterMFUser(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.requestCredentialsTemplate, Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetMFDomain(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.SetUserTicket().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterAdvisor().
registerUserAdminWithUserId()
async Task< ServiceResult< ApplicationUser > > Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerUserAdminWithUserId (string UserName, string Email, string userId) inline
Parameters
UserName
Email
userId
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.
Definition at line 270 of file AccountService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._accountStatusService, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerApplicationUserWithUserId(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterAdvisor().
registerUserAdvisorWithUserId()
async Task< ServiceResult< ApplicationUser > > Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerUserAdvisorWithUserId (string UserName, string Email, string userId) inline
Parameters
UserName
Email
userId
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.
Definition at line 283 of file AccountService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._accountStatusService, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerApplicationUserWithUserId(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterAdvisor().
SignIn()
async Task< ServiceResult< LoginResponseVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SignIn (LogInVM Credentials, ApplicationUser appUser = null) inline
Parameters
Credentials
appUser
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.
Definition at line 516 of file AccountService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.AccountStatuses, Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.ClearSessionVariables(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.clientService, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.IClientService.GetClientByName(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.mindfireService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesAsync(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetS3Bucket(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SetSessionVariables(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.SetUserCredentials(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.Users, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.userService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SSOSignIn().
SSOSignIn()
async Task< ServiceResult< LoginResponseVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SSOSignIn (int clientId, string repId, string userId, bool admin) inline
Parameters
clientId
repId
userId
admin
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.
Definition at line 609 of file AccountService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.clientService, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.dbcService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBCService.GetUser(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.mapper, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.BaseEntityNamed.Name, Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterAdvisor(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesAsync(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SetSessionVariables(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SignIn(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IClientDBService< TModel, TModelVM >.Single(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.Users.
Member Data Documentation
_sessionService
readonly ISessionService Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._sessionService
Definition at line 152 of file AccountService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.AccountService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterMFUser(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterProfile(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerUserAdminWithUserId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerUserAdvisorWithUserId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SignIn(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SSOSignIn().
_socialNetworkService
readonly ISocialNetworkService Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._socialNetworkService
Definition at line 153 of file AccountService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.AccountService().
Property Documentation
_accountStatusService
IAccountStatusService Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._accountStatusService get
Definition at line 200 of file AccountService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.AccountService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerUserAdminWithUserId(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerUserAdvisorWithUserId().
_personaService
IPersonaService Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._personaService get private
Definition at line 195 of file AccountService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.AccountService().
_roleManager
RoleManager<ApplicationRole> Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._roleManager get
Definition at line 208 of file AccountService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.AccountService(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerApplicationUserWithUserId().
_session
ISession Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._session get
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.
Definition at line 154 of file AccountService.cs.
_userManager
UserManager<ApplicationUser> Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService._userManager get
Definition at line 204 of file AccountService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.AccountService(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerApplicationUserWithUserId().
amazonS3Service
IAmazonS3Service Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.amazonS3Service get
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.
Definition at line 165 of file AccountService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.AccountService().
clientService
IClientService Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.clientService get
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.
Definition at line 155 of file AccountService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.AccountService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SignIn(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SSOSignIn().
configuration
IConfiguration Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.configuration get
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.
Definition at line 160 of file AccountService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.AccountService(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterProfile().
dbContext
ApplicationDbContext Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.dbContext get private
Definition at line 213 of file AccountService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.AccountService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.IsRegistered(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterAdvisor(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerApplicationUserWithUserId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SignIn(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SSOSignIn().
dbcService
IDBCService Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.dbcService get
Definition at line 185 of file AccountService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.AccountService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.IsRegistered(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SSOSignIn().
logger
ILogger<AccountService> Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.logger get
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.
Definition at line 170 of file AccountService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.AccountService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.IsRegistered(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterAdvisor(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterProfile(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SignIn(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SSOSignIn().
mapper
IMapper Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.mapper get
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.
Definition at line 175 of file AccountService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.AccountService(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SSOSignIn().
mindfireService
IMindfireService Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.mindfireService get
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.
Definition at line 180 of file AccountService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.AccountService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterMFUser(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterProfile(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SignIn().
userService
IUserService Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.userService get
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.
Definition at line 190 of file AccountService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.AccountService().
The documentation for this class was generated from the following file:
Source/API/Services/Account/AccountService.cs