AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper Class Reference
Static Public Member Functions
static SegmentationFilter GenerateEqualFilter (string field, string value)
static SegmentationFilter FormatFilter (this SegmentationFilter segmentationFilter, List< ContactGroupForMF > groups)
static bool CheckSegmentationFilterIntegrity (this SegmentationFilter segmentationFilter)
static SegmentationFilter GenerateEmptyFilter ()
static SegmentationFilter SetGroupFilter (this SegmentationFilter segmentationFilter, List< ContactGroupForMF > groups, bool isThirdLevel=false)
static SegmentationFilter SetFilterCriteriasForNONEState (this SegmentationFilter segmentationFilter)
static SegmentationFilter SetDateFields (this SegmentationFilter segmentationFilter)
static SegmentationFilter SetTagsField (this SegmentationFilter segmentationFilter)
static SegmentationFilter UpdateRowNumbers (this SegmentationFilter segmentationFilter, int highestRow)
static SegmentationFilter RemoveGroupCriteria (this SegmentationFilter segmentationFilter, bool isThirdLevel=false)
static SegmentationFilter RemoveEmptyJoinOperationValue (this SegmentationFilter segmentationFilter)
static SegmentationFilter SetBlankCriteria (this SegmentationFilter segmentationFilter)
static SegmentationFilter SetCriteriaJoinToNumeric (this SegmentationFilter segmentationFilter)
static SegmentationFilter ReplaceNumericJoinOperator (this SegmentationFilter segmentationFilter)
static int GetHighestRow (this SegmentationFilter segmentationFilter, int highestTemp=0)
static int GetHighestRow (this IEnumerable< SegmentationFilterCriteria > criterias)
static void SetNoGroupFoundCriteria (this SegmentationFilterCriteria criteria)
static SegmentationFilterCriteria GenerateNoCriteriaFilter ()
Static Private Member Functions
static SegmentationFilter FormatFilterBase (this SegmentationFilter segmentationFilter, List< ContactGroupForMF > groups)
static ContactGroupForMF GetGroupByName (this List< ContactGroupForMF > groups, string name)
static string ReplaceJoinOperatorValue (this string cjo, int rowNumber, string newCjo)
static string RemoveJoinOperatorValue (this string cjo, int rowNumber)
static string RemoveEmptyJoinOperatorValue (this string cjo)
static string ReplaceNumericJoinOperator (this string cjo)
static DateTime SetTimeOffset (this string date)
Detailed Description
Definition at line 903 of file MindfireServiceModel.cs.
Member Function Documentation
CheckSegmentationFilterIntegrity()
static bool Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.CheckSegmentationFilterIntegrity (this SegmentationFilter segmentationFilter) inline static
Definition at line 950 of file MindfireServiceModel.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.CriteriaJoinOperator.
FormatFilter()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.FormatFilter (this SegmentationFilter segmentationFilter, List< ContactGroupForMF > groups) inline static
Definition at line 920 of file MindfireServiceModel.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.GenerateEmptyFilter().
FormatFilterBase()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.FormatFilterBase (this SegmentationFilter segmentationFilter, List< ContactGroupForMF > groups) inline static private
Definition at line 925 of file MindfireServiceModel.cs.
GenerateEmptyFilter()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.GenerateEmptyFilter () inline static
Definition at line 955 of file MindfireServiceModel.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.GenerateNoCriteriaFilter().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.FormatFilter(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.SetGroupFilter().
GenerateEqualFilter()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.GenerateEqualFilter (string field, string value) inline static
Definition at line 905 of file MindfireServiceModel.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddOrUpdateTag(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DeleteTag(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.DownloadTagContacts().
GenerateNoCriteriaFilter()
static SegmentationFilterCriteria Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.GenerateNoCriteriaFilter () inline static
Definition at line 1238 of file MindfireServiceModel.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.GenerateEmptyFilter().
GetGroupByName()
static ContactGroupForMF Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.GetGroupByName (this List< ContactGroupForMF > groups, string name) inline static private
Definition at line 1196 of file MindfireServiceModel.cs.
GetHighestRow() [1/2]
static int Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.GetHighestRow (this IEnumerable< SegmentationFilterCriteria > criterias) inline static
Definition at line 1191 of file MindfireServiceModel.cs.
GetHighestRow() [2/2]
static int Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.GetHighestRow (this SegmentationFilter segmentationFilter, int highestTemp = 0) inline static
Definition at line 1186 of file MindfireServiceModel.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias.
RemoveEmptyJoinOperationValue()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.RemoveEmptyJoinOperationValue (this SegmentationFilter segmentationFilter) inline static
Definition at line 1153 of file MindfireServiceModel.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.CriteriaJoinOperator.
RemoveEmptyJoinOperatorValue()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.RemoveEmptyJoinOperatorValue (this string cjo) inline static private
Definition at line 1211 of file MindfireServiceModel.cs.
RemoveGroupCriteria()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.RemoveGroupCriteria (this SegmentationFilter segmentationFilter, bool isThirdLevel = false) inline static
Definition at line 1138 of file MindfireServiceModel.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.CriteriaJoinOperator, and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias.
RemoveJoinOperatorValue()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.RemoveJoinOperatorValue (this string cjo, int rowNumber) inline static private
Definition at line 1206 of file MindfireServiceModel.cs.
ReplaceJoinOperatorValue()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.ReplaceJoinOperatorValue (this string cjo, int rowNumber, string newCjo) inline static private
Definition at line 1201 of file MindfireServiceModel.cs.
ReplaceNumericJoinOperator() [1/2]
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.ReplaceNumericJoinOperator (this SegmentationFilter segmentationFilter) inline static
Definition at line 1180 of file MindfireServiceModel.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.CriteriaJoinOperator.
ReplaceNumericJoinOperator() [2/2]
static string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.ReplaceNumericJoinOperator (this string cjo) inline static private
Definition at line 1218 of file MindfireServiceModel.cs.
SetBlankCriteria()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.SetBlankCriteria (this SegmentationFilter segmentationFilter) inline static
Definition at line 1159 of file MindfireServiceModel.cs.
SetCriteriaJoinToNumeric()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.SetCriteriaJoinToNumeric (this SegmentationFilter segmentationFilter) inline static
Definition at line 1170 of file MindfireServiceModel.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.CriteriaJoinOperator, and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias.
SetDateFields()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.SetDateFields (this SegmentationFilter segmentationFilter) inline static
Definition at line 1055 of file MindfireServiceModel.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.CriteriaJoinOperator, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias, and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.GenerateFilterCriteria().
SetFilterCriteriasForNONEState()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.SetFilterCriteriasForNONEState (this SegmentationFilter segmentationFilter) inline static
Definition at line 1013 of file MindfireServiceModel.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.GenerateFilterCriteria().
SetGroupFilter()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.SetGroupFilter (this SegmentationFilter segmentationFilter, List< ContactGroupForMF > groups, bool isThirdLevel = false) inline static
Definition at line 967 of file MindfireServiceModel.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.CriteriaJoinOperator, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias, and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.GenerateEmptyFilter().
SetNoGroupFoundCriteria()
static void Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.SetNoGroupFoundCriteria (this SegmentationFilterCriteria criteria) inline static
Definition at line 1230 of file MindfireServiceModel.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.Row.
SetTagsField()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.SetTagsField (this SegmentationFilter segmentationFilter) inline static
Definition at line 1093 of file MindfireServiceModel.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.GenerateFilterCriteria().
SetTimeOffset()
static DateTime Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.SetTimeOffset (this string date) inline static private
Definition at line 1225 of file MindfireServiceModel.cs.
UpdateRowNumbers()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.UpdateRowNumbers (this SegmentationFilter segmentationFilter, int highestRow) inline static
Definition at line 1126 of file MindfireServiceModel.cs.
The documentation for this class was generated from the following file:
Source/Domain/ExtServiceModel/MindfireServiceModel.cs