AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService Class Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService Class Reference
Public Member Functions
SocialNetworkService (ITwitterService twitterService, ILinkedinService linkedinService, ILogger< SocialNetworkService > logger, IConfiguration configuration, ApplicationDbContext dbContext, ClientDbContext clientDbContext, IPersonaMicroservice personaMicroservice, ISendEmailService sendEmailService, IHttpClientFactory httpClientFactory)
async Task< ServiceResult< string > > Sharing (SharingRequest sharingRequest)
Does actual posting on given social network.
bool Authenticate (IHeaderDictionary headerDictionary)
Check if request headder have valid Authorization.
async Task< ServiceResult< string > > UnlinkFromSocial (UnlinkSocialVM unlinkSocialVM)
async Task< ServiceResult< CheckSocialVM > > CheckSocialForUser (CheckSocialVM checkSocialVM)
async Task< ServiceResult< string > > SaveCredentials (List< SocialAccountInfoVM > socialAccountInfos, int clientId)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService
Properties
ITwitterService _twitterService [get, set]
ILinkedinService _linkedinService [get, set]
IConfiguration _configuration [get, set]
ILogger< SocialNetworkService > _logger [get, set]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService
Private Member Functions
async Task< bool > CheckRefreshTokenForWarning (SocialAccount account, string socialToken)
List< Settings > GetSettings (string groupName, int clientId=0)
async Task< EmailPreparingResponse > PreparingEmail (List< Settings > settings, int clientId, TokenExpirationWarningStatusResponse warningStatus)
async Task< ServiceResult< string > > CheckAndDownloadMessage (string body)
Static Private Member Functions
static void UnlinkedProvider (bool allActive, string socialName, UserProvider provider, List< UserProvider > userProviders)
Private Attributes
readonly ApplicationDbContext _dbContext
readonly ClientDbContext _clientDbContext
readonly IPersonaMicroservice _personaMicroservice
readonly ISendEmailService _sendEmailService
readonly IHttpClientFactory _httpClientFactory
Detailed Description
Definition at line 40 of file SocialNetworkService.cs.
Constructor & Destructor Documentation
SocialNetworkService()
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.SocialNetworkService (ITwitterService twitterService, ILinkedinService linkedinService, ILogger< SocialNetworkService > logger, IConfiguration configuration, ApplicationDbContext dbContext, ClientDbContext clientDbContext, IPersonaMicroservice personaMicroservice, ISendEmailService sendEmailService, IHttpClientFactory httpClientFactory) inline
Definition at line 64 of file SocialNetworkService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._clientDbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._configuration, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._httpClientFactory, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._linkedinService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._logger, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._personaMicroservice, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._sendEmailService, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._twitterService.
Member Function Documentation
Authenticate()
bool Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Authenticate (IHeaderDictionary headerDictionary) inline
Check if request headder have valid Authorization.
Parameters
headerDictionary
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.
Definition at line 300 of file SocialNetworkService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._configuration, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._logger.
CheckAndDownloadMessage()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckAndDownloadMessage (string body) inline private
Definition at line 526 of file SocialNetworkService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._httpClientFactory.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Sharing().
CheckRefreshTokenForWarning()
async Task< bool > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckRefreshTokenForWarning (SocialAccount account, string socialToken) inline private
Definition at line 168 of file SocialNetworkService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._linkedinService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._logger, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._personaMicroservice, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._sendEmailService, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialAccount.AccountId, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.CheckTokensStatusForWarning(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetFilteredPersonas(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.GetSettings(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.LinkedinAccounts, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.PreparingEmail(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ISendEmailService.SendEmail().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Sharing().
CheckSocialForUser()
async Task< ServiceResult< CheckSocialVM > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckSocialForUser (CheckSocialVM checkSocialVM) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.
Definition at line 347 of file SocialNetworkService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._linkedinService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._twitterService, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.CheckSocialVM.AllActive, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.CheckTokensStatusForWarning(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.DoesExist(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.DoesExist(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.GetBySocialToken(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.GetBySocialToken(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.GetProfile(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.GetProfile(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.CheckSocialVM.Providers, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.Remove(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.Remove(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.CheckSocialVM.SocialToken, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.UnlinkedProvider().
GetSettings()
List< Settings > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.GetSettings (string groupName, int clientId = 0) inline private
Definition at line 244 of file SocialNetworkService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckRefreshTokenForWarning().
PreparingEmail()
async Task< EmailPreparingResponse > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.PreparingEmail (List< Settings > settings, int clientId, TokenExpirationWarningStatusResponse warningStatus) inline private
Definition at line 256 of file SocialNetworkService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._clientDbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.Clients, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.TokenExpirationWarningStatusResponse.RefreshTokenLastingDays, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.TokenExpirationWarningStatusResponse.WarningStatus.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckRefreshTokenForWarning().
SaveCredentials()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.SaveCredentials (List< SocialAccountInfoVM > socialAccountInfos, int clientId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.
Definition at line 492 of file SocialNetworkService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._linkedinService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._twitterService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.SaveCredentials(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.SaveCredentials().
Sharing()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Sharing (SharingRequest sharingRequest) inline
Does actual posting on given social network.
Parameters
sharingRequest
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.
Definition at line 91 of file SocialNetworkService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._linkedinService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._logger, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._twitterService, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.Accounts, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckAndDownloadMessage(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckRefreshTokenForWarning(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.LogSocialPost, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SharingRequest.PublishForUser, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.PublishTweet(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesAsync(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.SharePost(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SharingRequest.SocialContent, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.SocialToken, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.Text.
UnlinkedProvider()
static void Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.UnlinkedProvider (bool allActive, string socialName, UserProvider provider, List< UserProvider > userProviders) inline static private
Definition at line 516 of file SocialNetworkService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckSocialForUser().
UnlinkFromSocial()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.UnlinkFromSocial (UnlinkSocialVM unlinkSocialVM) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.
Definition at line 322 of file SocialNetworkService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._linkedinService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._twitterService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.DoesExist(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.DoesExist(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.Remove(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.Remove(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.UnlinkSocialVM.SocialProvider, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.UnlinkSocialVM.SocialToken.
Member Data Documentation
_clientDbContext
readonly ClientDbContext Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._clientDbContext private
Definition at line 43 of file SocialNetworkService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.PreparingEmail(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.SocialNetworkService().
_dbContext
readonly ApplicationDbContext Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._dbContext private
Definition at line 42 of file SocialNetworkService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckRefreshTokenForWarning(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Sharing(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.SocialNetworkService().
_httpClientFactory
readonly IHttpClientFactory Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._httpClientFactory private
Definition at line 46 of file SocialNetworkService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckAndDownloadMessage(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.SocialNetworkService().
_personaMicroservice
readonly IPersonaMicroservice Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._personaMicroservice private
Definition at line 44 of file SocialNetworkService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckRefreshTokenForWarning(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.SocialNetworkService().
_sendEmailService
readonly ISendEmailService Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._sendEmailService private
Definition at line 45 of file SocialNetworkService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckRefreshTokenForWarning(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.SocialNetworkService().
Property Documentation
_configuration
IConfiguration Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._configuration get set
Definition at line 56 of file SocialNetworkService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Authenticate(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.SocialNetworkService().
_linkedinService
ILinkedinService Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._linkedinService get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.
Definition at line 52 of file SocialNetworkService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckRefreshTokenForWarning(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckSocialForUser(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.SaveCredentials(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Sharing(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.SocialNetworkService(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.UnlinkFromSocial().
_logger
ILogger<SocialNetworkService> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._logger get set
Definition at line 60 of file SocialNetworkService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Authenticate(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckRefreshTokenForWarning(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Sharing(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.SocialNetworkService().
_twitterService
ITwitterService Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService._twitterService get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.
Definition at line 48 of file SocialNetworkService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckSocialForUser(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.SaveCredentials(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Sharing(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.SocialNetworkService(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.UnlinkFromSocial().
The documentation for this class was generated from the following file:
Source/Infrastructure/Social/SocialNetworkService.cs