var _associated_groups_filter_v_m_8cs =
[
    [ "Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.AssociatedGroupsFilterVM", "dc/db0/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_domain_1_1_view_model_1_1_contact_manager_1_1_associated_groups_filter_v_m.html", "dc/db0/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_domain_1_1_view_model_1_1_contact_manager_1_1_associated_groups_filter_v_m" ]
];