AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper Class Reference
Static Public Member Functions
static string GetDisplayName (State state)
static string GetName (State state)
static string GetDesription (State state)
static string GetNameByDisplayName (string displayName, bool caseSensitive=false)
static State GetByDisplayName (string displayName, bool caseSensitive=false)
static State GetByName (string name, bool caseSensitive=false)
static List< KeyValuePair< string, string > > GetForSelectList ()
Detailed Description
Definition at line 91 of file State.cs.
Member Function Documentation
GetByDisplayName()
static State Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetByDisplayName (string displayName, bool caseSensitive = false) inline static
Definition at line 151 of file State.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetDisplayName().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetNameByDisplayName().
GetByName()
static State Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetByName (string name, bool caseSensitive = false) inline static
Definition at line 175 of file State.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetName().
GetDesription()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetDesription (State state) inline static
Definition at line 122 of file State.cs.
GetDisplayName()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetDisplayName (State state) inline static
Definition at line 93 of file State.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetByDisplayName(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetForSelectList().
GetForSelectList()
static List< KeyValuePair< string, string > > Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetForSelectList () inline static
Definition at line 199 of file State.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetDisplayName(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetName().
GetName()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetName (State state) inline static
Definition at line 117 of file State.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetByName(), Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetForSelectList(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetNameByDisplayName().
GetNameByDisplayName()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetNameByDisplayName (string displayName, bool caseSensitive = false) inline static
Definition at line 146 of file State.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetByDisplayName(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Enums.StateHelper.GetName().
The documentation for this class was generated from the following file:
Source/Domain/Enums/State.cs