AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF Class Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF Class Reference
Public Member Functions
AccountServiceMF (IConfiguration configuration, ISessionService sessionService, IUserServiceMF userServiceMF, IHttpClientFactory contextFactory, ILoggerFactory loggerFactory)
async Task< ServiceResult< GetAccountResponse > > GetAccount (long accountId, string ticket)
async Task< ServiceResult< GetAccountListResponse > > GetAccountList (byte status=255)
async Task< ServiceResult< CreateAccountResponse > > CreateAccount (string email, string firstName, string lastName, string password, string accountName)
async Task< ServiceResult< UpdateAccountResponse > > AccountSetSuspended (long accountId, string ticket)
async Task< ServiceResult< UpdateAccountResponse > > AccountSetActive (long accountId, string ticket)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService
BaseMindfireService (IConfiguration configuration, string serviceName, ISessionService sessionService, IHttpClientFactory clientFactory, ILoggerFactory loggerFactory)
async Task< TResponse > Post< TResponse > (string endpoint, object body)
async Task< TResponse > PostDashboard< TResponse > (string endpoint, object body)
async Task< TResponse > Get< TResponse > (string endpoint)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IAccountServiceMF
Private Attributes
readonly IUserServiceMF _userservice
Additional Inherited Members
Public Attributes inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService
readonly ILogger _logger
string _accountNamePrefix
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService
ISession _session [get]
RequestCredentials masterRequestCredentials [get, set]
RequestCredentials userRequestCredentials [get, set]
IMindfireSettings configuration [get, set]
string ServiceName [get]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IBaseMindfireService
Detailed Description
Definition at line 25 of file AccountServiceMF.cs.
Constructor & Destructor Documentation
AccountServiceMF()
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF.AccountServiceMF (IConfiguration configuration, ISessionService sessionService, IUserServiceMF userServiceMF, IHttpClientFactory contextFactory, ILoggerFactory loggerFactory) inline
Definition at line 28 of file AccountServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF._userservice.
Member Function Documentation
AccountSetActive()
async Task< ServiceResult< UpdateAccountResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF.AccountSetActive (long accountId, string ticket) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IAccountServiceMF.
Definition at line 186 of file AccountServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF.GetAccountList(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.masterRequestCredentials.
AccountSetSuspended()
async Task< ServiceResult< UpdateAccountResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF.AccountSetSuspended (long accountId, string ticket) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IAccountServiceMF.
Definition at line 149 of file AccountServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF.GetAccount(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.masterRequestCredentials.
CreateAccount()
async Task< ServiceResult< CreateAccountResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF.CreateAccount (string email, string firstName, string lastName, string password, string accountName) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IAccountServiceMF.
Definition at line 94 of file AccountServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService._session, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF._userservice, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IUserServiceMF.Authenticate(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.masterRequestCredentials.
GetAccount()
async Task< ServiceResult< GetAccountResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF.GetAccount (long accountId, string ticket) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IAccountServiceMF.
Definition at line 34 of file AccountServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.masterRequestCredentials.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF.AccountSetSuspended().
GetAccountList()
async Task< ServiceResult< GetAccountListResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF.GetAccountList (byte status = 255) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IAccountServiceMF.
Definition at line 58 of file AccountServiceMF.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.BaseMindfireService.masterRequestCredentials.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF.AccountSetActive().
Member Data Documentation
_userservice
readonly IUserServiceMF Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF._userservice private
Definition at line 27 of file AccountServiceMF.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF.AccountServiceMF(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.AccountServiceMF.CreateAccount().
The documentation for this class was generated from the following file:
Source/Infrastructure/Mindfire/AccountServiceMF.cs