var 20211126111801___log_social_post_8_designer_8cs =
[
    [ "Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.Migrations.LogSocialPost", "dd/ddc/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_databases_1_1_migrations_1_1_log_social_post.html", "dd/ddc/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_databases_1_1_migrations_1_1_log_social_post" ]
];