var _salesforce_service_8cs =
[
    [ "Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService", "db/d9f/interface_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_salesforce_1_1_i_salesforce_service.html", "db/d9f/interface_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_salesforce_1_1_i_salesforce_service" ],
    [ "Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService", "dd/d92/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_salesforce_1_1_salesforce_service.html", "dd/d92/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_salesforce_1_1_salesforce_service" ]
];