AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBCService Interface Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBCService Interface Reference
Public Member Functions
Task< IEnumerable< DBCAccountingUnit > > GetAccountingUnits (Guid userGuid)
Task< ServiceResult< DBCUser > > GetUser (string userGuid)
Detailed Description
Definition at line 21 of file DBCService.cs.
Member Function Documentation
GetAccountingUnits()
Task< IEnumerable< DBCAccountingUnit > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBCService.GetAccountingUnits (Guid userGuid)
Parameters
userGuid
Returns
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.DBCService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController.GetAccountingUnits().
GetUser()
Task< ServiceResult< DBCUser > > Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBCService.GetUser (string userGuid)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.DBCService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.IsRegistered(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SSOSignIn(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UpdateContactsCollectionField(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts().
The documentation for this interface was generated from the following file:
Source/API/Services/DBCService.cs