AMM: Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController Class Reference
Utility Controller.
Public Member Functions
UtilityController (IStateService stateService)
Utility Controller Constructor.
ControllerResult< IReadOnlyCollection< StateVM > > GetStates ()
Get a list of all States.
ControllerResult< IReadOnlyCollection< StateVM > > GetCanadianProvinces ()
Get a list of all Canadian provinces.
ControllerResult< IReadOnlyCollection< KeyValuePair< string, string > > > GetTimeZones ()
Get a list of all Time Zones.
Protected Member Functions
string SessionUserName ()
Currently logedin user name.
Private Attributes
readonly IStateService service
Detailed Description
Utility Controller.
Definition at line 20 of file UtilityController.cs.
Constructor & Destructor Documentation
UtilityController()
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController.UtilityController (IStateService stateService) inline
Utility Controller Constructor.
Parameters
stateService
Definition at line 26 of file UtilityController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController.service.
Member Function Documentation
GetCanadianProvinces()
ControllerResult< IReadOnlyCollection< StateVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController.GetCanadianProvinces () inline
Get a list of all Canadian provinces.
Returns
List of all States
<response code = "200">List of all Canadian provinces or Error message</response>
Definition at line 58 of file UtilityController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.IStateService.GetStates(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController.service.
GetStates()
ControllerResult< IReadOnlyCollection< StateVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController.GetStates () inline
Get a list of all States.
Returns
List of all States
<response code = "200">List of all States or Error message</response>
Definition at line 48 of file UtilityController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.IStateService.GetStates(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController.service.
GetTimeZones()
ControllerResult< IReadOnlyCollection< KeyValuePair< string, string > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController.GetTimeZones () inline
Get a list of all Time Zones.
Returns
List of all Time Zones
<response code = "200">List of all Time Zones</response>
Definition at line 68 of file UtilityController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.GetTimeZoneList().
SessionUserName()
string Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController.SessionUserName () inline protected
Currently logedin user name.
Returns
Username of the logedin user
Definition at line 35 of file UtilityController.cs.
Member Data Documentation
service
readonly IStateService Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController.service private
Definition at line 40 of file UtilityController.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController.GetCanadianProvinces(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController.GetStates(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController.UtilityController().
The documentation for this class was generated from the following file:
Source/API/Controllers/UtilityController.cs