AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent Class Reference
Public Member Functions
SocialContent ()
Static Package Functions
static SocialContent GenerateSocialContent (SharingMessage sharingMessage)
Properties
string Text [get, set]
SocialLink Link [get, set]
SocialPicture Picture [get, set]
SocialVideo Video [get, set]
Private Member Functions
SocialContent (SharingMessage sharingMessage)
Detailed Description
Definition at line 64 of file SharingRequest.cs.
Constructor & Destructor Documentation
SocialContent() [1/2]
Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.SocialContent () inline
Definition at line 66 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.GenerateSocialContent().
SocialContent() [2/2]
Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.SocialContent (SharingMessage sharingMessage) inline private
Definition at line 70 of file SharingRequest.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.Text.body, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialLink.GenerateSocialLink(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialPicture.GenerateSocialPicture(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialVideo.GenerateSocialVideo(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.SharingMessage.parts, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.Parts.text.
Member Function Documentation
GenerateSocialContent()
static SocialContent Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.GenerateSocialContent (SharingMessage sharingMessage) inline static package
Definition at line 78 of file SharingRequest.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.SocialContent().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SharingRequest.SharingRequest().
Property Documentation
Link
SocialLink Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.Link get set
Definition at line 87 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.CheckShareMediaCategory(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.CheckTwitterCategory().
Picture
SocialPicture Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.Picture get set
Definition at line 91 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.CheckShareMediaCategory(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.CheckTwitterCategory(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMedia().
Text
string Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.Text get set
Definition at line 83 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareRequest(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Sharing().
Video
SocialVideo Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SocialContent.Video get set
Definition at line 95 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.CheckShareMediaCategory(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.CheckTwitterCategory(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GenerateShareMedia().
The documentation for this class was generated from the following file:
Source/Domain/ViewModel/Social/SharingRequest.cs