AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService Class Reference
Public Member Functions
JobPoolService (IServiceScopeFactory serviceScopeFactory, ILoggerFactory loggerFactory)
JobRunner StartJob< T > (Func< IServiceProvider, Task< T > > func)
JobRunner StartJob< T > (Func< IServiceProvider, Task< T > > func, object data)
JobRunner StartJob< T > (Func< IServiceProvider, Task< T > > func, Func< IServiceScope, object > getData)
JobRunner GetJobRunner (Guid id)
JobRunner< T > GetJobRunner< T > (Guid id)
Job GetJob (Guid id)
Job< T > GetJob< T > (Guid id)
JobRunner GetCurrentJobRunner ()
JobRunner< T > GetCurrentJobRunner< T > ()
void RemoveJobRunner (Guid id)
void RemoveJobRunner (JobRunner jobRunner)
void RemoveJob (Job job)
void RemoveJob (Guid id)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.Services.IJobPoolService
Private Member Functions
JobRunner StartJob< T > (Func< IServiceProvider, Task< T > > func, object data, IServiceScope wrapperServiceScope=null)
void CleanUpJobRunnersAndJobs ()
Private Attributes
readonly IServiceScopeFactory serviceScopeFactory
readonly ILogger logger
readonly Dictionary< int, JobRunner > jobRunnersByTaskScheduler = []
Detailed Description
Definition at line 18 of file JobPoolService.cs.
Constructor & Destructor Documentation
JobPoolService()
Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.JobPoolService (IServiceScopeFactory serviceScopeFactory, ILoggerFactory loggerFactory) inline
Definition at line 24 of file JobPoolService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.logger, and Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.serviceScopeFactory.
Member Function Documentation
CleanUpJobRunnersAndJobs()
void Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.CleanUpJobRunnersAndJobs () inline private
Definition at line 178 of file JobPoolService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.Job, Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.jobRunnersByTaskScheduler, and Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.serviceScopeFactory.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.StartJob< T >().
GetCurrentJobRunner()
JobRunner Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.GetCurrentJobRunner () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.IJobPoolService.
Definition at line 133 of file JobPoolService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.jobRunnersByTaskScheduler.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.GetCurrentJobRunner< T >().
GetCurrentJobRunner< T >()
JobRunner< T > Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.GetCurrentJobRunner< T > () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.IJobPoolService.
Definition at line 143 of file JobPoolService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.GetCurrentJobRunner().
GetJob()
Job Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.GetJob (Guid id) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.IJobPoolService.
Definition at line 122 of file JobPoolService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.Job, and Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.serviceScopeFactory.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.GetJob< T >().
GetJob< T >()
Job< T > Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.GetJob< T > (Guid id) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.IJobPoolService.
Type Constraints
T : class
Definition at line 128 of file JobPoolService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.GetJob().
GetJobRunner()
JobRunner Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.GetJobRunner (Guid id) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.IJobPoolService.
Definition at line 112 of file JobPoolService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.jobRunnersByTaskScheduler.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.GetJobRunner< T >().
GetJobRunner< T >()
JobRunner< T > Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.GetJobRunner< T > (Guid id) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.IJobPoolService.
Definition at line 117 of file JobPoolService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.GetJobRunner().
RemoveJob() [1/2]
void Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.RemoveJob (Guid id) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.IJobPoolService.
Definition at line 172 of file JobPoolService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.RemoveJob(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.serviceScopeFactory.
RemoveJob() [2/2]
void Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.RemoveJob (Job job) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.IJobPoolService.
Definition at line 165 of file JobPoolService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChanges(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.serviceScopeFactory.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.RemoveJob().
RemoveJobRunner() [1/2]
void Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.RemoveJobRunner (Guid id) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.IJobPoolService.
Definition at line 148 of file JobPoolService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.jobRunnersByTaskScheduler.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.RemoveJobRunner().
RemoveJobRunner() [2/2]
void Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.RemoveJobRunner (JobRunner jobRunner) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.IJobPoolService.
Definition at line 157 of file JobPoolService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Services.JobPool.JobRunner< T >.Id, and Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.RemoveJobRunner().
StartJob< T >() [1/4]
JobRunner Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.StartJob< T > (Func< IServiceProvider, Task< T > > func) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.IJobPoolService.
Type Constraints
T : class
Definition at line 30 of file JobPoolService.cs.
StartJob< T >() [2/4]
JobRunner Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.StartJob< T > (Func< IServiceProvider, Task< T > > func, Func< IServiceScope, object > getData) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.IJobPoolService.
Type Constraints
T : class
Definition at line 40 of file JobPoolService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.serviceScopeFactory.
StartJob< T >() [3/4]
JobRunner Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.StartJob< T > (Func< IServiceProvider, Task< T > > func, object data) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.Services.IJobPoolService.
Type Constraints
T : class
Definition at line 35 of file JobPoolService.cs.
StartJob< T >() [4/4]
JobRunner Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.StartJob< T > (Func< IServiceProvider, Task< T > > func, object data, IServiceScope wrapperServiceScope = null) inline private
Type Constraints
T : class
Definition at line 53 of file JobPoolService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.CleanUpJobRunnersAndJobs(), Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.Job< T >.Id, Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.jobRunnersByTaskScheduler, Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.serviceScopeFactory, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.JobPool.JobRunner< T >.Start().
Member Data Documentation
jobRunnersByTaskScheduler
readonly Dictionary<int, JobRunner> Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.jobRunnersByTaskScheduler = [] private
Definition at line 22 of file JobPoolService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.CleanUpJobRunnersAndJobs(), Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.GetCurrentJobRunner(), Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.GetJobRunner(), Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.RemoveJobRunner(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.StartJob< T >().
logger
readonly ILogger Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.logger private
Definition at line 21 of file JobPoolService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.JobPoolService(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.StartJob< T >().
serviceScopeFactory
readonly IServiceScopeFactory Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.serviceScopeFactory private
Definition at line 20 of file JobPoolService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.CleanUpJobRunnersAndJobs(), Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.GetJob(), Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.JobPoolService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.RemoveJob(), Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.RemoveJob(), Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.StartJob< T >(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.StartJob< T >().
The documentation for this class was generated from the following file:
Source/API/Services/JobPoolService.cs