AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment Class Reference
Static Public Member Functions
static Comment GetComment (XElement element)
Properties
string Type [get, set]
string SubType [get, set]
bool ReadOnlyElement [get, set]
bool SubjectReadOnly = true [get, set]
bool Optional [get, set]
string SelectName [get, set]
bool? EditableTime [get, set]
bool? HasBlankSignatureBlock [get, set]
bool? SendToPersonaContactOnly [get, set]
PreviewDescription PreviewDescription [get, set]
Detailed Description
Definition at line 8 of file Comment.cs.
Member Function Documentation
GetComment()
static Comment Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.GetComment (XElement element) inline static
Definition at line 48 of file Comment.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.GetCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapEmailElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapSocialElementToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapUserCampaignToXML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLtoCampaignElement(), Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLToSchedule(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.PendingCampaignDetails(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetScheduleConfig().
Property Documentation
EditableTime
bool? Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.EditableTime get set
Definition at line 31 of file Comment.cs.
HasBlankSignatureBlock
bool? Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.HasBlankSignatureBlock get set
Definition at line 35 of file Comment.cs.
Optional
bool Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.Optional get set
Definition at line 23 of file Comment.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.MapXMLtoCampaignElement().
PreviewDescription
PreviewDescription Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.PreviewDescription get set
Definition at line 43 of file Comment.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignBuilderService.SetScheduleConfig().
ReadOnlyElement
bool Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.ReadOnlyElement get set
Definition at line 18 of file Comment.cs.
SelectName
string Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.SelectName get set
Definition at line 27 of file Comment.cs.
SendToPersonaContactOnly
bool? Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.SendToPersonaContactOnly get set
Definition at line 39 of file Comment.cs.
SubjectReadOnly
bool Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.SubjectReadOnly = true get set
Definition at line 22 of file Comment.cs.
SubType
string Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.SubType get set
Definition at line 14 of file Comment.cs.
Type
string Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.Type get set
Definition at line 10 of file Comment.cs.
The documentation for this class was generated from the following file:
Source/Domain/ViewModel/CampaignBuilder/Comment.cs