var _social_network_service_8cs =
[
    [ "Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService", "da/d0c/interface_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_social_1_1_i_social_network_service.html", "da/d0c/interface_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_social_1_1_i_social_network_service" ],
    [ "Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService", "d7/d5a/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_social_1_1_social_network_service.html", "d7/d5a/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_social_1_1_social_network_service" ]
];