AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T > Class Template Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T > Class Template Reference
Public Member Functions
Table ()
int GetColumnNo (string columnName)
T[] Row (int row)
T[][] AllRows ()
T[] Column (int no)
T[] Column (string columnName)
T Data (int row, int columnNo)
T Data (int row, string columnName)
T DataOrDefault (int row, string columnName)
string[] Header ()
void SetValue (int row, int columnNo, T value)
Set value for specific field.
void SetValue (int row, string columnName, T value)
Set value for specific field.
bool SetHeader (string[] names)
Set header.
bool SetHeader (List< string > names)
Set header.
bool DeleteRow (int row)
Delete row.
bool AppendRow (List< T > data)
Append row.
bool InsertRow (int index, List< T > data)
Insert row.
bool DeleteColumn (string columnName)
Delete column.
bool DeleteColumn (int no)
Delete column.
bool AppendColumn (string columnName, List< T > data)
bool InsertEmptyValues ()
check if there are fields without "" (that are null)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.ITableReader< T >
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.ITableWriter< T >
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.IRowEditor< T >
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.IColumnEditor< T >
Protected Attributes
List< List< T > > _data
List< string > _header
Properties
int Columns [get]
int Rows [get]
Detailed Description
Definition at line 63 of file Table.cs.
Constructor & Destructor Documentation
Table()
Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Table () inline
Definition at line 68 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._data, and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._header.
Member Function Documentation
AllRows()
T[][] Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.AllRows () inline
Definition at line 86 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._data.
AppendColumn()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.AppendColumn (string columnName, List< T > data) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.IColumnEditor< T >.
Definition at line 264 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._data, Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._header, and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.InsertEmptyValues().
AppendRow()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.AppendRow (List< T > data) inline
Append row.
Parameters
data List<T> data
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.IRowEditor< T >.
Definition at line 211 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._data, and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Columns.
Column() [1/2]
T[] Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Column (int no) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.ITableReader< T >.
Definition at line 91 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._data, and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._header.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddGroupsAndTagsToDb(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Column(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CountContacts().
Column() [2/2]
T[] Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Column (string columnName) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.ITableReader< T >.
Definition at line 107 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Column(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.GetColumnNo().
Data() [1/2]
T Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Data (int row, int columnNo) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.ITableReader< T >.
Definition at line 112 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._data.
Data() [2/2]
T Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Data (int row, string columnName) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.ITableReader< T >.
Definition at line 117 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._data, and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.GetColumnNo().
DataOrDefault()
T Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.DataOrDefault (int row, string columnName) inline
Definition at line 122 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._data, and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.GetColumnNo().
DeleteColumn() [1/2]
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.DeleteColumn (int no) inline
Delete column.
Parameters
no Integer
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.IColumnEditor< T >.
Definition at line 249 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._data, and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._header.
DeleteColumn() [2/2]
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.DeleteColumn (string columnName) inline
Delete column.
Parameters
columnName string
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.IColumnEditor< T >.
Definition at line 239 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.DeleteColumn(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.GetColumnNo().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.DeleteColumn().
DeleteRow()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.DeleteRow (int row) inline
Delete row.
Parameters
row Integer row
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.IRowEditor< T >.
Definition at line 200 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._data.
GetColumnNo()
int Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.GetColumnNo (string columnName) inline
Definition at line 74 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._header.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddGroupsAndTagsToDb(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Column(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Data(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.DataOrDefault(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.DeleteColumn(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.SetValue().
Header()
string[] Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Header () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.ITableReader< T >.
Definition at line 133 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._header.
InsertEmptyValues()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.InsertEmptyValues () inline
check if there are fields without "" (that are null)
Returns
Definition at line 288 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._data, and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._header.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.AppendColumn().
InsertRow()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.InsertRow (int index, List< T > data) inline
Insert row.
Parameters
index
data
Returns
Definition at line 227 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._data.
Row()
T[] Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Row (int row) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.ITableReader< T >.
Definition at line 81 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._data.
SetHeader() [1/2]
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.SetHeader (List< string > names) inline
Set header.
Parameters
names List of strings
Returns
Definition at line 183 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._header.
SetHeader() [2/2]
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.SetHeader (string[] names) inline
Set header.
Parameters
names string array of names
Returns
Definition at line 166 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._header.
SetValue() [1/2]
void Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.SetValue (int row, int columnNo, T value) inline
Set value for specific field.
Parameters
row
columnNo
value
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.ITableWriter< T >.
Definition at line 144 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._data.
SetValue() [2/2]
void Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.SetValue (int row, string columnName, T value) inline
Set value for specific field.
Parameters
row
columnName
value
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.ITableWriter< T >.
Definition at line 155 of file Table.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._data, and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.GetColumnNo().
Member Data Documentation
_data
List<List<T> > Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._data protected
Definition at line 65 of file Table.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.AllRows(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.AppendColumn(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.AppendRow(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Column(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Data(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Data(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.DataOrDefault(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.DeleteColumn(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.DeleteRow(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.InsertEmptyValues(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.InsertRow(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Row(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.SetValue(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.SetValue(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Table().
_header
List<string> Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >._header protected
Definition at line 66 of file Table.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.AppendColumn(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Column(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.DeleteColumn(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.GetColumnNo(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Header(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.InsertEmptyValues(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.SetHeader(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.SetHeader(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Table().
Property Documentation
Columns
int Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Columns get
Definition at line 308 of file Table.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.AppendRow().
Rows
int Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Rows get
Definition at line 309 of file Table.cs.
The documentation for this class was generated from the following file:
Source/Domain/Utility/Table.cs