AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService Class Reference
Public Member Functions
RedShiftService (IConfiguration config)
async Task< IEnumerable< TClass > > getSqlMSSqlAsync< TClass > (string sql)
async Task< IEnumerable< TClass > > getSqlRedShiftAsync< TClass > (string sql)
async Task< Dictionary< string, List< Dictionary< string, object > > > > getSqlRedShiftMultipleAsync (IEnumerable<(string, string)> namedQueries)
async Task< DTOCamapigns > getCampaignsAsync (long accountId, IEnumerable< long > campaignIds, IEnumerable< long > programIds, bool thisMonth=false)
async Task< IEnumerable< DBOCampaignElements > > getCamapignElements (long accountId, IEnumerable< long > campaignIds)
string getSentEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getOpenedEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getClicksEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getSpamEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getUnsubscribeEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getSuppressedEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getUndeliverableEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getSocialPostsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getPrintsSentSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getMicrositeVisitsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getMicrositeClicksSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getMicrositeSubmitsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getTopNEngagedCampaignsSql (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
string getTopNEngagedContactsSql (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
async Task< IEnumerable< DTOCampaignLaunches > > getTopNCampaigns (int topN, int clientId, bool thisMonth=false, bool onlyActive=true)
async Task< int > geTotalNumberOfLaunchedCampaigns (int clientId, bool thisMonth=false, bool onlyActive=true)
async Task< IEnumerable< DTONamedCount > > getTopNClickRateByOutboundName (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
async Task< IEnumerable< DTONamedCount > > getTopNClickRateByOutboundScheduleName (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
async Task< IEnumerable< DTONamedCount > > getTopNClickRateByEmail (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
async Task< IEnumerable< DTONamedCount > > getTopNClickRateByAction (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
async Task< IEnumerable< DTONamedCount > > getTopNOpenRateByOutboundName (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
async Task< IEnumerable< DTONamedCount > > getTopNOpenRateByOutboundScheduleName (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
async Task< IEnumerable< DateValue > > getOpenRatesOverDays (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
async Task< IEnumerable< DateValue > > getClickRatesOverDays (long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
async Task< IEnumerable< DTOContactDetail > > getContactDetails (long accountId, int campaignId)
async Task< IEnumerable< DTOInboundElement > > getInboundElements (long accountId, int campaignId)
async Task< IEnumerable< DTOOutboundDetail > > getOutboundDetails (long accountId, int campaignId)
async Task< IEnumerable< string > > getElegetOutboundElementContactsOpened (long accountId, int campaignId, int outboundId, int outboundScheduleId)
async Task< IEnumerable< string > > getElegetOutboundElementContactsSentTo (long accountId, int campaignId, int outboundId, int outboundScheduleId)
async Task< IEnumerable< string > > getElegetOutboundElementContactsClicks (long accountId, int campaignId, int outboundId, int outboundScheduleId)
async Task< IEnumerable< string > > getElegetOutboundElementContactsSpam (long accountId, int campaignId, int outboundId, int outboundScheduleId)
async Task< IEnumerable< string > > getElegetOutboundElementContactsHardBounced (long accountId, int campaignId, int outboundId, int outboundScheduleId)
async Task< IEnumerable< string > > getElegetOutboundElementContactsSoftBounced (long accountId, int campaignId, int outboundId, int outboundScheduleId)
async Task< IEnumerable< string > > getElegetOutboundElementContactsSuppressed (long accountId, int campaignId, int outboundId, int outboundScheduleId)
async Task< IEnumerable< string > > getElegetOutboundElementContactsFailed (long accountId, int campaignId, int outboundId, int outboundScheduleId)
async Task< IEnumerable< string > > getElegetOutboundElementContactsUnsubscribed (long accountId, int campaignId, int outboundId, int outboundScheduleId)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService
Private Member Functions
string formatCampaignsSql (long accountId, IEnumerable< long > campaignIds, IEnumerable< long > programIds, bool thisMonth=false)
string formatOutboundsSQL (long accountId, IEnumerable< long > campaigns)
Static Private Member Functions
static string format (string source, IEnumerable< KeyValuePair< string, string > > param)
static string formatOutboundSqlForRedShift (string SQL, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
static string formatInboundSqlForRedShift (string SQL, long accountId, IEnumerable< long > campaignIds, bool thisMonth=false)
static async Task< IEnumerable< TClass > > getSqlAsync< TClass > (DbConnection conn, string sql)
Private Attributes
readonly IConfiguration _config
readonly string _rsConnectionString
readonly string _msConnectionString
readonly string _undiliverableEmailSQL
readonly string _sendsEmailSQL
readonly string _opensEmailSQL
readonly string _clicksEmailSQL
readonly string _spamEmailSQL
readonly string _unsubscribeEmailSQL
readonly string _suppressedEmailSQL
readonly string _socialPostsSQL
readonly string _printSentSQL
readonly string _micrositeVisits
readonly string _micrositeClicks
readonly string _micrositeSubmits
readonly string _topEngagedCampaigns
readonly string _topEngagedContacts
readonly string _topNLaunchedCampaigns
readonly string _totalLaunchedCampaigns
readonly string campaignsSQL
readonly string campaignsSQLOrderBy = @"ORDER BY foxtrot.campaign.submitdate DESC"
readonly string outboundsSQL
readonly string _topClickrateByOutboundName
readonly string _topClickRateByOutboundScheduleName
readonly string _topClickRateByEmail
readonly string _topClickRateByAction
readonly string _clickRateOverDays
readonly string _topOpenRateByOutboundName
readonly string _topOpenRateByOutboundScheduleName
readonly string _openRateOverDays
readonly string _contactDetailsSQL
readonly string _inboundElementsSql
readonly string _inboundElementsClicksSql
readonly string _inboundElementsVisitsSql
readonly string _outboundElementsSQL
readonly string _outboundElementsContactsSQL
readonly string _outboundElementOpenedSQL
readonly string _outboundElementOpenedContactsSQL
readonly string _outboundElementClicksSQL
readonly string _outboundElementClicksContactsSQL
readonly string _outboundElementSpamSQL
readonly string _outboundElementSpamContactsSQL
readonly string _outboundElementHardBouncedSQL
readonly string _outboundElementHardBouncedContactsSQL
readonly string _outboundElementSoftBouncedSQL
readonly string _outboundElementSoftBouncedContactsSQL
readonly string _outboundElementSuppressedSQL
readonly string _outboundElementSuppressedContactsSQL
readonly string _outboundElementFailedSQL
readonly string _outboundElementFailedContactsSQL
readonly string _outboundElementUnsubscribedSQL
readonly string _outboundElementUnsubscribedContactsSQL
Detailed Description
Definition at line 66 of file RedShiftService.cs.
Constructor & Destructor Documentation
RedShiftService()
Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.RedShiftService (IConfiguration config) inline
Definition at line 547 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._config, Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._msConnectionString, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._rsConnectionString.
Member Function Documentation
format()
static string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.format (string source, IEnumerable< KeyValuePair< string, string > > param) inline static private
Definition at line 554 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getContactDetails(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsClicks(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsFailed(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsHardBounced(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsOpened(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsSentTo(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsSoftBounced(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsSpam(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsSuppressed(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsUnsubscribed(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getInboundElements(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.geTotalNumberOfLaunchedCampaigns(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOutboundDetails(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNCampaigns().
formatCampaignsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatCampaignsSql (long accountId, IEnumerable< long > campaignIds, IEnumerable< long > programIds, bool thisMonth = false) inline private
Definition at line 652 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.campaignsSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.campaignsSQLOrderBy.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getCampaignsAsync().
formatInboundSqlForRedShift()
static string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatInboundSqlForRedShift (string SQL, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline static private
Definition at line 610 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getClickRatesOverDays(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getMicrositeClicksSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getMicrositeSubmitsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getMicrositeVisitsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOpenRatesOverDays(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNClickRateByAction(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNClickRateByEmail(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNClickRateByOutboundName(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNClickRateByOutboundScheduleName(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNEngagedCampaignsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNEngagedContactsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNOpenRateByOutboundName(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNOpenRateByOutboundScheduleName().
formatOutboundSqlForRedShift()
static string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatOutboundSqlForRedShift (string SQL, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline static private
Definition at line 568 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getClicksEmailsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOpenedEmailsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getPrintsSentSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSentEmailsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSocialPostsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSpamEmailsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSuppressedEmailsSql(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getUndeliverableEmailsSql(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getUnsubscribeEmailsSql().
formatOutboundsSQL()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatOutboundsSQL (long accountId, IEnumerable< long > campaigns) inline private
Definition at line 708 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.outboundsSQL.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getCamapignElements().
getCamapignElements()
async Task< IEnumerable< DBOCampaignElements > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getCamapignElements (long accountId, IEnumerable< long > campaignIds) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 859 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatOutboundsSQL().
getCampaignsAsync()
async Task< DTOCamapigns > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getCampaignsAsync (long accountId, IEnumerable< long > campaignIds, IEnumerable< long > programIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 854 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatCampaignsSql().
getClickRatesOverDays()
async Task< IEnumerable< DateValue > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getClickRatesOverDays (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1022 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._clickRateOverDays, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatInboundSqlForRedShift().
getClicksEmailsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getClicksEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 875 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._clicksEmailSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatOutboundSqlForRedShift().
getContactDetails()
async Task< IEnumerable< DTOContactDetail > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getContactDetails (long accountId, int campaignId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1028 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._contactDetailsSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.format().
getElegetOutboundElementContactsClicks()
async Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsClicks (long accountId, int campaignId, int outboundId, int outboundScheduleId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1202 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementClicksContactsSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.format().
getElegetOutboundElementContactsFailed()
async Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsFailed (long accountId, int campaignId, int outboundId, int outboundScheduleId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1267 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementFailedContactsSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.format().
getElegetOutboundElementContactsHardBounced()
async Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsHardBounced (long accountId, int campaignId, int outboundId, int outboundScheduleId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1228 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementHardBouncedContactsSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.format().
getElegetOutboundElementContactsOpened()
async Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsOpened (long accountId, int campaignId, int outboundId, int outboundScheduleId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1176 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementOpenedContactsSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.format().
getElegetOutboundElementContactsSentTo()
async Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsSentTo (long accountId, int campaignId, int outboundId, int outboundScheduleId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1189 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementsContactsSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.format().
getElegetOutboundElementContactsSoftBounced()
async Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsSoftBounced (long accountId, int campaignId, int outboundId, int outboundScheduleId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1241 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementSoftBouncedContactsSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.format().
getElegetOutboundElementContactsSpam()
async Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsSpam (long accountId, int campaignId, int outboundId, int outboundScheduleId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1215 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementSpamContactsSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.format().
getElegetOutboundElementContactsSuppressed()
async Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsSuppressed (long accountId, int campaignId, int outboundId, int outboundScheduleId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1254 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementSuppressedContactsSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.format().
getElegetOutboundElementContactsUnsubscribed()
async Task< IEnumerable< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsUnsubscribed (long accountId, int campaignId, int outboundId, int outboundScheduleId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1280 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementUnsubscribedContactsSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.format().
getInboundElements()
async Task< IEnumerable< DTOInboundElement > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getInboundElements (long accountId, int campaignId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1045 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._inboundElementsClicksSql, Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._inboundElementsSql, Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._inboundElementsVisitsSql, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.format().
getMicrositeClicksSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getMicrositeClicksSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 915 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._micrositeClicks, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatInboundSqlForRedShift().
getMicrositeSubmitsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getMicrositeSubmitsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 920 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._micrositeSubmits, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatInboundSqlForRedShift().
getMicrositeVisitsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getMicrositeVisitsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 910 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._micrositeVisits, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatInboundSqlForRedShift().
getOpenedEmailsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOpenedEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 870 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._opensEmailSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatOutboundSqlForRedShift().
getOpenRatesOverDays()
async Task< IEnumerable< DateValue > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOpenRatesOverDays (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1017 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._openRateOverDays, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatInboundSqlForRedShift().
geTotalNumberOfLaunchedCampaigns()
async Task< int > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.geTotalNumberOfLaunchedCampaigns (int clientId, bool thisMonth = false, bool onlyActive = true) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 958 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._totalLaunchedCampaigns, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.format().
getOutboundDetails()
async Task< IEnumerable< DTOOutboundDetail > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOutboundDetails (long accountId, int campaignId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1083 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementClicksSQL, Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementFailedSQL, Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementHardBouncedSQL, Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementOpenedSQL, Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementSoftBouncedSQL, Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementSpamSQL, Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementsSQL, Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementSuppressedSQL, Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementUnsubscribedSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.format().
getPrintsSentSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getPrintsSentSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 905 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._printSentSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatOutboundSqlForRedShift().
getSentEmailsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSentEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 865 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._sendsEmailSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatOutboundSqlForRedShift().
getSocialPostsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSocialPostsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 900 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._socialPostsSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatOutboundSqlForRedShift().
getSpamEmailsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSpamEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 880 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._spamEmailSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatOutboundSqlForRedShift().
getSqlAsync< TClass >()
static async Task< IEnumerable< TClass > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSqlAsync< TClass > (DbConnection conn, string sql) inline static private
Definition at line 731 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSqlMSSqlAsync< TClass >(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSqlRedShiftAsync< TClass >().
getSqlMSSqlAsync< TClass >()
async Task< IEnumerable< TClass > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSqlMSSqlAsync< TClass > (string sql) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 796 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._msConnectionString, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSqlAsync< TClass >().
getSqlRedShiftAsync< TClass >()
async Task< IEnumerable< TClass > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSqlRedShiftAsync< TClass > (string sql) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 802 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._rsConnectionString, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSqlAsync< TClass >().
getSqlRedShiftMultipleAsync()
async Task< Dictionary< string, List< Dictionary< string, object > > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSqlRedShiftMultipleAsync (IEnumerable<(string, string)> namedQueries) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 808 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._rsConnectionString.
getSuppressedEmailsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSuppressedEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 890 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._suppressedEmailSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatOutboundSqlForRedShift().
getTopNCampaigns()
async Task< IEnumerable< DTOCampaignLaunches > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNCampaigns (int topN, int clientId, bool thisMonth = false, bool onlyActive = true) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 935 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topNLaunchedCampaigns, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.format().
getTopNClickRateByAction()
async Task< IEnumerable< DTONamedCount > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNClickRateByAction (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1001 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topClickRateByAction, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatInboundSqlForRedShift().
getTopNClickRateByEmail()
async Task< IEnumerable< DTONamedCount > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNClickRateByEmail (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 996 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topClickRateByEmail, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatInboundSqlForRedShift().
getTopNClickRateByOutboundName()
async Task< IEnumerable< DTONamedCount > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNClickRateByOutboundName (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 986 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topClickrateByOutboundName, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatInboundSqlForRedShift().
getTopNClickRateByOutboundScheduleName()
async Task< IEnumerable< DTONamedCount > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNClickRateByOutboundScheduleName (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 991 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topClickRateByOutboundScheduleName, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatInboundSqlForRedShift().
getTopNEngagedCampaignsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNEngagedCampaignsSql (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 925 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topEngagedCampaigns, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatInboundSqlForRedShift().
getTopNEngagedContactsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNEngagedContactsSql (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 930 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topEngagedContacts, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatInboundSqlForRedShift().
getTopNOpenRateByOutboundName()
async Task< IEnumerable< DTONamedCount > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNOpenRateByOutboundName (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1006 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topOpenRateByOutboundName, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatInboundSqlForRedShift().
getTopNOpenRateByOutboundScheduleName()
async Task< IEnumerable< DTONamedCount > > Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNOpenRateByOutboundScheduleName (int topN, long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 1011 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topOpenRateByOutboundScheduleName, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatInboundSqlForRedShift().
getUndeliverableEmailsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getUndeliverableEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 895 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._undiliverableEmailSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatOutboundSqlForRedShift().
getUnsubscribeEmailsSql()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getUnsubscribeEmailsSql (long accountId, IEnumerable< long > campaignIds, bool thisMonth = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IRedShiftService.
Definition at line 885 of file RedShiftService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._unsubscribeEmailSQL, and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatOutboundSqlForRedShift().
Member Data Documentation
_clickRateOverDays
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._clickRateOverDays private
Initial value:
= @"
SELECT        foxtrot.eventtransaction.dim_date_id as date, COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id), 0) AS value
FROM            foxtrot.eventtransaction INNER JOIN
                         foxtrot.campaign ON foxtrot.eventtransaction.account_id = foxtrot.campaign.account_id AND foxtrot.eventtransaction.campaign_id = foxtrot.campaign.id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.eventtransaction.account_id = foxtrot.outboundschedule.account_id AND foxtrot.eventtransaction.outboundschedule_id = foxtrot.outboundschedule.id AND
                         foxtrot.eventtransaction.outbound_id = foxtrot.outboundschedule.outbound_id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.event.description IN ('Contact clicked on a link in email', 'Contact clicked an outside link', 'Contact clicked a link in Email', 'Clicked')) ##DateFilter## ##CampaignIdsFilter##
GROUP BY foxtrot.eventtransaction.dim_date_id
ORDER BY foxtrot.eventtransaction.dim_date_id"
Definition at line 270 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getClickRatesOverDays().
_clicksEmailSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._clicksEmailSQL private
Initial value:
= @"SELECT COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id),0) AS Undiliverable
FROM foxtrot.eventtransaction
INNER JOIN foxtrot.campaign ON foxtrot.eventtransaction.account_id = foxtrot.campaign.account_id AND foxtrot.eventtransaction.campaign_id = foxtrot.campaign.id
INNER JOIN foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
INNER JOIN foxtrot.outboundschedule ON foxtrot.eventtransaction.account_id = foxtrot.outboundschedule.account_id AND foxtrot.eventtransaction.outboundschedule_id = foxtrot.outboundschedule.id AND foxtrot.eventtransaction.outbound_id = foxtrot.outboundschedule.outbound_id
WHERE (foxtrot.eventtransaction.account_id = ##AccountId##) ##DateFilter## ##CampaignIdsFilter##
AND (foxtrot.event.description IN ('Contact clicked on a link in email', 'Contact clicked an outside link', 'Contact clicked a link in Email', 'Clicked'))"
Definition at line 94 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getClicksEmailsSql().
_config
readonly IConfiguration Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._config private
Definition at line 69 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.RedShiftService().
_contactDetailsSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._contactDetailsSQL private
Initial value:
= @"
SELECT        foxtrot.outbound.name AS OutboundName, foxtrot.outboundschedule.name AS ScheduleName, foxtrot.contact.email, foxtrot.event.name AS action, COUNT(foxtrot.eventtransaction.id) AS Count
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id AND foxtrot.eventtransaction.outbound_id = foxtrot.outbound.id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id AND
                         foxtrot.eventtransaction.outboundschedule_id = foxtrot.outboundschedule.id INNER JOIN
                         foxtrot.outboundcontact ON foxtrot.outboundschedule.account_id = foxtrot.outboundcontact.account_id AND foxtrot.outboundschedule.id = foxtrot.outboundcontact.outboundschedule_id AND
                         foxtrot.eventtransaction.outboundcontact_id = foxtrot.outboundcontact.id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id INNER JOIN
                         foxtrot.contact ON foxtrot.outboundcontact.account_id = foxtrot.contact.account_id AND foxtrot.outboundcontact.contact_id = foxtrot.contact.id
WHERE        (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.campaign.account_id = ##AccountId##)
GROUP BY foxtrot.campaign.id, foxtrot.outbound.id, foxtrot.outboundschedule.id, foxtrot.outbound.name, ScheduleName, foxtrot.event.name, foxtrot.contact.email
ORDER BY foxtrot.campaign.id, foxtrot.outbound.id, foxtrot.outboundschedule.id"
Definition at line 315 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getContactDetails().
_inboundElementsClicksSql
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._inboundElementsClicksSql private
Initial value:
= @"
SELECT        COUNT(foxtrot.event.name) AS count
FROM            foxtrot.inbound INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.inbound.account_id = foxtrot.eventtransaction.account_id AND foxtrot.inbound.id = foxtrot.eventtransaction.inbound_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
WHERE        (foxtrot.inbound.campaign_id = ##CampaignId##) AND (foxtrot.inbound.account_id = ##AccountId##) AND (foxtrot.event.name IN ('Page: Link - Click', 'Page: Button - Click', 'Clicked')) AND (foxtrot.inbound.id = ##InboundId##)"
Definition at line 335 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getInboundElements().
_inboundElementsSql
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._inboundElementsSql private
Initial value:
= @"
SELECT DISTINCT foxtrot.inbound.id, foxtrot.inbound.name AS InboundName, foxtrot.inbound.startdate, foxtrot.inbound.enddate
FROM            foxtrot.inbound INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.inbound.account_id = foxtrot.eventtransaction.account_id AND foxtrot.inbound.id = foxtrot.eventtransaction.inbound_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
WHERE        (foxtrot.inbound.campaign_id = ##CampaignId##) AND (foxtrot.inbound.account_id = ##AccountId##)"
Definition at line 329 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getInboundElements().
_inboundElementsVisitsSql
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._inboundElementsVisitsSql private
Initial value:
= @"
SELECT        COUNT(foxtrot.event.name) AS count
FROM            foxtrot.inbound INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.inbound.account_id = foxtrot.eventtransaction.account_id AND foxtrot.inbound.id = foxtrot.eventtransaction.inbound_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
WHERE        (foxtrot.inbound.campaign_id = ##CampaignId##) AND (foxtrot.inbound.account_id = ##AccountId##) AND (foxtrot.event.name = 'Contact Visited Page') AND (foxtrot.inbound.id = ##InboundId##)"
Definition at line 341 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getInboundElements().
_micrositeClicks
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._micrositeClicks private
Initial value:
= @"SELECT COALESCE(COUNT(foxtrot.inbound.id),0) AS Contacts
FROM foxtrot.inbound
INNER JOIN foxtrot.eventtransaction ON foxtrot.inbound.account_id = foxtrot.eventtransaction.account_id AND foxtrot.inbound.id = foxtrot.eventtransaction.inbound_id
INNER JOIN foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
INNER JOIN foxtrot.campaign ON foxtrot.inbound.account_id = foxtrot.campaign.account_id AND foxtrot.inbound.campaign_id = foxtrot.campaign.id
WHERE (foxtrot.inbound.account_id = ##AccountId##) AND (foxtrot.event.name in ('Page: Link - Click', 'Page: Button - Click', 'Clicked')) ##DateFilter## ##CampaignIdsFilter##"
Definition at line 139 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getMicrositeClicksSql().
_micrositeSubmits
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._micrositeSubmits private
Initial value:
= @"SELECT COALESCE(COUNT(foxtrot.inbound.id),0) AS Contacts
FROM foxtrot.inbound
INNER JOIN foxtrot.eventtransaction ON foxtrot.inbound.account_id = foxtrot.eventtransaction.account_id AND foxtrot.inbound.id = foxtrot.eventtransaction.inbound_id
INNER JOIN foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
INNER JOIN foxtrot.campaign ON foxtrot.inbound.account_id = foxtrot.campaign.account_id AND foxtrot.inbound.campaign_id = foxtrot.campaign.id
WHERE (foxtrot.inbound.account_id = ##AccountId##) AND (foxtrot.event.name in ('Page: Form - Submit', 'Page: Submit Form Data', 'Contact Submitted Page', 'Contact provided form data')) ##DateFilter## ##CampaignIdsFilter##"
Definition at line 145 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getMicrositeSubmitsSql().
_micrositeVisits
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._micrositeVisits private
Initial value:
= @"SELECT COALESCE(COUNT(foxtrot.inbound.id),0) AS Contacts
FROM foxtrot.inbound
INNER JOIN foxtrot.eventtransaction ON foxtrot.inbound.account_id = foxtrot.eventtransaction.account_id AND foxtrot.inbound.id = foxtrot.eventtransaction.inbound_id
INNER JOIN foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
INNER JOIN foxtrot.campaign ON foxtrot.inbound.account_id = foxtrot.campaign.account_id AND foxtrot.inbound.campaign_id = foxtrot.campaign.id
WHERE (foxtrot.inbound.account_id = ##AccountId##) AND (foxtrot.event.name in ('Page: Visit', 'Contact Visited Page', 'Contact visited Microsite')) ##DateFilter## ##CampaignIdsFilter##"
Definition at line 133 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getMicrositeVisitsSql().
_msConnectionString
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._msConnectionString private
Definition at line 71 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSqlMSSqlAsync< TClass >(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.RedShiftService().
_openRateOverDays
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._openRateOverDays private
Initial value:
= @"
SELECT        foxtrot.eventtransaction.dim_date_id as date, COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id), 0) AS value
FROM            foxtrot.eventtransaction INNER JOIN
                         foxtrot.campaign ON foxtrot.eventtransaction.account_id = foxtrot.campaign.account_id AND foxtrot.eventtransaction.campaign_id = foxtrot.campaign.id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.eventtransaction.account_id = foxtrot.outboundschedule.account_id AND foxtrot.eventtransaction.outboundschedule_id = foxtrot.outboundschedule.id AND
                         foxtrot.eventtransaction.outbound_id = foxtrot.outboundschedule.outbound_id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.event.description IN ('Contact opened Email', 'Contact opened email')) ##DateFilter## ##CampaignIdsFilter##
GROUP BY foxtrot.eventtransaction.dim_date_id
ORDER BY foxtrot.eventtransaction.dim_date_id"
Definition at line 304 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOpenRatesOverDays().
_opensEmailSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._opensEmailSQL private
Initial value:
= @"SELECT COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id),0) AS Undiliverable
FROM foxtrot.eventtransaction
INNER JOIN foxtrot.campaign ON foxtrot.eventtransaction.account_id = foxtrot.campaign.account_id AND foxtrot.eventtransaction.campaign_id = foxtrot.campaign.id
INNER JOIN foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
INNER JOIN foxtrot.outboundschedule ON foxtrot.eventtransaction.account_id = foxtrot.outboundschedule.account_id AND foxtrot.eventtransaction.outboundschedule_id = foxtrot.outboundschedule.id AND foxtrot.eventtransaction.outbound_id = foxtrot.outboundschedule.outbound_id
WHERE (foxtrot.eventtransaction.account_id = ##AccountId##) ##DateFilter## ##CampaignIdsFilter##
AND (foxtrot.event.description IN ('Contact opened Email', 'Contact opened email'))"
Definition at line 87 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOpenedEmailsSql().
_outboundElementClicksContactsSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementClicksContactsSQL private
Initial value:
= @"
SELECT        DISTINCT foxtrot.contact.accountid
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id INNER JOIN
                         foxtrot.outboundcontact ON foxtrot.campaign.account_id = foxtrot.outboundcontact.account_id AND foxtrot.eventtransaction.outboundcontact_id = foxtrot.outboundcontact.id AND foxtrot.outboundschedule.id = foxtrot.outboundcontact.outboundschedule_id INNER JOIN
                         foxtrot.contact ON foxtrot.outboundcontact.contact_id = foxtrot.contact.id AND foxtrot.campaign.account_id = foxtrot.contact.account_id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##) AND (foxtrot.event.description IN ('Contact clicked on a link in email', 'Contact clicked an outside link', 'Contact clicked a link in Email', 'Clicked'))"
Definition at line 408 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsClicks().
_outboundElementClicksSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementClicksSQL private
Initial value:
= @"
SELECT        COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id), 0) AS count
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##) AND (foxtrot.event.description IN ('Contact clicked on a link in email', 'Contact clicked an outside link', 'Contact clicked a link in Email', 'Clicked'))"
Definition at line 399 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOutboundDetails().
_outboundElementFailedContactsSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementFailedContactsSQL private
Initial value:
= @"
SELECT        DISTINCT foxtrot.contact.accountid
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id INNER JOIN
                         foxtrot.outboundcontact ON foxtrot.campaign.account_id = foxtrot.outboundcontact.account_id AND foxtrot.eventtransaction.outboundcontact_id = foxtrot.outboundcontact.id AND foxtrot.outboundschedule.id = foxtrot.outboundcontact.outboundschedule_id INNER JOIN
                         foxtrot.contact ON foxtrot.outboundcontact.contact_id = foxtrot.contact.id AND foxtrot.campaign.account_id = foxtrot.contact.account_id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##) AND (foxtrot.event.description IN ('Email could not be delivered (failed)', 'Email failed to process'))"
Definition at line 513 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsFailed().
_outboundElementFailedSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementFailedSQL private
Initial value:
= @"
SELECT        COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id), 0) AS count
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##) AND (foxtrot.event.description IN ('Email could not be delivered (failed)', 'Email failed to process'))"
Definition at line 504 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOutboundDetails().
_outboundElementHardBouncedContactsSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementHardBouncedContactsSQL private
Initial value:
= @"
SELECT        DISTINCT foxtrot.contact.accountid
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id  INNER JOIN
                         foxtrot.outboundcontact ON foxtrot.campaign.account_id = foxtrot.outboundcontact.account_id AND foxtrot.eventtransaction.outboundcontact_id = foxtrot.outboundcontact.id AND foxtrot.outboundschedule.id = foxtrot.outboundcontact.outboundschedule_id INNER JOIN
                         foxtrot.contact ON foxtrot.outboundcontact.contact_id = foxtrot.contact.id AND foxtrot.campaign.account_id = foxtrot.contact.account_id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##) AND (foxtrot.event.description = 'Email hard bounced')"
Definition at line 450 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsHardBounced().
_outboundElementHardBouncedSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementHardBouncedSQL private
Initial value:
= @"
SELECT        COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id), 0) AS count
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##) AND (foxtrot.event.description = 'Email hard bounced')"
Definition at line 441 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOutboundDetails().
_outboundElementOpenedContactsSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementOpenedContactsSQL private
Initial value:
= @"
SELECT DISTINCT foxtrot.contact.accountid
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id INNER JOIN
                         foxtrot.outboundcontact ON foxtrot.campaign.account_id = foxtrot.outboundcontact.account_id AND foxtrot.eventtransaction.outboundcontact_id = foxtrot.outboundcontact.id AND foxtrot.outboundschedule.id = foxtrot.outboundcontact.outboundschedule_id INNER JOIN
                         foxtrot.contact ON foxtrot.outboundcontact.contact_id = foxtrot.contact.id AND foxtrot.campaign.account_id = foxtrot.contact.account_id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##) AND (foxtrot.event.description IN ('Contact opened Email', 'Contact opened email'))
"
Definition at line 386 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsOpened().
_outboundElementOpenedSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementOpenedSQL private
Initial value:
= @"
SELECT        COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id), 0) AS count
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##) AND (foxtrot.event.description IN ('Contact opened Email', 'Contact opened email'))
"
Definition at line 376 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOutboundDetails().
_outboundElementsContactsSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementsContactsSQL private
Initial value:
= @"
                        SELECT        accountId
                        FROM(SELECT DISTINCT
                                                    foxtrot.outbound.name AS outboundname, foxtrot.outboundschedule.name AS outboundschedulename, foxtrot.outboundschedule.date, foxtrot.outbound.id AS outboundid,
                                                    foxtrot.outboundschedule.id AS outboundscheduleid, foxtrot.outboundcontact.id AS outboundcontactid, foxtrot.contact.accountid as accountId
                          FROM            foxtrot.campaign INNER JOIN
                                                    foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id INNER JOIN
                                                    foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                                                    foxtrot.outboundschedule ON foxtrot.campaign.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                                                    foxtrot.outboundcontact ON foxtrot.campaign.account_id = foxtrot.outboundcontact.account_id AND foxtrot.outboundschedule.id = foxtrot.outboundcontact.outboundschedule_id INNER JOIN
                                                    foxtrot.contact ON foxtrot.campaign.account_id = foxtrot.contact.account_id AND foxtrot.outboundcontact.contact_id = foxtrot.contact.id INNER JOIN
                                                    foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id AND foxtrot.outboundcontact.event_id = foxtrot.event.id
                         WHERE        (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.campaign.account_id = ##AccountId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##)) tmptable"
Definition at line 362 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsSentTo().
_outboundElementSoftBouncedContactsSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementSoftBouncedContactsSQL private
Initial value:
= @"
SELECT        DISTINCT foxtrot.contact.accountid
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id  INNER JOIN
                         foxtrot.outboundcontact ON foxtrot.campaign.account_id = foxtrot.outboundcontact.account_id AND foxtrot.eventtransaction.outboundcontact_id = foxtrot.outboundcontact.id AND foxtrot.outboundschedule.id = foxtrot.outboundcontact.outboundschedule_id INNER JOIN
                         foxtrot.contact ON foxtrot.outboundcontact.contact_id = foxtrot.contact.id AND foxtrot.campaign.account_id = foxtrot.contact.account_id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##) AND (foxtrot.event.description IN ('Email soft bounced', 'Email was (soft) bounced'))"
Definition at line 471 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsSoftBounced().
_outboundElementSoftBouncedSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementSoftBouncedSQL private
Initial value:
= @"
SELECT        COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id), 0) AS count
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##) AND (foxtrot.event.description IN ('Email soft bounced', 'Email was (soft) bounced'))"
Definition at line 462 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOutboundDetails().
_outboundElementSpamContactsSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementSpamContactsSQL private
Initial value:
= @"
SELECT        DISTINCT foxtrot.contact.accountid
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id INNER JOIN
                         foxtrot.outboundcontact ON foxtrot.campaign.account_id = foxtrot.outboundcontact.account_id AND foxtrot.eventtransaction.outboundcontact_id = foxtrot.outboundcontact.id AND foxtrot.outboundschedule.id = foxtrot.outboundcontact.outboundschedule_id INNER JOIN
                         foxtrot.contact ON foxtrot.outboundcontact.contact_id = foxtrot.contact.id AND foxtrot.campaign.account_id = foxtrot.contact.account_id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##) AND (foxtrot.event.description IN ('Contact marked email as spam', 'Contact marked Email as spam'))"
Definition at line 429 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsSpam().
_outboundElementSpamSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementSpamSQL private
Initial value:
= @"
SELECT        COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id), 0) AS count
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##) AND (foxtrot.event.description IN ('Contact marked email as spam', 'Contact marked Email as spam'))"
Definition at line 420 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOutboundDetails().
_outboundElementsSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementsSQL private
Initial value:
= @"
SELECT        outboundname, outboundschedulename, date, outboundid, outboundscheduleid, COUNT(outboundcontactid) AS contactcount
FROM(SELECT DISTINCT
                                                    foxtrot.outbound.name AS outboundname, foxtrot.outboundschedule.name AS outboundschedulename, foxtrot.outboundschedule.date, foxtrot.outbound.id AS outboundid,
                                                    foxtrot.outboundschedule.id AS outboundscheduleid, foxtrot.outboundcontact.id AS outboundcontactid
                          FROM            foxtrot.campaign INNER JOIN
                                                    foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id INNER JOIN
                                                    foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                                                    foxtrot.outboundschedule ON foxtrot.campaign.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                                                    foxtrot.outboundcontact ON foxtrot.campaign.account_id = foxtrot.outboundcontact.account_id AND foxtrot.outboundschedule.id = foxtrot.outboundcontact.outboundschedule_id INNER JOIN
                                                    foxtrot.contact ON foxtrot.campaign.account_id = foxtrot.contact.account_id AND foxtrot.outboundcontact.contact_id = foxtrot.contact.id INNER JOIN
                                                    foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id AND foxtrot.outboundcontact.event_id = foxtrot.event.id
                         WHERE        (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.campaign.account_id = ##AccountId##)) tmptable
GROUP BY outboundname, outboundschedulename, date, outboundid, outboundscheduleid"
Definition at line 348 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOutboundDetails().
_outboundElementSuppressedContactsSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementSuppressedContactsSQL private
Initial value:
= @"
SELECT        DISTINCT foxtrot.contact.accountid
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id INNER JOIN
                         foxtrot.outboundcontact ON foxtrot.campaign.account_id = foxtrot.outboundcontact.account_id AND foxtrot.eventtransaction.outboundcontact_id = foxtrot.outboundcontact.id AND foxtrot.outboundschedule.id = foxtrot.outboundcontact.outboundschedule_id INNER JOIN
                         foxtrot.contact ON foxtrot.outboundcontact.contact_id = foxtrot.contact.id AND foxtrot.campaign.account_id = foxtrot.contact.account_id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##) AND (foxtrot.event.description = 'Email not sent due to suppression list')"
Definition at line 492 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsSuppressed().
_outboundElementSuppressedSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementSuppressedSQL private
Initial value:
= @"
SELECT        COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id), 0) AS count
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##) AND (foxtrot.event.description = 'Email not sent due to suppression list')"
Definition at line 483 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOutboundDetails().
_outboundElementUnsubscribedContactsSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementUnsubscribedContactsSQL private
Initial value:
= @"
SELECT        DISTINCT foxtrot.contact.accountid
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id INNER JOIN
                         foxtrot.outboundcontact ON foxtrot.campaign.account_id = foxtrot.outboundcontact.account_id AND foxtrot.eventtransaction.outboundcontact_id = foxtrot.outboundcontact.id AND foxtrot.outboundschedule.id = foxtrot.outboundcontact.outboundschedule_id INNER JOIN
                         foxtrot.contact ON foxtrot.outboundcontact.contact_id = foxtrot.contact.id AND foxtrot.campaign.account_id = foxtrot.contact.account_id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##) AND (foxtrot.event.description IN ('Contact opted-out of Email', 'Contact opted-out (unsubscribed)'))"
Definition at line 534 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getElegetOutboundElementContactsUnsubscribed().
_outboundElementUnsubscribedSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._outboundElementUnsubscribedSQL private
Initial value:
= @"
SELECT        COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id), 0) AS count
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.campaign.id = ##CampaignId##) AND (foxtrot.outbound.id = ##OutboundId##) AND (foxtrot.outboundschedule.id = ##ScheduleId##) AND (foxtrot.event.description IN ('Contact opted-out of Email', 'Contact opted-out (unsubscribed)'))"
Definition at line 525 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getOutboundDetails().
_printSentSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._printSentSQL private
Initial value:
= @"SELECT COUNT(foxtrot.outboundcontact.contact_id) AS Count
FROM foxtrot.outboundschedule
INNER JOIN foxtrot.outbound ON foxtrot.outboundschedule.account_id = foxtrot.outbound.account_id AND foxtrot.outboundschedule.outbound_id = foxtrot.outbound.id
INNER JOIN foxtrot.campaign ON foxtrot.outbound.account_id = foxtrot.campaign.account_id AND foxtrot.outbound.campaign_id = foxtrot.campaign.id
INNER JOIN foxtrot.outboundcontact ON foxtrot.outboundschedule.account_id = foxtrot.outboundcontact.account_id AND foxtrot.outboundschedule.id = foxtrot.outboundcontact.outboundschedule_id
WHERE (foxtrot.outbound.account_id = ##AccountId##) AND (foxtrot.outbound.servicetype_id = 205) ##DateFilter## ##CampaignIdsFilter##"
Definition at line 127 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getPrintsSentSql().
_rsConnectionString
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._rsConnectionString private
Definition at line 70 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSqlRedShiftAsync< TClass >(), Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSqlRedShiftMultipleAsync(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.RedShiftService().
_sendsEmailSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._sendsEmailSQL private
Initial value:
= @"SELECT COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id),0) AS Undiliverable
FROM foxtrot.eventtransaction
INNER JOIN foxtrot.campaign ON foxtrot.eventtransaction.account_id = foxtrot.campaign.account_id AND foxtrot.eventtransaction.campaign_id = foxtrot.campaign.id
INNER JOIN foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
INNER JOIN foxtrot.outboundschedule ON foxtrot.eventtransaction.account_id = foxtrot.outboundschedule.account_id AND foxtrot.eventtransaction.outboundschedule_id = foxtrot.outboundschedule.id AND foxtrot.eventtransaction.outbound_id = foxtrot.outboundschedule.outbound_id
WHERE (foxtrot.eventtransaction.account_id = ##AccountId##) ##DateFilter## ##CampaignIdsFilter##
AND (foxtrot.event.description = 'Email sent to Contact')"
Definition at line 80 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSentEmailsSql().
_socialPostsSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._socialPostsSQL private
Initial value:
= @"SELECT COALESCE(COUNT(foxtrot.outboundschedule.date),0) AS Count
FROM foxtrot.outboundschedule
INNER JOIN foxtrot.outbound ON foxtrot.outboundschedule.account_id = foxtrot.outbound.account_id AND foxtrot.outboundschedule.outbound_id = foxtrot.outbound.id
INNER JOIN foxtrot.campaign ON foxtrot.outbound.account_id = foxtrot.campaign.account_id AND foxtrot.outbound.campaign_id = foxtrot.campaign.id
WHERE (foxtrot.outbound.account_id = ##AccountId##) AND(foxtrot.outbound.servicetype_id = 2019) ##DateFilter## ##CampaignIdsFilter##"
Definition at line 122 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSocialPostsSql().
_spamEmailSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._spamEmailSQL private
Initial value:
= @"SELECT COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id),0) AS Undiliverable
FROM foxtrot.eventtransaction
INNER JOIN foxtrot.campaign ON foxtrot.eventtransaction.account_id = foxtrot.campaign.account_id AND foxtrot.eventtransaction.campaign_id = foxtrot.campaign.id
INNER JOIN foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
INNER JOIN foxtrot.outboundschedule ON foxtrot.eventtransaction.account_id = foxtrot.outboundschedule.account_id AND foxtrot.eventtransaction.outboundschedule_id = foxtrot.outboundschedule.id AND foxtrot.eventtransaction.outbound_id = foxtrot.outboundschedule.outbound_id
WHERE (foxtrot.eventtransaction.account_id = ##AccountId##) ##DateFilter## ##CampaignIdsFilter##
AND (foxtrot.event.description IN ('Contact marked email as spam', 'Contact marked Email as spam'))"
Definition at line 101 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSpamEmailsSql().
_suppressedEmailSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._suppressedEmailSQL private
Initial value:
= @"SELECT COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id),0) AS Undiliverable
FROM foxtrot.eventtransaction
INNER JOIN foxtrot.campaign ON foxtrot.eventtransaction.account_id = foxtrot.campaign.account_id AND foxtrot.eventtransaction.campaign_id = foxtrot.campaign.id
INNER JOIN foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
INNER JOIN foxtrot.outboundschedule ON foxtrot.eventtransaction.account_id = foxtrot.outboundschedule.account_id AND foxtrot.eventtransaction.outboundschedule_id = foxtrot.outboundschedule.id AND foxtrot.eventtransaction.outbound_id = foxtrot.outboundschedule.outbound_id
WHERE (foxtrot.eventtransaction.account_id = ##AccountId##) ##DateFilter## ##CampaignIdsFilter##
AND (foxtrot.event.description = 'Email not sent due to suppression list')"
Definition at line 115 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getSuppressedEmailsSql().
_topClickRateByAction
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topClickRateByAction private
Initial value:
= @"
SELECT        foxtrot.event.description as name, COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id), 0) AS count
FROM            foxtrot.eventtransaction INNER JOIN
                         foxtrot.campaign ON foxtrot.eventtransaction.account_id = foxtrot.campaign.account_id AND foxtrot.eventtransaction.campaign_id = foxtrot.campaign.id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.eventtransaction.account_id = foxtrot.outboundschedule.account_id AND foxtrot.eventtransaction.outboundschedule_id = foxtrot.outboundschedule.id AND
                         foxtrot.eventtransaction.outbound_id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.outbound ON foxtrot.eventtransaction.account_id = foxtrot.outbound.account_id AND foxtrot.eventtransaction.outbound_id = foxtrot.outbound.id AND
                         foxtrot.eventtransaction.campaign_id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.contact ON foxtrot.eventtransaction.account_id = foxtrot.contact.account_id AND foxtrot.eventtransaction.contact_id = foxtrot.contact.id INNER JOIN
                         foxtrot.servicetype ON foxtrot.eventtransaction.servicetype_id = foxtrot.servicetype.id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.event.servicetype_id IN (201, 205)) ##DateFilter## ##CampaignIdsFilter##
GROUP BY foxtrot.event.description, foxtrot.servicetype.name
ORDER BY foxtrot.servicetype.name DESC"
Definition at line 256 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNClickRateByAction().
_topClickRateByEmail
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topClickRateByEmail private
Initial value:
= @"
SELECT  top ##No##      foxtrot.contact.email as name, COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id), 0) AS count
FROM            foxtrot.eventtransaction INNER JOIN
                         foxtrot.campaign ON foxtrot.eventtransaction.account_id = foxtrot.campaign.account_id AND foxtrot.eventtransaction.campaign_id = foxtrot.campaign.id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.eventtransaction.account_id = foxtrot.outboundschedule.account_id AND foxtrot.eventtransaction.outboundschedule_id = foxtrot.outboundschedule.id AND
                         foxtrot.eventtransaction.outbound_id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.outbound ON foxtrot.eventtransaction.account_id = foxtrot.outbound.account_id AND foxtrot.eventtransaction.outbound_id = foxtrot.outbound.id AND
                         foxtrot.eventtransaction.campaign_id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.contact ON foxtrot.eventtransaction.account_id = foxtrot.contact.account_id AND foxtrot.eventtransaction.contact_id = foxtrot.contact.id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.event.description IN ('Contact clicked on a link in email', 'Contact clicked an outside link', 'Contact clicked a link in Email', 'Clicked')) ##DateFilter## ##CampaignIdsFilter##
GROUP BY foxtrot.contact.email
ORDER BY count DESC"
Definition at line 243 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNClickRateByEmail().
_topClickrateByOutboundName
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topClickrateByOutboundName private
Initial value:
= @"
SELECT  top ##No##      foxtrot.outbound.name, COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id), 0) AS count
FROM            foxtrot.eventtransaction INNER JOIN
                         foxtrot.campaign ON foxtrot.eventtransaction.account_id = foxtrot.campaign.account_id AND foxtrot.eventtransaction.campaign_id = foxtrot.campaign.id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.eventtransaction.account_id = foxtrot.outboundschedule.account_id AND foxtrot.eventtransaction.outboundschedule_id = foxtrot.outboundschedule.id AND
                         foxtrot.eventtransaction.outbound_id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.outbound ON foxtrot.eventtransaction.account_id = foxtrot.outbound.account_id AND foxtrot.eventtransaction.outbound_id = foxtrot.outbound.id AND
                         foxtrot.eventtransaction.campaign_id = foxtrot.outbound.campaign_id
WHERE        (foxtrot.eventtransaction.account_id =  ##AccountId##) AND (foxtrot.event.description IN ('Contact clicked on a link in email', 'Contact clicked an outside link', 'Contact clicked a link in Email', 'Clicked')) ##DateFilter## ##CampaignIdsFilter##
GROUP BY foxtrot.outbound.name
ORDER BY count DESC"
Definition at line 219 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNClickRateByOutboundName().
_topClickRateByOutboundScheduleName
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topClickRateByOutboundScheduleName private
Initial value:
= @"
SELECT  top ##No##      foxtrot.outboundschedule.name, COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id), 0) AS count
FROM            foxtrot.eventtransaction INNER JOIN
                         foxtrot.campaign ON foxtrot.eventtransaction.account_id = foxtrot.campaign.account_id AND foxtrot.eventtransaction.campaign_id = foxtrot.campaign.id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.eventtransaction.account_id = foxtrot.outboundschedule.account_id AND foxtrot.eventtransaction.outboundschedule_id = foxtrot.outboundschedule.id AND
                         foxtrot.eventtransaction.outbound_id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.outbound ON foxtrot.eventtransaction.account_id = foxtrot.outbound.account_id AND foxtrot.eventtransaction.outbound_id = foxtrot.outbound.id AND
                         foxtrot.eventtransaction.campaign_id = foxtrot.outbound.campaign_id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.event.description IN ('Contact clicked on a link in email', 'Contact clicked an outside link', 'Contact clicked a link in Email', 'Clicked')) ##DateFilter## ##CampaignIdsFilter##
GROUP BY foxtrot.outboundschedule.name
ORDER BY count DESC"
Definition at line 231 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNClickRateByOutboundScheduleName().
_topEngagedCampaigns
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topEngagedCampaigns private
Initial value:
= @"
SELECT TOP ##No## Campaign AS Name, SUM(Action)::float / SUM(sent) AS engagement
from (
SELECT        Campaign, COUNT(outboundcontact_id) AS Action, 0 as Sent
FROM            (SELECT foxtrot.eventtransaction.outboundcontact_id, foxtrot.event.name, foxtrot.campaign.name AS Campaign
                          FROM            foxtrot.campaign INNER JOIN
                                                    foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                                                    foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                                                    foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND
                                                    foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                                                    foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
                          WHERE        (foxtrot.campaign.account_id = ##AccountId##) AND (foxtrot.event.name IN ('Contact clicked a link in Email', 'Clicked', 'Contact opened Email'))  ##DateFilter## ##CampaignIdsFilter##
) derivedtbl_1
GROUP BY Campaign
Union
SELECT        Campaign, 0 as Action, COUNT(outboundcontact_id) AS Sent
FROM            (SELECT foxtrot.eventtransaction.outboundcontact_id, foxtrot.event.name, foxtrot.campaign.name AS Campaign
                          FROM            foxtrot.campaign INNER JOIN
                                                    foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                                                    foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                                                    foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND
                                                    foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id INNER JOIN
                                                    foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
                          WHERE        (foxtrot.campaign.account_id = ##AccountId##) AND (foxtrot.event.name IN ('Email sent to Contact')) ##DateFilter## ##CampaignIdsFilter##
) derivedtbl_1
GROUP BY Campaign)
GROUP BY Campaign
ORDER BY engagement desc
"
Definition at line 152 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNEngagedCampaignsSql().
_topEngagedContacts
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topEngagedContacts private
Initial value:
= @"
SELECT TOP ##No## foxtrot.contact.email as Name, COUNT(foxtrot.eventtransaction.contactscount) AS engagement
FROM            foxtrot.campaign INNER JOIN
                         foxtrot.outbound ON foxtrot.campaign.account_id = foxtrot.outbound.account_id AND foxtrot.campaign.id = foxtrot.outbound.campaign_id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.outbound.account_id = foxtrot.outboundschedule.account_id AND foxtrot.outbound.id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.outboundcontact ON foxtrot.outboundschedule.account_id = foxtrot.outboundcontact.account_id AND foxtrot.outboundschedule.id = foxtrot.outboundcontact.outboundschedule_id INNER JOIN
                         foxtrot.contact ON foxtrot.outboundcontact.account_id = foxtrot.contact.account_id AND foxtrot.outboundcontact.contact_id = foxtrot.contact.id INNER JOIN
                         foxtrot.eventtransaction ON foxtrot.campaign.account_id = foxtrot.eventtransaction.account_id AND foxtrot.campaign.id = foxtrot.eventtransaction.campaign_id AND foxtrot.outbound.id = foxtrot.eventtransaction.outbound_id AND
                         foxtrot.outboundschedule.id = foxtrot.eventtransaction.outboundschedule_id AND foxtrot.outboundcontact.id = foxtrot.eventtransaction.outboundcontact_id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
WHERE        (foxtrot.campaign.account_id = ##AccountId##) AND (foxtrot.event.name IN ('Contact clicked a link in Email', 'Clicked', 'Contact opened Email')) ##DateFilter## ##CampaignIdsFilter##
GROUP BY foxtrot.contact.email
ORDER BY engagement DESC"
Definition at line 181 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNEngagedContactsSql().
_topNLaunchedCampaigns
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topNLaunchedCampaigns private
Initial value:
= @"
select top ##No## c.Name, IsNull(Count(c.id),0) as No, c.id as CampaignId
from UserCampaigns uc
join Campaigns c on c.id = uc.CampaignId
where uc.ClientId = ##ClientId## and uc.Status <> 'Edit' ##DateFilter## ##OnlyActive##
group by c.Name, uc.ClientId, c.id
order by No Desc"
Definition at line 195 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNCampaigns().
_topOpenRateByOutboundName
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topOpenRateByOutboundName private
Initial value:
= @"
SELECT   top ##No##     foxtrot.outbound.name, COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id), 0) AS count
FROM            foxtrot.eventtransaction INNER JOIN
                         foxtrot.campaign ON foxtrot.eventtransaction.account_id = foxtrot.campaign.account_id AND foxtrot.eventtransaction.campaign_id = foxtrot.campaign.id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.eventtransaction.account_id = foxtrot.outboundschedule.account_id AND foxtrot.eventtransaction.outboundschedule_id = foxtrot.outboundschedule.id AND
                         foxtrot.eventtransaction.outbound_id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.outbound ON foxtrot.eventtransaction.account_id = foxtrot.outbound.account_id AND foxtrot.eventtransaction.outbound_id = foxtrot.outbound.id AND
                         foxtrot.eventtransaction.campaign_id = foxtrot.outbound.campaign_id
WHERE        (foxtrot.eventtransaction.account_id =  ##AccountId##) AND (foxtrot.event.description IN ('Contact opened Email', 'Contact opened email')) ##DateFilter## ##CampaignIdsFilter##
GROUP BY foxtrot.outbound.name
ORDER BY count DESC"
Definition at line 280 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNOpenRateByOutboundName().
_topOpenRateByOutboundScheduleName
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._topOpenRateByOutboundScheduleName private
Initial value:
= @"
SELECT  top ##No##      foxtrot.outboundschedule.name, COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id), 0) AS count
FROM            foxtrot.eventtransaction INNER JOIN
                         foxtrot.campaign ON foxtrot.eventtransaction.account_id = foxtrot.campaign.account_id AND foxtrot.eventtransaction.campaign_id = foxtrot.campaign.id INNER JOIN
                         foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id INNER JOIN
                         foxtrot.outboundschedule ON foxtrot.eventtransaction.account_id = foxtrot.outboundschedule.account_id AND foxtrot.eventtransaction.outboundschedule_id = foxtrot.outboundschedule.id AND
                         foxtrot.eventtransaction.outbound_id = foxtrot.outboundschedule.outbound_id INNER JOIN
                         foxtrot.outbound ON foxtrot.eventtransaction.account_id = foxtrot.outbound.account_id AND foxtrot.eventtransaction.outbound_id = foxtrot.outbound.id AND
                         foxtrot.eventtransaction.campaign_id = foxtrot.outbound.campaign_id
WHERE        (foxtrot.eventtransaction.account_id = ##AccountId##) AND (foxtrot.event.description IN ('Contact opened Email', 'Contact opened email')) ##DateFilter## ##CampaignIdsFilter##
GROUP BY foxtrot.outboundschedule.name
ORDER BY count DESC"
Definition at line 292 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getTopNOpenRateByOutboundScheduleName().
_totalLaunchedCampaigns
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._totalLaunchedCampaigns private
Initial value:
= @"select IsNull(Count(uc.id),0) as No
from UserCampaigns uc
where uc.ClientId = ##ClientId## and uc.Status <> 'Edit' ##DateFilter## ##OnlyActive##"
Definition at line 202 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.geTotalNumberOfLaunchedCampaigns().
_undiliverableEmailSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._undiliverableEmailSQL private
Initial value:
= @"SELECT COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id) AS Undiliverable
FROM foxtrot.eventtransaction
INNER JOIN foxtrot.campaign ON foxtrot.eventtransaction.account_id = foxtrot.campaign.account_id AND foxtrot.eventtransaction.campaign_id = foxtrot.campaign.id
INNER JOIN foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
INNER JOIN foxtrot.outboundschedule ON foxtrot.eventtransaction.account_id = foxtrot.outboundschedule.account_id AND foxtrot.eventtransaction.outboundschedule_id = foxtrot.outboundschedule.id AND foxtrot.eventtransaction.outbound_id = foxtrot.outboundschedule.outbound_id
WHERE (foxtrot.eventtransaction.account_id = ##AccountId##) ##DateFilter## ##CampaignIdsFilter##
AND (foxtrot.event.description IN ('Email hard bounced', 'Email could not be delivered (failed)', 'Email failed to process', 'Email soft bounced', 'Email was (soft) bounced'))"
Definition at line 73 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getUndeliverableEmailsSql().
_unsubscribeEmailSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService._unsubscribeEmailSQL private
Initial value:
= @"SELECT COALESCE(COUNT(DISTINCT foxtrot.eventtransaction.outboundcontact_id),0) AS Undiliverable
FROM foxtrot.eventtransaction
INNER JOIN foxtrot.campaign ON foxtrot.eventtransaction.account_id = foxtrot.campaign.account_id AND foxtrot.eventtransaction.campaign_id = foxtrot.campaign.id
INNER JOIN foxtrot.event ON foxtrot.eventtransaction.event_id = foxtrot.event.id
INNER JOIN foxtrot.outboundschedule ON foxtrot.eventtransaction.account_id = foxtrot.outboundschedule.account_id AND foxtrot.eventtransaction.outboundschedule_id = foxtrot.outboundschedule.id AND foxtrot.eventtransaction.outbound_id = foxtrot.outboundschedule.outbound_id
WHERE (foxtrot.eventtransaction.account_id = ##AccountId##) ##DateFilter## ##CampaignIdsFilter##
AND (foxtrot.event.description IN ('Contact opted-out of Email', 'Contact opted-out (unsubscribed)'))"
Definition at line 108 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.getUnsubscribeEmailsSql().
campaignsSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.campaignsSQL private
Initial value:
= @"SELECT foxtrot.campaign.id, foxtrot.campaign.program_id, foxtrot.campaign.name, foxtrot.campaign.submitdate, foxtrot.campaign.startdate, foxtrot.campaign.enddate, foxtrot.campaign.state
                                                FROM foxtrot.campaign
                                                WHERE foxtrot.campaign.account_id = ##param##"
Definition at line 206 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatCampaignsSql().
campaignsSQLOrderBy
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.campaignsSQLOrderBy = @"ORDER BY foxtrot.campaign.submitdate DESC" private
Definition at line 209 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatCampaignsSql().
outboundsSQL
readonly string Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.outboundsSQL private
Initial value:
= @"SELECT     foxtrot.outbound.campaign_id AS CampaignId, foxtrot.servicetype.name AS Service, COUNT(foxtrot.servicetype.name) AS Count
                                                 FROM       foxtrot.outbound
                                                 INNER JOIN foxtrot.servicetype ON foxtrot.outbound.servicetype_id = foxtrot.servicetype.id
                                                 WHERE      foxtrot.outbound.account_id = ##accountid##
                                                 AND        foxtrot.outbound.campaign_id IN (##CampaignIds##)
                                                 GROUP BY CampaignId, Service
                                                 ORDER BY CampaignId"
Definition at line 211 of file RedShiftService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.RedShiftService.formatOutboundsSQL().
The documentation for this class was generated from the following file:
Source/API/Services/RedShiftService.cs