AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser Class Reference
Public Member Functions
PublishForUser ()
Static Package Functions
static PublishForUser GeneratePublishForUser (SharingMessage sharingMessage)
Properties
string SocialToken [get, set]
int CampaignElementId [get, set]
List< SocialAccount > Accounts [get, set]
Private Member Functions
PublishForUser (SharingMessage sharingMessage)
Detailed Description
Definition at line 33 of file SharingRequest.cs.
Constructor & Destructor Documentation
PublishForUser() [1/2]
Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.PublishForUser () inline
Definition at line 36 of file SharingRequest.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.Accounts.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.GeneratePublishForUser().
PublishForUser() [2/2]
Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.PublishForUser (SharingMessage sharingMessage) inline private
Definition at line 40 of file SharingRequest.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.PublishForUser.campaign_element_id, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.CampaignElementId, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.SharingMessage.publish_for_user, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.SocialToken, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.Social.PublishForUser.user_token.
Member Function Documentation
GeneratePublishForUser()
static PublishForUser Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.GeneratePublishForUser (SharingMessage sharingMessage) inline static package
Definition at line 46 of file SharingRequest.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.PublishForUser().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SharingRequest.SharingRequest().
Property Documentation
Accounts
List<SocialAccount> Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.Accounts get set
Definition at line 59 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.PublishForUser(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Sharing().
CampaignElementId
int Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.CampaignElementId get set
Definition at line 55 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.PublishForUser().
SocialToken
string Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.SocialToken get set
Definition at line 51 of file SharingRequest.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PublishForUser.PublishForUser(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Sharing().
The documentation for this class was generated from the following file:
Source/Domain/ViewModel/Social/SharingRequest.cs