AMM: Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController Class Reference
Public Member Functions
DBCController (IDBCService dbcService, ISessionService sessionService)
async Task< ControllerResult< IEnumerable< DBCAccountingUnit > > > GetAccountingUnits ()
Private Attributes
readonly IDBCService _dbcService
readonly ISessionService _sessionService
Detailed Description
Definition at line 22 of file DBCController.cs.
Constructor & Destructor Documentation
DBCController()
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController.DBCController (IDBCService dbcService, ISessionService sessionService) inline
Parameters
dbcService
sessionService
Definition at line 31 of file DBCController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController._dbcService, and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController._sessionService.
Member Function Documentation
GetAccountingUnits()
async Task< ControllerResult< IEnumerable< DBCAccountingUnit > > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController.GetAccountingUnits () inline
Returns
Definition at line 41 of file DBCController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController._dbcService, Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBCService.GetAccountingUnits(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUserId().
Member Data Documentation
_dbcService
readonly IDBCService Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController._dbcService private
Definition at line 24 of file DBCController.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController.DBCController(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController.GetAccountingUnits().
_sessionService
readonly ISessionService Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController._sessionService private
Definition at line 25 of file DBCController.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController.DBCController(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController.GetAccountingUnits().
The documentation for this class was generated from the following file:
Source/API/Controllers/DBCController.cs