AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService Class Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService Class Reference
Public Member Functions
SparkPostService (IConfiguration configuration, IAmazonS3Service amazonS3Service)
async Task< ServiceResult< SendEmailResult > > SendEmail (SendEmail emailInfo, Dictionary< string, string > data=null, string s3Bucket=null)
async Task< ServiceResult< SendEmailResult > > SendEmail (string senderEmail, string senderName, string subject, string templateUrl, Dictionary< string, string > data, string s3Bucket, int? RefreshTokenLastingDays)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ISendEmailService
Private Attributes
readonly IConfiguration _config
readonly IAmazonS3Service _s3
readonly string _apiKey
Detailed Description
Definition at line 18 of file SparkPostService.cs.
Constructor & Destructor Documentation
SparkPostService()
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService.SparkPostService (IConfiguration configuration, IAmazonS3Service amazonS3Service) inline
Definition at line 23 of file SparkPostService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService._apiKey, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService._config, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService._s3.
Member Function Documentation
SendEmail() [1/2]
async Task< ServiceResult< SendEmailResult > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService.SendEmail (SendEmail emailInfo, Dictionary< string, string > data = null, string s3Bucket = null) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ISendEmailService.
Definition at line 30 of file SparkPostService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService._apiKey, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService._s3, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SendEmail.Content, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadString(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SendEmail.IsContentFromUrl, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SendEmail.RecipientEmail, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.Tags.ReplaceTags(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SendEmail.SenderEmail, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SendEmail.SenderName, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.SendEmail.Subject.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService.SendEmail().
SendEmail() [2/2]
async Task< ServiceResult< SendEmailResult > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService.SendEmail (string senderEmail, string senderName, string subject, string templateUrl, Dictionary< string, string > data, string s3Bucket, int? RefreshTokenLastingDays) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ISendEmailService.
Definition at line 149 of file SparkPostService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService.SendEmail().
Member Data Documentation
_apiKey
readonly string Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService._apiKey private
Definition at line 22 of file SparkPostService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService.SendEmail(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService.SparkPostService().
_config
readonly IConfiguration Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService._config private
Definition at line 20 of file SparkPostService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService.SparkPostService().
_s3
readonly IAmazonS3Service Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService._s3 private
Definition at line 21 of file SparkPostService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService.SendEmail(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService.SparkPostService().
The documentation for this class was generated from the following file:
Source/Infrastructure/SparkPost/SparkPostService.cs