AMM: Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController Class Reference
Public Member Functions
SocialNetworkController (ISocialNetworkService socialNetworkService, ClientDbContext clientDbContext)
Social networks controller.
async Task< ControllerResult< SocialAccountInfoVM > > GetTwitterAccountInfo (string verifierCode, string authorizationId, string clientName)
async Task< ControllerResult< SocialAccountInfoVM > > GetLinkedinAccountInfo (string code, string state, string clientName)
ControllerResult< string > SocialAuthorization (string provider, string clientName)
Get url for social authorization.
async Task< ControllerResult< string > > Sharing (SharingRequest sharingRequest)
Share post to all choosen social networks. Used by Mindfire to call AMM when a schedule is executed.
async Task< ControllerResult< string > > UnlinkSocial (UnlinkSocialVM unlinkSocialVM)
async Task< ControllerResult< CheckSocialVM > > CheckSocialForUser ([FromBody] CheckSocialVM checkSocialVM)
async Task< ControllerResult< string > > SaveCredentials ([FromBody] List< SocialAccountInfoVM > socialAccountInfos, [FromQuery] string clientName)
Properties
ISocialNetworkService _socialNetworkService [get, set]
ClientDbContext _clientDbContext [get, set]
Detailed Description
Definition at line 22 of file SocialNetworkController.cs.
Constructor & Destructor Documentation
SocialNetworkController()
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.SocialNetworkController (ISocialNetworkService socialNetworkService, ClientDbContext clientDbContext) inline
Social networks controller.
Parameters
socialNetworkService
clientDbContext
Definition at line 38 of file SocialNetworkController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController._clientDbContext, and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController._socialNetworkService.
Member Function Documentation
CheckSocialForUser()
async Task< ControllerResult< CheckSocialVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.CheckSocialForUser ([FromBody] CheckSocialVM checkSocialVM) inline
Parameters
checkSocialVM
Returns
Definition at line 132 of file SocialNetworkController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController._socialNetworkService, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.CheckSocialForUser().
GetLinkedinAccountInfo()
async Task< ControllerResult< SocialAccountInfoVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.GetLinkedinAccountInfo (string code, string state, string clientName) inline
Parameters
code
state
clientName
Returns
Definition at line 65 of file SocialNetworkController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController._clientDbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService._linkedinService, Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController._socialNetworkService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.Clients, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.GetSocailAccountInfo().
GetTwitterAccountInfo()
async Task< ControllerResult< SocialAccountInfoVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.GetTwitterAccountInfo (string verifierCode, string authorizationId, string clientName) inline
Parameters
verifierCode
authorizationId
clientName
Returns
Definition at line 52 of file SocialNetworkController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController._socialNetworkService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService._twitterService, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.GetSocailAccountInfo().
SaveCredentials()
async Task< ControllerResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.SaveCredentials ([FromBody] List< SocialAccountInfoVM > socialAccountInfos, [FromQuery] string clientName) inline
Parameters
socialAccountInfos
clientName
Returns
Definition at line 144 of file SocialNetworkController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController._clientDbContext, Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController._socialNetworkService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.Clients, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.SaveCredentials().
Sharing()
async Task< ControllerResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.Sharing (SharingRequest sharingRequest) inline
Share post to all choosen social networks. Used by Mindfire to call AMM when a schedule is executed.
Returns
Definition at line 105 of file SocialNetworkController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController._socialNetworkService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.Authenticate(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.Sharing().
SocialAuthorization()
ControllerResult< string > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.SocialAuthorization (string provider, string clientName) inline
Get url for social authorization.
Parameters
provider
clientName
Returns
Definition at line 84 of file SocialNetworkController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController._clientDbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService._linkedinService, Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController._socialNetworkService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService._twitterService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ITwitterService.Auth(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.Clients, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ILinkedinService.LoginRedirect().
UnlinkSocial()
async Task< ControllerResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.UnlinkSocial (UnlinkSocialVM unlinkSocialVM) inline
Parameters
unlinkSocialVM
Returns
Definition at line 121 of file SocialNetworkController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController._socialNetworkService, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.ISocialNetworkService.UnlinkFromSocial().
Property Documentation
_clientDbContext
ClientDbContext Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController._clientDbContext get set private
Definition at line 28 of file SocialNetworkController.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.GetLinkedinAccountInfo(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.SaveCredentials(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.SocialAuthorization(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.SocialNetworkController().
_socialNetworkService
ISocialNetworkService Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController._socialNetworkService get set private
Definition at line 24 of file SocialNetworkController.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.CheckSocialForUser(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.GetLinkedinAccountInfo(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.GetTwitterAccountInfo(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.SaveCredentials(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.Sharing(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.SocialAuthorization(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.SocialNetworkController(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.UnlinkSocial().
The documentation for this class was generated from the following file:
Source/API/Controllers/SocialNetworkController.cs