AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext Class Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext Class Reference
Public Member Functions
ApplicationDbContext (DbContextOptions< ApplicationDbContext > options, ISessionService sessionService)
override int SaveChanges ()
int SaveChangesWithoutTimestamps ()
override Task< int > SaveChangesAsync (CancellationToken cancellationToken=default)
void DetachAllEntities ()
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext
EntityEntry< TEntity > Update< TEntity > (TEntity entity)
EntityEntry< TEntity > Remove< TEntity > (TEntity entity)
DbSet< TModel > Set< TModel > ()
Protected Member Functions
override void OnModelCreating (ModelBuilder modelBuilder)
Properties
ISession _session [get]
virtual DbSet< AccountStatus > AccountStatuses [get, set]
virtual DbSet< Campaign > Campaigns [get, set]
virtual DbSet< CampaignType > CampaignTypes [get, set]
virtual DbSet< EmailDomain > EmailDomains [get, set]
virtual DbSet< EventDetail > EventDetails [get, set]
virtual DbSet< SignatureBlock > SignatureBlocks [get, set]
virtual DbSet< UserCampaign > UserCampaigns [get, set]
virtual DbSet< Settings > Settings [get, set]
virtual DbSet< SettingsGroup > SettingsGroups [get, set]
virtual DbSet< Schedule > Schedules [get, set]
virtual DbSet< CampaignElement > CampaignElements [get, set]
virtual DbSet< Contact > Contacts [get, set]
virtual DbSet< ContactTag > ContactTags [get, set]
virtual DbSet< ContactGroup > ContactGroups [get, set]
virtual DbSet< Template > Templates [get, set]
virtual DbSet< TemplateField > TemplateFields [get, set]
virtual DbSet< TemplateFieldOption > TemplateFieldOptions [get, set]
virtual DbSet< EditorField > EditorFields [get, set]
virtual DbSet< TemplateThumbnailModel > TemplateThumbnailModels [get, set]
virtual DbSet< TemplateThumbnailOverlayModel > TemplateThumbnailOverlayModels [get, set]
virtual DbSet< TwitterAccount > TwitterAccounts [get, set]
virtual DbSet< LinkedinAccount > LinkedinAccounts [get, set]
virtual DbSet< CustomizedVideo > CustomizedVideos [get, set]
virtual DbSet< CampaignSetting > CampaignSettings [get, set]
virtual DbSet< SocialPostLogLine > LogSocialPost [get, set]
virtual DbSet< Session > Session [get, set]
virtual DbSet< SessionData > SessionData [get, set]
virtual DbSet< Job > Job [get, set]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext
DbSet< ApplicationUser > Users [get]
Private Member Functions
void OnBeforeSaveChanges ()
void AddTimestampsToEntities ()
Private Attributes
readonly ISessionService _sessionService
Detailed Description
Definition at line 183 of file ApplicationDbContext.cs.
Constructor & Destructor Documentation
ApplicationDbContext()
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.ApplicationDbContext (DbContextOptions< ApplicationDbContext > options, ISessionService sessionService) inline
Definition at line 200 of file ApplicationDbContext.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext._sessionService.
Member Function Documentation
AddTimestampsToEntities()
void Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.AddTimestampsToEntities () inline private
Definition at line 211 of file ApplicationDbContext.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext._session.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.OnBeforeSaveChanges().
DetachAllEntities()
void Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.DetachAllEntities () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 270 of file ApplicationDbContext.cs.
OnBeforeSaveChanges()
void Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.OnBeforeSaveChanges () inline private
Definition at line 206 of file ApplicationDbContext.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.AddTimestampsToEntities().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChanges(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesAsync().
OnModelCreating()
override void Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.OnModelCreating (ModelBuilder modelBuilder) inline protected
Definition at line 400 of file ApplicationDbContext.cs.
SaveChanges()
override int Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChanges () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 252 of file ApplicationDbContext.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.OnBeforeSaveChanges().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AdminService.DeactivateUser(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.RemoveJob().
SaveChangesAsync()
override Task< int > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesAsync (CancellationToken cancellationToken = default) inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 264 of file ApplicationDbContext.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.OnBeforeSaveChanges().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetBySocialToken(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetBySocialToken(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetSocailAccountInfo(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetSocailAccountInfo(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF.GetUnsubscribedList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterAdvisor(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerApplicationUserWithUserId(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.Remove(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.Remove(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Scripts.UpdateBillingCodes.Run(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.SaveCredentials(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.SaveCredentials(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Sharing(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SignIn(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SSOSignIn().
SaveChangesWithoutTimestamps()
int Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SaveChangesWithoutTimestamps () inline
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 259 of file ApplicationDbContext.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Clear(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.GetOrCreateSession(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Remove(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Set().
Member Data Documentation
_sessionService
readonly ISessionService Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext._sessionService private
Definition at line 197 of file ApplicationDbContext.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.ApplicationDbContext().
Property Documentation
_session
ISession Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext._session get private
Definition at line 198 of file ApplicationDbContext.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.AddTimestampsToEntities().
AccountStatuses
virtual DbSet<AccountStatus> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.AccountStatuses get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 287 of file ApplicationDbContext.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SignIn().
CampaignElements
virtual DbSet<CampaignElement> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.CampaignElements get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 327 of file ApplicationDbContext.cs.
Campaigns
virtual DbSet<Campaign> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.Campaigns get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 291 of file ApplicationDbContext.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonaInstanceNamesForCampaign().
CampaignSettings
virtual DbSet<CampaignSetting> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.CampaignSettings get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 379 of file ApplicationDbContext.cs.
CampaignTypes
virtual DbSet<CampaignType> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.CampaignTypes get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 295 of file ApplicationDbContext.cs.
ContactGroups
virtual DbSet<ContactGroup> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.ContactGroups get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 339 of file ApplicationDbContext.cs.
Contacts
virtual DbSet<Contact> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.Contacts get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 331 of file ApplicationDbContext.cs.
ContactTags
virtual DbSet<ContactTag> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.ContactTags get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 335 of file ApplicationDbContext.cs.
CustomizedVideos
virtual DbSet<CustomizedVideo> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.CustomizedVideos get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 375 of file ApplicationDbContext.cs.
EditorFields
virtual DbSet<EditorField> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.EditorFields get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 355 of file ApplicationDbContext.cs.
EmailDomains
virtual DbSet<EmailDomain> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.EmailDomains get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 299 of file ApplicationDbContext.cs.
EventDetails
virtual DbSet<EventDetail> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.EventDetails get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 303 of file ApplicationDbContext.cs.
Job
virtual DbSet<Job> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.Job get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 395 of file ApplicationDbContext.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.CleanUpJobRunnersAndJobs(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.JobPoolService.GetJob().
LinkedinAccounts
virtual DbSet<LinkedinAccount> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.LinkedinAccounts get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 371 of file ApplicationDbContext.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.CheckRefreshTokenForWarning(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.DoesExist(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetBySocialToken(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetSocailAccountInfo(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.Remove(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.SaveCredentials(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.SharePost().
LogSocialPost
virtual DbSet<SocialPostLogLine> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.LogSocialPost get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 383 of file ApplicationDbContext.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.Sharing().
Schedules
virtual DbSet<Schedule> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.Schedules get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 323 of file ApplicationDbContext.cs.
Session
virtual DbSet<Session> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.Session get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 387 of file ApplicationDbContext.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.GetOrCreateSession().
SessionData
virtual DbSet<SessionData> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SessionData get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 391 of file ApplicationDbContext.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Clear(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Remove(), Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.Set(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.Session.DatabaseSession.TryGetValue().
Settings
virtual DbSet<Settings> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.Settings get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 315 of file ApplicationDbContext.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.SalesforceService.SalesforceService().
SettingsGroups
virtual DbSet<SettingsGroup> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SettingsGroups get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 319 of file ApplicationDbContext.cs.
SignatureBlocks
virtual DbSet<SignatureBlock> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.SignatureBlocks get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 307 of file ApplicationDbContext.cs.
TemplateFieldOptions
virtual DbSet<TemplateFieldOption> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.TemplateFieldOptions get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 351 of file ApplicationDbContext.cs.
TemplateFields
virtual DbSet<TemplateField> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.TemplateFields get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 347 of file ApplicationDbContext.cs.
Templates
virtual DbSet<Template> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.Templates get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 343 of file ApplicationDbContext.cs.
TemplateThumbnailModels
virtual DbSet<TemplateThumbnailModel> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.TemplateThumbnailModels get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 359 of file ApplicationDbContext.cs.
TemplateThumbnailOverlayModels
virtual DbSet<TemplateThumbnailOverlayModel> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.TemplateThumbnailOverlayModels get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 363 of file ApplicationDbContext.cs.
TwitterAccounts
virtual DbSet<TwitterAccount> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.TwitterAccounts get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 367 of file ApplicationDbContext.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.DoesExist(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetBySocialToken(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetSocailAccountInfo(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.PublishTweet(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.Remove(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.SaveCredentials().
UserCampaigns
virtual DbSet<UserCampaign> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ApplicationDbContext.UserCampaigns get set
Implements Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.
Definition at line 311 of file ApplicationDbContext.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Scripts.UpdateSocialCallbackUrl.Run().
The documentation for this class was generated from the following file:
Source/Infrastructure/Databases/ApplicationDbContext.cs