AMM: Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T > Class Template Reference
Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T > Class Template Reference
Public Member Functions
ControllerResult (ErrorVM error)
ControllerResult (IActionResult actionResult)
IActionResult Convert ()
ControllerResult (T data, ErrorVM error)
ControllerResult (T data)
ControllerResult (ErrorVM error)
ControllerResult (IActionResult actionResult)
ControllerResult (ActionResult< T > actionResult)
ControllerResult (ServiceResult< T > serviceResult, ErrorType errorType=ErrorType.Unspecified, int additionalFramesToSkip=0)
ControllerResult (ApiResponse< T > apiResponse, ErrorType errorType=ErrorType.Unspecified, int additionalFramesToSkip=0)
ControllerResult< T2 > As< T2 > ()
ControllerResult AsEmpty ()
Static Public Member Functions
static implicit operator ControllerResult (Error error)
static implicit operator ControllerResult (ActionResult actionResult)
static ControllerResult< T > From< T > (T data)
static ControllerResult From (IActionResult actionResult)
static ControllerResult< T > From< T > (ServiceResult< T > serviceResult)
static ControllerResult< T > From< T > (ApiResponse< T > apiResponse)
static ControllerResult< JobVM< T > > From< T > (Job< T > job)
static ControllerResult< JobVM< T > > From< T > (Job< ServiceResult< T > > job)
static ControllerResult< JobVM< T > > From< T > (Job< ApiResponse< T > > job)
static implicit operator ControllerResult< T > (T data)
static implicit operator ControllerResult< T > (Error error)
static implicit operator ControllerResult< T > (ActionResult< T > actionResult)
static implicit operator ControllerResult< T > (ActionResult actionResult)
static implicit operator ControllerResult< T > (ServiceResult< T > serviceResult)
static implicit operator ControllerResult< T > (ApiResponse< T > apiResponse)
Public Attributes
HttpStatusCode SuccessHttpStatusCode
Protected Member Functions
ControllerResult ()
virtual HttpStatusCode GetDefaultSuccessHttpStatusCode ()
virtual IActionResult GetActionResultOnSuccess ()
virtual IActionResult GetActionResultOnError ()
ControllerResult ()
override HttpStatusCode GetDefaultSuccessHttpStatusCode ()
override IActionResult GetActionResultOnSuccess ()
Protected Attributes
IActionResult actionResult
Properties
ErrorVM Error [get, protected set]
static ControllerResult Success [get]
T? Data [get, private set]
Detailed Description
Definition at line 124 of file ControllerResult.cs.
Constructor & Destructor Documentation
ControllerResult() [1/11]
Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult () inline protected
Definition at line 27 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.GetDefaultSuccessHttpStatusCode(), and Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.SuccessHttpStatusCode.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.As< T2 >(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.AsEmpty(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From< T >(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From< T >(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From< T >(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult< T >(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult< T >(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult< T >(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult< T >(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult< T >(), and Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult< T >().
ControllerResult() [2/11]
Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult (ErrorVM error) inline
Definition at line 32 of file ControllerResult.cs.
ControllerResult() [3/11]
Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult (IActionResult actionResult) inline
Definition at line 37 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.actionResult.
ControllerResult() [4/11]
Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult () inline protected
Definition at line 134 of file ControllerResult.cs.
ControllerResult() [5/11]
Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult (T data, ErrorVM error) inline
Definition at line 139 of file ControllerResult.cs.
ControllerResult() [6/11]
Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult (T data) inline
Definition at line 144 of file ControllerResult.cs.
ControllerResult() [7/11]
Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult (ErrorVM error) inline
Definition at line 149 of file ControllerResult.cs.
ControllerResult() [8/11]
Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult (IActionResult actionResult) inline
Definition at line 154 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.actionResult.
ControllerResult() [9/11]
Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult (ActionResult< T > actionResult) inline
Definition at line 159 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.actionResult.
ControllerResult() [10/11]
Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult (ServiceResult< T > serviceResult, ErrorType errorType = ErrorType::Unspecified, int additionalFramesToSkip = 0) inline
Definition at line 165 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ServiceModel.ServiceResult< T >.Data.
ControllerResult() [11/11]
Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult (ApiResponse< T > apiResponse, ErrorType errorType = ErrorType::Unspecified, int additionalFramesToSkip = 0) inline
Definition at line 171 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.Data.
Member Function Documentation
As< T2 >()
ControllerResult< T2 > Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.As< T2 > () inline
Definition at line 187 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult().
AsEmpty()
ControllerResult Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.AsEmpty () inline
Definition at line 192 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult().
Convert()
IActionResult Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.Convert () inline
Definition at line 57 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.actionResult, Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.GetActionResultOnError(), and Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.GetActionResultOnSuccess().
From()
static ControllerResult Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From (IActionResult actionResult) inline static
Definition at line 83 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.actionResult, and Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController.GetAccountingUnits(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< TService >.GetJob< T >(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< TService >.GetJobApiResponse< T >(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< TService >.GetJobServiceResult< T >(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController.GetTimeZones().
From< T >() [1/6]
static ControllerResult< T > Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From< T > (ApiResponse< T > apiResponse) inline static
Definition at line 93 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult().
From< T >() [2/6]
static ControllerResult< JobVM< T > > Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From< T > (Job< ApiResponse< T > > job) inline static
Definition at line 112 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.Data.
From< T >() [3/6]
static ControllerResult< JobVM< T > > Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From< T > (Job< ServiceResult< T > > job) inline static
Definition at line 103 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.Data.
From< T >() [4/6]
static ControllerResult< JobVM< T > > Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From< T > (Job< T > job) inline static
Definition at line 98 of file ControllerResult.cs.
From< T >() [5/6]
static ControllerResult< T > Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From< T > (ServiceResult< T > serviceResult) inline static
Definition at line 88 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult().
From< T >() [6/6]
static ControllerResult< T > Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From< T > (T data) inline static
Definition at line 78 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult().
GetActionResultOnError()
virtual IActionResult Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.GetActionResultOnError () inline protected virtual
Definition at line 52 of file ControllerResult.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.Convert().
GetActionResultOnSuccess() [1/2]
virtual IActionResult Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.GetActionResultOnSuccess () inline protected virtual
Definition at line 47 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.SuccessHttpStatusCode.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.Convert().
GetActionResultOnSuccess() [2/2]
override IActionResult Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.GetActionResultOnSuccess () inline protected
Definition at line 182 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.SuccessHttpStatusCode.
GetDefaultSuccessHttpStatusCode() [1/2]
virtual HttpStatusCode Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.GetDefaultSuccessHttpStatusCode () inline protected virtual
Definition at line 42 of file ControllerResult.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult().
GetDefaultSuccessHttpStatusCode() [2/2]
override HttpStatusCode Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.GetDefaultSuccessHttpStatusCode () inline protected
Definition at line 177 of file ControllerResult.cs.
operator ControllerResult() [1/2]
static implicit Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult (ActionResult actionResult) inline static
Definition at line 73 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.actionResult, and Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult().
operator ControllerResult() [2/2]
static implicit Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult (Error error) inline static
Definition at line 68 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult().
operator ControllerResult< T >() [1/6]
static implicit Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult< T > (ActionResult actionResult) inline static
Definition at line 212 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.actionResult, and Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult().
operator ControllerResult< T >() [2/6]
static implicit Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult< T > (ActionResult< T > actionResult) inline static
Definition at line 207 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.actionResult, and Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult().
operator ControllerResult< T >() [3/6]
static implicit Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult< T > (ApiResponse< T > apiResponse) inline static
Definition at line 222 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult().
operator ControllerResult< T >() [4/6]
static implicit Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult< T > (Error error) inline static
Definition at line 202 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult().
operator ControllerResult< T >() [5/6]
static implicit Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult< T > (ServiceResult< T > serviceResult) inline static
Definition at line 217 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult().
operator ControllerResult< T >() [6/6]
static implicit Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult< T > (T data) inline static
Definition at line 197 of file ControllerResult.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult().
Member Data Documentation
actionResult
IActionResult Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.actionResult protected
Definition at line 16 of file ControllerResult.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.Convert(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult(), Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult< T >(), and Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.operator ControllerResult< T >().
SuccessHttpStatusCode
HttpStatusCode Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.SuccessHttpStatusCode
Definition at line 19 of file ControllerResult.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.ControllerResult(), and Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.GetActionResultOnSuccess().
Property Documentation
Data
T? Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.Data get private set
Definition at line 127 of file ControllerResult.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From< T >(), and Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.From< T >().
Error
ErrorVM Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.Error get protected set
Definition at line 21 of file ControllerResult.cs.
Success
ControllerResult Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.Success static get
Definition at line 121 of file ControllerResult.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UserCampaignController.BulkSyncPersonaWithLaunchedCampaigns(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.DisconnectRT(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.DisconnectSF(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UserCampaignController.PersonaSyncWithLaunchedCampaigns(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.SFCallback(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.TestGet().
The documentation for this class was generated from the following file:
Source/API/Models/ControllerResult.cs