AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService Class Reference
Public Member Functions
CampaignService ()
CampaignService (IMapper mapper, ApplicationDbContext dbContext, IConfiguration configuration, ILogger< CampaignService > logger, ISettingsService settingsService, ISessionService sessionService, ISocialNetworkService socialNetworkService, IHttpClientFactory httpClientFactory)
async Task< ServiceResult< List< CampaignVM > > > GetCampaignsForProfile (CampaignFilterDTO campaignFilterDTO)
async Task< ServiceResult< List< CampaignVM > > > GetCampaignsByHierarchyTags (string hierarchyTag)
async Task< ServiceResult< List< RSSItemVM > > > GetRssFeeds (int campaignTemplateId)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< Campaign, CampaignVM >
NamedDbService ()
NamedDbService (IMapper mapper, IApplicationDbContext dbContext, IConfiguration configuration, ILogger< NamedDbService< TModel, TModelVM > > logger, ISocialNetworkService socialNetworkService, ISessionService sessionService)
override async Task< ServiceResult< TModelVM > > Update (TModelVM entityVM)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignService
Properties
ISettingsService SettingsService [get, set]
Static Private Member Functions
static void ParseFeedTitleDate (RSSItemVM rssItemVM, out DateTime dateTime)
Private Attributes
readonly IHttpClientFactory _httpClientFactory
Detailed Description
Definition at line 34 of file CampaignService.cs.
Constructor & Destructor Documentation
CampaignService() [1/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService.CampaignService () inline
Definition at line 43 of file CampaignService.cs.
CampaignService() [2/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService.CampaignService (IMapper mapper, ApplicationDbContext dbContext, IConfiguration configuration, ILogger< CampaignService > logger, ISettingsService settingsService, ISessionService sessionService, ISocialNetworkService socialNetworkService, IHttpClientFactory httpClientFactory) inline
Definition at line 46 of file CampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService._httpClientFactory.
Member Function Documentation
GetCampaignsByHierarchyTags()
async Task< ServiceResult< List< CampaignVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService.GetCampaignsByHierarchyTags (string hierarchyTag) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignService.
Definition at line 130 of file CampaignService.cs.
GetCampaignsForProfile()
async Task< ServiceResult< List< CampaignVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService.GetCampaignsForProfile (CampaignFilterDTO campaignFilterDTO) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignService.
Definition at line 62 of file CampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignFilter.InclusionTags, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignFilterDTO.InclusionTags, and Deluxe.DeluxeBrandCenter.AMM.API.Services.SettingsService.SingleByName().
GetRssFeeds()
async Task< ServiceResult< List< RSSItemVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService.GetRssFeeds (int campaignTemplateId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ICampaignService.
Definition at line 168 of file CampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService._httpClientFactory, and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService.ParseFeedTitleDate().
ParseFeedTitleDate()
static void Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService.ParseFeedTitleDate (RSSItemVM rssItemVM, out DateTime dateTime) inline static private
Definition at line 146 of file CampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.RSSItemVM.PubDate, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.RSSItemVM.Title.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService.GetRssFeeds().
Member Data Documentation
_httpClientFactory
readonly IHttpClientFactory Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService._httpClientFactory private
Definition at line 36 of file CampaignService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService.CampaignService(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService.GetRssFeeds().
Property Documentation
SettingsService
ISettingsService Deluxe.DeluxeBrandCenter.AMM.API.Services.CampaignService.SettingsService get set
Definition at line 38 of file CampaignService.cs.
The documentation for this class was generated from the following file:
Source/API/Services/CampaignService.cs