AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.TemplateService Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.TemplateService Class Reference
Public Member Functions
TemplateService ()
TemplateService (IMapper mapper, ApplicationDbContext dbContext, IConfiguration configuration, ILogger< TemplateService > logger, IAmazonS3Service amazonS3Service, ISocialNetworkService socialNetworkService, ISessionService sessionService)
async Task< ServiceResult< TemplateVM > > GetSingleByTemplateId (string templateId)
async Task< ServiceResult< string > > GetSignatureBlock (string position)
async Task< ServiceResult< string > > GetInsideMessageTemplate (string insideMessageTemplateName)
async Task< ServiceResult< string > > GetDisclosureTextTemplate (string disclosureTemplateName)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Template, TemplateVM >
DBService ()
DBService (IMapper mapper, IApplicationDbContext dbContext, IConfiguration configuration, ILogger< DBService< TModel, TModelVM > > logger, ISocialNetworkService socialNetworkService, ISessionService sessionService)
virtual async Task< string > UpdateSocialURLs (PMSPersonaDTO personalInfo)
virtual async Task< ServiceResult< TModelVM > > Delete (int id)
virtual async Task< ServiceResult< TModel > > Entity (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
virtual async Task< ServiceResult< TModelVM > > Single (int id)
virtual async Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
virtual async Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate, int clientId)
virtual async Task< ServiceResult< List< TModelVM > > > GetList ()
virtual async Task< ServiceResult< List< TModelVM > > > GetList (Expression< Func< TModel, bool > > predicate=null, Expression< Func< TModel, object > > orderBy=null, bool descending=false, bool disableTracking=false, string[] navigationPaths=null, bool clientSide=false, params Expression< Func< TModel, object > >[] include)
virtual async Task< ServiceResult< TModelVM > > Update (TModelVM entity)
virtual async Task< ServiceResult< TModel > > UpdateEntity (TModel entity)
virtual async Task< bool > DoesExist< TModelCheck > (int id)
virtual void FillHtmlWithPersonalInfo (ref string htmlContent, PMSPersonaDTO personalInfo, List< KeyValuePair< string, string > > editorFields=null, int? clientId=0, bool preview=false)
virtual void FillHtmlContent (ref string htmlContent, PMSPersonaDTO personalInfo, SignatureBlockVM signatureBlock, string insideMessage=null, List< KeyValuePair< string, string > > editorFields=null, bool preview=false)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.ITemplateService
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< Template, TemplateVM >
Task< ServiceResult< TModelVM > > Single (int id)
Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate, int clientId)
Task< ServiceResult< TModel > > Entity (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
Task< ServiceResult< List< TModelVM > > > GetList ()
Task< ServiceResult< List< TModelVM > > > GetList (Expression< Func< TModel, bool > > predicate=null, Expression< Func< TModel, object > > orderBy=null, bool descending=false, bool disableTracking=true, string[] navigationPaths=null, bool clientSide=false, params Expression< Func< TModel, object > >[] include)
Task< ServiceResult< TModelVM > > Delete (int id)
Task< ServiceResult< TModel > > UpdateEntity (TModel entity)
Task< ServiceResult< TModelVM > > Update (TModelVM entity)
Task< string > UpdateSocialURLs (PMSPersonaDTO personalInfo)
void FillHtmlWithPersonalInfo (ref string htmlContent, PMSPersonaDTO personalInfo, List< KeyValuePair< string, string > > editorFields=null, int? clientId=0, bool preview=false)
void FillHtmlContent (ref string htmlContent, PMSPersonaDTO personalInfo, SignatureBlockVM signatureBlock, string insideMessage=null, List< KeyValuePair< string, string > > editorFields=null, bool preview=false)
Properties
IAmazonS3Service AmazonS3Service [get, set]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Template, TemplateVM >
IApplicationDbContext dbContext [get, set]
IMapper mapper [get, set]
IConfiguration configuration [get, set]
ILogger< DBService< TModel, TModelVM > > logger [get]
string Client [get]
int? ClientId [get]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< Template, TemplateVM >
IApplicationDbContext dbContext [get, set]
IMapper mapper [get, set]
ILogger< DBService< TModel, TModelVM > > logger [get]
Additional Inherited Members
Public Attributes inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Template, TemplateVM >
ISocialNetworkService _socialNetworkService
ISessionService _sessionService
Protected Attributes inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Template, TemplateVM >
readonly DbSet< TModel > _dbSet
Detailed Description
Definition at line 30 of file TemplateService.cs.
Constructor & Destructor Documentation
TemplateService() [1/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.TemplateService.TemplateService () inline
Definition at line 37 of file TemplateService.cs.
TemplateService() [2/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.TemplateService.TemplateService (IMapper mapper, ApplicationDbContext dbContext, IConfiguration configuration, ILogger< TemplateService > logger, IAmazonS3Service amazonS3Service, ISocialNetworkService socialNetworkService, ISessionService sessionService) inline
Definition at line 41 of file TemplateService.cs.
Member Function Documentation
GetDisclosureTextTemplate()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.TemplateService.GetDisclosureTextTemplate (string disclosureTemplateName) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ITemplateService.
Definition at line 128 of file TemplateService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadHTMLFromContent().
GetInsideMessageTemplate()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.TemplateService.GetInsideMessageTemplate (string insideMessageTemplateName) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ITemplateService.
Definition at line 118 of file TemplateService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadHTMLFromContent().
GetSignatureBlock()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.TemplateService.GetSignatureBlock (string position) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ITemplateService.
Definition at line 92 of file TemplateService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ServiceModel.ServiceResult< T >.Data, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.AmazonS3Service.DownloadHTMLFromContent(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ServiceModel.ServiceResult< T >.ErrorMessage.
GetSingleByTemplateId()
async Task< ServiceResult< TemplateVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.TemplateService.GetSingleByTemplateId (string templateId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.ITemplateService.
Definition at line 55 of file TemplateService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Template, TemplateVM >.configuration, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Template, TemplateVM >.logger, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Parse(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Template, TemplateVM >.Single().
Property Documentation
AmazonS3Service
IAmazonS3Service Deluxe.DeluxeBrandCenter.AMM.API.Services.TemplateService.AmazonS3Service get set
Definition at line 32 of file TemplateService.cs.
The documentation for this class was generated from the following file:
Source/API/Services/TemplateService.cs