AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService Class Reference
Public Member Functions
ContactManagerService (IMindfireService mindfireService, IMapper mapper, ApplicationDbContext dbContext, IStateService stateService, IAmazonS3Service amazonS3Service, IConfiguration configuration, ILogger< ContactManagerService > logger, IRedTailService redTailService, ISalesforceService salesForceService, ISessionService sessionService, ISocialNetworkService socialNetworkService, IDBCService dbcService)
async Task< ServiceResult< IEnumerable< ContactVM > > > CreateContactMF (List< ContactVM > contactVMList)
async Task< ServiceResult< IEnumerable< ContactVM > > > GetContacts (SegmentationFilter filter=null, List< string > fields=null, string filterString=null, bool allContacts=false)
Get filtered List of Contacts.
async Task< ServiceResult< ContactVM > > GetContact (string accountId)
async Task< ServiceResult< IEnumerable< ContactVM > > > UpdateContactMF (List< ContactVM > contactVMList, bool doDelete=false)
Updates ContactList.
async Task< ServiceResult< PaginatedContactsVM > > GetPaginatedContacts (ContactFilterVM contactFilter, bool countContacts=false, int contactId=0)
Get Paginated Contacts. Exclusion of Unsubscribed and PersonaContacts are added to filter prior to MF API call.
async Task< ServiceResult< IPaginate< AssociatedGroupVM > > > GetContactAssociatedGroups (AssociatedGroupsFilterVM associatedGroupsFilterVM)
async Task< ServiceResult< ContactCSVTable > > GetContactsCSVTable (string filter, List< string > fields=null, bool allContacts=false)
async Task< ServiceResult< int > > CountContacts (SegmentationFilter filter)
Count Contacts except unsubscribed and Persona Contacts.
async Task< ServiceResult< ContactMapingVM > > GetColumnNames (IFormFile file)
async Task< ServiceResult< UploadContactsResponse > > UploadContacts (UploadContactsVM uploadContactsVM, string source)
ServiceResult< ContactGroupVM[]> GetContactGroupDB ()
Get Group from DB.
async Task< ServiceResult< IPaginate< ContactGroupVM > > > GetGroups (FilterConfiguration filterConfiguration)
Get paginated list of groups.
async Task< ServiceResult< ContactGroupVM > > GetGroup (int groupId, IDictionary< string, IEnumerable< string > > filterOut=null, bool doGetSimpleContacts=true)
async Task< ServiceResult< ContactGroupVM > > DeleteGroup (int groupId)
async Task< ServiceResult< ContactGroupVM > > AddOrUpdateContactGroup (ContactGroupVM contactGroupVM)
async Task< ServiceResult< ContactGroupVM > > RemoveContactFromGroup (ContactForRemoveFromGroupVM contactForRemoveFromGroupVM)
async Task< ServiceResult< IEnumerable< GroupCreationOption > > > GenerateGroupCreationOptions (List< string > fields)
ServiceResult< ContactGroupVM > AddManualContacts (ContactGroupVM contactGroupVM)
async Task< ServiceResult< ContactGroup > > AddOrUpdateGroupDb (ContactGroupVM contactGroupVM, string migrationUserId="")
async Task< ServiceResult< byte[]> > DownloadGroupContactsCSV (int groupId)
async Task< ServiceResult< IPaginate< ContactVM > > > GetGroupContactsPaginated (GetGroupContacts getGroupContacts)
async Task< ServiceResult< string[]> > GetTagNames ()
Get all tag Names from MF.
async Task< ServiceResult< IPaginate< ContactTagVM > > > GetTags (FilterConfiguration filterConfiguration)
Get list of Tags (UserId, Tag name and number of contacts associated with that tag)
async Task< ServiceResult< ContactTagVM > > DeleteTag (int tagId)
async Task< ServiceResult< ContactTagVM > > AddOrUpdateTag (ContactTagVM contactTagVM)
async Task< ServiceResult< IPaginate< UnsubscribedContact > > > GetUnsubscribedContactsPaginated (FilterConfiguration filterConfiguration)
async Task< ServiceResult< IEnumerable< UnsubscribedContact > > > GetUnsubscribedContacts ()
async Task< ServiceResult< IEnumerable< int > > > GetUnsubscribedContactsId ()
async Task< ServiceResult< IDictionary< string, IEnumerable< string > > > > GetContactsForFilteringOut ()
async Task< ServiceResult< byte[]> > DownloadCSV (SegmentationFilter segmentationFilter=null, bool allContacts=false)
ServiceResult< byte[]> DownloadTagsCSV ()
async Task< ServiceResult< byte[]> > DownloadUnsubscribedContactsCSV ()
async Task< ServiceResult< IEnumerable< MyContactActivity > > > GetLastActivities (ContactActivitiesVM contactActivitiesVM)
async Task< ServiceResult< bool > > DisconnectRedTail (string userId)
async Task< ServiceResult< IEnumerable< SelectListItem > > > RedtailLogin (string username, string password)
async Task< ServiceResult< IEnumerable< SelectListItem > > > GetRedtailTagGroups ()
async Task< ServiceResult< IEnumerable< ContactVM > > > GetRedtailTagGroup (RedTailTagGroupVM redTailTagGroup)
async Task< ServiceResult< UploadContactsResponse > > UploadRedTailContacts (UploadContactsRT uploadContactsRT)
string GetSFCallbackURL ()
async Task< ServiceResult< bool > > DisconnectSalesforce (string userId)
async Task< ServiceResult< bool > > SFAuthenticte (string code)
async Task< ServiceResult< IEnumerable< ContactImportAdminVM > > > GetSFContacts (SalesForceGetContactInput salesForceGetContactInput)
async Task< ServiceResult< IEnumerable< ContactImportAdminVM > > > GetSFLeads (SalesForceGetContactInput salesForceGetContactInput)
async Task< ServiceResult< IEnumerable< SalesForceCustomFieldAdminVM > > > SalesForceInit ()
async Task< ServiceResult< UploadContactsResponse > > UploadSaleForceContacts (UploadContactsSFVM uploadContactsSFVM)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >
DBService ()
DBService (IMapper mapper, IApplicationDbContext dbContext, IConfiguration configuration, ILogger< DBService< TModel, TModelVM > > logger, ISocialNetworkService socialNetworkService, ISessionService sessionService)
virtual async Task< string > UpdateSocialURLs (PMSPersonaDTO personalInfo)
virtual async Task< ServiceResult< TModelVM > > Delete (int id)
virtual async Task< ServiceResult< TModel > > Entity (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
virtual async Task< ServiceResult< TModelVM > > Single (int id)
virtual async Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
virtual async Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate, int clientId)
virtual async Task< ServiceResult< List< TModelVM > > > GetList ()
virtual async Task< ServiceResult< List< TModelVM > > > GetList (Expression< Func< TModel, bool > > predicate=null, Expression< Func< TModel, object > > orderBy=null, bool descending=false, bool disableTracking=false, string[] navigationPaths=null, bool clientSide=false, params Expression< Func< TModel, object > >[] include)
virtual async Task< ServiceResult< TModelVM > > Update (TModelVM entity)
virtual async Task< ServiceResult< TModel > > UpdateEntity (TModel entity)
virtual async Task< bool > DoesExist< TModelCheck > (int id)
virtual void FillHtmlWithPersonalInfo (ref string htmlContent, PMSPersonaDTO personalInfo, List< KeyValuePair< string, string > > editorFields=null, int? clientId=0, bool preview=false)
virtual void FillHtmlContent (ref string htmlContent, PMSPersonaDTO personalInfo, SignatureBlockVM signatureBlock, string insideMessage=null, List< KeyValuePair< string, string > > editorFields=null, bool preview=false)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< Contact, ContactVM >
Task< ServiceResult< TModelVM > > Single (int id)
Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate, int clientId)
Task< ServiceResult< TModel > > Entity (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
Task< ServiceResult< List< TModelVM > > > GetList ()
Task< ServiceResult< List< TModelVM > > > GetList (Expression< Func< TModel, bool > > predicate=null, Expression< Func< TModel, object > > orderBy=null, bool descending=false, bool disableTracking=true, string[] navigationPaths=null, bool clientSide=false, params Expression< Func< TModel, object > >[] include)
Task< ServiceResult< TModelVM > > Delete (int id)
Task< ServiceResult< TModel > > UpdateEntity (TModel entity)
Task< ServiceResult< TModelVM > > Update (TModelVM entity)
Task< string > UpdateSocialURLs (PMSPersonaDTO personalInfo)
void FillHtmlWithPersonalInfo (ref string htmlContent, PMSPersonaDTO personalInfo, List< KeyValuePair< string, string > > editorFields=null, int? clientId=0, bool preview=false)
void FillHtmlContent (ref string htmlContent, PMSPersonaDTO personalInfo, SignatureBlockVM signatureBlock, string insideMessage=null, List< KeyValuePair< string, string > > editorFields=null, bool preview=false)
Properties
string RowSeparator [get, set]
string FieldSeparator [get, set]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >
IApplicationDbContext dbContext [get, set]
IMapper mapper [get, set]
IConfiguration configuration [get, set]
ILogger< DBService< TModel, TModelVM > > logger [get]
string Client [get]
int? ClientId [get]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< Contact, ContactVM >
IApplicationDbContext dbContext [get, set]
IMapper mapper [get, set]
ILogger< DBService< TModel, TModelVM > > logger [get]
Private Member Functions
async Task< AssociatedGroupVM > IsContactInGroup (ContactGroupVM contactGroupVM, string accountId)
async Task< ServiceResult< Tuple< IEnumerable< ContactVM >, List< string > > > > MFGetTags ()
async Task FilterOutContacts (SegmentationFilter filter, IDictionary< string, IEnumerable< string > > filterOut=null)
Updates filter to exclude Unsubscribed and Ppersona Contacts.
async Task< ServiceResult< string > > GetErrorCSV (ContactCSVTable csvTable, string originalCSV)
ServiceResult< string > FormatCSV (ContactCSVTable csvTable, string source)
async Task< ServiceResult< string > > AddGroupsAndTagsToDb (ContactCSVTable csvTable)
async Task<(string, string)> SetTagName (ContactTagVM contactTag)
async Task< ServiceResult< ContactTag > > AddOrUpdateTagDb (ContactTagVM contactTagVM)
async Task< ServiceResult< ContactGroupVM > > UpdateContactsCollectionField (UploadFieldType uploadFieldType, string filter, CollectionField field, string newValue, string oldValue)
ServiceResult< SegmentationFilter > FormatFilter (SegmentationFilter segmentationFilter)
async Task FillContactInfoErrors (List< ContactVM > contactVMs, string rtUsername, string rtPassword, int limit)
async Task GetContactInfoAsync (List< ContactVM > contactVMs, string contactId, string rtUsername, string rtPassword)
Static Private Member Functions
static string GetSortExpressionString (IEnumerable< SortByConfiguration > sortByConfiguration)
static SegmentationFilter getManuallyAddedContactsFilter (SegmentationFilter filter)
static SegmentationFilter removeManuallyAdedContactsFromFilter (SegmentationFilter groupFilter)
static void SetAddresses (IEnumerable< ContactImportAdminVM > contactImprtList)
Private Attributes
readonly IMindfireService _mindfireService
readonly IStateService _stateService
readonly IAmazonS3Service _amazonS3Service
readonly IRedTailService _redTailService
readonly ISalesforceService _salesForceService
readonly IDBCService _dbcService
Additional Inherited Members
Public Attributes inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >
ISocialNetworkService _socialNetworkService
ISessionService _sessionService
Protected Attributes inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >
readonly DbSet< TModel > _dbSet
Detailed Description
Definition at line 96 of file ContactManagerService.cs.
Constructor & Destructor Documentation
ContactManagerService()
Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.ContactManagerService (IMindfireService mindfireService, IMapper mapper, ApplicationDbContext dbContext, IStateService stateService, IAmazonS3Service amazonS3Service, IConfiguration configuration, ILogger< ContactManagerService > logger, IRedTailService redTailService, ISalesforceService salesForceService, ISessionService sessionService, ISocialNetworkService socialNetworkService, IDBCService dbcService) inline
Definition at line 113 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._dbcService, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._redTailService, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._salesForceService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._stateService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.configuration, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FieldSeparator, and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.RowSeparator.
Member Function Documentation
AddGroupsAndTagsToDb()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddGroupsAndTagsToDb (ContactCSVTable csvTable) inline private
Definition at line 1293 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddOrUpdateTagDb(), Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.Column(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactTags, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.Domain.Table< T >.GetColumnNo(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts().
AddManualContacts()
ServiceResult< ContactGroupVM > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddManualContacts (ContactGroupVM contactGroupVM) inline
Parameters
contactGroupVM
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 1764 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.GenerateFilterCriteria(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.ContactGroupVM.SegmentationFilter, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.ContactGroupVM.SimpleContacts.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddOrUpdateGroupDb().
AddOrUpdateContactGroup()
async Task< ServiceResult< ContactGroupVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddOrUpdateContactGroup (ContactGroupVM contactGroupVM) inline
Parameters
contactGroupVM
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 1648 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddOrUpdateGroupDb(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.mapper, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.SaveChangesAsync().
AddOrUpdateGroupDb()
async Task< ServiceResult< ContactGroup > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddOrUpdateGroupDb (ContactGroupVM contactGroupVM, string migrationUserId = "") inline
Parameters
contactGroupVM
migrationUserId
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 1822 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddManualContacts(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactGroups, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityVM.Id, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityNamedVM.Name, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.ContactGroupVM.SegmentationFilter, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUserId().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddOrUpdateContactGroup().
AddOrUpdateTag()
async Task< ServiceResult< ContactTagVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddOrUpdateTag (ContactTagVM contactTagVM) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2092 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddOrUpdateTagDb(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.GenerateEqualFilter(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.mapper, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityNamedVM.Name, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.SaveChangesAsync(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientName(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.SetTagName(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UpdateContactsCollectionField(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityVM.Validate().
AddOrUpdateTagDb()
async Task< ServiceResult< ContactTag > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddOrUpdateTagDb (ContactTagVM contactTagVM) inline private
Definition at line 2149 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactTags, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.BaseEntity.Enabled, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityVM.Enabled, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityVM.Id, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.BaseEntityNamed.Name, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityNamedVM.Name, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.SaveChangesAsync(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddGroupsAndTagsToDb(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddOrUpdateTag().
CountContacts()
async Task< ServiceResult< int > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.CountContacts (SegmentationFilter filter) inline
Count Contacts except unsubscribed and Persona Contacts.
Parameters
filter
Returns
Contacts count
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 545 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.contactService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FilterOutContacts().
CreateContactMF()
async Task< ServiceResult< IEnumerable< ContactVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.CreateContactMF (List< ContactVM > contactVMList) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 141 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.contactService, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContacts(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.HashHelper.GetHashCode(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientName().
DeleteGroup()
async Task< ServiceResult< ContactGroupVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DeleteGroup (int groupId) inline
Parameters
groupId
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 1630 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactGroups, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.mapper, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.SaveChanges(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser().
DeleteTag()
async Task< ServiceResult< ContactTagVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DeleteTag (int tagId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2067 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactTags, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterHelper.GenerateEqualFilter(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.mapper, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.SaveChanges(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UpdateContactsCollectionField().
DisconnectRedTail()
async Task< ServiceResult< bool > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DisconnectRedTail (string userId) inline
Parameters
userId
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2515 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.SaveChangesAsync(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.Users.
DisconnectSalesforce()
async Task< ServiceResult< bool > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DisconnectSalesforce (string userId) inline
Parameters
userId
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2795 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.SaveChangesAsync(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.Session, Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetSFApiVersion(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetSFAuthToken(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetSFInstance(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetSFRefreshToken(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.Users.
DownloadCSV()
async Task< ServiceResult< byte[]> > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadCSV (SegmentationFilter segmentationFilter = null, bool allContacts = false) inline
Parameters
segmentationFilter
allContacts
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2298 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper.CreateFromContactList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FieldSeparator, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatFilter(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactsCSVTable(), Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetPropertyNames(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.RowSeparator, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientName().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadGroupContactsCSV().
DownloadGroupContactsCSV()
async Task< ServiceResult< byte[]> > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadGroupContactsCSV (int groupId) inline
Parameters
groupId
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 1874 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactGroups, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper.CreateFromContactList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FieldSeparator, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.mapper, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.RowSeparator, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser().
DownloadTagsCSV()
ServiceResult< byte[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadTagsCSV () inline
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2376 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactTags, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser().
DownloadUnsubscribedContactsCSV()
async Task< ServiceResult< byte[]> > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadUnsubscribedContactsCSV () inline
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2393 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetUnsubscribedContacts().
FillContactInfoErrors()
async Task Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FillContactInfoErrors (List< ContactVM > contactVMs, string rtUsername, string rtPassword, int limit) inline private
Parameters
contactVMs
rtUsername
rtPassword
limit
Returns
Definition at line 2608 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactInfoAsync().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetRedtailTagGroup().
FilterOutContacts()
async Task Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FilterOutContacts (SegmentationFilter filter, IDictionary< string, IEnumerable< string > > filterOut = null) inline private
Updates filter to exclude Unsubscribed and Ppersona Contacts.
Parameters
filter
Returns
Exceptions
Exception
Definition at line 564 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.CriteriaJoinOperator, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactsForFilteringOut(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.CountContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactsCSVTable(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroup(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetPaginatedContacts().
FormatCSV()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatCSV (ContactCSVTable csvTable, string source) inline private
Definition at line 1222 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._stateService, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.CheckImportType(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.FormatDateFields(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IStateService.GetStates(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ImportContactsType, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ReplaceHeader(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientName(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetAccountId(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetDateField(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetSource(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.SetStateField().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts().
FormatFilter()
ServiceResult< SegmentationFilter > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatFilter (SegmentationFilter segmentationFilter) inline private
Parameters
segmentationFilter
Returns
Definition at line 2494 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactGroupDB().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadCSV(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetPaginatedContacts().
GenerateGroupCreationOptions()
async Task< ServiceResult< IEnumerable< GroupCreationOption > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GenerateGroupCreationOptions (List< string > fields) inline
Parameters
fields
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 1706 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._stateService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactGroups, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactTags, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactsCSVTable(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IStateService.GetStates(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser().
GetColumnNames()
async Task< ServiceResult< ContactMapingVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetColumnNames (IFormFile file) inline
Parameters
file
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 882 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.configuration, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FieldSeparator, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetPropertyNames(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper.ReadCSVFromFile(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.RowSeparator, Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientName(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.UploadCSV(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper.Validate(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper.ValidateFile().
GetContact()
async Task< ServiceResult< ContactVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContact (string accountId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 218 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.GenerateFilterCriteria(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactsCSVTable(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger.
GetContactAssociatedGroups()
async Task< ServiceResult< IPaginate< AssociatedGroupVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactAssociatedGroups (AssociatedGroupsFilterVM associatedGroupsFilterVM) inline
Parameters
associatedGroupsFilterVM
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 400 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactGroups, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.IsContactInGroup(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.mapper, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUserId().
GetContactGroupDB()
ServiceResult< ContactGroupVM[]> Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactGroupDB () inline
Get Group from DB.
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 1322 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactGroups, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.mapper, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatFilter().
GetContactInfoAsync()
async Task Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactInfoAsync (List< ContactVM > contactVMs, string contactId, string rtUsername, string rtPassword) inline private
Parameters
contactVMs
contactId
rtUsername
rtPassword
Returns
Definition at line 2651 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._redTailService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.HashHelper.GetHashCode(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.RedTail.IRedTailService.PullRedtailContact(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientName().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FillContactInfoErrors(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetRedtailTagGroup().
GetContacts()
async Task< ServiceResult< IEnumerable< ContactVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContacts (SegmentationFilter filter = null, List< string > fields = null, string filterString = null, bool allContacts = false) inline
Get filtered List of Contacts.
Parameters
filter
fields
filterString
allContacts
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 200 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactsCSVTable(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.CreateContactMF(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroups(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.MFGetTags().
GetContactsCSVTable()
async Task< ServiceResult< ContactCSVTable > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactsCSVTable (string filter, List< string > fields = null, bool allContacts = false) inline
Parameters
filter
fields
allContacts
Returns
Definition at line 487 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.contactService, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FieldSeparator, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FilterOutContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.RowSeparator.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GenerateGroupCreationOptions(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContact(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UpdateContactsCollectionField(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts().
GetContactsForFilteringOut()
async Task< ServiceResult< IDictionary< string, IEnumerable< string > > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactsForFilteringOut () inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2270 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.configuration, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetUnsubscribedContactsId(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FilterOutContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroup(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroups().
GetErrorCSV()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetErrorCSV (ContactCSVTable csvTable, string originalCSV) inline private
Definition at line 1203 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.ErrorLog, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.GetErrorRows(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.UploadBadCSV().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts().
GetGroup()
async Task< ServiceResult< ContactGroupVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroup (int groupId, IDictionary< string, IEnumerable< string > > filterOut = null, bool doGetSimpleContacts = true) inline
Parameters
groupId
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 1495 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactGroups, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.GetContactsByPageResponse.ContactsCsv, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.contactService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FilterOutContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactsForFilteringOut(), Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.GetErrorMessage, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.getManuallyAddedContactsFilter(), Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.Result.HasErrorMessage, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.removeManuallyAdedContactsFromFilter(), Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.GetContactsByPageResponse.Result, Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientName(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroups().
GetGroupContactsPaginated()
async Task< ServiceResult< IPaginate< ContactVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroupContactsPaginated (GetGroupContacts getGroupContacts) inline
Parameters
getGroupContacts
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 1902 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactGroups, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetPaginatedContacts(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.GetGroupContacts.GroupId, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.mapper, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.FilterConfiguration.SearchConfiguration, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.SegmentationFilter(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.FilterConfiguration.SortByConfiguration.
GetGroups()
async Task< ServiceResult< IPaginate< ContactGroupVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroups (FilterConfiguration filterConfiguration) inline
Get paginated list of groups.
Parameters
filterConfiguration
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 1333 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.configuration, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactGroups, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactsForFilteringOut(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroup(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.PaginateConfiguration.Index, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.mapper, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.FilterConfiguration.PaginateConfiguration, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.FilterConfiguration.SearchConfiguration, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.SearchConfigurationMultiple.SearchFields, Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.PaginateConfiguration.Size, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.FilterConfiguration.SortByConfiguration.
GetLastActivities()
async Task< ServiceResult< IEnumerable< MyContactActivity > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetLastActivities (ContactActivitiesVM contactActivitiesVM) inline
Parameters
contactActivitiesVM
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2473 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.contactService, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.ContactActivitiesVM.ContactVM, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.ContactActivitiesVM.DateFrom, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.ContactActivitiesVM.DateTo, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FieldSeparator, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityVM.Id, and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.RowSeparator.
getManuallyAddedContactsFilter()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.getManuallyAddedContactsFilter (SegmentationFilter filter) inline static private
Definition at line 1460 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroup(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.removeManuallyAdedContactsFromFilter().
GetPaginatedContacts()
async Task< ServiceResult< PaginatedContactsVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetPaginatedContacts (ContactFilterVM contactFilter, bool countContacts = false, int contactId = 0) inline
Get Paginated Contacts. Exclusion of Unsubscribed and PersonaContacts are added to filter prior to MF API call.
Parameters
contactFilter
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 271 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.contactService, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.CriteriaJoinOperator, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FilterOutContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatFilter(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSortExpressionString(), Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.PaginateConfiguration.Index, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.FilterConfiguration.PaginateConfiguration, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.ContactFilterVM.SegmentationFilter, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.ContactFilterVM.SegmentationFilterString, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.PaginateConfiguration.Size, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.PaginatedContactsVM.size, and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.FilterConfiguration.SortByConfiguration.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroupContactsPaginated().
GetRedtailTagGroup()
async Task< ServiceResult< IEnumerable< ContactVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetRedtailTagGroup (RedTailTagGroupVM redTailTagGroup) inline
Parameters
redTailTagGroup
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2564 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._redTailService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.configuration, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FillContactInfoErrors(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactInfoAsync(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.RedTail.IRedTailService.PullRedtailTagGroup(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.RedTailTagGroupVM.TagGroup.
GetRedtailTagGroups()
async Task< ServiceResult< IEnumerable< SelectListItem > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetRedtailTagGroups () inline
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2554 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._redTailService, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.RedTail.IRedTailService.PullRedtailTagGroups().
GetSFCallbackURL()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSFCallbackURL () inline
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2779 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._salesForceService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService.callbackUrl, and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.configuration.
GetSFContacts()
async Task< ServiceResult< IEnumerable< ContactImportAdminVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSFContacts (SalesForceGetContactInput salesForceGetContactInput) inline
Parameters
salesForceGetContactInput
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2889 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._salesForceService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService.GetGetSalesForceContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.mapper, Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetSFApiVersion(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetSFAuthToken(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetSFInstance(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.SetAddresses().
GetSFLeads()
async Task< ServiceResult< IEnumerable< ContactImportAdminVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSFLeads (SalesForceGetContactInput salesForceGetContactInput) inline
Parameters
salesForceGetContactInput
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2906 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._salesForceService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService.GetSalesForceLeads(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.mapper, Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetSFApiVersion(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetSFAuthToken(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetSFInstance().
GetSortExpressionString()
static string Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSortExpressionString (IEnumerable< SortByConfiguration > sortByConfiguration) inline static private
Definition at line 374 of file ContactManagerService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetPaginatedContacts().
GetTagNames()
async Task< ServiceResult< string[]> > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetTagNames () inline
Get all tag Names from MF.
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 1961 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.MFGetTags().
GetTags()
async Task< ServiceResult< IPaginate< ContactTagVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetTags (FilterConfiguration filterConfiguration) inline
Get list of Tags (UserId, Tag name and number of contacts associated with that tag)
Parameters
filterConfiguration
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 1977 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.ClientId, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactTags, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.mapper, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.MFGetTags(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.SaveChangesAsync(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser().
GetUnsubscribedContacts()
async Task< ServiceResult< IEnumerable< UnsubscribedContact > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetUnsubscribedContacts () inline
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2228 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.reportService, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadUnsubscribedContactsCSV(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetUnsubscribedContactsPaginated().
GetUnsubscribedContactsId()
async Task< ServiceResult< IEnumerable< int > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetUnsubscribedContactsId () inline
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2251 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.reportService, and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactsForFilteringOut().
GetUnsubscribedContactsPaginated()
async Task< ServiceResult< IPaginate< UnsubscribedContact > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetUnsubscribedContactsPaginated (FilterConfiguration filterConfiguration) inline
Parameters
filterConfiguration
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2213 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetUnsubscribedContacts(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger.
IsContactInGroup()
async Task< AssociatedGroupVM > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.IsContactInGroup (ContactGroupVM contactGroupVM, string accountId) inline private
Definition at line 445 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.contactService, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.AssociatedGroupVM.GenerateContactIsInGroup(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.ContactGroupVM.SegmentationFilter.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactAssociatedGroups().
MFGetTags()
async Task< ServiceResult< Tuple< IEnumerable< ContactVM >, List< string > > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.MFGetTags () inline private
Definition at line 510 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContacts(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetTagNames(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetTags().
RedtailLogin()
async Task< ServiceResult< IEnumerable< SelectListItem > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.RedtailLogin (string username, string password) inline
Parameters
username
password
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2535 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._redTailService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.RedTail.IRedTailService.PullRedtailTagGroups(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.SaveChangesAsync(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser().
RemoveContactFromGroup()
async Task< ServiceResult< ContactGroupVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.RemoveContactFromGroup (ContactForRemoveFromGroupVM contactForRemoveFromGroupVM) inline
Parameters
contactForRemoveFromGroupVM
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 1665 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.AccountID, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactGroups, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactForRemoveFromGroupVM.ContactGroupVM, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactForRemoveFromGroupVM.ContactVM, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityVM.Id, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.mapper, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.SaveChanges().
removeManuallyAdedContactsFromFilter()
static SegmentationFilter Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.removeManuallyAdedContactsFromFilter (SegmentationFilter groupFilter) inline static private
Definition at line 1608 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.getManuallyAddedContactsFilter().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroup().
SalesForceInit()
async Task< ServiceResult< IEnumerable< SalesForceCustomFieldAdminVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.SalesForceInit () inline
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2921 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._salesForceService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService.GetCustomFieldsAdmin(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetSFApiVersion(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetSFAuthToken(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetSFInstance().
SetAddresses()
static void Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.SetAddresses (IEnumerable< ContactImportAdminVM > contactImprtList) inline static private
Parameters
contactImprtList
Definition at line 2864 of file ContactManagerService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSFContacts().
SetTagName()
async Task<(string, string)> Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.SetTagName (ContactTagVM contactTag) inline private
Definition at line 2131 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactTags, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityVM.Id, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityNamedVM.Name.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddOrUpdateTag().
SFAuthenticte()
async Task< ServiceResult< bool > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.SFAuthenticte (string code) inline
Parameters
code
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2826 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._salesForceService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Salesforce.ISalesforceService.Authenticate(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.SaveChangesAsync(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.Session, Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUserId(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.Users.
UpdateContactMF()
async Task< ServiceResult< IEnumerable< ContactVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UpdateContactMF (List< ContactVM > contactVMList, bool doDelete = false) inline
Updates ContactList.
Parameters
contactVMList
delete
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 244 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.contactService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger.
UpdateContactsCollectionField()
async Task< ServiceResult< ContactGroupVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UpdateContactsCollectionField (UploadFieldType uploadFieldType, string filter, CollectionField field, string newValue, string oldValue) inline private
Parameters
uploadFieldType
filter
field
newValue
oldValue
Returns
Definition at line 2422 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._dbcService, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.contactService, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactsCSVTable(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBCService.GetUser(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper.ResponseValidation(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUserId().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddOrUpdateTag(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DeleteTag().
UploadContacts()
async Task< ServiceResult< UploadContactsResponse > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts (UploadContactsVM uploadContactsVM, string source) inline
Parameters
uploadContactsVM
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 1015 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._dbcService, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddGroupsAndTagsToDb(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.configuration, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.contactService, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.UploadContactsVM.CSV, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DeleteFile(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadString(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FieldSeparator, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.UploadContactsVM.FileName, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactsCSVTable(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetErrorCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBCService.GetUser(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.UploadContactsVM.ImportContactsType, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.logger, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.UploadContactsVM.Mapping, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.RowSeparator, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.SaveChangesAsync(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientName(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetMaxContacts(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadRedTailContacts(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadSaleForceContacts().
UploadRedTailContacts()
async Task< ServiceResult< UploadContactsResponse > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadRedTailContacts (UploadContactsRT uploadContactsRT) inline
Parameters
uploadContactsRT
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2739 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactTags, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper.CreateFromContactList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FieldSeparator, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.RowSeparator, and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts().
UploadSaleForceContacts()
async Task< ServiceResult< UploadContactsResponse > > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadSaleForceContacts (UploadContactsSFVM uploadContactsSFVM) inline
Parameters
uploadContactsSFVM
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IContactManagerService.
Definition at line 2936 of file ContactManagerService.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.ContactTags, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper.CreateFromContactList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FieldSeparator, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< Contact, ContactVM >.mapper, Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.RowSeparator, and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts().
Member Data Documentation
_amazonS3Service
readonly IAmazonS3Service Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._amazonS3Service private
Definition at line 100 of file ContactManagerService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.ContactManagerService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetColumnNames(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetErrorCSV(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts().
_dbcService
readonly IDBCService Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._dbcService private
Definition at line 103 of file ContactManagerService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.ContactManagerService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UpdateContactsCollectionField(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts().
_mindfireService
readonly IMindfireService Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._mindfireService private
Definition at line 98 of file ContactManagerService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.ContactManagerService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.CountContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.CreateContactMF(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactsCSVTable(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroup(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetLastActivities(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetPaginatedContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetUnsubscribedContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetUnsubscribedContactsId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.IsContactInGroup(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UpdateContactMF(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UpdateContactsCollectionField(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts().
_redTailService
readonly IRedTailService Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._redTailService private
Definition at line 101 of file ContactManagerService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.ContactManagerService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactInfoAsync(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetRedtailTagGroup(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetRedtailTagGroups(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.RedtailLogin().
_salesForceService
readonly ISalesforceService Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._salesForceService private
Definition at line 102 of file ContactManagerService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.ContactManagerService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSFCallbackURL(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSFContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSFLeads(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.SalesForceInit(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.SFAuthenticte().
_stateService
readonly IStateService Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService._stateService private
Definition at line 99 of file ContactManagerService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.ContactManagerService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatCSV(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GenerateGroupCreationOptions().
Property Documentation
FieldSeparator
string Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FieldSeparator get set
Definition at line 109 of file ContactManagerService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.ContactManagerService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadGroupContactsCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetColumnNames(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactsCSVTable(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetLastActivities(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadRedTailContacts(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadSaleForceContacts().
RowSeparator
string Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.RowSeparator get set
Definition at line 105 of file ContactManagerService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.ContactManagerService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadGroupContactsCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetColumnNames(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactsCSVTable(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetLastActivities(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadRedTailContacts(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadSaleForceContacts().
The documentation for this class was generated from the following file:
Source/API/Services/ContactManager/ContactManagerService.cs