AMM: Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController Class Reference
Account Controller.
Public Member Functions
AccountController (IConfiguration configuration, IAccountService accountService, ISessionService sessionService)
Account Controller Constructor.
async Task< ControllerResult< LoginResponseVM > > SSOSignIn (string repId, string clientName, string userId, bool admin)
SSO SignIn endpoint (clientName used instead of clientId.
async Task< ControllerResult< IsRegisteredVM > > IsRegistered ([FromQuery] string userId)
ControllerResult TestGet ()
Used for deployment health-check.
Protected Member Functions
string SessionUserName ()
Currently logedin user name.
Properties
IAccountService service [get]
Account Service.
Private Attributes
readonly IConfiguration _configuration
readonly ISessionService _sessionService
Detailed Description
Account Controller.
Definition at line 25 of file AccountController.cs.
Constructor & Destructor Documentation
AccountController()
Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.AccountController (IConfiguration configuration, IAccountService accountService, ISessionService sessionService) inline
Account Controller Constructor.
Parameters
configuration
accountService Account Service
sessionService Account Service
Returns
Definition at line 34 of file AccountController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController._configuration, Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController._sessionService, and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.service.
Member Function Documentation
IsRegistered()
async Task< ControllerResult< IsRegisteredVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.IsRegistered ([FromQuery] string userId) inline
Parameters
repId
clientName
Returns
Definition at line 129 of file AccountController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.IsRegistered(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.service.
SessionUserName()
string Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.SessionUserName () inline protected
Currently logedin user name.
Returns
Username of the logedin user
Definition at line 44 of file AccountController.cs.
SSOSignIn()
async Task< ControllerResult< LoginResponseVM > > Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.SSOSignIn (string repId, string clientName, string userId, bool admin) inline
SSO SignIn endpoint (clientName used instead of clientId.
Parameters
repId
clientName
userId
admin
Returns
Token and logedIn User details
Definition at line 70 of file AccountController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController._configuration, Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.clientService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IClientService.GetClientByName(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.service, Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SetUserId(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.IAccountService.SSOSignIn().
TestGet()
ControllerResult Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.TestGet () inline
Used for deployment health-check.
Returns
Definition at line 144 of file AccountController.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ControllerResult< T >.Success.
Member Data Documentation
_configuration
readonly IConfiguration Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController._configuration private
Definition at line 49 of file AccountController.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.AccountController(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.SSOSignIn().
_sessionService
readonly ISessionService Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController._sessionService private
Definition at line 59 of file AccountController.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.AccountController(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.SSOSignIn().
Property Documentation
service
IAccountService Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.service get
Account Service.
Definition at line 54 of file AccountController.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.AccountController(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.IsRegistered(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.SSOSignIn().
The documentation for this class was generated from the following file:
Source/API/Controllers/AccountController.cs