AMM: Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM Class Reference
Public Member Functions
ErrorVM (Error error)
async Task WriteTo (HttpResponse response)
Static Public Member Functions
static implicit operator ErrorVM (Error error)
static ErrorVM New (ErrorType type=ErrorType.Unspecified, int additionalFramesToSkip=0)
static ErrorVM New (string message, ErrorType type=ErrorType.Unspecified, int additionalFramesToSkip=0)
static ErrorVM New (Exception exception, ErrorType type=ErrorType.Unspecified)
static ErrorVM From< T > (ServiceResult< T > serviceResult, ErrorType errorType=ErrorType.Unspecified, int additionalFramesToSkip=0)
static ErrorVM From< T > (ApiResponse< T > apiResponse, ErrorType errorType=ErrorType.Unspecified, int additionalFramesToSkip=0)
Properties
int Code [get]
string Type [get]
string Message [get]
string StackTrace [get]
int HttpStatusCode [get]
Detailed Description
Definition at line 14 of file ErrorVM.cs.
Constructor & Destructor Documentation
ErrorVM()
Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.ErrorVM (Error error) inline
Definition at line 48 of file ErrorVM.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.Code, Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.Message, Deluxe.DeluxeBrandCenter.AMM.Domain.Models.Error.Message, Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.StackTrace, Deluxe.DeluxeBrandCenter.AMM.Domain.Models.Error.StackTrace, Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.Type, and Deluxe.DeluxeBrandCenter.AMM.Domain.Models.Error.Type.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.operator ErrorVM().
Member Function Documentation
From< T >() [1/2]
static ErrorVM Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.From< T > (ApiResponse< T > apiResponse, ErrorType errorType = ErrorType::Unspecified, int additionalFramesToSkip = 0) inline static
Definition at line 93 of file ErrorVM.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ControllerModel.ApiResponse< T >.ErrorMessages.
From< T >() [2/2]
static ErrorVM Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.From< T > (ServiceResult< T > serviceResult, ErrorType errorType = ErrorType::Unspecified, int additionalFramesToSkip = 0) inline static
Definition at line 83 of file ErrorVM.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ServiceModel.ServiceResult< T >.ErrorMessage.
New() [1/3]
static ErrorVM Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.New (ErrorType type = ErrorType::Unspecified, int additionalFramesToSkip = 0) inline static
Definition at line 68 of file ErrorVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Middleware.ExceptionMiddleware.Invoke().
New() [2/3]
static ErrorVM Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.New (Exception exception, ErrorType type = ErrorType::Unspecified) inline static
Definition at line 78 of file ErrorVM.cs.
New() [3/3]
static ErrorVM Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.New (string message, ErrorType type = ErrorType::Unspecified, int additionalFramesToSkip = 0) inline static
Definition at line 73 of file ErrorVM.cs.
operator ErrorVM()
static implicit Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.operator ErrorVM (Error error) inline static
Definition at line 63 of file ErrorVM.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.ErrorVM().
WriteTo()
async Task Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.WriteTo (HttpResponse response) inline
Definition at line 56 of file ErrorVM.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.HttpStatusCode.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Middleware.ExceptionMiddleware.Invoke().
Property Documentation
Code
int Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.Code get
Definition at line 16 of file ErrorVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.ErrorVM().
HttpStatusCode
int Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.HttpStatusCode get
Definition at line 37 of file ErrorVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.WriteTo().
Message
string Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.Message get
Definition at line 26 of file ErrorVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.ErrorVM().
StackTrace
string Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.StackTrace get
Definition at line 31 of file ErrorVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.ErrorVM().
Type
string Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.Type get
Definition at line 21 of file ErrorVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Models.ErrorVM.ErrorVM().
The documentation for this class was generated from the following file:
Source/API/Models/ErrorVM.cs