AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< TModel, TModelVM > Class Template Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< TModel, TModelVM > Class Template Reference
Public Member Functions
NamedDbService ()
NamedDbService (IMapper mapper, IApplicationDbContext dbContext, IConfiguration configuration, ILogger< NamedDbService< TModel, TModelVM > > logger, ISocialNetworkService socialNetworkService, ISessionService sessionService)
override async Task< ServiceResult< TModelVM > > Update (TModelVM entityVM)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >
DBService ()
DBService (IMapper mapper, IApplicationDbContext dbContext, IConfiguration configuration, ILogger< DBService< TModel, TModelVM > > logger, ISocialNetworkService socialNetworkService, ISessionService sessionService)
virtual async Task< string > UpdateSocialURLs (PMSPersonaDTO personalInfo)
virtual async Task< ServiceResult< TModelVM > > Delete (int id)
virtual async Task< ServiceResult< TModel > > Entity (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
virtual async Task< ServiceResult< TModelVM > > Single (int id)
virtual async Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
virtual async Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate, int clientId)
virtual async Task< ServiceResult< List< TModelVM > > > GetList ()
virtual async Task< ServiceResult< List< TModelVM > > > GetList (Expression< Func< TModel, bool > > predicate=null, Expression< Func< TModel, object > > orderBy=null, bool descending=false, bool disableTracking=false, string[] navigationPaths=null, bool clientSide=false, params Expression< Func< TModel, object > >[] include)
virtual async Task< ServiceResult< TModel > > UpdateEntity (TModel entity)
virtual async Task< bool > DoesExist< TModelCheck > (int id)
virtual void FillHtmlWithPersonalInfo (ref string htmlContent, PMSPersonaDTO personalInfo, List< KeyValuePair< string, string > > editorFields=null, int? clientId=0, bool preview=false)
virtual void FillHtmlContent (ref string htmlContent, PMSPersonaDTO personalInfo, SignatureBlockVM signatureBlock, string insideMessage=null, List< KeyValuePair< string, string > > editorFields=null, bool preview=false)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >
Additional Inherited Members
Public Attributes inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >
ISocialNetworkService _socialNetworkService
ISessionService _sessionService
Protected Attributes inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >
readonly DbSet< TModel > _dbSet
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >
IApplicationDbContext dbContext [get, set]
IMapper mapper [get, set]
IConfiguration configuration [get, set]
ILogger< DBService< TModel, TModelVM > > logger [get]
string Client [get]
int? ClientId [get]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >
Detailed Description
Type Constraints
TModel : BaseEntityNamed
TModelVM : BaseEntityNamedVM
Definition at line 24 of file NamedDbService.cs.
Constructor & Destructor Documentation
NamedDbService() [1/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< TModel, TModelVM >.NamedDbService () inline
Definition at line 26 of file NamedDbService.cs.
NamedDbService() [2/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< TModel, TModelVM >.NamedDbService (IMapper mapper, IApplicationDbContext dbContext, IConfiguration configuration, ILogger< NamedDbService< TModel, TModelVM > > logger, ISocialNetworkService socialNetworkService, ISessionService sessionService) inline
Definition at line 30 of file NamedDbService.cs.
Member Function Documentation
Update()
override async Task< ServiceResult< TModelVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< TModel, TModelVM >.Update (TModelVM entityVM) inline virtual
Reimplemented from Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.
Definition at line 43 of file NamedDbService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._dbSet, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >._sessionService, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.logger, Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.mapper, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.SaveChanges(), Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single().
The documentation for this class was generated from the following file:
Source/API/Services/NamedDbService.cs