AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF Interface Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF Interface Reference
Public Member Functions
Task< ServiceResult< PublishProgramResponse > > PublishProgram (string programXML)
Task< ServiceResult< PublishProgramResponse > > PublishProgram (RequestCredentials credentials, string programXML)
Task< ServiceResult< UndoProgramChangesResponse > > UndoProgramChanges (int programId)
Task< ServiceResult< UndoProgramChangesResponse > > UndoProgramChanges (RequestCredentials credentials, int programId)
Task< ServiceResult< UndoProgramChangesResponse > > UndoProgramChanges (string ticket, int programId)
Task< ServiceResult< ProgramCheckoutResponse > > CheckOutProgram (int programId)
Task< ServiceResult< ProgramCheckoutResponse > > CheckOutProgram (RequestCredentials credentials, int programId)
Task< ServiceResult< ProgramCheckoutResponse > > CheckOutProgram (string ticket, int programId)
Task< ServiceResult< ProgramCheckinResponse > > CheckInProgram (string programXML)
Task< ServiceResult< ProgramCheckinResponse > > CheckInProgram (RequestCredentials credentials, string programXML, string comment="")
Task< ServiceResult< ProgramCheckinResponse > > CheckInProgram (string ticket, string programXML)
Task< ServiceResult< ProgramCheckinResponse > > CheckInProgram (string ticket, string programXML, string comment="")
Task< ServiceResult< ProgramCheckinResponse > > StopCampaign (int programId, string ticket, string comment)
Task< ServiceResult< GetProgramListResponse > > GetProgramList (RequestCredentials credentials, short status=255)
Task< ServiceResult< GetOutboundsScheduleListResponse > > GetOutboundsScheduleList (List< KeyValuePair< string, string > > outboundList)
Task< ServiceResult< GetProgramInfoResponse > > GetProgramInfo (int programId)
Task< ServiceResult< GetProgramInfoResponse > > GetProgramInfo (string mfTicket, int programId)
Task< ServiceResult< GetProgramResponse > > GetProgram (int programId)
Task< ServiceResult< GetProgramResponse > > GetProgram (string ticket, int programId)
Task< ServiceResult< GetProgramResponse > > GetProgram (RequestCredentials credentials, int programId)
Additional Inherited Members
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IBaseMindfireService
IMindfireSettings configuration [get]
RequestCredentials masterRequestCredentials [get, set]
RequestCredentials userRequestCredentials [get, set]
string ServiceName [get]
Detailed Description
Definition at line 18 of file ProgramServiceMF.cs.
Member Function Documentation
CheckInProgram() [1/4]
Task< ServiceResult< ProgramCheckinResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.CheckInProgram (RequestCredentials credentials, string programXML, string comment = "")
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
CheckInProgram() [2/4]
Task< ServiceResult< ProgramCheckinResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.CheckInProgram (string programXML)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Extensions.IProgramServiceMFExtensions.CheckInProgramResiliently().
CheckInProgram() [3/4]
Task< ServiceResult< ProgramCheckinResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.CheckInProgram (string ticket, string programXML)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
CheckInProgram() [4/4]
Task< ServiceResult< ProgramCheckinResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.CheckInProgram (string ticket, string programXML, string comment = "")
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
CheckOutProgram() [1/3]
Task< ServiceResult< ProgramCheckoutResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.CheckOutProgram (int programId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Extensions.IProgramServiceMFExtensions.CheckOutProgramResiliently().
CheckOutProgram() [2/3]
Task< ServiceResult< ProgramCheckoutResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.CheckOutProgram (RequestCredentials credentials, int programId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
CheckOutProgram() [3/3]
Task< ServiceResult< ProgramCheckoutResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.CheckOutProgram (string ticket, int programId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
GetOutboundsScheduleList()
Task< ServiceResult< GetOutboundsScheduleListResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.GetOutboundsScheduleList (List< KeyValuePair< string, string > > outboundList)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
GetProgram() [1/3]
Task< ServiceResult< GetProgramResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.GetProgram (int programId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Extensions.IProgramServiceMFExtensions.GetProgramResiliently().
GetProgram() [2/3]
Task< ServiceResult< GetProgramResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.GetProgram (RequestCredentials credentials, int programId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
GetProgram() [3/3]
Task< ServiceResult< GetProgramResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.GetProgram (string ticket, int programId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
GetProgramInfo() [1/2]
Task< ServiceResult< GetProgramInfoResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.GetProgramInfo (int programId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
GetProgramInfo() [2/2]
Task< ServiceResult< GetProgramInfoResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.GetProgramInfo (string mfTicket, int programId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
GetProgramList()
Task< ServiceResult< GetProgramListResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.GetProgramList (RequestCredentials credentials, short status = 255)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
PublishProgram() [1/2]
Task< ServiceResult< PublishProgramResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.PublishProgram (RequestCredentials credentials, string programXML)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
PublishProgram() [2/2]
Task< ServiceResult< PublishProgramResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.PublishProgram (string programXML)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
StopCampaign()
Task< ServiceResult< ProgramCheckinResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.StopCampaign (int programId, string ticket, string comment)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
UndoProgramChanges() [1/3]
Task< ServiceResult< UndoProgramChangesResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.UndoProgramChanges (int programId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Extensions.IProgramServiceMFExtensions.CheckInProgramResiliently(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Extensions.IProgramServiceMFExtensions.CheckOutProgramResiliently(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Extensions.IProgramServiceMFExtensions.GetProgramResiliently().
UndoProgramChanges() [2/3]
Task< ServiceResult< UndoProgramChangesResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.UndoProgramChanges (RequestCredentials credentials, int programId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
UndoProgramChanges() [3/3]
Task< ServiceResult< UndoProgramChangesResponse > > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.IProgramServiceMF.UndoProgramChanges (string ticket, int programId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ProgramServiceMF.
The documentation for this interface was generated from the following file:
Source/Infrastructure/Mindfire/ProgramServiceMF.cs