AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService Class Reference
Public Member Functions
UserCampaignService ()
UserCampaignService (IMapper mapper, ApplicationDbContext applicationDbContext, IConfiguration configuration, ILogger< UserCampaignService > logger, IMindfireService mindfireService, IPersonaService personaService, ITemplateService templateService, IAmazonS3Service amazonS3Service, IPersonaMicroservice personaMicroservice, ISignatureBlockService signatureBlockService, ICampaignService campaignService, ISettingsService settingsService, ISocialNetworkService socialNetworkService, ISessionService sessionService)
async Task< ServiceResult< UserCampaignVM > > CampaignDetails (int id)
async Task< ServiceResult< IList< UserCampaignSimpleVM > > > MyCampaigns (string mindfireStatus, bool waitingApproval)
async Task< ServiceResult< UserCampaignVM > > PendingCampaignDetails (int id)
async Task< ServiceResult< IList< UserCampaignSimpleVM > > > PendingCampaigns ()
async Task< ServiceResult< List< OutboundScheduleVM > > > GetOutboundsScheduleListAsync (OutboundFilterVM outboundFilterVM)
async Task< ServiceResult< UserCampaign > > SetOutboundIds (UserCampaign userCampaign)
async Task< ServiceResult< IList< string > > > StopCampaigns (List< int > programIds, ApplicationUser user)
async Task< ServiceResult< UserCampaignVM > > StopCampaign (int programId)
async Task< ServiceResult< UserCampaignVM > > StartCampaign (int programId)
async Task< ServiceResult< IList< string > > > GetBase64Images (IList< string > imageUrls)
async Task< ServiceResult< ICollection< UserCampaign > > > SyncPersonaDataWithMF (string personaInstanceId)
void FillAdvisorContentVariables (PMSPersonaDTO personalInfo, IEnumerable< XElement > contentVariables, XElement contentVariablesXMLElement, bool isForDirectMail=false, int clientId=0, bool hasAlternateAddress=false)
void SetContentVariable (XElement contentVariablesXMLElement, string name, string value, bool htmlEncode=true)
void FillAdvisorColumns (ICollection< XElement > columns, XElement rouleGroup, PMSPersonaDTO personalInf, bool hasAlternateAddress=false)
void NormalizeDMVariablesAndColumns (XElement columns, XElement rouleGroup)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< UserCampaign, UserCampaignVM >
NamedDbService ()
NamedDbService (IMapper mapper, IApplicationDbContext dbContext, IConfiguration configuration, ILogger< NamedDbService< TModel, TModelVM > > logger, ISocialNetworkService socialNetworkService, ISessionService sessionService)
override async Task< ServiceResult< TModelVM > > Update (TModelVM entityVM)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >
Task< ServiceResult< TModelVM > > Single (int id)
Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
Task< ServiceResult< TModelVM > > Single (Expression< Func< TModel, bool > > predicate, int clientId)
Task< ServiceResult< TModel > > Entity (Expression< Func< TModel, bool > > predicate=null, bool disableTracking=false, string[] navigationPaths=null, params Expression< Func< TModel, object > >[] include)
Task< ServiceResult< List< TModelVM > > > GetList ()
Task< ServiceResult< List< TModelVM > > > GetList (Expression< Func< TModel, bool > > predicate=null, Expression< Func< TModel, object > > orderBy=null, bool descending=false, bool disableTracking=true, string[] navigationPaths=null, bool clientSide=false, params Expression< Func< TModel, object > >[] include)
Task< ServiceResult< TModelVM > > Delete (int id)
Task< ServiceResult< TModel > > UpdateEntity (TModel entity)
Task< ServiceResult< TModelVM > > Update (TModelVM entity)
Task< string > UpdateSocialURLs (PMSPersonaDTO personalInfo)
void FillHtmlWithPersonalInfo (ref string htmlContent, PMSPersonaDTO personalInfo, List< KeyValuePair< string, string > > editorFields=null, int? clientId=0, bool preview=false)
void FillHtmlContent (ref string htmlContent, PMSPersonaDTO personalInfo, SignatureBlockVM signatureBlock, string insideMessage=null, List< KeyValuePair< string, string > > editorFields=null, bool preview=false)
Private Member Functions
string ReplaceStageFolder (string url)
async Task< ServiceResult< string > > UpdateLaunchedCampaign (UserCampaign userCampaign, PMSPersonaDTO personaVM)
ServiceResult< string > UpdateMAML (XElement programXML, PMSPersonaDTO personaVM, string signatureBlock, int? clientId)
Static Private Member Functions
static void RefreshSchedule (XElement campaignElement)
static string GetPersonaGuid (XElement maml)
static string getRouleValue (XElement rouleGroup, string name)
Private Attributes
readonly IMindfireService _mindfireService
readonly IPersonaService _personaService
readonly ITemplateService _templateService
readonly IAmazonS3Service _amazonS3Service
readonly IPersonaMicroservice _personaMicroservice
readonly ISignatureBlockService _signatureBlockService
readonly ICampaignService _campaignService
readonly ISettingsService _settingsService
Additional Inherited Members
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >
IApplicationDbContext dbContext [get, set]
IMapper mapper [get, set]
ILogger< DBService< TModel, TModelVM > > logger [get]
Detailed Description
Definition at line 54 of file UserCampaignService.cs.
Constructor & Destructor Documentation
UserCampaignService() [1/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UserCampaignService () inline
Definition at line 66 of file UserCampaignService.cs.
UserCampaignService() [2/2]
Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UserCampaignService (IMapper mapper, ApplicationDbContext applicationDbContext, IConfiguration configuration, ILogger< UserCampaignService > logger, IMindfireService mindfireService, IPersonaService personaService, ITemplateService templateService, IAmazonS3Service amazonS3Service, IPersonaMicroservice personaMicroservice, ISignatureBlockService signatureBlockService, ICampaignService campaignService, ISettingsService settingsService, ISocialNetworkService socialNetworkService, ISessionService sessionService) inline
Definition at line 70 of file UserCampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._campaignService, Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._personaMicroservice, Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._personaService, Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._settingsService, Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._signatureBlockService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._templateService.
Member Function Documentation
CampaignDetails()
async Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.CampaignDetails (int id) inline
Parameters
id
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.
Definition at line 102 of file UserCampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._personaService, Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._signatureBlockService, Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._templateService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.Bucket, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadCampaignTemplate(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadPreviewTemplate(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadString(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadStringHTML(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.FillHtmlContent(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.FillHtmlWithPersonalInfo(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.GetPersonaByGUID(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ITemplateService.GetSingleByTemplateId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.logger, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Parse(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.programService, Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.ReplaceStageFolder(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< TModel, TModelVM >.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.UpdateSocialURLs(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.UploadHtml().
FillAdvisorColumns()
void Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.FillAdvisorColumns (ICollection< XElement > columns, XElement rouleGroup, PMSPersonaDTO personalInf, bool hasAlternateAddress = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.
Definition at line 1529 of file UserCampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.getRouleValue().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UpdateMAML().
FillAdvisorContentVariables()
void Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.FillAdvisorContentVariables (PMSPersonaDTO personalInfo, IEnumerable< XElement > contentVariables, XElement contentVariablesXMLElement, bool isForDirectMail = false, int clientId = 0, bool hasAlternateAddress = false) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.
Definition at line 1312 of file UserCampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.dbContext, Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.SetContentVariable(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.IApplicationDbContext.Settings.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UpdateMAML().
GetBase64Images()
async Task< ServiceResult< IList< string > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.GetBase64Images (IList< string > imageUrls) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.
Definition at line 1101 of file UserCampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._personaMicroservice, and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.ConvertImagesFromUrlToBase64().
GetOutboundsScheduleListAsync()
async Task< ServiceResult< List< OutboundScheduleVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.GetOutboundsScheduleListAsync (OutboundFilterVM outboundFilterVM) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.
Definition at line 496 of file UserCampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.Domain.ServiceModel.ServiceResult< T >.Data, Deluxe.DeluxeBrandCenter.AMM.Domain.ServiceModel.ServiceResult< T >.ErrorMessage, Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.GetList(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.OutboundFilterVM.ProgramIDList, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.programService.
GetPersonaGuid()
static string Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.GetPersonaGuid (XElement maml) inline static private
Definition at line 1236 of file UserCampaignService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UpdateLaunchedCampaign().
getRouleValue()
static string Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.getRouleValue (XElement rouleGroup, string name) inline static private
Definition at line 1733 of file UserCampaignService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.FillAdvisorColumns().
MyCampaigns()
async Task< ServiceResult< IList< UserCampaignSimpleVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.MyCampaigns (string mindfireStatus, bool waitingApproval) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.
Definition at line 346 of file UserCampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._personaMicroservice, Deluxe.DeluxeBrandCenter.AMM.Domain.ServiceModel.ServiceResult< T >.Data, Deluxe.DeluxeBrandCenter.AMM.Domain.ServiceModel.ServiceResult< T >.ErrorMessage, Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.GetList(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.PMS.IPersonaMicroservice.GetUserPersonasType(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.logger.
NormalizeDMVariablesAndColumns()
void Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.NormalizeDMVariablesAndColumns (XElement columns, XElement rouleGroup) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.
Definition at line 1674 of file UserCampaignService.cs.
PendingCampaignDetails()
async Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.PendingCampaignDetails (int id) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.
Definition at line 392 of file UserCampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._amazonS3Service, Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._campaignService, Deluxe.DeluxeBrandCenter.AMM.Infrastructure.AWS.S3.IAmazonS3Service.DownloadCampaignTemplate(), Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.CampaignBuilder.Comment.GetComment(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.logger, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.Single().
PendingCampaigns()
async Task< ServiceResult< IList< UserCampaignSimpleVM > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.PendingCampaigns () inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.
Definition at line 442 of file UserCampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._personaService, Deluxe.DeluxeBrandCenter.AMM.Domain.ServiceModel.ServiceResult< T >.Data, Deluxe.DeluxeBrandCenter.AMM.Domain.ServiceModel.ServiceResult< T >.ErrorMessage, Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.GetList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.logger, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.Single().
RefreshSchedule()
static void Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.RefreshSchedule (XElement campaignElement) inline static private
Parameters
campaignElement
Returns
Definition at line 870 of file UserCampaignService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.StartCampaign().
ReplaceStageFolder()
string Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.ReplaceStageFolder (string url) inline private
Definition at line 1096 of file UserCampaignService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.CampaignDetails().
SetContentVariable()
void Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.SetContentVariable (XElement contentVariablesXMLElement, string name, string value, bool htmlEncode = true) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.
Definition at line 1500 of file UserCampaignService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.FillAdvisorContentVariables(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UpdateMAML().
SetOutboundIds()
async Task< ServiceResult< UserCampaign > > Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.SetOutboundIds (UserCampaign userCampaign) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.
Definition at line 584 of file UserCampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaign.CampaignElements, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaign.ProgramId, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.programService.
StartCampaign()
async Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.StartCampaign (int programId) inline
Parameters
programId
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.
Definition at line 766 of file UserCampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.Entity(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.mapper, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.programService, Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.RefreshSchedule(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.UpdateEntity().
StopCampaign()
async Task< ServiceResult< UserCampaignVM > > Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.StopCampaign (int programId) inline
Parameters
programId
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.
Definition at line 693 of file UserCampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.Entity(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.mapper, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.programService, and Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.UpdateEntity().
StopCampaigns()
async Task< ServiceResult< IList< string > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.StopCampaigns (List< int > programIds, ApplicationUser user) inline
Parameters
programIds
profileId
Returns
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.
Definition at line 623 of file UserCampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.Entity(), Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.ApplicationUser.MFTicket, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.programService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.UpdateEntity(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.userService.
SyncPersonaDataWithMF()
async Task< ServiceResult< ICollection< UserCampaign > > > Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.SyncPersonaDataWithMF (string personaInstanceId) inline
Implements Deluxe.DeluxeBrandCenter.AMM.API.Services.IUserCampaignService.
Definition at line 1107 of file UserCampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._personaService, Deluxe.DeluxeBrandCenter.AMM.API.Services.IPersonaService.GetPersonaByGUID(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.logger, and Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UpdateLaunchedCampaign().
UpdateLaunchedCampaign()
async Task< ServiceResult< string > > Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UpdateLaunchedCampaign (UserCampaign userCampaign, PMSPersonaDTO personaVM) inline private
Definition at line 1151 of file UserCampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._mindfireService, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaign.AlternateAddress, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.AddressInfoVM.City, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.BaseEntity.ClientId, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaign.CustomSettings, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PMSPersonaDTO.Duplicate(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.GetPersonaGuid(), Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.ApplicationUser.MFTicket, Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.JsonHelper.Parse(), Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaign.ProgramId, Deluxe.DeluxeBrandCenter.AMM.API.Services.IMindfireService.programService, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.SignatureBlock.Signature, Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaign.SignatureBlock, Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UpdateMAML(), and Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.UserCampaign.User.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.SyncPersonaDataWithMF().
UpdateMAML()
ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UpdateMAML (XElement programXML, PMSPersonaDTO personaVM, string signatureBlock, int? clientId) inline private
Definition at line 1251 of file UserCampaignService.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._settingsService, Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.PMSPersonaDTO.Data, Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.FillAdvisorColumns(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.FillAdvisorContentVariables(), Deluxe.DeluxeBrandCenter.AMM.API.Services.IDBService< UserCampaign, UserCampaignVM >.FillHtmlWithPersonalInfo(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.SetContentVariable(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ISettingsService.SingleByName().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UpdateLaunchedCampaign().
Member Data Documentation
_amazonS3Service
readonly IAmazonS3Service Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._amazonS3Service private
Definition at line 60 of file UserCampaignService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.CampaignDetails(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.PendingCampaignDetails(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UserCampaignService().
_campaignService
readonly ICampaignService Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._campaignService private
Definition at line 63 of file UserCampaignService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.PendingCampaignDetails(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UserCampaignService().
_mindfireService
readonly IMindfireService Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._mindfireService private
Definition at line 57 of file UserCampaignService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.CampaignDetails(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.GetOutboundsScheduleListAsync(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.SetOutboundIds(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.StartCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.StopCampaign(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.StopCampaigns(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UpdateLaunchedCampaign(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UserCampaignService().
_personaMicroservice
readonly IPersonaMicroservice Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._personaMicroservice private
Definition at line 61 of file UserCampaignService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.GetBase64Images(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.MyCampaigns(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UserCampaignService().
_personaService
readonly IPersonaService Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._personaService private
Definition at line 58 of file UserCampaignService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.CampaignDetails(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.PendingCampaigns(), Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.SyncPersonaDataWithMF(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UserCampaignService().
_settingsService
readonly ISettingsService Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._settingsService private
Definition at line 64 of file UserCampaignService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UpdateMAML(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UserCampaignService().
_signatureBlockService
readonly ISignatureBlockService Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._signatureBlockService private
Definition at line 62 of file UserCampaignService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.CampaignDetails(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UserCampaignService().
_templateService
readonly ITemplateService Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService._templateService private
Definition at line 59 of file UserCampaignService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.CampaignDetails(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.UserCampaignService.UserCampaignService().
The documentation for this class was generated from the following file:
Source/API/Services/UserCampaignService.cs