var 20190424115324__rss_user_campaign_updates_8cs =
[
    [ "Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.Migrations.rssUserCampaignUpdates", "dd/da6/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_databases_1_1_migrations_1_1rss_user_campaign_updates.html", "dd/da6/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_databases_1_1_migrations_1_1rss_user_campaign_updates" ]
];