AMM: Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Program Class Reference
Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Program Class Reference
Static Public Member Functions
new static void Main (string[] args)
Static Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Program
static void Main (string[] args)
Additional Inherited Members
Static Protected Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.API.Program
static IConfigurationBuilder ConfigureConfigurationBuilder (ConfigurationManager configurationManager, string[] args)
static IConfigurationRoot BuildConfiguration (ConfigurationManager configurationManager, string[] args)
static void ConfigureLogging (IConfigurationRoot config)
static void ConfigureServices (IServiceCollection services, IConfigurationRoot config)
static void ConfigureJson (IMvcBuilder mvcBuilder)
static void ConfigureHost (ConfigureHostBuilder host)
static void ConfigureWebHost (ConfigureWebHostBuilder webHost)
static WebApplication BuildApplication (WebApplicationBuilder builder)
static void ConfigureApplication (WebApplication application, IConfigurationRoot config)
static void MigrateDatabase (WebApplication app, IConfigurationRoot config)
Detailed Description
Definition at line 14 of file Program.cs.
Member Function Documentation
Main()
new static void Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Program.Main (string[] args) inline static
Definition at line 16 of file Program.cs.
References Deluxe.DeluxeBrandCenter.AMM.API.Program.BuildApplication(), Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureApplication(), Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureConfigurationBuilder(), Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureHost(), Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureLogging(), Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureServices(), Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureWebHost(), and Deluxe.DeluxeBrandCenter.AMM.API.Program.MigrateDatabase().
The documentation for this class was generated from the following file:
Scripts/ScriptRunner/Program.cs