var 20190222094516___designations_update_8_designer_8cs =
[
    [ "Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.Migrations.DesignationsUpdate", "de/dac/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_databases_1_1_migrations_1_1_designations_update.html", "de/dac/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_infrastructure_1_1_databases_1_1_migrations_1_1_designations_update" ]
];