AMM: Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods Class Reference
Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods Class Reference
Static Public Member Functions
static ContactGroupVM Rollout (this ContactGroupVM group, IEnumerable< ContactGroup > contactGroups)
static void Renumber (this SegmentationFilter filter, int start, int step)
static void Merge (this SegmentationFilter destination, SegmentationFilter source, string mergeOperator)
static void ReplaceRowWithFilter (this SegmentationFilter destination, SegmentationFilter source, int row)
static GetCombinedFilterAndFieldsResult GetCombinedFilterAndFields (this IEnumerable< ContactGroupVM > contactGroups)
static GetCombinedFilterAndFieldsResult GetCombinedFilterAndFields (this IEnumerable< ContactGroup > contactGroups)
static Func< ContactVM, bool > GetContactMatcher (this SegmentationFilter filter, string joinOperator=null, Func< ContactVM, bool > previousMatcher=null)
static int CountContacts (this ContactGroupVM group, IEnumerable< ContactVM > contacts, IEnumerable< ContactGroup > groups)
static int CountContacts (this ContactGroup group, IEnumerable< ContactVM > contacts, IEnumerable< ContactGroup > groups)
Static Private Member Functions
static DateTime SetTimeOffset (this string date)
static ContactGroupVM RolloutDates (this ContactGroupVM group)
static ContactGroupVM RolloutNONEState (this ContactGroupVM group)
static ContactGroupVM RolloutTags (this ContactGroupVM group)
static ContactGroupVM RolloutGroups (this ContactGroupVM group, IEnumerable< ContactGroup > contactGroups, int recursionLevel=0)
static ContactGroupVM RolloutBlank (this ContactGroupVM group)
Detailed Description
Definition at line 21 of file ContactManagerExtensionMethods.cs.
Member Function Documentation
CountContacts() [1/2]
static int Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.CountContacts (this ContactGroup group, IEnumerable< ContactVM > contacts, IEnumerable< ContactGroup > groups) inline static
Definition at line 599 of file ContactManagerExtensionMethods.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.ContactManager.ContactGroup.Filter, and Deluxe.DeluxeBrandCenter.AMM.Domain.DataModel.BaseEntityNamed.Name.
CountContacts() [2/2]
static int Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.CountContacts (this ContactGroupVM group, IEnumerable< ContactVM > contacts, IEnumerable< ContactGroup > groups) inline static
Definition at line 581 of file ContactManagerExtensionMethods.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityNamedVM.Name, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.SegmentationFilter(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.ContactGroupVM.SegmentationFilter.
GetCombinedFilterAndFields() [1/2]
static GetCombinedFilterAndFieldsResult Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.GetCombinedFilterAndFields (this IEnumerable< ContactGroup > contactGroups) inline static
Definition at line 422 of file ContactManagerExtensionMethods.cs.
GetCombinedFilterAndFields() [2/2]
static GetCombinedFilterAndFieldsResult Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.GetCombinedFilterAndFields (this IEnumerable< ContactGroupVM > contactGroups) inline static
Definition at line 359 of file ContactManagerExtensionMethods.cs.
GetContactMatcher()
static Func< ContactVM, bool > Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.GetContactMatcher (this SegmentationFilter filter, string joinOperator = null, Func< ContactVM, bool > previousMatcher = null) inline static
Definition at line 428 of file ContactManagerExtensionMethods.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.CriteriaJoinOperator, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias, and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.GetContactMatcher().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.GetContactMatcher().
Merge()
static void Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.Merge (this SegmentationFilter destination, SegmentationFilter source, string mergeOperator) inline static
Definition at line 318 of file ContactManagerExtensionMethods.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.CriteriaJoinOperator, and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias.
Renumber()
static void Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.Renumber (this SegmentationFilter filter, int start, int step) inline static
Definition at line 300 of file ContactManagerExtensionMethods.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.CriteriaJoinOperator.
ReplaceRowWithFilter()
static void Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.ReplaceRowWithFilter (this SegmentationFilter destination, SegmentationFilter source, int row) inline static
Definition at line 340 of file ContactManagerExtensionMethods.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.CriteriaJoinOperator, and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias.
Rollout()
static ContactGroupVM Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.Rollout (this ContactGroupVM group, IEnumerable< ContactGroup > contactGroups) inline static
Definition at line 286 of file ContactManagerExtensionMethods.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.ContactGroupVM.SegmentationFilter.
RolloutBlank()
static ContactGroupVM Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.RolloutBlank (this ContactGroupVM group) inline static private
Definition at line 258 of file ContactManagerExtensionMethods.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.ContactGroupVM.SegmentationFilter.
RolloutDates()
static ContactGroupVM Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.RolloutDates (this ContactGroupVM group) inline static private
Definition at line 29 of file ContactManagerExtensionMethods.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.GenerateFilterCriteria(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.ContactGroupVM.SegmentationFilter.
RolloutGroups()
static ContactGroupVM Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.RolloutGroups (this ContactGroupVM group, IEnumerable< ContactGroup > contactGroups, int recursionLevel = 0) inline static private
Definition at line 162 of file ContactManagerExtensionMethods.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias, and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.ContactGroupVM.SegmentationFilter.
RolloutNONEState()
static ContactGroupVM Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.RolloutNONEState (this ContactGroupVM group) inline static private
Definition at line 61 of file ContactManagerExtensionMethods.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.GenerateFilterCriteria(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.ContactGroupVM.SegmentationFilter.
RolloutTags()
static ContactGroupVM Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.RolloutTags (this ContactGroupVM group) inline static private
Definition at line 107 of file ContactManagerExtensionMethods.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilter.Criterias, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.Mindfire.SegmentationFilterCriteria.GenerateFilterCriteria(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.ContactGroupVM.SegmentationFilter.
SetTimeOffset()
static DateTime Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManager.ContactManagerExtensionMethods.SetTimeOffset (this string date) inline static private
Definition at line 23 of file ContactManagerExtensionMethods.cs.
The documentation for this class was generated from the following file:
Source/API/Services/ContactManager/ContactManagerExtensionMethods.cs