AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService Interface Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService Interface Reference
Public Member Functions
void SetUserId (string userId)
ApplicationUser SessionGetUser ()
string GetSessionString (string key)
int? GetSessionInt32 (string key)
string SessionGetUserId ()
string SessionGetClientName ()
string SessionGetMFAccountNamePrefix ()
string SessionGetMFDomain ()
string SessionGetMFAccountId ()
string SessionGetRootUrl ()
string SessionGetDefaultUserType ()
string SessionGetS3Bucket ()
string SessionGetTechnicalSupportPhone ()
string SessionGetDefaultFromAddress ()
string SessionGetCompanyId ()
string SessionGetTenant ()
int? SessionGetClientId ()
int? SessionGetMFMasterAccountId ()
int? SessionGetUserCreditCard ()
int? SessionGetDeadlineForSubscription ()
int? SessionGetMaxContacts ()
int? SessionGetMaxPersonas ()
string SessionGetGlobalFormId ()
string SessionGetSFAuthToken ()
string SessionGetSFInstance ()
string SessionGetSFRefreshToken ()
string SessionGetSFApiVersion ()
bool SetSessionString (string key, string value)
bool SetSessionInt32 (string key, int value)
bool SessionSetUserId (string value)
bool SessionSetClientName (string value)
bool SessionSetMFAccountNamePrefix (string value)
bool SessionSetMFDomain (string value)
bool SessionSetMFAccountId (string value)
bool SessionSetRootUrl (string value)
bool SessionSetDefaultUserType (string value)
bool SessionSetS3Bucket (string value)
bool SessionSetTechnicalSupportPhone (string value)
bool SessionSetDefaultFromAddress (string value)
bool SessionSetCompanyId (string value)
bool SessionSetTenant (string value)
bool SessionSetClientId (int value)
bool SessionSetMFMasterAccountId (int value)
bool SessionSetUserCreditCard (int value)
bool SessionSetDeadlineForSubscription (int value)
bool SessionSetMaxContacts (int value)
bool SessionSetMaxPersonas (int value)
bool SessionSetGlobalFormId (string value)
bool SessionSetSFAuthToken (string value)
bool SessionSetSFInstance (string value)
bool SessionSetSFRefreshToken (string value)
bool SessionSetSFApiVersion (string value)
void ClearSessionVariables ()
bool SetSessionVariables (ClientVM client, ApplicationUser user)
Properties
ISession Session [get]
bool Ephemeral [get, set]
Detailed Description
Definition at line 10 of file ISessionService.cs.
Member Function Documentation
ClearSessionVariables()
void Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.ClearSessionVariables ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SignIn().
GetSessionInt32()
int? Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.GetSessionInt32 (string key)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
GetSessionString()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.GetSessionString (string key)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionGetClientId()
int? Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientId ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Delete(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.DoesExist< TModelCheck >(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Entity(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.FillHtmlContent(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.GetBySocialToken(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetBySocialToken(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsAndStats(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.GetList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.GetList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.MindfireService.MindfireService(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerUserAdminWithUserId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.registerUserAdvisorWithUserId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.MindfireService.SetUserCredentials(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Single(), Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.Update(), Deluxe.DeluxeBrandCenter.AMM.API.Services.NamedDbService< TModel, TModelVM >.Update(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.DBService< TModel, TModelVM >.UpdateEntity().
SessionGetClientName()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetClientName ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.AddOrUpdateContactGroup(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddOrUpdateTag(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.CreateContact(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.CreateContactMF(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.FormatCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetColumnNames(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactInfoAsync(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroup(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SignatureBlockController.Update(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.TemplateController.Update(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.UpdateContact(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts().
SessionGetCompanyId()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetCompanyId ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionGetDeadlineForSubscription()
int? Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetDeadlineForSubscription ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionGetDefaultFromAddress()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetDefaultFromAddress ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionGetDefaultUserType()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetDefaultUserType ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionGetGlobalFormId()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetGlobalFormId ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.UpdateEmailSPFApproved().
SessionGetMaxContacts()
int? Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetMaxContacts ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts().
SessionGetMaxPersonas()
int? Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetMaxPersonas ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionGetMFAccountId()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetMFAccountId ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionGetMFAccountNamePrefix()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetMFAccountNamePrefix ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterMFUser().
SessionGetMFDomain()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetMFDomain ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.RegisterProfile().
SessionGetMFMasterAccountId()
int? Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetMFMasterAccountId ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionGetRootUrl()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetRootUrl ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionGetS3Bucket()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetS3Bucket ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SignIn().
SessionGetSFApiVersion()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetSFApiVersion ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSFContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSFLeads(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.SalesForceInit().
SessionGetSFAuthToken()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetSFAuthToken ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSFContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSFLeads(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.SalesForceInit().
SessionGetSFInstance()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetSFInstance ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSFContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetSFLeads(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.SalesForceInit().
SessionGetSFRefreshToken()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetSFRefreshToken ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionGetTechnicalSupportPhone()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetTechnicalSupportPhone ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionGetTenant()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetTenant ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionGetUser()
ApplicationUser Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUser ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddGroupsAndTagsToDb(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddOrUpdateTagDb(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DeleteGroup(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DeleteTag(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadGroupContactsCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadTagsCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GenerateGroupCreationOptions(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactGroupDB(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetErrorCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroup(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroupContactsPaginated(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetGroups(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetRedtailTagGroup(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetTags(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetUnsubscribedContacts(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetUnsubscribedContactsId(), Deluxe.DeluxeBrandCenter.AMM.API.Services.MindfireService.MindfireService(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.RedTail.RedTailService.PullRedtailTagGroups(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.RedtailLogin(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadContacts().
SessionGetUserCreditCard()
int? Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUserCreditCard ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionGetUserId()
string Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionGetUserId ()
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.AddOrUpdateGroupDb(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.ContactManagerController.DisconnectRT(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.FindPersonaByType(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.DBCController.GetAccountingUnits(), Deluxe.DeluxeBrandCenter.AMM.API.Services.BIService.GetCampaignsWithElements(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetContactAssociatedGroups(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonaByGUID(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonaInstanceNamesForAudience(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.GetPersonasForProfile(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ReportServiceMF.GetUnsubscribedList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.SFAuthenticte(), Deluxe.DeluxeBrandCenter.AMM.API.Services.PersonaService.Single(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UpdateContactsCollectionField().
SessionSetClientId()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetClientId (int value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetClientName()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetClientName (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetCompanyId()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetCompanyId (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetDeadlineForSubscription()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetDeadlineForSubscription (int value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetDefaultFromAddress()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetDefaultFromAddress (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetDefaultUserType()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetDefaultUserType (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetGlobalFormId()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetGlobalFormId (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetMaxContacts()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetMaxContacts (int value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetMaxPersonas()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetMaxPersonas (int value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetMFAccountId()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetMFAccountId (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetMFAccountNamePrefix()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetMFAccountNamePrefix (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetMFDomain()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetMFDomain (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetMFMasterAccountId()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetMFMasterAccountId (int value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetRootUrl()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetRootUrl (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetS3Bucket()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetS3Bucket (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetSFApiVersion()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetSFApiVersion (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DisconnectSalesforce().
SessionSetSFAuthToken()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetSFAuthToken (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DisconnectSalesforce().
SessionSetSFInstance()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetSFInstance (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DisconnectSalesforce().
SessionSetSFRefreshToken()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetSFRefreshToken (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DisconnectSalesforce().
SessionSetTechnicalSupportPhone()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetTechnicalSupportPhone (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetTenant()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetTenant (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetUserCreditCard()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetUserCreditCard (int value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SessionSetUserId()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SessionSetUserId (string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SetSessionInt32()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SetSessionInt32 (string key, int value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SetSessionString()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SetSessionString (string key, string value)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
SetSessionVariables()
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SetSessionVariables (ClientVM client, ApplicationUser user)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Scripts.SyncCampaignElementMetadata.Run(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Scripts.SyncCampaignWithPersona.Run(), Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SignIn(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.AccountService.SSOSignIn().
SetUserId()
void Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.SetUserId (string userId)
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.IDPExtensionMethods.AddIDPAuthentication(), Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureServices(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Scripts.SyncCampaignElementMetadata.Run(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Scripts.SyncCampaignWithPersona.Run(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Scripts.UpdateBillingCodes.Run(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Scripts.UpdateRecurringSchedules.Run(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Scripts.UpdateSocialCallbackUrl.Run(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.AccountController.SSOSignIn().
Property Documentation
Ephemeral
bool Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.Ephemeral get set
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Definition at line 18 of file ISessionService.cs.
Session
ISession Deluxe.DeluxeBrandCenter.AMM.Domain.Services.ISessionService.Session get
Implemented in Deluxe.DeluxeBrandCenter.AMM.API.Services.SessionService.
Definition at line 12 of file ISessionService.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DisconnectSalesforce(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.SFAuthenticte(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.RootController< TService >.StartJob< T >().
The documentation for this interface was generated from the following file:
Source/Domain/Services/ISessionService.cs