AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils Class Reference
Static Public Member Functions
static DateTime convertToLocalTime (DateTime utcDateTime, string timeZoneId)
static DateTime convertToUtc (DateTime localDateTime, string timeZoneId)
static string TimeZoneIdToDisplayName (string timeZoneId)
static string getTimeZoneDisplayName (string timeZoneId)
static TimeSpan GetTimeZoneOffset (string timeZoneId)
static IReadOnlyCollection< KeyValuePair< string, string > > GetTimeZoneList ()
static double ConvertToUnixTimestamp (DateTime date)
static DateTime ConvertUnixTimestampToDate (double timeStamp)
Detailed Description
Definition at line 198 of file Utility.cs.
Member Function Documentation
convertToLocalTime()
static DateTime Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.convertToLocalTime (DateTime utcDateTime, string timeZoneId) inline static
Definition at line 200 of file Utility.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.GetTimeZoneOffset().
ConvertToUnixTimestamp()
static double Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.ConvertToUnixTimestamp (DateTime date) inline static
Definition at line 394 of file Utility.cs.
convertToUtc()
static DateTime Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.convertToUtc (DateTime localDateTime, string timeZoneId) inline static
Definition at line 207 of file Utility.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.GetTimeZoneOffset().
ConvertUnixTimestampToDate()
static DateTime Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.ConvertUnixTimestampToDate (double timeStamp) inline static
Definition at line 401 of file Utility.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.LinkedinService.DeterminingWarnings().
getTimeZoneDisplayName()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.getTimeZoneDisplayName (string timeZoneId) inline static
Definition at line 219 of file Utility.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.GetTimeZoneList().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.GetTimeZoneOffset(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.TimeZoneIdToDisplayName().
GetTimeZoneList()
static IReadOnlyCollection< KeyValuePair< string, string > > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.GetTimeZoneList () inline static
Definition at line 246 of file Utility.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.getTimeZoneDisplayName(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.UtilityController.GetTimeZones().
GetTimeZoneOffset()
static TimeSpan Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.GetTimeZoneOffset (string timeZoneId) inline static
Definition at line 232 of file Utility.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.getTimeZoneDisplayName().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.convertToLocalTime(), and Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.convertToUtc().
TimeZoneIdToDisplayName()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.TimeZoneIdToDisplayName (string timeZoneId) inline static
Definition at line 214 of file Utility.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.DateTimeUtils.getTimeZoneDisplayName().
The documentation for this class was generated from the following file:
Source/Domain/Utility/Utility.cs