AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM Class Reference
Public Member Functions
ContactVM ()
ContactVM (string headder, string values)
void Sanitize ()
override ViewModelValidation Validate (string clientName)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityVM
Static Public Member Functions
static IEnumerable< ContactFieldDescriptor > GetPropertyNames ()
static string GetDisplayName (PropertyInfo propertyInfo)
static bool CheckIfExluded (PropertyInfo propertyInfo)
static bool CheckIfPropertyIsRequired (PropertyInfo propertyInfo)
static int GetMaxLength (PropertyInfo propertyInfo)
static string GetRegex (PropertyInfo propertyInfo)
static IEnumerable< string > GetDateFields ()
Properties
string PURL [get, set]
string AccountID [get, set]
DateTime? CreatedAt [get, set]
DateTime? UpdatedAt [get, set]
string GroupName [get, set]
string MFGroupName [get, set]
string FirstName [get, set]
string MiddleName [get, set]
string LastName [get, set]
string Nickname [get, set]
string Gender [get, set]
string Email [get, set]
string Company [get, set]
string Address1 [get, set]
string Address2 [get, set]
string City [get, set]
string State [get, set]
string Sorting [get, set]
string Zip [get, set]
string HomePhone [get, set]
string Mobile [get, set]
string Phone [get, set]
DateTime? BirthDate [get, set]
DateTime? Anniversary [get, set]
DateTime? ClientStart [get, set]
string Tags [get, set]
string Preferences [get, set]
string FacebookAccount [get, set]
string LinkedInAccount [get, set]
string TwitterAccount [get, set]
string Website [get, set]
string Title [get, set]
string ContactSource [get, set]
Properties inherited from Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityVM
int Id [get, set]
DateTime DateCreated [get, set]
DateTime DateModified [get, set]
bool Enabled [get, set]
Detailed Description
Definition at line 14 of file ContactVM.cs.
Constructor & Destructor Documentation
ContactVM() [1/2]
Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.ContactVM () inline
Definition at line 16 of file ContactVM.cs.
ContactVM() [2/2]
Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.ContactVM (string headder, string values) inline
Definition at line 20 of file ContactVM.cs.
Member Function Documentation
CheckIfExluded()
static bool Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.CheckIfExluded (PropertyInfo propertyInfo) inline static
Definition at line 268 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetPropertyNames().
CheckIfPropertyIsRequired()
static bool Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.CheckIfPropertyIsRequired (PropertyInfo propertyInfo) inline static
Definition at line 272 of file ContactVM.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Validate().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetPropertyNames().
GetDateFields()
static IEnumerable< string > Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetDateFields () inline static
Definition at line 284 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.FormatDateFields().
GetDisplayName()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetDisplayName (PropertyInfo propertyInfo) inline static
Definition at line 264 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetPropertyNames().
GetMaxLength()
static int Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetMaxLength (PropertyInfo propertyInfo) inline static
Definition at line 276 of file ContactVM.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Validate().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetPropertyNames().
GetPropertyNames()
static IEnumerable< ContactFieldDescriptor > Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetPropertyNames () inline static
Definition at line 249 of file ContactVM.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.CheckIfExluded(), Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.CheckIfPropertyIsRequired(), Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetDisplayName(), Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetMaxLength(), Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetRegex(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactFieldDescriptor.Name.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.ContactCSVTable.AddContactList(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadCSV(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetColumnNames().
GetRegex()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetRegex (PropertyInfo propertyInfo) inline static
Definition at line 280 of file ContactVM.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Validate().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetPropertyNames().
Sanitize()
void Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize () inline
Definition at line 45 of file ContactVM.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.AccountID, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Address1, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Address2, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.City, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Company, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.ContactSource, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Email, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.FacebookAccount, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.FirstName, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Gender, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GroupName, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.HomePhone, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.LastName, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.LinkedInAccount, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.MFGroupName, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.MiddleName, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Mobile, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Nickname, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Phone, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Preferences, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.PURL, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sorting, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.State, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Tags, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Title, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.TwitterAccount, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Website, and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Zip.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.CreateContact(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Mindfire.ContactServiceMF.UpdateContact().
Validate()
override ViewModelValidation Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Validate (string clientName) inline virtual
Reimplemented from Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.BaseEntityVM.
Definition at line 187 of file ContactVM.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Address1, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.City, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Email, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.MFGroupName, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.State, Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Title, and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Zip.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.CheckIfPropertyIsRequired(), Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetMaxLength(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GetRegex().
Property Documentation
AccountID
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.AccountID get set
Definition at line 301 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.RemoveContactFromGroup(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
Address1
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Address1 get set
Definition at line 361 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Validate().
Address2
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Address2 get set
Definition at line 366 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
Anniversary
DateTime? Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Anniversary get set
Definition at line 411 of file ContactVM.cs.
BirthDate
DateTime? Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.BirthDate get set
Definition at line 406 of file ContactVM.cs.
City
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.City get set
Definition at line 371 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Validate().
ClientStart
DateTime? Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.ClientStart get set
Definition at line 416 of file ContactVM.cs.
Company
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Company get set
Definition at line 356 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
ContactSource
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.ContactSource get set
Definition at line 456 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
CreatedAt
DateTime? Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.CreatedAt get set
Definition at line 306 of file ContactVM.cs.
Email
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Email get set
Definition at line 351 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Validate().
FacebookAccount
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.FacebookAccount get set
Definition at line 431 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
FirstName
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.FirstName get set
Definition at line 326 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
Gender
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Gender get set
Definition at line 346 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
GroupName
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.GroupName get set
Definition at line 316 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
HomePhone
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.HomePhone get set
Definition at line 391 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
LastName
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.LastName get set
Definition at line 336 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
LinkedInAccount
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.LinkedInAccount get set
Definition at line 436 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
MFGroupName
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.MFGroupName get set
Definition at line 321 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Validate().
MiddleName
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.MiddleName get set
Definition at line 331 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
Mobile
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Mobile get set
Definition at line 396 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
Nickname
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Nickname get set
Definition at line 341 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
Phone
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Phone get set
Definition at line 401 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
Preferences
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Preferences get set
Definition at line 426 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
PURL
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.PURL get set
Definition at line 296 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
Sorting
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sorting get set
Definition at line 381 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
State
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.State get set
Definition at line 376 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Validate().
Tags
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Tags get set
Definition at line 421 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
Title
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Title get set
Definition at line 451 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Validate().
TwitterAccount
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.TwitterAccount get set
Definition at line 441 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
UpdatedAt
DateTime? Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.UpdatedAt get set
Definition at line 311 of file ContactVM.cs.
Website
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Website get set
Definition at line 446 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize().
Zip
string Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Zip get set
Definition at line 386 of file ContactVM.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Sanitize(), and Deluxe.DeluxeBrandCenter.AMM.Domain.ExtServiceModel.ContactVM.Validate().
The documentation for this class was generated from the following file:
Source/Domain/ViewModel/ContactManager/ContactVM.cs