AMM: Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext Class Reference
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext Class Reference
Public Member Functions
ClientDbContext (DbContextOptions< ClientDbContext > options)
override int SaveChanges ()
override Task< int > SaveChangesAsync (CancellationToken cancellationToken=default)
Protected Member Functions
override void OnModelCreating (ModelBuilder modelBuilder)
Properties
virtual DbSet< Client > Clients [get, set]
virtual DbSet< User > Users [get, set]
Private Member Functions
void OnBeforeSaveChanges ()
void AddTimestampsToEntities ()
Detailed Description
Definition at line 14 of file ClientDbContext.cs.
Constructor & Destructor Documentation
ClientDbContext()
Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.ClientDbContext (DbContextOptions< ClientDbContext > options) inline
Definition at line 16 of file ClientDbContext.cs.
Member Function Documentation
AddTimestampsToEntities()
void Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.AddTimestampsToEntities () inline private
Definition at line 27 of file ClientDbContext.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.OnBeforeSaveChanges().
OnBeforeSaveChanges()
void Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.OnBeforeSaveChanges () inline private
Definition at line 22 of file ClientDbContext.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.AddTimestampsToEntities().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.SaveChanges(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.SaveChangesAsync().
OnModelCreating()
override void Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.OnModelCreating (ModelBuilder modelBuilder) inline protected
Definition at line 66 of file ClientDbContext.cs.
SaveChanges()
override int Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.SaveChanges () inline
Definition at line 45 of file ClientDbContext.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.OnBeforeSaveChanges().
SaveChangesAsync()
override Task< int > Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.SaveChangesAsync (CancellationToken cancellationToken = default) inline
Definition at line 51 of file ClientDbContext.cs.
References Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.OnBeforeSaveChanges().
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ClientDBService< TModel, TModelVM >.Delete(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ClientDBService< TModel, TModelVM >.Update().
Property Documentation
Clients
virtual DbSet<Client> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.Clients get set
Definition at line 57 of file ClientDbContext.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.IDPExtensionMethods.AddIDPAuthentication(), Deluxe.DeluxeBrandCenter.AMM.API.Program.ConfigureServices(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.GetLinkedinAccountInfo(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.TwitterService.GetSocailAccountInfo(), Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Social.SocialNetworkService.PreparingEmail(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Scripts.SyncCampaignElementMetadata.Run(), Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Scripts.SyncCampaignWithPersona.Run(), Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.SaveCredentials(), and Deluxe.DeluxeBrandCenter.AMM.API.Controllers.SocialNetworkController.SocialAuthorization().
Users
virtual DbSet<User> Deluxe.DeluxeBrandCenter.AMM.Infrastructure.Databases.ClientDbContext.Users get set
Definition at line 61 of file ClientDbContext.cs.
The documentation for this class was generated from the following file:
Source/Infrastructure/Databases/ClientDbContext.cs