var _red_tail_tag_group_v_m_8cs =
[
    [ "Deluxe.DeluxeBrandCenter.AMM.Domain.ViewModel.ContactManager.RedTailTagGroupVM", "dc/d59/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_domain_1_1_view_model_1_1_contact_manager_1_1_red_tail_tag_group_v_m.html", "dc/d59/class_deluxe_1_1_deluxe_brand_center_1_1_a_m_m_1_1_domain_1_1_view_model_1_1_contact_manager_1_1_red_tail_tag_group_v_m" ]
];