AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.Tags Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.Tags Class Reference
Static Public Member Functions
static string ReplaceTags (string text, object model)
static string ReplaceTags (string text, List< KeyValuePair< string, string > > model)
static string ReplaceTags (string text, Dictionary< string, string > model)
Detailed Description
Definition at line 421 of file Utility.cs.
Member Function Documentation
ReplaceTags() [1/3]
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.Tags.ReplaceTags (string text, Dictionary< string, string > model) inline static
Definition at line 489 of file Utility.cs.
ReplaceTags() [2/3]
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.Tags.ReplaceTags (string text, List< KeyValuePair< string, string > > model) inline static
Definition at line 463 of file Utility.cs.
ReplaceTags() [3/3]
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.Tags.ReplaceTags (string text, object model) inline static
Definition at line 423 of file Utility.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.Tags.ReplaceTags().
Referenced by Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.Util.Tags.ReplaceTags(), and Deluxe.DeluxeBrandCenter.AMM.Infrastructure.SparkPost.SparkPostService.SendEmail().
The documentation for this class was generated from the following file:
Source/Domain/Utility/Utility.cs