AMM: Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper Class Reference
Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper Class Reference
Static Public Member Functions
static ServiceResult< string > ResponseValidation (ServiceResult< ImportContactsResponse > response)
static ServiceResult< string > Validate (string[] header, string[][] data)
static ServiceResult< string > ValidateFile (IFormFile file)
static ServiceResult< string > ReadCSVFromFile (IFormFile file)
static ServiceResult< string > ReadCSVFromName (string filename)
static ServiceResult< string > WriteCSVFile (IFormFile file)
static ServiceResult< ContactCSVTable > CreateFromContactList (IEnumerable< ContactVM > contacts, bool excludeProperties=false)
static string ReplaceNewLine (this string csv)
Detailed Description
Definition at line 15 of file CSVHelper.cs.
Member Function Documentation
CreateFromContactList()
static ServiceResult< ContactCSVTable > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper.CreateFromContactList (IEnumerable< ContactVM > contacts, bool excludeProperties = false) inline static
Definition at line 150 of file CSVHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.DownloadGroupContactsCSV(), Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadRedTailContacts(), and Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UploadSaleForceContacts().
ReadCSVFromFile()
static ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper.ReadCSVFromFile (IFormFile file) inline static
Definition at line 91 of file CSVHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetColumnNames().
ReadCSVFromName()
static ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper.ReadCSVFromName (string filename) inline static
Definition at line 111 of file CSVHelper.cs.
ReplaceNewLine()
static string Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper.ReplaceNewLine (this string csv) inline static
Definition at line 157 of file CSVHelper.cs.
ResponseValidation()
static ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper.ResponseValidation (ServiceResult< ImportContactsResponse > response) inline static
Definition at line 17 of file CSVHelper.cs.
References Deluxe.DeluxeBrandCenter.AMM.Domain.ServiceModel.ServiceResult< T >.Data, and Deluxe.DeluxeBrandCenter.AMM.Domain.ServiceModel.ServiceResult< T >.ErrorMessage.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.UpdateContactsCollectionField().
Validate()
static ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper.Validate (string[] header, string data[][]) inline static
Definition at line 38 of file CSVHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetColumnNames().
ValidateFile()
static ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper.ValidateFile (IFormFile file) inline static
Definition at line 76 of file CSVHelper.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.API.Services.ContactManagerService.GetColumnNames().
WriteCSVFile()
static ServiceResult< string > Deluxe.DeluxeBrandCenter.AMM.Domain.Utility.CSVHelper.WriteCSVFile (IFormFile file) inline static
Definition at line 127 of file CSVHelper.cs.
The documentation for this class was generated from the following file:
Source/Domain/Utility/CSVHelper.cs