AMM: Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType > Class Template Reference
Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType > Class Template Reference abstract
Public Member Functions
Script (IConfiguration configuration)
async Task< string > Execute (DataType data)
Public Member Functions inherited from Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.IScript< DataType >
Static Public Member Functions
static void MapRoute (Type thisType, RouteGroupBuilder routes, WebApplication application)
Protected Member Functions
virtual string GetName ()
virtual CsvLogger< CsvLogEntryType > GetCsvLogger ()
Task Run (CsvLogger< CsvLogEntryType > logger, DataType data)
Protected Attributes
readonly IConfiguration _configuration
Detailed Description
Type Constraints
CsvLogEntryType : CsvLogScriptEntry
CsvLogEntryType : new()
Definition at line 14 of file Script.cs.
Constructor & Destructor Documentation
Script()
Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >.Script (IConfiguration configuration) inline
Definition at line 28 of file Script.cs.
References Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >._configuration.
Member Function Documentation
Execute()
async Task< string > Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >.Execute (DataType data) inline
Implements Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.IScript< DataType >.
Definition at line 43 of file Script.cs.
References Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >.GetCsvLogger(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >.Run().
GetCsvLogger()
virtual CsvLogger< CsvLogEntryType > Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >.GetCsvLogger () inline protected virtual
Definition at line 38 of file Script.cs.
References Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >._configuration, and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >.GetName().
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >.Execute().
GetName()
virtual string Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >.GetName () inline protected virtual
Definition at line 33 of file Script.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >.GetCsvLogger().
MapRoute()
static void Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >.MapRoute (Type thisType, RouteGroupBuilder routes, WebApplication application) inline static
Definition at line 18 of file Script.cs.
Run()
Task Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >.Run (CsvLogger< CsvLogEntryType > logger, DataType data) abstract protected
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >.Execute().
Member Data Documentation
_configuration
readonly IConfiguration Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >._configuration protected
Definition at line 16 of file Script.cs.
Referenced by Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >.GetCsvLogger(), and Deluxe.DeluxeBrandCenter.AMM.ScriptRunner.Services.Script< CsvLogEntryType, DataType >.Script().
The documentation for this class was generated from the following file:
Scripts/ScriptRunner/Services/Script.cs